// Copyright 2022-2023 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Vulkan Documentation

include::{config}/attribs.adoc[]
include::{generated}/specattribs.adoc[]

== About

link:https://docs.vulkan.org/[This site] gathers together several key
Vulkan documents including specifications, guides, tutorials and samples
into a single site allowing for easy cross-searching and cross-linking
across documents to help navigate quickly to the information you need
for developing Vulkan-based applications.

For more details about and resources for using the Vulkan graphics API,
see the Vulkan developer website at https://vulkan.org .

This build of the site includes the Vulkan {SPECREVISION} API specification
{APITITLE}, generated on {SPECDATE} {SPECREMARK}.

== Navigation

The left sidebar links to pages in the current spec.
Proposals are available at the bottom of the sidebar links for the spec.

The right sidebar is sections within the current page.

The bottom-left button switches between the various documentation modules and specs.

The top contains a text searchbar.
It will suggest matches to search terms found in all the modules of the
site.

== Site Information

link:https://docs.vulkan.org/[This site] is generated using the
link:https://docs.antora.org/[Antora] static site generator.

If you need to report a problem or build the site yourself, start with
the
link:https://github.com/KhronosGroup/Vulkan-Site/[Vulkan-Site]
repository on GitHub.
