#!/usr/bin/python3

from genspec import *

buildBranch('1.0',
	    xmlTargets = 'clobber full_install pdf_install',
	    specTargets = 'xhtml styleguide manhtml manhtmlpages pdf',
	    repoDir = '/home/tree/git/Vulkan-Docs',
	    outDir = '/home/tree/git/Vulkan-Web-Registry/specs')
buildBranch('1.0-wsi_extensions',
	    xmlTargets = 'clobber full_install',
	    specTargets = 'xhtml manhtml',
	    repoDir = '/home/tree/git/Vulkan-Docs',
	    outDir = '/home/tree/git/Vulkan-Web-Registry/specs')

print('echo Info: post-generation cleanup')
print('git checkout ' + coreBranch)

createTags(buildOnFriday())
