#!/bin/sh
# makeKHR - invoke Makefile with the right options to build with all
# KHR extensions included.
# Usage: makeKHR targets

echo Building KHR extensions for targets $*
extensions=""
for ext in \
    VK_KHR_android_surface   \
    VK_KHR_display           \
    VK_KHR_display_swapchain \
    VK_KHR_mir_surface       \
    VK_KHR_surface           \
    VK_KHR_swapchain         \
    VK_KHR_wayland_surface   \
    VK_KHR_win32_surface     \
    VK_KHR_xcb_surface       \
    VK_KHR_xlib_surface      \
    VK_AMD_draw_indirect_count \
    VK_AMD_gcn_shader \
    VK_AMD_rasterization_order \
    VK_AMD_shader_explicit_vertex_parameter \
    VK_AMD_shader_trinary_minmax \
    VK_EXT_debug_marker \
    VK_EXT_debug_report \
    VK_IMG_filter_cubic \
    VK_NV_dedicated_allocation \
    VK_NV_external_memory \
    VK_NV_external_memory_capabilities \
    VK_NV_external_memory_win32 \
    VK_NV_win32_keyed_mutex \
    VK_NV_glsl_shader \
; do
    extensions="$extensions $ext"
done

make clean_generated
make EXTENSIONS="$extensions" APITITLE="(with many extensions)" $*
