#!/bin/sh
# makeKHR - invoke Makefile with the right options to build with all
# KHR extensions included.
# Usage: makeKHR targets

echo Building KHR extensions for targets $*
extensions=""
for ext in \
    VK_KHR_android_surface   \
    VK_KHR_display           \
    VK_KHR_display_swapchain \
    VK_KHR_mir_surface       \
    VK_KHR_surface           \
    VK_KHR_swapchain         \
    VK_KHR_wayland_surface   \
    VK_KHR_win32_surface     \
    VK_KHR_xcb_surface       \
    VK_KHR_xlib_surface      \
; do
    extensions="$extensions $ext"
done

make clean_generated
make EXTENSIONS="$extensions" APITITLE="(with WSI extensions)" $*
