#!/bin/sh
#
# Copyright (c) 2016-2017 The Khronos Group Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# makeKHR - invoke Makefile with the right options to build with all
# KHR extensions included.

# Usage: makeKHR targets

echo Building KHR extensions for targets $*
extensions=""
for ext in \
    VK_KHR_android_surface   \
    VK_KHR_display           \
    VK_KHR_display_swapchain \
    VK_KHR_get_physical_device_properties2 \
    VK_KHR_maintenance1      \
    VK_KHR_mir_surface       \
    VK_KHR_shader_draw_parameters \
    VK_KHR_surface           \
    VK_KHR_swapchain         \
    VK_KHR_wayland_surface   \
    VK_KHR_win32_surface     \
    VK_KHR_xcb_surface       \
    VK_KHR_xlib_surface      \
; do
    extensions="$extensions $ext"
done

make clean_generated
make EXTENSIONS="$extensions" APITITLE="(with KHR extensions)" $*
