#!/bin/sh
# makeBranch - invoke Makefile with the right options to build with a
# specific extension included.
# Usage: makeBranch extension targets
extension=$1
shift
echo extension is $extension targets are $*

make clean_generated
make EXTENSIONS="$extension" APITITLE="(with extension $extension)" $*
