// Copyright 2014-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

// This section is included inside the Pipelines chapter (pipelines.adoc)


[[pipelines-creation-feedback]]
== Pipeline Creation Feedback

[open,refpage='VkPipelineCreationFeedbackCreateInfo',desc='Request for feedback about the creation of a pipeline',type='structs',xrefs='VkGraphicsPipelineCreateInfo VkComputePipelineCreateInfo VkRayTracingPipelineCreateInfoNV VkRayTracingPipelineCreateInfoKHR VkPipelineCreationFeedback',alias='VkPipelineCreationFeedbackCreateInfoEXT']
--
Feedback about the creation of a particular pipeline object can: be obtained
by adding a sname:VkPipelineCreationFeedbackCreateInfo structure to the
pname:pNext chain of slink:VkGraphicsPipelineCreateInfo,
ifdef::VK_KHR_ray_tracing_pipeline[slink:VkRayTracingPipelineCreateInfoKHR,]
ifdef::VK_NV_ray_tracing[slink:VkRayTracingPipelineCreateInfoNV,]
or slink:VkComputePipelineCreateInfo.
The sname:VkPipelineCreationFeedbackCreateInfo structure is defined as:

include::{generated}/api/structs/VkPipelineCreationFeedbackCreateInfo.adoc[]

ifdef::VK_EXT_pipeline_creation_feedback[]
or the equivalent

include::{generated}/api/structs/VkPipelineCreationFeedbackCreateInfoEXT.adoc[]
endif::VK_EXT_pipeline_creation_feedback[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pPipelineCreationFeedback is a pointer to a
    slink:VkPipelineCreationFeedback structure.
  * pname:pipelineStageCreationFeedbackCount is the number of elements in
    pname:pPipelineStageCreationFeedbacks.
  * pname:pPipelineStageCreationFeedbacks is a pointer to an array of
    pname:pipelineStageCreationFeedbackCount
    slink:VkPipelineCreationFeedback structures.

An implementation should: write pipeline creation feedback to
pname:pPipelineCreationFeedback and may: write pipeline stage creation
feedback to pname:pPipelineStageCreationFeedbacks.
An implementation must: set or clear the
ename:VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT in
slink:VkPipelineCreationFeedback::pname:flags for
pname:pPipelineCreationFeedback and every element of
pname:pPipelineStageCreationFeedbacks.

[NOTE]
.Note
====
One common scenario for an implementation to skip per-stage feedback is when
ename:VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT is
set in pname:pPipelineCreationFeedback.
====

When chained to
ifdef::VK_KHR_ray_tracing_pipeline[slink:VkRayTracingPipelineCreateInfoKHR,]
ifdef::VK_NV_ray_tracing[slink:VkRayTracingPipelineCreateInfoNV,]
ifdef::VK_NV_ray_tracing,VK_KHR_ray_tracing_pipeline[or]
slink:VkGraphicsPipelineCreateInfo, the `i` element of
pname:pPipelineStageCreationFeedbacks corresponds to the `i` element of
ifdef::VK_KHR_ray_tracing_pipeline[slink:VkRayTracingPipelineCreateInfoKHR::pname:pStages,]
ifdef::VK_NV_ray_tracing[slink:VkRayTracingPipelineCreateInfoNV::pname:pStages,]
ifdef::VK_NV_ray_tracing,VK_KHR_ray_tracing_pipeline[or]
slink:VkGraphicsPipelineCreateInfo::pname:pStages.
When chained to slink:VkComputePipelineCreateInfo, the first element of
pname:pPipelineStageCreationFeedbacks corresponds to
slink:VkComputePipelineCreateInfo::pname:stage.

include::{generated}/validity/structs/VkPipelineCreationFeedbackCreateInfo.adoc[]
--

[open,refpage='VkPipelineCreationFeedback',desc='Feedback about the creation of a pipeline or pipeline stage',type='structs',xrefs='VkPipelineCreationFeedbackCreateInfo VkPipelineCreationFeedbackFlagBits',alias='VkPipelineCreationFeedbackEXT']
--
The sname:VkPipelineCreationFeedback structure is defined as:

include::{generated}/api/structs/VkPipelineCreationFeedback.adoc[]

ifdef::VK_EXT_pipeline_creation_feedback[]
or the equivalent

include::{generated}/api/structs/VkPipelineCreationFeedbackEXT.adoc[]
endif::VK_EXT_pipeline_creation_feedback[]

  * pname:flags is a bitmask of elink:VkPipelineCreationFeedbackFlagBits
    providing feedback about the creation of a pipeline or of a pipeline
    stage.
  * pname:duration is the duration spent creating a pipeline or pipeline
    stage in nanoseconds.

If the ename:VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT is not set in
pname:flags, an implementation must: not set any other bits in pname:flags,
and the values of all other sname:VkPipelineCreationFeedback data members
are undefined:.

include::{generated}/validity/structs/VkPipelineCreationFeedback.adoc[]
--

[open,refpage='VkPipelineCreationFeedbackFlagBits',desc='Bitmask specifying pipeline or pipeline stage creation feedback',type='enums',xrefs='VkPipelineCreationFeedbackCreateInfo VkPipelineCreationFeedback',alias='VkPipelineCreationFeedbackFlagBitsEXT']
--
Possible values of the pname:flags member of
slink:VkPipelineCreationFeedback are:

include::{generated}/api/enums/VkPipelineCreationFeedbackFlagBits.adoc[]

ifdef::VK_EXT_pipeline_creation_feedback[]
or the equivalent

include::{generated}/api/enums/VkPipelineCreationFeedbackFlagBitsEXT.adoc[]
endif::VK_EXT_pipeline_creation_feedback[]

  * ename:VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT indicates that the
    feedback information is valid.
  * ename:VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT
    indicates that a readily usable pipeline or pipeline stage was found in
    the pname:pipelineCache specified by the application in the pipeline
    creation command.
+
An implementation should: set the
ename:VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT bit
if it was able to avoid the large majority of pipeline or pipeline stage
creation work by using the pname:pipelineCache parameter of
flink:vkCreateGraphicsPipelines,
ifdef::VK_KHR_ray_tracing_pipeline[flink:vkCreateRayTracingPipelinesKHR,]
ifdef::VK_NV_ray_tracing[flink:vkCreateRayTracingPipelinesNV,]
or flink:vkCreateComputePipelines.
When an implementation sets this bit for the entire pipeline, it may: leave
it unset for any stage.
+
[NOTE]
.Note
====
Implementations are encouraged to provide a meaningful signal to
applications using this bit.
The intention is to communicate to the application that the pipeline or
pipeline stage was created "`as fast as it gets`" using the pipeline cache
provided by the application.
If an implementation uses an internal cache, it is discouraged from setting
this bit as the feedback would be unactionable.
====

  * ename:VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT
    indicates that the base pipeline specified by the
    pname:basePipelineHandle or pname:basePipelineIndex member of the
    stext:Vk*PipelineCreateInfo structure was used to accelerate the
    creation of the pipeline.
+
An implementation should: set the
ename:VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT bit if it
was able to avoid a significant amount of work by using the base pipeline.
+
[NOTE]
.Note
====
While "`significant amount of work`" is subjective, implementations are
encouraged to provide a meaningful signal to applications using this bit.
For example, a 1% reduction in duration may not warrant setting this bit,
while a 50% reduction would.
====
--

[open,refpage='VkPipelineCreationFeedbackFlags',desc='Bitmask of VkPipelineCreationFeedbackFlagBits',type='flags',xrefs='VkPipelineCreationFeedback VkPipelineCreationFeedbackFlagBits',alias='VkPipelineCreationFeedbackFlagsEXT']
--
include::{generated}/api/flags/VkPipelineCreationFeedbackFlags.adoc[]

ifdef::VK_EXT_pipeline_creation_feedback[]
or the equivalent

include::{generated}/api/flags/VkPipelineCreationFeedbackFlagsEXT.adoc[]
endif::VK_EXT_pipeline_creation_feedback[]

tname:VkPipelineCreationFeedbackFlags is a bitmask type for providing zero
or more elink:VkPipelineCreationFeedbackFlagBits.
--
