# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# To run a Docker container on Azure, this image is required per 'Hosted agents' in
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops&tabs=yaml
pool:
  vmImage: 'ubuntu-latest'

container: khronosgroup/docker-images:vulkan-docs

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    set -x
    cat /etc/lsb-release
    echo "In Azure script action, files are:" ; ls
  displayName: 'Run a multi-line script'
