#!/usr/bin/env bash
#
# Copyright 2016-2021 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

# makeAllExts - invoke Makefile with the right options to build with all
# extensions included.

./makeSpec -clean -spec all $*
