#!/usr/bin/env bash
#
# Copyright 2016-2021 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

# makeExt - invoke Makefile with the right options to build with a
# specific extension included. Only one extension may be specified;
# for more complex builds, invoke 'makeSpec' directly.
#
# Usage: makeExt extension targets

extension=$1
shift

./makeSpec -clean -spec core -extension $extension $*
