version = 1
SPDX-PackageName = "Vulkan-Docs"
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/Vulkan-Docs"

[[annotations]]
path = ["images/**.svg", "config/chunkindex/custom.patch", "config/CI/**", "config/**/docinfo-header.html", "build_tests/expectations/**", "build_tests/images/**.svg", "images/proposals/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2026 The Khronos Group Inc."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "katex/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-2019 Khan Academy and other contributors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "config/chunkindex/lunr.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 Oliver Nightingale"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "config/optimize-pdf"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2016 OpenDevise Inc. and the Asciidoctor Project"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "config/khronos.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Dan Allen"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "config/fonts/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2019 M+ Fonts Project"
SPDX-License-Identifier = "LicenseRef-MPLUS"

[[annotations]]
path = "scripts/htmldiff/htmldiff.pl"
precedence = "aggregate"
SPDX-FileCopyrightText = ["1998-2006 MACS, Inc.", "2007 SiSco, Inc."]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.json", "scripts/vuidCounts.py", "config/chunkindex/addscript.**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2026 The Khronos Group Inc."
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "config/copyright-spec.adoc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2026 The Khronos Group Inc"
SPDX-License-Identifier = "LicenseRef-KhronosSpecCopyright"

[[annotations]]
path = "scripts/asciidoctor-chunker/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 Wataru Shito (@waterloo_jp)"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ".gitlab/merge_request_templates/extensiontemplate.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 The Khronos Group Inc"
SPDX-License-Identifier = "CC-BY-4.0"
