#!/usr/bin/env bash
specdir=out
RHOST=kaylee
RPATH=/home/khronos/memberftp/vulkan/

cd $specdir || (echo "Can't cd to $specdir !" ; exit 1)
# Create tarball and upload/copy/extract that to speed things
echo "Creating tarball"
tar czpf /tmp/tarball.tgz .
echo "Uploading tarball"
scp /tmp/tarball.tgz $RHOST:$RPATH
echo "Extracting tarball on server"
# Could add "&& rm tarball.tgz" but nice to have around
ssh $RHOST "cd $RPATH && tar xzpf tarball.tgz"
echo "Removing tarball"
rm /tmp/tarball.tgz

# scp -rp * $RHOST:$RPATH
