// Copyright 2014-2022 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

ifdef::VKSC_VERSION_1_0[]

[appendix]
[[appendix-scid]]
= Safety Critical ID Tags (SCID)

Safety Critical ID tags are used within the Vulkan SC Specification to
reference safety critical change justifications intended to give the reader
an understanding of why deviations from the Vulkan Specification have been
made.

The SCID tags reference the Change Justification Table in the Introduction.

== Format of SCID Tags

SCID tags are formatted like this:

[source,asciidoc]
----
<<SCID-#>>
----

where # is replaced by the specific SCID number (e.g. SCID-3).
The SCID will show up in the specification enclosed with [] brackets (e.g.
[SCID-3]).

If multiple SCIDs are being referenced, separate them with a comma (e.g.
[SCID-3], [SCID-5]).

The SCIDs should be placed at the end of the sentence describing the change
(e.g. This flag is not supported in Vulkan SC [SCID-8]).
A SCID should also be added to any entry that will appear in the Vulkan SC
deviations appendix.

endif::VKSC_VERSION_1_0[]
