// Copyright 2014-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[platformCreateSurface_win32]]
=== Win32 Platform

[open,refpage='vkCreateWin32SurfaceKHR',desc='Create a VkSurfaceKHR object for an Win32 native window',type='protos']
--
:refpage: vkCreateWin32SurfaceKHR

To create a sname:VkSurfaceKHR object for a Win32 window, call:

include::{generated}/api/protos/vkCreateWin32SurfaceKHR.adoc[]

  * pname:instance is the instance to associate the surface with.
  * pname:pCreateInfo is a pointer to a sname:VkWin32SurfaceCreateInfoKHR
    structure containing parameters affecting the creation of the surface
    object.
  * pname:pAllocator is the allocator used for host memory allocated for the
    surface object when there is no more specific allocator available (see
    <<memory-allocation,Memory Allocation>>).
  * pname:pSurface is a pointer to a slink:VkSurfaceKHR handle in which the
    created surface object is returned.

include::{generated}/validity/protos/vkCreateWin32SurfaceKHR.adoc[]

Some Vulkan functions may: call the `SendMessage` system API when
interacting with a sname:VkSurfaceKHR through a sname:VkSwapchainKHR.
In a multithreaded environment, calling `SendMessage` from a thread that is
not the thread associated with pname:pCreateInfo::pname:hwnd will block
until the application has processed the window message.
Thus, applications should: either call these Vulkan functions on the message
pump thread, or make sure their message pump is actively running.
Failing to do so may: result in deadlocks.

The functions subject to this requirement are:

  * flink:vkCreateSwapchainKHR
  * flink:vkDestroySwapchainKHR
  * flink:vkAcquireNextImageKHR and flink:vkAcquireNextImage2KHR
  * flink:vkQueuePresentKHR
ifdef::VK_EXT_swapchain_maintenance1[]
  * flink:vkReleaseSwapchainImagesEXT
endif::VK_EXT_swapchain_maintenance1[]
ifdef::VK_EXT_full_screen_exclusive[]
  * flink:vkAcquireFullScreenExclusiveModeEXT
  * flink:vkReleaseFullScreenExclusiveModeEXT
endif::VK_EXT_full_screen_exclusive[]
ifdef::VK_EXT_hdr_metadata[]
  * flink:vkSetHdrMetadataEXT
endif::VK_EXT_hdr_metadata[]
--

[open,refpage='VkWin32SurfaceCreateInfoKHR',desc='Structure specifying parameters of a newly created Win32 surface object',type='structs']
--
The sname:VkWin32SurfaceCreateInfoKHR structure is defined as:

include::{generated}/api/structs/VkWin32SurfaceCreateInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is reserved for future use.
  * pname:hinstance is the Win32 code:HINSTANCE for the window to associate
    the surface with.
  * pname:hwnd is the Win32 code:HWND for the window to associate the
    surface with.

.Valid Usage
****
  * [[VUID-VkWin32SurfaceCreateInfoKHR-hinstance-01307]]
    pname:hinstance must: be a valid Win32 code:HINSTANCE
  * [[VUID-VkWin32SurfaceCreateInfoKHR-hwnd-01308]]
    pname:hwnd must: be a valid Win32 code:HWND
****

include::{generated}/validity/structs/VkWin32SurfaceCreateInfoKHR.adoc[]
--

With Win32, pname:minImageExtent, pname:maxImageExtent, and
pname:currentExtent must: always equal the window size.

The pname:currentExtent of a Win32 surface must: have both pname:width and
pname:height greater than 0, or both of them 0.

[NOTE]
.Note
====
Due to above restrictions,
ifdef::VK_EXT_swapchain_maintenance1[]
unless slink:VkSwapchainPresentScalingCreateInfoEXT is used to specify
handling of disparities between surface and swapchain dimensions,
endif::VK_EXT_swapchain_maintenance1[]
it is only possible to create a new swapchain on this platform with
pname:imageExtent being equal to the current size of the window, as reported
in slink:VkSurfaceCapabilitiesKHR::pname:currentExtent.

The window size may: become [eq]#(0, 0)# on this platform (e.g. when the
window is minimized), and so a swapchain cannot: be created until the size
changes.
====

[open,refpage='VkWin32SurfaceCreateFlagsKHR',desc='Reserved for future use',type='flags']
--
include::{generated}/api/flags/VkWin32SurfaceCreateFlagsKHR.adoc[]

tname:VkWin32SurfaceCreateFlagsKHR is a bitmask type for setting a mask, but
is currently reserved for future use.
--
