// Copyright 2018-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[present-wait2]]
== Present Wait

Applications wanting to control the pacing of the application by monitoring
when presentation processes have completed to limit the number of
outstanding images queued for presentation, need to have a method of being
signaled during the presentation process.

ifdef::VK_GOOGLE_display_timing[]
Using the `apiext:VK_GOOGLE_display_timing` extension, applications can
discover when images were presented, but only asynchronously.
endif::VK_GOOGLE_display_timing[]

Providing a mechanism which allows applications to block, waiting for a
specific step of the presentation process to complete allows them to control
the amount of outstanding work (and hence the potential lag in responding to
user input or changes in the rendering environment).

The `apiext:VK_KHR_present_wait2` extension allows applications to tell the
presentation engine at the flink:vkQueuePresentKHR call that it plans on
waiting for presentation by passing a slink:VkPresentId2KHR structure.
The pname:presentId passed in that structure may then be passed to a future
flink:vkWaitForPresent2KHR call to cause the application to block until that
presentation is finished.

This functionality was originally provided by the
`apiext:VK_KHR_present_wait` extension, which has been deprecated and
replaced by `apiext:VK_KHR_present_wait2`.

[open,refpage='VkPresentWait2InfoKHR',desc='Structure describing parameters of a presentation wait',type='structs']
--
The sname:VkPresentWait2InfoKHR structure is defined as:

include::{generated}/api/structs/VkPresentWait2InfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentId is the presentation presentId to wait for.
  * pname:timeout is the timeout period in units of nanoseconds.
    pname:timeout is adjusted to the closest value allowed by the
    implementation-dependent timeout accuracy, which may: be substantially
    longer than one nanosecond, and may: be longer than the requested
    period.

include::{generated}/validity/structs/VkPresentWait2InfoKHR.adoc[]
--
