#! /bin/bash
#
# Copyright 2023-2024 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

echo "Note: Run 'pytest test_reflow.py' first to generate results/"

for result_file in results/*/src-*.adoc; do
  src_file=$(basename $result_file)
  test_name=${src_file%.adoc}
  test_name=${test_name#src-}
  tag=$(basename $(dirname $result_file))

  cp -f "$result_file" "expect-$test_name-$tag.adoc"
done
