// Copyright (c) 2018-2022 NVIDIA Corporation.
//
// SPDX-License-Identifier: CC-BY-4.0

[[present-barrier]]
== Present Barrier

The `apiext:VK_NV_present_barrier` extension allows applications to
synchronize corresponding presentation requests across multiple swapchains
using the _present barrier_.
A swapchain is said to be using the _present barrier_ if the swapchain is
created by adding a slink:VkSwapchainPresentBarrierCreateInfoNV structure to
the pname:pNext chain of the slink:VkSwapchainCreateInfoKHR structure, and
setting
slink:VkSwapchainPresentBarrierCreateInfoNV::pname:presentBarrierEnable to
true.

A set of corresponding presentation requests is defined as exactly one
queued presentation request associated with each swapchain using the present
barrier, whether or not that queued request has executed.
A given presentation request is added, when created by calling
flink:vkQueuePresentKHR and specifying a swapchain using the present
barrier, either to the oldest existing set of corresponding requests for
which there is no existing member associated with the request's swapchain,
or to a new set of corresponding requests if no such set exists.

A set of corresponding requests is said to be _full_ when it contains one
request from each swapchain using the present barrier.
Queued presentation of an image to a swapchain using the _present barrier_
is _deferred_ by the implementation until the set of corresponding requests
is full, and the visibility operations associated with all requests in that
set, as described by flink:vkQueuePresentKHR, have completed.

Additionally, the set of swapchains using the present barrier can be in the
same process, or different processes running under the same operating
system.
And if the required synchronization hardware is connected and correctly
configured, this extension also supports applications to synchronize
corresponding presentation requests using the _present barrier_ across
distributed systems.
However, the configuration mechanism of the required hardware is outside the
scope of the Vulkan specification and this extension.

[open,refpage='VkSwapchainPresentBarrierCreateInfoNV',desc='specify the present barrier membership of this swapchain',type='structs']
--
The slink:VkSwapchainPresentBarrierCreateInfoNV structure is defined as:

include::{generated}/api/structs/VkSwapchainPresentBarrierCreateInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentBarrierEnable is a boolean value indicating a request for
    using the _present barrier_.

If the pname:pNext chain of slink:VkSwapchainCreateInfoKHR does not include
this structure, the default value for pname:presentBarrierEnable is
ename:VK_FALSE, meaning the swapchain does not request to use the present
barrier.
Additionally, when recreating a swapchain that was using the present
barrier, and the pname:pNext chain of slink:VkSwapchainCreateInfoKHR does
not include this structure, it means the swapchain will stop using the
present barrier.

include::{generated}/validity/structs/VkSwapchainPresentBarrierCreateInfoNV.adoc[]
--
