# Copyright 2020 The Khronos Group Inc.
# SPDX-License-Identifier: MIT

# Vulkan spec PDF stylesheet

# Use fallback theme to get some math special characters
extends: default-with-fallback-font

# Add chapter names to the page footer
footer:
  recto:
    right:
      content: '{chapter-title} | {page-number}'
  verso:
    left:
      content: '{page-number} | {chapter-title}'

# Add a role for VUID tags
role:
  vuid:
    font_family: $literal_font_family
    font_size: round($base_font_size * 0.85)
    font_color: 808080
