// Copyright 2018-2025 The Khronos Group Inc.
// Copyright 2020-2024 NVIDIA Corporation
// SPDX-License-Identifier: CC-BY-4.0

==== Acquiring and Releasing Displays

On some platforms, access to displays is limited to a single process or
native driver instance.
On such platforms, some or all of the displays may not be available to
Vulkan if they are already in use by a native windowing system or other
application.

ifdef::VK_EXT_acquire_xlib_display[]
include::{chapters}/VK_EXT_acquire_xlib_display/acquire_xlib_display.adoc[]
endif::VK_EXT_acquire_xlib_display[]

ifdef::VK_NV_acquire_winrt_display[]
[open,refpage='vkAcquireWinrtDisplayNV',desc='Acquire access to a VkDisplayKHR',type='protos']
--
:refpage: vkAcquireWinrtDisplayNV

To acquire permission to directly access a display in Vulkan on Windows 10,
call:

include::{generated}/api/protos/vkAcquireWinrtDisplayNV.adoc[]

  * pname:physicalDevice The physical device the display is on.
  * pname:display The display the caller wishes to control in Vulkan.

All permissions necessary to control the display are granted to the Vulkan
instance associated with pname:physicalDevice until the display is released
or the application is terminated.
Permission to access the display may: be revoked by events that cause
Windows 10 itself to lose access to pname:display.
If this has happened, operations which require access to the display must:
fail with an appropriate error code.
If permission to access pname:display has already been acquired by another
entity, the call must: return the error code
ename:VK_ERROR_INITIALIZATION_FAILED.

[NOTE]
====
The Vulkan instance acquires control of a
https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaytarget["`winrt::Windows::Devices::Display::Core::DisplayTarget`"]
by performing an operation equivalent to
https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaymanager.tryacquiretarget["`winrt::Windows::Devices::Display::Core::DisplayManager.TryAcquireTarget()`"]
on the "`DisplayTarget`".
====

[NOTE]
====
One example of when Windows 10 loses access to a display is when the display
is hot-unplugged.
====

[NOTE]
====
One example of when a display has already been acquired by another entity is
when the Windows desktop compositor (DWM) is in control of the display.
Beginning with Windows 10 version 2004 it is possible to cause DWM to
release a display by using the "`Advanced display settings`" sub-page of the
"`Display settings`" control panel.
flink:vkAcquireWinrtDisplayNV does not itself cause DWM to release a
display; this action must be performed outside of Vulkan.
====

include::{chapters}/commonvalidity/no_dynamic_allocations_common.adoc[]

include::{generated}/validity/protos/vkAcquireWinrtDisplayNV.adoc[]
--

[open,refpage='vkGetWinrtDisplayNV',desc='Query the VkDisplayKHR corresponding to a WinRT DisplayTarget',type='protos']
--
:refpage: vkGetWinrtDisplayNV

When acquiring displays on Windows 10, an application may also wish to
enumerate and identify them using a native handle rather than a
sname:VkDisplayKHR handle.

To determine the sname:VkDisplayKHR handle corresponding to a
https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaytarget["`winrt::Windows::Devices::Display::Core::DisplayTarget`"],
call:

include::{generated}/api/protos/vkGetWinrtDisplayNV.adoc[]

  * pname:physicalDevice The physical device on which to query the display
    handle.
  * pname:deviceRelativeId The value of the
    https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaytarget.adapterrelativeid["`AdapterRelativeId`"]
    property of a
    https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displaytarget["`DisplayTarget`"]
    that is enumerated by a
    https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displayadapter["`DisplayAdapter`"]
    with an
    https://docs.microsoft.com/en-us/uwp/api/windows.devices.display.core.displayadapter.id["`Id`"]
    property matching the pname:deviceLUID property of a
    slink:VkPhysicalDeviceIDProperties for pname:physicalDevice.
  * pname:pDisplay The corresponding slink:VkDisplayKHR handle will be
    returned here.

If there is no slink:VkDisplayKHR corresponding to pname:deviceRelativeId on
pname:physicalDevice, dlink:VK_NULL_HANDLE must: be returned in
pname:pDisplay.

include::{chapters}/commonvalidity/no_dynamic_allocations_common.adoc[]

include::{generated}/validity/protos/vkGetWinrtDisplayNV.adoc[]
--
endif::VK_NV_acquire_winrt_display[]

ifdef::VK_EXT_acquire_drm_display[]
include::{chapters}/VK_EXT_acquire_drm_display/acquire_drm_display.adoc[]
endif::VK_EXT_acquire_drm_display[]

[open,refpage='vkReleaseDisplayEXT',desc='Release access to an acquired VkDisplayKHR',type='protos']
--
To release a previously acquired display, call:

include::{generated}/api/protos/vkReleaseDisplayEXT.adoc[]

  * pname:physicalDevice The physical device the display is on.
  * pname:display The display to release control of.

include::{generated}/validity/protos/vkReleaseDisplayEXT.adoc[]
--
