// Copyright (c) 2021-2022 The Brenwill Workshop Ltd.
//
// SPDX-License-Identifier: CC-BY-4.0

[[metal-objects]]
=== Metal Objects

A Vulkan implementation that is layered on top of Metal on Apple device
platform, and implements the `apiext:VK_EXT_metal_objects` extension,
supports the ability to import and export the underlying Metal objects
associated with specific Vulkan objects.

The underlying Metal objects associated with certain Vulkan objects can be
exported from those Vulkan objects using the pname:pNext chain of the
slink:VkExportMetalObjectsInfoEXT parameter of the
flink:vkExportMetalObjectsEXT command.

An slink:VkDeviceMemory object can be allocated on an existing
code:MTLBuffer object, by including the code:MTLBuffer object in a
slink:VkImportMetalBufferInfoEXT structure in the pname:pNext chain of the
slink:VkMemoryAllocateInfo structure in the flink:vkAllocateMemory command.

A new slink:VkImage object can be created on an existing code:IOSurface
object, or one or more existing Metal code:MTLTexture objects, by including
those Metal objects in either slink:VkImportMetalIOSurfaceInfoEXT or
slink:VkImportMetalTextureInfoEXT structures in the pname:pNext chain of the
slink:VkImageCreateInfo structure in the flink:vkCreateImage command.

[open,refpage='VkExportMetalObjectCreateInfoEXT',desc='Structure that identifies the Metal objects that can be exported from Vulkan objects',type='structs']
--
To export Metal objects from Vulkan objects, the app must: first indicate
the intention to do so during the creation of the Vulkan object, by
including one or more slink:VkExportMetalObjectCreateInfoEXT structures in
the pname:pNext chain of the slink:VkInstanceCreateInfo,
slink:VkMemoryAllocateInfo, slink:VkImageCreateInfo,
slink:VkImageViewCreateInfo, slink:VkBufferViewCreateInfo,
slink:VkSemaphoreCreateInfo, or slink:VkEventCreateInfo, in the
corresponding Vulkan object creation command.

The sname:VkExportMetalObjectCreateInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalObjectCreateInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:exportObjectType is a elink:VkExportMetalObjectTypeFlagBitsEXT
    indicating the type of Metal object that the application may request to
    be exported from the Vulkan object.

include::{generated}/validity/structs/VkExportMetalObjectCreateInfoEXT.adoc[]
--

[open,refpage='VkExportMetalObjectTypeFlagBitsEXT',desc='Bitmask specifying Metal object types that can be exported from a Vulkan object',type='enums']
--
Bits which indicate the types of Metal objects that may be exported from a
corresponding Vulkan object are:

include::{generated}/api/enums/VkExportMetalObjectTypeFlagBitsEXT.adoc[]

  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_DEVICE_BIT_EXT indicates a Metal
    code:MTLDevice may be exported.
  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_COMMAND_QUEUE_BIT_EXT indicates
    a Metal code:MTLCommandQueue may be exported.
  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_BUFFER_BIT_EXT indicates a Metal
    code:MTLBuffer may be exported.
  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_TEXTURE_BIT_EXT indicates a
    Metal code:MTLTexture may be exported.
  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_IOSURFACE_BIT_EXT indicates a
    Metal code:IOSurface may be exported.
  * ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_SHARED_EVENT_BIT_EXT indicates a
    Metal code:MTLSharedEvent may be exported.
--

[open,refpage='VkExportMetalObjectTypeFlagsEXT',desc='Bitmask of VkExportMetalObjectTypeFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkExportMetalObjectTypeFlagsEXT.adoc[]

tname:VkExportMetalObjectTypeFlagsEXT is a bitmask type for setting a mask
of zero or more elink:VkExportMetalObjectTypeFlagBitsEXT.
--

[open,refpage='vkExportMetalObjectsEXT',desc='Export Metal objects from the corresponding Vulkan objects',type='protos']
--
To export Metal objects that underlie Vulkan objects, call:

include::{generated}/api/protos/vkExportMetalObjectsEXT.adoc[]

  * pname:device is the device that created the Vulkan objects.
  * pname:pMetalObjectsInfo is a pointer to a
    slink:VkExportMetalObjectsInfoEXT structure whose pname:pNext chain
    contains structures, each identifying a Vulkan object and providing a
    pointer through which the Metal object will be returned.

include::{generated}/validity/protos/vkExportMetalObjectsEXT.adoc[]
--

[open,refpage='VkExportMetalObjectsInfoEXT',desc='Structure whose pNext chain identifies Vulkan objects and corresponding Metal objects',type='structs']
--
The sname:VkExportMetalObjectsInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalObjectsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.

.Valid Usage
****
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06791]]
    If the pname:pNext chain includes a slink:VkExportMetalDeviceInfoEXT
    structure, the slink:VkInstance must: have been created with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_DEVICE_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkInstanceCreateInfo structure in the
    flink:vkCreateInstance command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06792]]
    If the pname:pNext chain includes a
    slink:VkExportMetalCommandQueueInfoEXT structure, the slink:VkInstance
    must: have been created with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_COMMAND_QUEUE_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkInstanceCreateInfo structure in the
    flink:vkCreateInstance command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06793]]
    If the pname:pNext chain includes a slink:VkExportMetalBufferInfoEXT
    structure, the slink:VkDeviceMemory in its pname:memory member must:
    have been allocated with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_BUFFER_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkMemoryAllocateInfo structure in the
    flink:vkAllocateMemory command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06794]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, exactly one of its pname:image, pname:imageView, or
    pname:bufferView members must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06795]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and its pname:image member is not dlink:VK_NULL_HANDLE, the
    slink:VkImage in its pname:image member must: have been created with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_TEXTURE_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkImageCreateInfo structure in the
    flink:vkCreateImage command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06796]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and its pname:imageView member is not dlink:VK_NULL_HANDLE,
    the slink:VkImageView in its pname:imageView member must: have been
    created with ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_TEXTURE_BIT_EXT in
    the pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkImageViewCreateInfo structure in the
    flink:vkCreateImageView command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06797]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and its pname:bufferView member is not dlink:VK_NULL_HANDLE,
    the slink:VkBufferView in its pname:bufferView member must: have been
    created with ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_TEXTURE_BIT_EXT in
    the pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkBufferViewCreateInfo structure in the
    flink:vkCreateBufferView command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06798]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and if either its pname:image or pname:imageView member is
    not dlink:VK_NULL_HANDLE, then pname:plane must: be
    ename:VK_IMAGE_ASPECT_PLANE_0_BIT, ename:VK_IMAGE_ASPECT_PLANE_1_BIT, or
    ename:VK_IMAGE_ASPECT_PLANE_2_BIT
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06799]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and if the slink:VkImage in its pname:image member does not
    have a multi-planar format, then its pname:plane member must: be
    ename:VK_IMAGE_ASPECT_PLANE_0_BIT
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06800]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and if the slink:VkImage in its pname:image member has a
    multi-planar format with only two planes, then its pname:plane member
    must: not be ename:VK_IMAGE_ASPECT_PLANE_2_BIT
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06801]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and if the slink:VkImageView in its pname:imageView member
    does not have a multi-planar format, then its pname:plane member must:
    be ename:VK_IMAGE_ASPECT_PLANE_0_BIT
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06802]]
    If the pname:pNext chain includes a slink:VkExportMetalTextureInfoEXT
    structure, and if the slink:VkImageView in its pname:imageView member
    has a multi-planar format with only two planes, then its pname:plane
    member must: not be ename:VK_IMAGE_ASPECT_PLANE_2_BIT
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06803]]
    If the pname:pNext chain includes a slink:VkExportMetalIOSurfaceInfoEXT
    structure, the slink:VkImage in its pname:image member must: have been
    created with ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_IOSURFACE_BIT_EXT
    in the pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkImageCreateInfo structure in the
    flink:vkCreateImage command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06804]]
    If the pname:pNext chain includes a
    slink:VkExportMetalSharedEventInfoEXT structure, exactly one of its
    pname:semaphore or pname:event members must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06805]]
    If the pname:pNext chain includes a
    slink:VkExportMetalSharedEventInfoEXT structure, and its pname:semaphore
    member is not dlink:VK_NULL_HANDLE, the slink:VkSemaphore in its
    pname:semaphore member must: have been created with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_SHARED_EVENT_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkSemaphoreCreateInfo structure in the
    flink:vkCreateSemaphore command
  * [[VUID-VkExportMetalObjectsInfoEXT-pNext-06806]]
    If the pname:pNext chain includes a
    slink:VkExportMetalSharedEventInfoEXT structure, and its pname:event
    member is not dlink:VK_NULL_HANDLE, the slink:VkEvent in its pname:event
    member must: have been created with
    ename:VK_EXPORT_METAL_OBJECT_TYPE_METAL_SHARED_EVENT_BIT_EXT in the
    pname:exportObjectType member of a
    slink:VkExportMetalObjectCreateInfoEXT structure in the pname:pNext
    chain of the slink:VkEventCreateInfo structure in the
    flink:vkCreateEvent command
****

include::{generated}/validity/structs/VkExportMetalObjectsInfoEXT.adoc[]
--

[open,refpage='VkExportMetalDeviceInfoEXT',desc='Structure that identifies a VkDevice object and corresponding Metal MTLDevice object',type='structs']
--
To export the Metal code:MTLDevice object underlying the
slink:VkPhysicalDevice associated with a slink:VkDevice object, include a
sname:VkExportMetalDeviceInfoEXT structure in the pname:pNext chain of the
pname:pMetalObjectsInfo parameter of a flink:vkExportMetalObjectsEXT call.

The sname:VkExportMetalDeviceInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalDeviceInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:mtlDevice is the Metal `id<MTLDevice>` object underlying the
    slink:VkPhysicalDevice associated with the slink:VkDevice object
    identified in the call.
    The implementation will return the code:MTLDevice in this member, or it
    will return `NULL` if no code:MTLDevice could be found underlying the
    slink:VkPhysicalDevice object.

include::{generated}/validity/structs/VkExportMetalDeviceInfoEXT.adoc[]
--

[open,refpage='MTLDevice_id',desc='Metal MTLDevice type reference',type='basetypes']
--
The type `id<MTLDevice>` is defined in Apple's Metal framework, but to
remove an unnecessary compile time dependency, an incomplete type definition
of basetype:MTLDevice_id is provided in the Vulkan headers:

include::{generated}/api/basetypes/MTLDevice_id.adoc[]
--

[open,refpage='VkExportMetalCommandQueueInfoEXT',desc='Structure that identifies a VkQueue object and corresponding Metal MTLCommandQueue object',type='structs']
--
To export the Metal code:MTLCommandQueue object underlying a slink:VkQueue
object, include a sname:VkExportMetalCommandQueueInfoEXT structure in the
pname:pNext chain of the pname:pMetalObjectsInfo parameter of a
flink:vkExportMetalObjectsEXT call.

The sname:VkExportMetalCommandQueueInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalCommandQueueInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:queue is a slink:VkQueue.
  * pname:mtlCommandQueue is the Metal `id<MTLCommandQueue>` object
    underlying the slink:VkQueue object in pname:queue.
    The implementation will return the code:MTLCommandQueue in this member,
    or it will return `NULL` if no code:MTLCommandQueue could be found
    underlying the slink:VkQueue object.

include::{generated}/validity/structs/VkExportMetalCommandQueueInfoEXT.adoc[]
--

[open,refpage='MTLCommandQueue_id',desc='Metal MTLCommandQueue type reference',type='basetypes']
--
The type `id<MTLCommandQueue>` is defined in Apple's Metal framework, but to
remove an unnecessary compile time dependency, an incomplete type definition
of basetype:MTLCommandQueue_id is provided in the Vulkan headers:

include::{generated}/api/basetypes/MTLCommandQueue_id.adoc[]
--

[open,refpage='VkExportMetalBufferInfoEXT',desc='Structure that identifies a VkDeviceMemory object and corresponding Metal MTLBuffer object',type='structs']
--
To export the Metal code:MTLBuffer object underlying a slink:VkDeviceMemory
object, include a sname:VkExportMetalBufferInfoEXT structure in the
pname:pNext chain of the pname:pMetalObjectsInfo parameter of a
flink:vkExportMetalObjectsEXT call.

The sname:VkExportMetalBufferInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalBufferInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:memory is a slink:VkDeviceMemory.
  * pname:mtlBuffer is the Metal `id<MTLBuffer>` object underlying the
    slink:VkDeviceMemory object in pname:memory.
    The implementation will return the code:MTLBuffer in this member, or it
    will return `NULL` if no code:MTLBuffer could be found underlying the
    slink:VkDeviceMemory object.

include::{generated}/validity/structs/VkExportMetalBufferInfoEXT.adoc[]
--

[open,refpage='VkImportMetalBufferInfoEXT',desc='Structure that identifies a Metal MTLBuffer object to use when creating a VkDeviceMemory object.',type='structs']
--
To import a Metal code:MTLBuffer object to underlie a slink:VkDeviceMemory
object, include a sname:VkImportMetalBufferInfoEXT structure in the
pname:pNext chain of the slink:VkMemoryAllocateInfo structure in a
flink:vkAllocateMemory command.

The sname:VkImportMetalBufferInfoEXT structure is defined as:

include::{generated}/api/structs/VkImportMetalBufferInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:mtlBuffer is the Metal `id<MTLBuffer>` object that is to underlie
    the slink:VkDeviceMemory.

The app must: ensure that the configuration of the `id<MTLBuffer>` object is
compatible with the configuration of the slink:VkDeviceMemory.
Failure to do so results in undefined: behavior.

include::{generated}/validity/structs/VkImportMetalBufferInfoEXT.adoc[]
--

[open,refpage='MTLBuffer_id',desc='Metal MTLBuffer type reference',type='basetypes']
--
The type `id<MTLBuffer>` is defined in Apple's Metal framework, but to
remove an unnecessary compile time dependency, an incomplete type definition
of basetype:MTLBuffer_id is provided in the Vulkan headers:

include::{generated}/api/basetypes/MTLBuffer_id.adoc[]
--

[open,refpage='VkExportMetalTextureInfoEXT',desc='Structure that identifies a VkImage, VkImageView, or VkBufferView object and corresponding Metal MTLTexture object',type='structs']
--
To export a Metal code:MTLTexture object underlying a slink:VkImage,
slink:VkImageView, or slink:VkBufferView object, include a
sname:VkExportMetalTextureInfoEXT structure in the pname:pNext chain of the
pname:pMetalObjectsInfo parameter of a flink:vkExportMetalObjectsEXT call.

The sname:VkExportMetalTextureInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalTextureInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:image is dlink:VK_NULL_HANDLE or a slink:VkImage.
  * pname:imageView is dlink:VK_NULL_HANDLE or a slink:VkImageView.
  * pname:bufferView is dlink:VK_NULL_HANDLE or a slink:VkBufferView.
  * pname:plane indicates the plane of a multi-planar slink:VkImage or
    slink:VkImageView.
  * pname:mtlTexture is the Metal `id<MTLTexture>` object underlying the
    slink:VkImage, slink:VkImageView, or slink:VkBufferView object in
    pname:image, pname:imageView, or pname:bufferView, respectively, at the
    plane indicated in pname:aspectMask.
    The implementation will return the code:MTLTexture in this member, or it
    will return `NULL` if no code:MTLTexture could be found underlying the
    slink:VkImage, slink:VkImageView, or slink:VkBufferView object, at the
    plane indicated in pname:aspectMask.

include::{generated}/validity/structs/VkExportMetalTextureInfoEXT.adoc[]
--

[open,refpage='VkImportMetalTextureInfoEXT',desc='Structure that identifies Metal MTLTexture objects to use when creating a VkImage.',type='structs']
--
To import one or more existing Metal code:MTLTexture objects to underlie a
slink:VkImage object, include one or more sname:VkImportMetalTextureInfoEXT
structures in the pname:pNext chain of the slink:VkImageCreateInfo structure
in a flink:vkCreateImage command.

The sname:VkImportMetalTextureInfoEXT structure is defined as:

include::{generated}/api/structs/VkImportMetalTextureInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:plane indicates the plane of the slink:VkImage that the
    `id<MTLTexture>` object should be attached to.
  * pname:mtlTexture is a the Metal `id<MTLTexture>` object that is to
    underlie the slink:VkImage plane.

The pname:pNext chain must: include one sname:VkImportMetalTextureInfoEXT
structure for each plane in the slink:VkImage.
The app must: ensure that the configuration of the Metal `id<MTLTexture>`
objects are compatible with the configuration of the slink:VkImage.
Failure to do so results in undefined: behavior.

include::{generated}/validity/structs/VkImportMetalTextureInfoEXT.adoc[]
--

[open,refpage='MTLTexture_id',desc='Metal MTLTexture type reference',type='basetypes']
--
The type `id<MTLTexture>` is defined in Apple's Metal framework, but to
remove an unnecessary compile time dependency, an incomplete type definition
of basetype:MTLTexture_id is provided in the Vulkan headers:

include::{generated}/api/basetypes/MTLTexture_id.adoc[]
--

[open,refpage='VkExportMetalIOSurfaceInfoEXT',desc='Structure that identifies a VkImage object and corresponding Metal IOSurfaceRef object',type='structs']
--
To export the Metal basetype:IOSurfaceRef object underlying a slink:VkImage
object, include a sname:VkExportMetalIOSurfaceInfoEXT structure in the
pname:pNext chain of the pname:pMetalObjectsInfo parameter of a
flink:vkExportMetalObjectsEXT call.

The sname:VkExportMetalIOSurfaceInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalIOSurfaceInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:image is a slink:VkImage.
  * pname:ioSurface is the Metal basetype:IOSurfaceRef object underlying the
    slink:VkImage object in pname:image.
    The implementation will return the basetype:IOSurfaceRef in this member,
    or it will return `NULL` if no basetype:IOSurfaceRef could be found
    underlying the slink:VkImage object.

include::{generated}/validity/structs/VkExportMetalIOSurfaceInfoEXT.adoc[]
--

[open,refpage='VkImportMetalIOSurfaceInfoEXT',desc='Structure that identifies a VkImage object and corresponding Metal IOSurfaceRef object to use.',type='structs']
--
To import, or create, a Metal basetype:IOSurfaceRef object to underlie a
slink:VkImage object, include a sname:VkImportMetalIOSurfaceInfoEXT
structure in the pname:pNext chain of the slink:VkImageCreateInfo structure
in a flink:vkCreateImage command.

The sname:VkImportMetalIOSurfaceInfoEXT structure is defined as:

include::{generated}/api/structs/VkImportMetalIOSurfaceInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:ioSurface is dlink:VK_NULL_HANDLE or the Metal
    basetype:IOSurfaceRef object that is to underlie the slink:VkImage.

If pname:ioSurface is not dlink:VK_NULL_HANDLE, it will be used to underlie
the slink:VkImage.
If pname:ioSurface is dlink:VK_NULL_HANDLE, the implementation will create a
new code:IOSurface to underlie the slink:VkImage.

If provided, the app must: ensure that the configuration of the
basetype:IOSurfaceRef object is compatible with the configuration of the
slink:VkImage.
Failure to do so results in undefined: behavior.

include::{generated}/validity/structs/VkImportMetalIOSurfaceInfoEXT.adoc[]
--

[open,refpage='IOSurfaceRef',desc='Metal IOSurfaceRef type reference',type='basetypes']
--
The type basetype:IOSurfaceRef is defined in Apple's CoreGraphics framework,
but to remove an unnecessary compile time dependency, an incomplete type
definition of basetype:IOSurfaceRef is provided in the Vulkan headers:

include::{generated}/api/basetypes/IOSurfaceRef.adoc[]
--

[open,refpage='VkExportMetalSharedEventInfoEXT',desc='Structure that identifies a VkSemaphore or VkEvent object and corresponding Metal MTLSharedEvent object',type='structs']
--
To export the Metal code:MTLSharedEvent object underlying a
slink:VkSemaphore or slink:VkEvent object, include a
sname:VkExportMetalSharedEventInfoEXT structure in the pname:pNext chain of
the pname:pMetalObjectsInfo parameter of a flink:vkExportMetalObjectsEXT
call.

The sname:VkExportMetalSharedEventInfoEXT structure is defined as:

include::{generated}/api/structs/VkExportMetalSharedEventInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:semaphore is dlink:VK_NULL_HANDLE or a slink:VkSemaphore.
  * pname:event is dlink:VK_NULL_HANDLE or a slink:VkEvent.
  * pname:mtlSharedEvent is the Metal `id<MTLSharedEvent>` object underlying
    the slink:VkSemaphore or slink:VkEvent object in pname:semaphore or
    pname:event, respectively.
    The implementation will return the code:MTLSharedEvent in this member,
    or it will return `NULL` if no code:MTLSharedEvent could be found
    underlying the slink:VkSemaphore or slink:VkEvent object.

include::{generated}/validity/structs/VkExportMetalSharedEventInfoEXT.adoc[]
--

[open,refpage='VkImportMetalSharedEventInfoEXT',desc='Structure that identifies a VkSemaphore or VkEvent object and corresponding Metal Shared Event object to use.',type='structs']
--
To import a Metal `id<MTLSharedEvent>` object to underlie a
slink:VkSemaphore or slink:VkEvent object, include a
sname:VkImportMetalSharedEventInfoEXT structure in the pname:pNext chain of
the slink:VkSemaphoreCreateInfo or slink:VkEventCreateInfo structure in a
flink:vkCreateSemaphore or flink:vkCreateEvent command, respectively.

The sname:VkImportMetalSharedEventInfoEXT structure is defined as:

include::{generated}/api/structs/VkImportMetalSharedEventInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:mtlSharedEvent is the Metal `id<MTLSharedEvent>` object that is to
    underlie the slink:VkSemaphore or slink:VkEvent.

ifdef::VK_KHR_timeline_semaphore[]
If the pname:pNext chain of the slink:VkSemaphoreCreateInfo structure
includes both sname:VkImportMetalSharedEventInfoEXT and
slink:VkSemaphoreTypeCreateInfo, the code:signaledValue property of the
imported `id<MTLSharedEvent>` object will be set to pname:initialValue of
slink:VkSemaphoreTypeCreateInfo.
endif::VK_KHR_timeline_semaphore[]

include::{generated}/validity/structs/VkImportMetalSharedEventInfoEXT.adoc[]
--

[open,refpage='MTLSharedEvent_id',desc='Metal MTLSharedEvent type reference',type='basetypes']
--
The type `id<MTLSharedEvent>` is defined in Apple's Metal framework, but to
remove an unnecessary compile time dependency, an incomplete type definition
of basetype:MTLSharedEvent_id is provided in the Vulkan headers:

include::{generated}/api/basetypes/MTLSharedEvent_id.adoc[]
--

