// Copyright 2021-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_EXT_external_semaphore_drm_syncobj
:toc: left
:docs: https://docs.vulkan.org/spec/latest/
:refpages: https://docs.vulkan.org/refpages/latest/refpages/source/
:sectnums:

This extension aims to add interoperability between timeline semaphores and
syncobjs.

== Problem Statement

Linux DRM synchronization objects (syncobjs) are a kernel primitive that can be
used to implement timeline semaphores. Syncobjs can be represented as file
descriptors and some implementations use them as the file type of
`VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT`.

Syncobjs are also used for inter-process synchronization. In some situations it
might be useful to use the same syncobj both as a timeline semaphore and for
inter-process synchronization.

Syncobjs furthermore allow applications to asynchronously wait for individual
timeline points by integrating with `poll(2)`. In some applications it might be
preferable to use this mechanism to wait for signal operations.

Currently, there is no official mechanism for applications to export syncobjs
from timeline semaphores or to import syncobjs into timeline semaphores.
Applications can detect whether the file descriptor used for
`VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT` refers to a syncobj but this
does not solve the issue on implementations that do not use syncobjs.

== Proposal

The `VK_EXT_external_semaphore_drm_syncobj` extension adds a new handle type
`VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_DRM_SYNCOBJ_BIT_EXT`.

This type can be used to import syncobjs into/export syncobjs from timeline
semaphores with _reference_ transference and _permanent_ permanence.

Existing VUs disallow _temporary_ permanence for timeline semaphores.

The mapping between syncobj points and timeline semaphore points is unambiguous
since both support `2^64 - 1` points for timeline operations.

== Issues

=== Should binary semaphores also be supported?

Some implementations use syncobjs to implement binary semaphores. This was not
explored as part of this proposal. If the need arises, the author believes that
support could be added with a new revision of the extension.

For now, binary semaphores already support interop via
`VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT`, albeit without
wait-before-signal support.
