// Copyright 2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_EXT_ycbcr_3plane_16bit_lsb_formats
:toc: left
:docs: https://docs.vulkan.org/spec/latest/
:extensions: {docs}appendices/extensions.html#
:sectnums:

This extension adds support for 10/12/14 bit {YCbCr} formats used by software
decoders like ffmpeg, dav1d and libvpx.

== Problem Statement

Many popular software video decoders - such as ffmpeg/libav, dav1d and libvpx -
use formats for 10, 12 and 14 bit content that are not yet supported in Vulkan,
but are supported by Linux DRM and Mesa GLES (at least the 10 and 12 bit ones).
These formats are long established and optimized for the given task and it would
be very hard for decoders to switch to formats optimized for hardware video
decoders such as P010.

Supporting these formats directly in drivers has various advantages for apps
and system compositors, as it allows to avoid unnecessary copies and/or quality
loss. Further more it can also simplify code-sharing with code-paths for
hardware decoders.

Unfortunately it is not possible to use the existing 16 bit formats such as
VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM as - unlike most formats used by hardware
decoders - the alignment is LSB, not MSB. The bit-values thus need to get
shifted by 6, 4 or 2 bits.

== Proposal

Add the formats in question. For any drivers already supporting YCbCr formats
via shaders this should be straight forward. Values in the 0.0 - 1.0 range just
need to get multiplied by 65535.0 / 1023.0 (for 10 bit), 65535.0 / 4095.0 (for
12 bit) or 65535.0 / 16383.0 (for 14 bit).

== Issues
