// Copyright 2023-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

# VK_EXT_attachment_feedback_loop_dynamic_state
:toc: left
:refpage: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/
:sectnums:

This document proposes adding support for setting attachment feedback loops dynamically.

## Problem Statement

VK_EXT_attachment_feedback_loop_layout added functionality for handling feedback loops as a static pipeline state. Recent advances
in the Vulkan API have moved towards having dynamic states for every corresponding static pipeline state, but there is still no dynamic
state for attachment feedback loops.

This proposal aims to provide this functionality.


## Solution Space

This functionality cannot be provided in any other way.

## Proposal

### API Features

The following features are exposed by this extension:

[source,c]
----
typedef struct VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT {
    VkStructureType    sType;
    void*              pNext;
    VkBool32           attachmentFeedbackLoopDynamicState;
} VkPhysicalDeviceAttachmentFeedbackLoopDynamicStateFeaturesEXT;
----

`attachmentFeedbackLoopDynamicState` is the core feature enabling this extension's functionality.


## Examples

As an example, if an application creates a graphics pipeline using `VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT`,
`vkCmdSetAttachmentFeedbackLoopEnableEXT` can then be used to dynamically enable feedback loops on a per-aspect basis.

## Issues

No known issues.
