// Copyright 2021-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= Proposal Template
:toc: left
:refpage: https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/
:sectnums:

This document details the VK_KHR_ray_tracing_position_fetch extension which exposes the ability to fetch vertex positions from an acceleration structure hit when ray tracing. 

== Problem Statement

Acceleration structures used in ray tracing have the position of the geometry provided to them and have to have at least some derived form of the position encoded in them.
Applications frequently need to know the position or derived attribute of the triangle on a hit, so it is desirable to be able to share that information to avoid duplication.
One of the derived attributes that is of particular interest is the normal of the hit. 

== Solution Space

Options considered:

- Expose the normal (potentially compressed) of the triangle at the hit
- Expose the positions of the triangle at the hit

Exposing the normal is only beneficial for an implementation that cannot expose the positions encoded in the acceleration structure, which seems to be a rare case.
Exposing the positions of the triangle is more general and the application can easily compute the normal itself.

We choose the latter.

== Proposal

=== New SPIR-V decorations

A new SPIR-V extension https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing_position_fetch.html[SPV_KHR_ray_tracing_position_fetch]
adds one ray pipeline shader variable decoration:
  
    * `HitTriangleVertexPositionsKHR` which indicates a builtin which contains the vertex position values for a triangle hit in any-hit or closest hit shaders

=== New SPIR-V instructions

A new SPIR-V extension https://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_ray_tracing_position_fetch.html[SPV_KHR_ray_tracing_position_fetch]
adds one shader instruction:
  
    * `OpRayQueryGetIntersectionTriangleVertexPositionsKHR` which returns the vertex position values for a triangle hit when using ray query

=== New Acceleration structure build flag

    * `VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_DATA_ACCESS_KHR` on an acceleration structure indicates that an application wants to be able to read the data from that acceleration structure

=== GLSL mapping

      gl_HitVertexTrianglePositionsEXT -> HitTriangleVertexPositionsKHR decorated OpVariable

      rayQueryGetIntersectionTriangleVertexPositionsEXT -> OpRayQueryGetIntersectionTriangleVertexPositionsKHR instruction


=== HLSL mapping

HLSL does not provide this functionality yet.

== Issues

None.

== Further Functionality

None.
