// Copyright 2021-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

= VK_KHR_shader_constant_data
:toc: left
:docs: https://docs.vulkan.org/spec/latest/
:extensions: {docs}appendices/extensions.html#
:sectnums:
// Required so images render in github
ifndef::images[:images: ../images]

This extension allows applications to specify large constant data arrays in their shaders, and to specialize them.

== Problem Statement

https://gitlab.khronos.org/spirv/spirv-extensions/-/blob/SPV_KHR_large_constants/SPV_KHR_constant_data.asciidoc[`SPV_KHR_constant_data`] added the capability to specify arrayed data as constants in SPIR-V, to enable the specification of strings as data, or other chunks of data, in a more compact manner than previously available.
A detailed problem statement on why this was added to SPIR-V is provided in the https://gitlab.khronos.org/spirv/spirv-extensions/-/blob/SPV_KHR_large_constants/SPV_KHR_constant_data.asciidoc[`SPV_KHR_constant_data` specification].

Support for this extension is required in Vulkan to add better string support to Vulkan, and particularly for link:{extensions}VK_KHR_shader_abort[VK_KHR_shader_abort].


== Solution Space

For the most part, exposing this extension is as trivial as most other SPIR-V extensions.
Despite specialization constant data being new in SPIR-V, the Vulkan specialization constant API already supports constants of arbitrary size, as long as they match the size of the data in SPIR-V.

== Proposal

The only change to the Vulkan API is to enable shaders using the SPV_KHR_constant_data extension.
