// Copyright 2015-2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[[descriptorbuffers]]
= Descriptor Buffers

If the <<features-descriptorBuffer, pname:descriptorBuffer>> feature is
enabled, an alternative way to specify descriptor sets is via buffers,
rather than descriptor set objects.


[[descriptorbuffers-puttingdescriptorsinmemory]]
== Putting Descriptors in Memory

Commands are provided to retrieve descriptor data, and also to locate where
in memory that data must: be written to match the given descriptor set
layout.

[open,refpage='vkGetDescriptorSetLayoutSizeEXT',desc='Get the size of a descriptor set layout in memory',type='protos']
--
To determine the amount of memory needed to store all descriptors with a
given layout, call:

include::{generated}/api/protos/vkGetDescriptorSetLayoutSizeEXT.adoc[]

  * pname:device is the logical device that gets the size.
  * pname:layout is the descriptor set layout being queried.
  * pname:pLayoutSizeInBytes is a pointer to basetype:VkDeviceSize where the
    size in bytes will be written.

The size of a descriptor set layout will be at least as large as the sum
total of the size of all descriptors in the layout, and may: be larger.
This size represents the amount of memory that will be required to store all
of the descriptors for this layout in memory, when placed according to the
layout's offsets as obtained by
flink:vkGetDescriptorSetLayoutBindingOffsetEXT.

ifdef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
If any pname:binding in pname:layout is
ename:VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT, the returned size
includes space for the maximum pname:descriptorCount descriptors as declared
for that pname:binding.
To compute the required size of a descriptor set with a
ename:VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT:

  {empty}:: [eq]#size = offset + descriptorSize {times}
            variableDescriptorCount#

where [eq]#offset# is obtained by
flink:vkGetDescriptorSetLayoutBindingOffsetEXT and [eq]#descriptorSize# is
the size of the relevant descriptor as obtained from
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT, and
[eq]#variableDescriptorCount# is the equivalent of
slink:VkDescriptorSetVariableDescriptorCountAllocateInfo::pname:pDescriptorCounts.
ifdef::VK_COMPUTE_VERSION_1_3,VK_EXT_inline_uniform_block[]
For ename:VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
[eq]#variableDescriptorCount# is the size in bytes for the inline uniform
block, and [eq]#descriptorSize# is 1.
endif::VK_COMPUTE_VERSION_1_3,VK_EXT_inline_uniform_block[]

If
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:combinedImageSamplerDescriptorSingleArray
is ename:VK_FALSE and the variable descriptor type is
ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
[eq]#variableDescriptorCount# is always considered to be the upper bound.
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]

.Valid Usage
****
  * [[VUID-vkGetDescriptorSetLayoutSizeEXT-None-08011]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkGetDescriptorSetLayoutSizeEXT-layout-08012]]
    pname:layout must: have been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT flag set
  * [[VUID-vkGetDescriptorSetLayoutSizeEXT-layout-11811]]
    pname:layout must: have not been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT flag set
  * [[VUID-vkGetDescriptorSetLayoutSizeEXT-layout-11812]]
    pname:layout must: have not been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_EMBEDDED_IMMUTABLE_SAMPLERS_BIT_EXT
    flag set
****

include::{generated}/validity/protos/vkGetDescriptorSetLayoutSizeEXT.adoc[]
--

[open,refpage='vkGetDescriptorSetLayoutBindingOffsetEXT',desc='Get the offset of a binding within a descriptor set layout',type='protos']
--
To get the offset of a binding within a descriptor set layout in memory,
call:

include::{generated}/api/protos/vkGetDescriptorSetLayoutBindingOffsetEXT.adoc[]

  * pname:device is the logical device that gets the offset.
  * pname:layout is the descriptor set layout being queried.
  * pname:binding is the binding number being queried.
  * pname:pOffset is a pointer to basetype:VkDeviceSize where the byte
    offset of the binding will be written.

Each binding in a descriptor set layout is assigned an offset in memory by
the implementation.
When a shader accesses a resource with that binding, it will access the
bound descriptor buffer from that offset to look for its descriptor.
This command provides an application with that offset, so that descriptors
can be placed in the correct locations.
The precise location accessed by a shader for a given descriptor is as
follows:

  {empty}:: [eq]#location = bufferAddress {plus} setOffset {plus}
            descriptorOffset {plus} (arrayElement {times} descriptorSize)#

where [eq]#bufferAddress# and [eq]#setOffset# are the base address and
offset for the identified descriptor set as specified by
flink:vkCmdBindDescriptorBuffersEXT and
flink:vkCmdSetDescriptorBufferOffsetsEXT, [eq]#descriptorOffset# is the
offset for the binding returned by this command, [eq]#arrayElement# is the
index into the array specified in the shader, and [eq]#descriptorSize# is
the size of the relevant descriptor as obtained from
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT.
Applications are responsible for placing valid descriptors at the expected
location in order for a shader to access it.
The overall offset added to [eq]#bufferAddress# to calculate [eq]#location#
must: be less than
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:maxSamplerDescriptorBufferRange
for samplers and
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:maxResourceDescriptorBufferRange
for resources.

ifdef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
If any pname:binding in pname:layout is
ename:VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT, that
pname:binding must: have the largest offset of any pname:binding.
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]

ifdef::VK_EXT_mutable_descriptor_type,VK_VALVE_mutable_descriptor_type[]
A descriptor pname:binding with type ename:VK_DESCRIPTOR_TYPE_MUTABLE_EXT
can: be used.
Any potential types in
slink:VkMutableDescriptorTypeCreateInfoEXT::pname:pDescriptorTypes for
pname:binding share the same offset.
If the size of the <<descriptors-mutable, mutable descriptor>> is larger
than the size of a concrete descriptor type being accessed, the padding area
is ignored by the implementation.
endif::VK_EXT_mutable_descriptor_type,VK_VALVE_mutable_descriptor_type[]

.Valid Usage
****
  * [[VUID-vkGetDescriptorSetLayoutBindingOffsetEXT-None-08013]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkGetDescriptorSetLayoutBindingOffsetEXT-layout-08014]]
    pname:layout must: have been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_DESCRIPTOR_BUFFER_BIT_EXT flag set
  * [[VUID-vkGetDescriptorSetLayoutBindingOffsetEXT-layout-11813]]
    pname:layout must: have not been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT flag set
  * [[VUID-vkGetDescriptorSetLayoutBindingOffsetEXT-layout-11814]]
    pname:layout must: have not been created with the
    ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_EMBEDDED_IMMUTABLE_SAMPLERS_BIT_EXT
    flag set
****

include::{generated}/validity/protos/vkGetDescriptorSetLayoutBindingOffsetEXT.adoc[]
--

[open,refpage='vkGetDescriptorEXT',desc='To get a descriptor to place in a buffer',type='protos']
--
To get descriptor data to place in a buffer, call:

include::{generated}/api/protos/vkGetDescriptorEXT.adoc[]

  * pname:device is the logical device that gets the descriptor.
  * pname:pDescriptorInfo is a pointer to a slink:VkDescriptorGetInfoEXT
    structure specifying the parameters of the descriptor to get.
  * pname:dataSize is the amount of the descriptor data to get in bytes.
  * pname:pDescriptor is a pointer to an application-allocated buffer where
    the descriptor will be written.

The size of the data for each descriptor type is determined by the value in
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT.
This value also defines the stride in bytes for arrays of that descriptor
type.

If the
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:combinedImageSamplerDescriptorSingleArray
property is ename:VK_FALSE the implementation requires an array of
ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER descriptors to be written
into a descriptor buffer as an array of image descriptors, immediately
followed by an array of sampler descriptors.
Applications must: write the first
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:sampledImageDescriptorSize
bytes of the data returned through pname:pDescriptor to the first array, and
the remaining
slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:samplerDescriptorSize
bytes of the data to the second array.
For variable-sized descriptor bindings of
ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER descriptors, the two arrays
each have a size equal to the upper bound pname:descriptorCount of that
binding.

A descriptor obtained by this command references the underlying
slink:VkImageView or slink:VkSampler, and these objects must: not be
destroyed before the last time a descriptor is dynamically accessed.
For descriptor types which consume an address instead of an object, the
underlying slink:VkBuffer is referenced instead.

.Valid Usage
****
  * [[VUID-vkGetDescriptorEXT-None-08015]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkGetDescriptorEXT-dataSize-08125]]
ifdef::VK_COMPUTE_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion[]
    If pname:pDescriptorInfo->type is not
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER or
    pname:pDescriptorInfo->data.pCombinedImageSampler has an pname:imageView
    member that was not created with a sname:VkSamplerYcbcrConversionInfo
    structure in its pname:pNext chain,
endif::VK_COMPUTE_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion[]
    pname:dataSize must: equal the size of a descriptor of type
    slink:VkDescriptorGetInfoEXT::pname:type determined by the value in
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT
ifdef::VK_EXT_fragment_density_map[]
    , or determined by
    slink:VkPhysicalDeviceDescriptorBufferDensityMapPropertiesEXT::pname:combinedImageSamplerDensityMapDescriptorSize
    if pname:pDescriptorInfo specifies a
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER whose slink:VkSampler
    was created with ename:VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT set
endif::VK_EXT_fragment_density_map[]
ifdef::VK_COMPUTE_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion[]
  * [[VUID-vkGetDescriptorEXT-descriptorType-09469]]
    If pname:pDescriptorInfo->type is
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER and
    pname:pDescriptorInfo->data.pCombinedImageSampler has an pname:imageView
    member that was created with a sname:VkSamplerYcbcrConversionInfo
    structure in its pname:pNext chain, pname:dataSize must: equal the size
    of
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:combinedImageSamplerDescriptorSize
    times
    slink:VkSamplerYcbcrConversionImageFormatProperties::pname:combinedImageSamplerDescriptorCount
endif::VK_COMPUTE_VERSION_1_1,VK_KHR_sampler_ycbcr_conversion[]
  * [[VUID-vkGetDescriptorEXT-pDescriptorInfo-09507]]
    If pname:pDescriptorInfo->type is
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER and it has a
    pname:imageView that is dlink:VK_NULL_HANDLE then pname:dataSize must:
    be equal to the size of
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:combinedImageSamplerDescriptorSize
****

include::{generated}/validity/protos/vkGetDescriptorEXT.adoc[]
--

[open,refpage='VkDescriptorGetInfoEXT',desc='Structure specifying parameters of descriptor to get',type='structs']
--
Information about the descriptor to get is passed in a
sname:VkDescriptorGetInfoEXT structure:

include::{generated}/api/structs/VkDescriptorGetInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:type is the type of descriptor to get.
  * pname:data is a slink:VkDescriptorDataEXT union containing the
    information needed to get the descriptor.

.Valid Usage
****
  * [[VUID-VkDescriptorGetInfoEXT-type-08018]]
    pname:type must: not be ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
    ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC or
    ename:VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK
  * [[VUID-VkDescriptorGetInfoEXT-type-08019]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, the
    pname:pCombinedImageSampler->sampler member of pname:data must: be a
    slink:VkSampler created on pname:device
  * [[VUID-VkDescriptorGetInfoEXT-type-08020]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, the
    pname:pCombinedImageSampler->imageView member of pname:data must: be a
    slink:VkImageView created on pname:device, or dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorGetInfoEXT-type-08021]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT, the
    pname:pInputAttachmentImage->imageView member of pname:data must: be a
    slink:VkImageView created on pname:device
  * [[VUID-VkDescriptorGetInfoEXT-type-08022]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, and if
    pname:pSampledImage is not `NULL`, the pname:pSampledImage->imageView
    member of pname:data must: be a slink:VkImageView created on
    pname:device, or dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorGetInfoEXT-type-08023]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and if
    pname:pStorageImage is not `NULL`, the pname:pStorageImage->imageView
    member of pname:data must: be a slink:VkImageView created on
    pname:device, or dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorGetInfoEXT-type-09427]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
    pname:pUniformBuffer is not `NULL` , the number of texel buffer elements
    given by [eq]#({lfloor}pname:pUniformBuffer->range / (texel block
    size){rfloor} {times} (texels per block))# where texel block size and
    texels per block are as defined in the <<formats-compatibility,
    Compatible Formats>> table for pname:pUniformBuffer->format, must: be
    less than or equal to
    sname:VkPhysicalDeviceLimits::pname:maxTexelBufferElements
  * [[VUID-VkDescriptorGetInfoEXT-type-09428]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
    pname:pStorageBuffer is not `NULL` , the number of texel buffer elements
    given by [eq]#({lfloor}pname:pStorageBuffer->range / (texel block
    size){rfloor} {times} (texels per block))# where texel block size and
    texels per block are as defined in the <<formats-compatibility,
    Compatible Formats>> table for pname:pStorageBuffer->format, must: be
    less than or equal to
    sname:VkPhysicalDeviceLimits::pname:maxTexelBufferElements
ifdef::VK_KHR_acceleration_structure[]
  * [[VUID-VkDescriptorGetInfoEXT-type-08028]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR and
    pname:accelerationStructure is not `0`, pname:accelerationStructure
    must: contain the address of a slink:VkAccelerationStructureKHR created
    on pname:device
endif::VK_KHR_acceleration_structure[]
ifdef::VK_NV_ray_tracing[]
  * [[VUID-VkDescriptorGetInfoEXT-type-08029]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV and
    pname:accelerationStructure is not `0`, pname:accelerationStructure
    must: contain the handle of a slink:VkAccelerationStructureNV created on
    pname:device, returned by flink:vkGetAccelerationStructureHandleNV
endif::VK_NV_ray_tracing[]
ifdef::VK_ARM_tensors[]
  * [[VUID-VkDescriptorGetInfoEXT-type-09701]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_TENSOR_ARM, a
    slink:VkDescriptorGetTensorInfoARM structure must: be included in the
    pname:pNext chain and pname:data is ignored
endif::VK_ARM_tensors[]
  * [[VUID-VkDescriptorGetInfoEXT-type-12216]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER and
    pname:pCombinedImageSampler->imageView is not dlink:VK_NULL_HANDLE, the
    pname:pCombinedImageSampler->imageView member of pname:data must: have
    been created with ename:VK_IMAGE_USAGE_SAMPLED_BIT set
  * [[VUID-VkDescriptorGetInfoEXT-type-12217]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
    pname:pSampledImage is not `NULL`, and pname:pSampledImage->imageView is
    not dlink:VK_NULL_HANDLE, the pname:pSampledImage->imageView member of
    pname:data must: have been created with ename:VK_IMAGE_USAGE_SAMPLED_BIT
    set
  * [[VUID-VkDescriptorGetInfoEXT-type-12218]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
    pname:pStorageImage is not `NULL`, and pname:pStorageImage->imageView is
    not dlink:VK_NULL_HANDLE, the pname:pStorageImage->imageView member of
    pname:data must: have been created with ename:VK_IMAGE_USAGE_STORAGE_BIT
    set
  * [[VUID-VkDescriptorGetInfoEXT-type-12219]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT, the
    pname:pInputAttachmentImage->imageView member of pname:data must: have
    been created with ename:VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT set
  * [[VUID-VkDescriptorGetInfoEXT-type-12220]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
    pname:pUniformBuffer is not `NULL` and pname:pUniformBuffer->address is
    not zero, pname:pUniformBuffer->address must: be a device address
    allocated to the application from a buffer created with the
    ename:VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT usage flag set
  * [[VUID-VkDescriptorGetInfoEXT-type-12221]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
    pname:pStorageBuffer is not `NULL` and pname:pStorageBuffer->address is
    not zero, pname:pStorageBuffer->address must: be a device address
    allocated to the application from a buffer created with the
    ename:VK_BUFFER_USAGE_STORAGE_BUFFER_BIT usage flag set
  * [[VUID-VkDescriptorGetInfoEXT-type-12222]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
    pname:pUniformTexelBuffer is not `NULL` and
    pname:pUniformTexelBuffer->address is not zero,
    pname:pUniformTexelBuffer->address must: be a device address allocated
    to the application from a buffer created with the
    ename:VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT usage flag set
  * [[VUID-VkDescriptorGetInfoEXT-type-12223]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
    pname:pStorageTexelBuffer is not `NULL` and
    pname:pStorageTexelBuffer->address is not zero,
    pname:pStorageTexelBuffer->address must: be a device address allocated
    to the application from a buffer created with the
    ename:VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT usage flag set
  * [[VUID-VkDescriptorGetInfoEXT-type-12265]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER and
    pname:pUniformBuffer is not `NULL`, pname:pUniformBuffer->address must:
    be aligned to
    sname:VkPhysicalDeviceLimits::pname:minUniformBufferOffsetAlignment
  * [[VUID-VkDescriptorGetInfoEXT-type-12266]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER and
    pname:pStorageBuffer is not `NULL`, pname:pStorageBuffer->address must:
    be aligned to
    sname:VkPhysicalDeviceLimits::pname:minStorageBufferOffsetAlignment
  * [[VUID-VkDescriptorGetInfoEXT-type-12269]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER, and
    pname:pUniformTexelBuffer is not `NULL`,
    pname:pUniformTexelBuffer->address must: be a multiple of the effective
    alignment requirement as determined by
    <<limits-minTexelBufferOffsetAlignment,pname:minTexelBufferOffsetAlignment>>
  * [[VUID-VkDescriptorGetInfoEXT-type-12270]]
    If pname:type is ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, the and
    pname:pStorageTexelBuffer is not `NULL`,
    pname:pStorageTexelBuffer->address must: be a multiple of the effective
    alignment requirement as determined by
    <<limits-minTexelBufferOffsetAlignment,pname:minTexelBufferOffsetAlignment>>
****

include::{generated}/validity/structs/VkDescriptorGetInfoEXT.adoc[]
--

[open,refpage='VkDescriptorDataEXT',desc='Structure specifying descriptor data',type='structs']
--
Data describing the descriptor is passed in a sname:VkDescriptorDataEXT
structure:

include::{generated}/api/structs/VkDescriptorDataEXT.adoc[]

  * pname:pSampler is a pointer to a slink:VkSampler handle specifying the
    parameters of a ename:VK_DESCRIPTOR_TYPE_SAMPLER descriptor.
  * pname:pCombinedImageSampler is a pointer to a
    slink:VkDescriptorImageInfo structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER descriptor.
  * pname:pInputAttachmentImage is a pointer to a
    slink:VkDescriptorImageInfo structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT descriptor.
  * pname:pSampledImage is a pointer to a slink:VkDescriptorImageInfo
    structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE descriptor.
  * pname:pStorageImage is a pointer to a slink:VkDescriptorImageInfo
    structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_STORAGE_IMAGE descriptor.
  * pname:pUniformTexelBuffer is a pointer to a
    slink:VkDescriptorAddressInfoEXT structure specifying the parameters of
    a ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER descriptor.
  * pname:pStorageTexelBuffer is a pointer to a
    slink:VkDescriptorAddressInfoEXT structure specifying the parameters of
    a ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER descriptor.
  * pname:pUniformBuffer is a pointer to a slink:VkDescriptorAddressInfoEXT
    structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER descriptor.
  * pname:pStorageBuffer is a pointer to a slink:VkDescriptorAddressInfoEXT
    structure specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER descriptor.
ifdef::VK_KHR_acceleration_structure+VK_NV_ray_tracing[]
  * pname:accelerationStructure is
ifdef::VK_KHR_acceleration_structure[]
     the address of a slink:VkAccelerationStructureKHR specifying the
     parameters of a ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR
     descriptor
endif::VK_KHR_acceleration_structure[]
ifdef::VK_KHR_acceleration_structure+VK_NV_ray_tracing[, or ]
ifdef::VK_NV_ray_tracing[]
    a slink:VkAccelerationStructureNV handle specifying the parameters of a
    ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV descriptor.
endif::VK_NV_ray_tracing[]
endif::VK_KHR_acceleration_structure+VK_NV_ray_tracing[]
ifndef::VK_NV_ray_tracing,VK_NV_ray_tracing[]
  * pname:accelerationStructure is reserved for future use and is ignored.
endif::VK_NV_ray_tracing,VK_NV_ray_tracing[]

ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
If the <<features-nullDescriptor, pname:nullDescriptor>> feature is enabled,
pname:pSampledImage, pname:pStorageImage, pname:pUniformTexelBuffer,
pname:pStorageTexelBuffer, pname:pUniformBuffer, and pname:pStorageBuffer
can: each be `NULL`.
Loads from a null descriptor return zero values and stores and atomics to a
null descriptor are discarded.

ifdef::VK_KHR_acceleration_structure,VK_NV_ray_tracing[]
If the <<features-nullDescriptor, pname:nullDescriptor>> feature is enabled,
pname:accelerationStructure can: be `0`.
A null acceleration structure descriptor results in the miss shader being
invoked.
endif::VK_KHR_acceleration_structure,VK_NV_ray_tracing[]
endif::VK_EXT_robustness2,VK_KHR_robustness2[]

.Valid Usage
****
ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
  * [[VUID-VkDescriptorDataEXT-type-08034]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pCombinedImageSampler->imageView must: not be
    dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorDataEXT-type-08035]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pSampledImage must: not be `NULL` and
    pname:pSampledImage->imageView must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorDataEXT-type-08036]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pStorageImage must: not be `NULL` and
    pname:pStorageImage->imageView must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkDescriptorDataEXT-type-08037]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pUniformTexelBuffer must: not be `NULL`
  * [[VUID-VkDescriptorDataEXT-type-08038]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pStorageTexelBuffer must: not be `NULL`
  * [[VUID-VkDescriptorDataEXT-type-08039]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pUniformBuffer must: not be `NULL`
  * [[VUID-VkDescriptorDataEXT-type-08040]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:pStorageBuffer must: not be `NULL`
ifdef::VK_KHR_acceleration_structure[]
  * [[VUID-VkDescriptorDataEXT-type-08041]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:accelerationStructure must: not be `0`
endif::VK_KHR_acceleration_structure[]
ifdef::VK_NV_ray_tracing[]
  * [[VUID-VkDescriptorDataEXT-type-08042]]
    If slink:VkDescriptorGetInfoEXT::pname:type is
    ename:VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_NV, and the
    <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:accelerationStructure must: not be `0`
endif::VK_NV_ray_tracing[]
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
****

include::{generated}/validity/structs/VkDescriptorDataEXT.adoc[]

--

[open,refpage='VkDescriptorAddressInfoEXT',desc='Structure specifying descriptor buffer address info',type='structs']
--
Data describing a ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER, or
ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER descriptor is passed in a
sname:VkDescriptorAddressInfoEXT structure:

include::{generated}/api/structs/VkDescriptorAddressInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:address is either `0` or a device address at an offset in a
    buffer, where the base address can be queried from
    flink:vkGetBufferDeviceAddress.
  * pname:range is the size in bytes of the buffer or buffer view used by
    the descriptor.
  * pname:format is the format of the data elements in the buffer view and
    is ignored for buffers.

.Valid Usage
****
  * [[VUID-VkDescriptorAddressInfoEXT-None-09508]]
    If
ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
    pname:address is not zero, and
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
    the descriptor is of type ename:VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER
    or ename:VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER, then pname:format
    must: not be ename:VK_FORMAT_UNDEFINED
  * [[VUID-VkDescriptorAddressInfoEXT-address-08043]]
ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
    If the <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled,
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
    pname:address must: not be zero
ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
  * [[VUID-VkDescriptorAddressInfoEXT-nullDescriptor-08938]]
    If pname:address is zero, pname:range must: be ename:VK_WHOLE_SIZE
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
  * [[VUID-VkDescriptorAddressInfoEXT-nullDescriptor-08939]]
ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
    If pname:address is not zero,
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
    pname:range must: not be ename:VK_WHOLE_SIZE
  * [[VUID-VkDescriptorAddressInfoEXT-range-08045]]
    If pname:address is not zero, then pname:range must: be less than or
    equal to the size of the buffer containing pname:address minus the
    offset of pname:address from the base address of the buffer
  * [[VUID-VkDescriptorAddressInfoEXT-range-08940]]
    pname:range must: not be zero
ifdef::VK_EXT_ycbcr_2plane_444_formats[]
  * [[VUID-VkDescriptorAddressInfoEXT-None-12271]]
    If
ifdef::VK_BASE_VERSION_1_3[Vulkan 1.3 is not supported and]
    the <<features-ycbcr2plane444Formats,pname:ycbcr2plane444Formats>>
    feature is not enabled, pname:format must: not be
    ename:VK_FORMAT_G8_B8R8_2PLANE_444_UNORM,
    ename:VK_FORMAT_G10X6_B10X6R10X6_2PLANE_444_UNORM_3PACK16,
    ename:VK_FORMAT_G12X4_B12X4R12X4_2PLANE_444_UNORM_3PACK16, or
    ename:VK_FORMAT_G16_B16R16_2PLANE_444_UNORM
endif::VK_EXT_ycbcr_2plane_444_formats[]
****

include::{generated}/validity/structs/VkDescriptorAddressInfoEXT.adoc[]

ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
If the <<features-nullDescriptor, pname:nullDescriptor>> feature is enabled,
pname:address can: be zero.
Loads from a null descriptor return zero values and stores and atomics to a
null descriptor are discarded.
endif::VK_EXT_robustness2,VK_KHR_robustness2[]
--

Immutable samplers specified in a descriptor set layout through
pname:pImmutableSamplers must: be provided by applications when obtaining
descriptor data.
Immutable samplers written in a descriptor buffer must: have identical
parameters to the immutable samplers in the descriptor set layout that
consumes the sampler.

[NOTE]
====
If the descriptor set layout was created with
ename:VK_DESCRIPTOR_SET_LAYOUT_CREATE_EMBEDDED_IMMUTABLE_SAMPLERS_BIT_EXT,
there is no buffer backing for the immutable sampler, so this requirement
does not exist.
The implementation handles allocation of these descriptors internally.
====

[NOTE]
====
As descriptors are now in regular memory, drivers cannot hide copies of
immutable samplers that end up in descriptor sets from the application.
As such, applications are required to provide these samplers as if they were
not provided immutably.
====

ifdef::VK_ARM_tensors[]
[open,refpage='VkDescriptorGetTensorInfoARM',desc='Structure specifying parameters to get descriptor data for tensor views',type='structs']
--
The sname:VkDescriptorGetTensorInfoARM is defined as:

include::{generated}/api/structs/VkDescriptorGetTensorInfoARM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:tensorView is a slink:VkTensorViewARM handle specifying the
    parameters of a ename:VK_DESCRIPTOR_TYPE_TENSOR_ARM descriptor.

ifdef::VK_EXT_robustness2[]
.Valid Usage
****
  * [[VUID-VkDescriptorGetTensorInfoARM-nullDescriptor-09899]]
    If the <<features-nullDescriptor, pname:nullDescriptor>> feature is not
    enabled, pname:tensorView must: not be dlink:VK_NULL_HANDLE
****
endif::VK_EXT_robustness2[]

include::{generated}/validity/structs/VkDescriptorGetTensorInfoARM.adoc[]
--
endif::VK_ARM_tensors[]

[[descriptorbuffers-binding]]
== Binding Descriptor Buffers

Descriptor buffers have their own separate binding point on the command
buffer, with buffers bound using flink:vkCmdBindDescriptorBuffersEXT.
flink:vkCmdSetDescriptorBufferOffsetsEXT assigns pairs of buffer binding
indices and buffer offsets to the same binding point on the command buffer
as flink:vkCmdBindDescriptorSets, allowing subsequent
<<pipelines-bindpoint-commands, bound pipeline commands>> to use the
specified descriptor buffers.
Bindings applied via flink:vkCmdBindDescriptorSets cannot: exist
simultaneously with those applied via calls to
flink:vkCmdSetDescriptorBufferOffsetsEXT or
flink:vkCmdBindDescriptorBufferEmbeddedSamplersEXT, as calls to
flink:vkCmdSetDescriptorBufferOffsetsEXT or
flink:vkCmdBindDescriptorBufferEmbeddedSamplersEXT invalidate any bindings
by previous calls to flink:vkCmdBindDescriptorSets and vice-versa.

[open,refpage='vkCmdBindDescriptorBuffersEXT',desc='Binding descriptor buffers to a command buffer',type='protos']
--
:refpage: vkCmdBindDescriptorBuffersEXT

To bind descriptor buffers to a command buffer, call:

include::{generated}/api/protos/vkCmdBindDescriptorBuffersEXT.adoc[]

  * pname:commandBuffer is the command buffer that the descriptor buffers
    will be bound to.
  * pname:bufferCount is the number of elements in the pname:pBindingInfos
    array.
  * pname:pBindingInfos is a pointer to an array of
    slink:VkDescriptorBufferBindingInfoEXT structures.

`vkCmdBindDescriptorBuffersEXT` causes any offsets previously set by
flink:vkCmdSetDescriptorBufferOffsetsEXT that use the bindings numbered
[`0`..
pname:bufferCount-1] to be no longer valid for subsequent bound pipeline
commands.
Any previously bound buffers at binding points greater than or equal to
pname:bufferCount are unbound.

.Valid Usage
****
include::{chapters}/commonvalidity/invalidate_heap_common.adoc[]
  * [[VUID-vkCmdBindDescriptorBuffersEXT-None-08047]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkCmdBindDescriptorBuffersEXT-maxSamplerDescriptorBufferBindings-08048]]
    There must: be no more than
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:maxSamplerDescriptorBufferBindings
    elements in pname:pBindingInfos with
    slink:VkDescriptorBufferBindingInfoEXT::pname:usage containing
    ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT
  * [[VUID-vkCmdBindDescriptorBuffersEXT-maxResourceDescriptorBufferBindings-08049]]
    There must: be no more than
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:maxResourceDescriptorBufferBindings
    elements in pname:pBindingInfos with
    slink:VkDescriptorBufferBindingInfoEXT::pname:usage containing
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT
  * [[VUID-vkCmdBindDescriptorBuffersEXT-None-08050]]
    There must: be no more than `1` element in pname:pBindingInfos with
    slink:VkDescriptorBufferBindingInfoEXT::pname:usage containing
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT
  * [[VUID-vkCmdBindDescriptorBuffersEXT-bufferCount-08051]]
    pname:bufferCount must: be less than or equal to
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:maxDescriptorBufferBindings
  * [[VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-08053]]
    For each element of pname:pBindingInfos, the buffer from which
    pname:address was queried must: have been created with the
    ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT usage flag set
    if it contains sampler descriptor data
  * [[VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-08054]]
    For each element of pname:pBindingInfos, the buffer from which
    pname:address was queried must: have been created with the
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT usage flag set
    if it contains resource descriptor data
  * [[VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-08055]]
    For each element of pname:pBindingInfos, at least one buffer from which
    pname:address was queried must contain pname:usage
ifdef::VK_ARM_data_graph[]
  * [[VUID-vkCmdBindDescriptorBuffersEXT-pBindingInfos-09947]]
    For all elements of pname:pBindingInfos, the buffer from which
    pname:address was queried must: have been created with the
    ename:VK_BUFFER_USAGE_2_DATA_GRAPH_FOREIGN_DESCRIPTOR_BIT_ARM usage flag
    set if the command pool from which pname:commandBuffer was allocated
    from was created with any element of
    slink:VkDataGraphProcessingEngineCreateInfoARM::pname:pProcessingEngines
    with pname:isForeign set to ename:VK_TRUE
endif::VK_ARM_data_graph[]
****

include::{generated}/validity/protos/vkCmdBindDescriptorBuffersEXT.adoc[]
--

[open,refpage='VkDescriptorBufferBindingInfoEXT',desc='Structure specifying descriptor buffer binding information',type='structs']
--
:refpage: VkDescriptorBufferBindingInfoEXT

Data describing a descriptor buffer binding is passed in a
sname:VkDescriptorBufferBindingInfoEXT structure:

include::{generated}/api/structs/VkDescriptorBufferBindingInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:address is a basetype:VkDeviceAddress specifying the device
    address defining the descriptor buffer to be bound.
  * pname:usage is a bitmask of elink:VkBufferUsageFlagBits specifying the
    slink:VkBufferCreateInfo::pname:usage for the buffer from which
    pname:address was queried.
    Usage flags other than
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT,
    ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, and
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT are
    ignored.

ifdef::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance5[]
If the pname:pNext chain includes a slink:VkBufferUsageFlags2CreateInfo
structure, slink:VkBufferUsageFlags2CreateInfo::pname:usage from that
structure is used instead of pname:usage from this structure.
endif::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance5[]

.Valid Usage
****
include::{chapters}/commonvalidity/buffer_usage_flags_common.adoc[]
  * [[VUID-VkDescriptorBufferBindingInfoEXT-usage-10998]]
    The pname:usage must include at least one of
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT,
    ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, or
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT
  * [[VUID-VkDescriptorBufferBindingInfoEXT-bufferlessPushDescriptors-08056]]
    If <<limits-bufferlessPushDescriptors,
    sname:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:bufferlessPushDescriptors>>
    is ename:VK_FALSE, and pname:usage contains
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT, then
    the pname:pNext chain must: include a
    slink:VkDescriptorBufferBindingPushDescriptorBufferHandleEXT structure
  * [[VUID-VkDescriptorBufferBindingInfoEXT-address-08057]]
    pname:address must: be aligned to
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:descriptorBufferOffsetAlignment
  * [[VUID-VkDescriptorBufferBindingInfoEXT-usage-08122]]
    If pname:usage includes
    ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT, pname:address
    must: be a device address allocated to the application from a buffer
    created with the ename:VK_BUFFER_USAGE_SAMPLER_DESCRIPTOR_BUFFER_BIT_EXT
    usage flag set
  * [[VUID-VkDescriptorBufferBindingInfoEXT-usage-08123]]
    If pname:usage includes
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT, pname:address
    must: be a device address allocated to the application from a buffer
    created with the
    ename:VK_BUFFER_USAGE_RESOURCE_DESCRIPTOR_BUFFER_BIT_EXT usage flag set
ifdef::VK_COMPUTE_VERSION_1_4,VK_KHR_push_descriptor[]
  * [[VUID-VkDescriptorBufferBindingInfoEXT-usage-08124]]
    If pname:usage includes
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT,
    pname:address must: be a device address allocated to the application
    from a buffer created with the
    ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT usage
    flag set
endif::VK_COMPUTE_VERSION_1_4,VK_KHR_push_descriptor[]
****

include::{generated}/validity/structs/VkDescriptorBufferBindingInfoEXT.adoc[]
--

[open,refpage='VkDescriptorBufferBindingPushDescriptorBufferHandleEXT',desc='Structure specifying push descriptor buffer binding information',type='structs']
--
When the <<limits-bufferlessPushDescriptors,
sname:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:bufferlessPushDescriptors>>
property is ename:VK_FALSE, the sname:VkBuffer handle of the buffer for push
descriptors is passed in a
sname:VkDescriptorBufferBindingPushDescriptorBufferHandleEXT structure:

include::{generated}/api/structs/VkDescriptorBufferBindingPushDescriptorBufferHandleEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:buffer is the sname:VkBuffer handle of the buffer for push
    descriptors.

.Valid Usage
****
  * [[VUID-VkDescriptorBufferBindingPushDescriptorBufferHandleEXT-bufferlessPushDescriptors-08059]]
    <<limits-bufferlessPushDescriptors,
    sname:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:bufferlessPushDescriptors>>
    must: be ename:VK_FALSE
****

include::{generated}/validity/structs/VkDescriptorBufferBindingPushDescriptorBufferHandleEXT.adoc[]
--

[open,refpage='vkCmdSetDescriptorBufferOffsetsEXT',desc='Setting descriptor buffer offsets in a command buffer',type='protos']
--
:refpage: vkCmdSetDescriptorBufferOffsetsEXT

To set descriptor buffer offsets in a command buffer, call:

include::{generated}/api/protos/vkCmdSetDescriptorBufferOffsetsEXT.adoc[]

  * pname:commandBuffer is the command buffer in which the descriptor buffer
    offsets will be set.
  * pname:pipelineBindPoint is a elink:VkPipelineBindPoint indicating the
    type of the pipeline that will use the descriptors.
  * pname:layout is a slink:VkPipelineLayout object used to program the
    bindings.
  * pname:firstSet is the number of the first set to be bound.
  * pname:setCount is the number of elements in the pname:pBufferIndices and
    pname:pOffsets arrays.
  * pname:pBufferIndices is a pointer to an array of indices into the
    descriptor buffer binding points set by
    flink:vkCmdBindDescriptorBuffersEXT.
  * pname:pOffsets is a pointer to an array of basetype:VkDeviceSize offsets
    to apply to the bound descriptor buffers.

fname:vkCmdSetDescriptorBufferOffsetsEXT binds pname:setCount pairs of
descriptor buffers, specified by indices into the binding points bound using
flink:vkCmdBindDescriptorBuffersEXT, and buffer offsets to set numbers
[pname:firstSet..pname:firstSet+pname:setCount-1] for subsequent
<<pipelines-bindpoint-commands, bound pipeline commands>> set by
pname:pipelineBindPoint.
Set [pname:firstSet + i] is bound to the descriptor buffer at binding
pname:pBufferIndices[i] at an offset of pname:pOffsets[i].
Any bindings that were previously applied via these sets, or calls to
flink:vkCmdBindDescriptorSets, are no longer valid.
Other sets will also be invalidated upon calling this command if
pname:layout differs from the pipeline layout used to bind those other sets,
as described in <<descriptors-compatibility,Pipeline Layout Compatibility>>.

After binding descriptors, applications can: modify descriptor memory either
by performing writes on the host or with device commands.
When descriptor memory is updated with device commands, visibility for the
shader stage accessing a descriptor is ensured with the
ename:VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT access flag.
Implementations must: not access resources referenced by these descriptors
unless they are dynamically accessed by shaders.
Descriptors bound with this call can: be undefined: if they are not
dynamically accessed by shaders.

Implementations may: read descriptor data for any statically accessed
ifdef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
descriptor if the pname:binding in pname:layout is not declared with the
ename:VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT flag.
If the pname:binding in pname:layout is declared with
ename:VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT, implementations
must: not read descriptor data that is not dynamically accessed.
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
ifndef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
descriptor.
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]

Applications must: ensure that any descriptor which the implementation may:
read must: be in-bounds of the underlying descriptor buffer binding.

ifdef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
[NOTE]
====
Applications can freely decide how large a variable descriptor buffer
binding is, so it may not be safe to read such descriptor payloads
statically.
The intention of these rules is to allow implementations to speculatively
prefetch descriptor payloads where feasible.
====
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]

Dynamically accessing a resource through descriptor data from an unbound
region of a <<sparsememory-partially-resident-buffers, sparse
partially-resident buffer>> will result in invalid descriptor data being
read, and therefore undefined: behavior.

[NOTE]
====
For descriptors written by the host, visibility is implied through the
automatic visibility operation on queue submit, and there is no need to
consider etext:VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT.
Explicit synchronization for descriptors is only required when descriptors
are updated on the device.
====

ifdef::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]
[NOTE]
====
The requirements above imply that all descriptor bindings have been defined
with the equivalent of ename:VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT,
ename:VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT and
ename:VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT, but enabling those features
is not required to get this behavior.
====
endif::VK_COMPUTE_VERSION_1_2,VK_EXT_descriptor_indexing[]

.Valid Usage
****
include::{chapters}/commonvalidity/invalidate_heap_common.adoc[]
include::{chapters}/commonvalidity/set_descriptor_buffer_offsets_common.adoc[]
  * [[VUID-vkCmdSetDescriptorBufferOffsetsEXT-None-08060]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkCmdSetDescriptorBufferOffsetsEXT-pipelineBindPoint-08067]]
    pname:pipelineBindPoint must: be supported by the pname:commandBuffer's
    parent sname:VkCommandPool's queue family
****

include::{generated}/validity/protos/vkCmdSetDescriptorBufferOffsetsEXT.adoc[]
--

ifdef::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance6[]
[open,refpage='vkCmdSetDescriptorBufferOffsets2EXT',desc='Setting descriptor buffer offsets in a command buffer',type='protos']
--
:refpage: vkCmdSetDescriptorBufferOffsets2EXT

To set descriptor buffer offsets in a command buffer, call:

include::{generated}/api/protos/vkCmdSetDescriptorBufferOffsets2EXT.adoc[]

  * pname:commandBuffer is the command buffer in which the descriptor buffer
    offsets will be set.
  * pname:pSetDescriptorBufferOffsetsInfo is a pointer to a
    sname:VkSetDescriptorBufferOffsetsInfoEXT structure.

.Valid Usage
****
include::{chapters}/commonvalidity/invalidate_heap_common.adoc[]
  * [[VUID-vkCmdSetDescriptorBufferOffsets2EXT-descriptorBuffer-09470]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkCmdSetDescriptorBufferOffsets2EXT-pSetDescriptorBufferOffsetsInfo-09471]]
    Each bit in pname:pSetDescriptorBufferOffsetsInfo->stageFlags must: be a
    stage supported by the pname:commandBuffer's parent
    sname:VkCommandPool's queue family
****

include::{generated}/validity/protos/vkCmdSetDescriptorBufferOffsets2EXT.adoc[]
--

[open,refpage='VkSetDescriptorBufferOffsetsInfoEXT',desc='Structure specifying descriptor buffer offsets to set in a command buffer',type='structs']
--
:refpage: VkSetDescriptorBufferOffsetsInfoEXT

The sname:VkSetDescriptorBufferOffsetsInfoEXT structure is defined as:

include::{generated}/api/structs/VkSetDescriptorBufferOffsetsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:stageFlags is a bitmask of elink:VkShaderStageFlagBits specifying
    the shader stages the descriptor sets will be bound to
  * pname:layout is a slink:VkPipelineLayout object used to program the
    bindings.
ifdef::VK_NV_per_stage_descriptor_set[]
    If the <<features-dynamicPipelineLayout, pname:dynamicPipelineLayout>>
    feature is enabled, pname:layout can: be dlink:VK_NULL_HANDLE and the
    layout must: be specified by chaining slink:VkPipelineLayoutCreateInfo
    structure off the pname:pNext
endif::VK_NV_per_stage_descriptor_set[]
  * pname:firstSet is the number of the first set to be bound.
  * pname:setCount is the number of elements in the pname:pBufferIndices and
    pname:pOffsets arrays.
  * pname:pBufferIndices is a pointer to an array of indices into the
    descriptor buffer binding points set by
    flink:vkCmdBindDescriptorBuffersEXT.
  * pname:pOffsets is a pointer to an array of basetype:VkDeviceSize offsets
    to apply to the bound descriptor buffers.

If pname:stageFlags specifies a subset of all stages corresponding to one or
more pipeline bind points, the binding operation still affects all stages
corresponding to the given pipeline bind point(s) as if the equivalent
original version of this command had been called with the same parameters.
For example, specifying a pname:stageFlags value of
ename:VK_SHADER_STAGE_VERTEX_BIT | ename:VK_SHADER_STAGE_FRAGMENT_BIT |
ename:VK_SHADER_STAGE_COMPUTE_BIT is equivalent to calling the original
version of this command once with ename:VK_PIPELINE_BIND_POINT_GRAPHICS and
once with ename:VK_PIPELINE_BIND_POINT_COMPUTE.

.Valid Usage
****
include::{chapters}/commonvalidity/set_descriptor_buffer_offsets_common.adoc[]
include::{chapters}/commonvalidity/dynamic_pipeline_layout_common.adoc[]
****

include::{generated}/validity/structs/VkSetDescriptorBufferOffsetsInfoEXT.adoc[]
--
endif::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance6[]

[open,refpage='vkCmdBindDescriptorBufferEmbeddedSamplersEXT',desc='Setting embedded immutable samplers offsets in a command buffer',type='protos']
--
:refpage: vkCmdBindDescriptorBufferEmbeddedSamplersEXT

To bind an embedded immutable sampler set to a command buffer, call:

include::{generated}/api/protos/vkCmdBindDescriptorBufferEmbeddedSamplersEXT.adoc[]

  * pname:commandBuffer is the command buffer that the embedded immutable
    samplers will be bound to.
  * pname:pipelineBindPoint is a elink:VkPipelineBindPoint indicating the
    type of the pipeline that will use the embedded immutable samplers.
  * pname:layout is a slink:VkPipelineLayout object used to program the
    bindings.
  * pname:set is the number of the set to be bound.

`vkCmdBindDescriptorBufferEmbeddedSamplersEXT` binds the embedded immutable
samplers in pname:set of pname:layout to pname:set for the command buffer
for subsequent <<pipelines-bindpoint-commands, bound pipeline commands>> set
by pname:pipelineBindPoint.
Any previous binding to this set by flink:vkCmdSetDescriptorBufferOffsetsEXT
or this command is overwritten.
Any sets that were last bound by a call to flink:vkCmdBindDescriptorSets are
invalidated upon calling this command.
Other sets will also be invalidated upon calling this command if
pname:layout differs from the pipeline layout used to bind those other sets,
as described in <<descriptors-compatibility,Pipeline Layout Compatibility>>.

.Valid Usage
****
include::{chapters}/commonvalidity/invalidate_heap_common.adoc[]
include::{chapters}/commonvalidity/bind_descriptor_buffer_embedded_samplers_common.adoc[]
  * [[VUID-vkCmdBindDescriptorBufferEmbeddedSamplersEXT-None-08068]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkCmdBindDescriptorBufferEmbeddedSamplersEXT-pipelineBindPoint-08069]]
    pname:pipelineBindPoint must: be supported by the pname:commandBuffer's
    parent sname:VkCommandPool's queue family
****

include::{generated}/validity/protos/vkCmdBindDescriptorBufferEmbeddedSamplersEXT.adoc[]
--

ifdef::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance6[]
[open,refpage='vkCmdBindDescriptorBufferEmbeddedSamplers2EXT',desc='Setting embedded immutable samplers offsets in a command buffer',type='protos']
--
:refpage: vkCmdBindDescriptorBufferEmbeddedSamplers2EXT

To bind an embedded immutable sampler set to a command buffer, call:

include::{generated}/api/protos/vkCmdBindDescriptorBufferEmbeddedSamplers2EXT.adoc[]

  * pname:commandBuffer is the command buffer that the embedded immutable
    samplers will be bound to.
  * pname:pBindDescriptorBufferEmbeddedSamplersInfo is a pointer to a
    sname:VkBindDescriptorBufferEmbeddedSamplersInfoEXT structure.

.Valid Usage
****
include::{chapters}/commonvalidity/invalidate_heap_common.adoc[]
  * [[VUID-vkCmdBindDescriptorBufferEmbeddedSamplers2EXT-descriptorBuffer-09472]]
    The <<features-descriptorBuffer, pname:descriptorBuffer>> feature must:
    be enabled
  * [[VUID-vkCmdBindDescriptorBufferEmbeddedSamplers2EXT-pBindDescriptorBufferEmbeddedSamplersInfo-09473]]
    Each bit in pname:pBindDescriptorBufferEmbeddedSamplersInfo->stageFlags
    must: be a stage supported by the pname:commandBuffer's parent
    sname:VkCommandPool's queue family
****

include::{generated}/validity/protos/vkCmdBindDescriptorBufferEmbeddedSamplers2EXT.adoc[]
--

[open,refpage='VkBindDescriptorBufferEmbeddedSamplersInfoEXT',desc='Structure specifying embedded immutable sampler offsets to set in a command buffer',type='structs']
--
:refpage: VkBindDescriptorBufferEmbeddedSamplersInfoEXT

The sname:VkBindDescriptorBufferEmbeddedSamplersInfoEXT structure is defined
as:

include::{generated}/api/structs/VkBindDescriptorBufferEmbeddedSamplersInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:stageFlags is a bitmask of elink:VkShaderStageFlagBits specifying
    the shader stages that will use the embedded immutable samplers.
  * pname:layout is a slink:VkPipelineLayout object used to program the
    bindings.
ifdef::VK_NV_per_stage_descriptor_set[]
    If the <<features-dynamicPipelineLayout, pname:dynamicPipelineLayout>>
    feature is enabled, pname:layout can: be dlink:VK_NULL_HANDLE and the
    layout must: be specified by chaining slink:VkPipelineLayoutCreateInfo
    structure off the pname:pNext
endif::VK_NV_per_stage_descriptor_set[]
  * pname:set is the number of the set to be bound.

If pname:stageFlags specifies a subset of all stages corresponding to one or
more pipeline bind points, the binding operation still affects all stages
corresponding to the given pipeline bind point(s) as if the equivalent
original version of this command had been called with the same parameters.
For example, specifying a pname:stageFlags value of
ename:VK_SHADER_STAGE_VERTEX_BIT | ename:VK_SHADER_STAGE_FRAGMENT_BIT |
ename:VK_SHADER_STAGE_COMPUTE_BIT is equivalent to calling the original
version of this command once with ename:VK_PIPELINE_BIND_POINT_GRAPHICS and
once with ename:VK_PIPELINE_BIND_POINT_COMPUTE.

.Valid Usage
****
include::{chapters}/commonvalidity/bind_descriptor_buffer_embedded_samplers_common.adoc[]
include::{chapters}/commonvalidity/dynamic_pipeline_layout_common.adoc[]
****

include::{generated}/validity/structs/VkBindDescriptorBufferEmbeddedSamplersInfoEXT.adoc[]
--
endif::VK_COMPUTE_VERSION_1_4,VK_KHR_maintenance6[]


[[descriptorbuffers-updates]]
== Updating Descriptor Buffers

Updates to descriptor data in buffers can: be performed by any operation on
either the host or device that can: access memory.

Descriptor buffer reads can: be synchronized using
ename:VK_ACCESS_2_DESCRIPTOR_BUFFER_READ_BIT_EXT in the relevant shader
stage.


[[descriptorbuffers-push-descriptors]]
== Push Descriptors With Descriptor Buffers

If the <<features-descriptorBufferPushDescriptors,
pname:descriptorBufferPushDescriptors>> feature is enabled, push descriptors
can: be used with descriptor buffers in the same way as with descriptor
sets.

The <<limits-bufferlessPushDescriptors,
sname:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:bufferlessPushDescriptors>>
property indicates whether the implementation requires a buffer to back push
descriptors.
If the property is ename:VK_FALSE then before recording any push
descriptors, the application must: bind exactly `1` descriptor buffer that
was created with the
ename:VK_BUFFER_USAGE_PUSH_DESCRIPTORS_DESCRIPTOR_BUFFER_BIT_EXT usage flag
set.
When this buffer is bound, any previously recorded push descriptors that are
required for a subsequent command must: be recorded again.


[[descriptorbuffers-capturereplay]]
== Capture and Replay

In a similar way to <<features-bufferDeviceAddressCaptureReplay,
pname:bufferDeviceAddressCaptureReplay>>, the
<<features-descriptorBufferCaptureReplay,
pname:descriptorBufferCaptureReplay>> feature allows the creation of opaque
handles for objects at capture time that can: be passed into object creation
calls in a future replay, causing descriptors to be created with the same
data.
The opaque memory address for any memory used by these resources must: have
been captured using flink:vkGetDeviceMemoryOpaqueCaptureAddress and be
replayed using slink:VkMemoryOpaqueCaptureAddressAllocateInfo.

[open,refpage='vkGetBufferOpaqueCaptureDescriptorDataEXT',desc='Get buffer opaque capture descriptor data',type='protos']
--
To get the opaque descriptor data for a buffer, call:

include::{generated}/api/protos/vkGetBufferOpaqueCaptureDescriptorDataEXT.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a slink:VkBufferCaptureDescriptorDataInfoEXT
    structure specifying the buffer.
  * pname:pData is a pointer to an application-allocated buffer where the
    data will be written.

.Valid Usage
****
  * [[VUID-vkGetBufferOpaqueCaptureDescriptorDataEXT-None-08072]]
    The <<features-descriptorBufferCaptureReplay,
    pname:descriptorBufferCaptureReplay>> feature must: be enabled
  * [[VUID-vkGetBufferOpaqueCaptureDescriptorDataEXT-pData-08073]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:bufferCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetBufferOpaqueCaptureDescriptorDataEXT-device-08074]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetBufferOpaqueCaptureDescriptorDataEXT.adoc[]
--

[open,refpage='VkBufferCaptureDescriptorDataInfoEXT',desc='Structure specifying a buffer for descriptor capture',type='structs']
--
Information about the buffer to get descriptor buffer capture data for is
passed in a sname:VkBufferCaptureDescriptorDataInfoEXT structure:

include::{generated}/api/structs/VkBufferCaptureDescriptorDataInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:buffer is the sname:VkBuffer handle of the buffer to get opaque
    capture data for.

.Valid Usage
****
  * [[VUID-VkBufferCaptureDescriptorDataInfoEXT-buffer-08075]]
    pname:buffer must: have been created with
    ename:VK_BUFFER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT set in
    slink:VkBufferCreateInfo::pname:flags
****

include::{generated}/validity/structs/VkBufferCaptureDescriptorDataInfoEXT.adoc[]
--


[open,refpage='vkGetImageOpaqueCaptureDescriptorDataEXT',desc='Get image opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for an image, call:

include::{generated}/api/protos/vkGetImageOpaqueCaptureDescriptorDataEXT.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a slink:VkImageCaptureDescriptorDataInfoEXT
    structure specifying the image.
  * pname:pData is a pointer to an application-allocated buffer where the
    data will be written.

.Valid Usage
****
  * [[VUID-vkGetImageOpaqueCaptureDescriptorDataEXT-None-08076]]
    The <<features-descriptorBufferCaptureReplay,
    pname:descriptorBufferCaptureReplay>> feature must: be enabled
  * [[VUID-vkGetImageOpaqueCaptureDescriptorDataEXT-pData-08077]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:imageCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetImageOpaqueCaptureDescriptorDataEXT-device-08078]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetImageOpaqueCaptureDescriptorDataEXT.adoc[]
--

[open,refpage='VkImageCaptureDescriptorDataInfoEXT',desc='Structure specifying an image for descriptor capture',type='structs']
--
Information about the image to get descriptor buffer capture data for is
passed in a sname:VkImageCaptureDescriptorDataInfoEXT structure:

include::{generated}/api/structs/VkImageCaptureDescriptorDataInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:image is the sname:VkImage handle of the image to get opaque
    capture data for.

.Valid Usage
****
  * [[VUID-VkImageCaptureDescriptorDataInfoEXT-image-08079]]
    pname:image must: have been created with
    ename:VK_IMAGE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT set in
    slink:VkImageCreateInfo::pname:flags
****

include::{generated}/validity/structs/VkImageCaptureDescriptorDataInfoEXT.adoc[]
--

[open,refpage='vkGetImageViewOpaqueCaptureDescriptorDataEXT',desc='Get image view opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for an image view, call:

include::{generated}/api/protos/vkGetImageViewOpaqueCaptureDescriptorDataEXT.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a
    slink:VkImageViewCaptureDescriptorDataInfoEXT structure specifying the
    image view.
  * pname:pData is a pointer to an application-allocated buffer where the
    data will be written.

.Valid Usage
****
  * [[VUID-vkGetImageViewOpaqueCaptureDescriptorDataEXT-None-08080]]
    The <<features-descriptorBufferCaptureReplay,
    pname:descriptorBufferCaptureReplay>> feature must: be enabled
  * [[VUID-vkGetImageViewOpaqueCaptureDescriptorDataEXT-pData-08081]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:imageViewCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetImageViewOpaqueCaptureDescriptorDataEXT-device-08082]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetImageViewOpaqueCaptureDescriptorDataEXT.adoc[]
--

[open,refpage='VkImageViewCaptureDescriptorDataInfoEXT',desc='Structure specifying an image view for descriptor capture',type='structs']
--
Information about the image view to get descriptor buffer capture data for
is passed in a sname:VkImageViewCaptureDescriptorDataInfoEXT structure:

include::{generated}/api/structs/VkImageViewCaptureDescriptorDataInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:imageView is the sname:VkImageView handle of the image view to get
    opaque capture data for.

.Valid Usage
****
  * [[VUID-VkImageViewCaptureDescriptorDataInfoEXT-imageView-08083]]
    pname:imageView must: have been created with
    ename:VK_IMAGE_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT set
    in slink:VkImageViewCreateInfo::pname:flags
****

include::{generated}/validity/structs/VkImageViewCaptureDescriptorDataInfoEXT.adoc[]
--

[open,refpage='vkGetSamplerOpaqueCaptureDescriptorDataEXT',desc='Get sampler opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for a sampler, call:

include::{generated}/api/protos/vkGetSamplerOpaqueCaptureDescriptorDataEXT.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a
    slink:VkSamplerCaptureDescriptorDataInfoEXT structure specifying the
    sampler.
  * pname:pData is a pointer to an application-allocated buffer where the
    data will be written.

.Valid Usage
****
  * [[VUID-vkGetSamplerOpaqueCaptureDescriptorDataEXT-None-08084]]
    The <<features-descriptorBufferCaptureReplay,
    pname:descriptorBufferCaptureReplay>> feature must: be enabled
  * [[VUID-vkGetSamplerOpaqueCaptureDescriptorDataEXT-pData-08085]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:samplerCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetSamplerOpaqueCaptureDescriptorDataEXT-device-08086]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetSamplerOpaqueCaptureDescriptorDataEXT.adoc[]
--

[open,refpage='VkSamplerCaptureDescriptorDataInfoEXT',desc='Structure specifying a sampler for descriptor capture',type='structs']
--
Information about the sampler to get descriptor buffer capture data for is
passed in a sname:VkSamplerCaptureDescriptorDataInfoEXT structure:

include::{generated}/api/structs/VkSamplerCaptureDescriptorDataInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:sampler is the sname:VkSampler handle of the sampler to get opaque
    capture data for.

.Valid Usage
****
  * [[VUID-VkSamplerCaptureDescriptorDataInfoEXT-sampler-08087]]
    pname:sampler must: have been created with
    ename:VK_SAMPLER_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT set in
    slink:VkSamplerCreateInfo::pname:flags
****

include::{generated}/validity/structs/VkSamplerCaptureDescriptorDataInfoEXT.adoc[]
--

ifdef::VK_NV_ray_tracing,VK_KHR_acceleration_structure[]
[open,refpage='vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT',desc='Get acceleration structure opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for an acceleration structure,
call:

include::{generated}/api/protos/vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a
    slink:VkAccelerationStructureCaptureDescriptorDataInfoEXT structure
    specifying the acceleration structure.
  * pname:pData is a pointer to an application-allocated buffer where the
    data will be written.

.Valid Usage
****
  * [[VUID-vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT-None-08088]]
    The <<features-descriptorBufferCaptureReplay,
    pname:descriptorBufferCaptureReplay>> feature must: be enabled
  * [[VUID-vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT-pData-08089]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferPropertiesEXT::pname:accelerationStructureCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT-device-08090]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT.adoc[]
--

[open,refpage='VkAccelerationStructureCaptureDescriptorDataInfoEXT',desc='Structure specifying an acceleration structure for descriptor capture',type='structs']
--
Information about the acceleration structure to get descriptor buffer
capture data for is passed in a
sname:VkAccelerationStructureCaptureDescriptorDataInfoEXT structure:

include::{generated}/api/structs/VkAccelerationStructureCaptureDescriptorDataInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:accelerationStructure is the sname:VkAccelerationStructureKHR
    handle of the acceleration structure to get opaque capture data for.
  * pname:accelerationStructureNV is the sname:VkAccelerationStructureNV
    handle of the acceleration structure to get opaque capture data for.

.Valid Usage
****
  * [[VUID-VkAccelerationStructureCaptureDescriptorDataInfoEXT-accelerationStructure-08091]]
    If pname:accelerationStructure is not dlink:VK_NULL_HANDLE then
    pname:accelerationStructure must: have been created with
    ename:VK_ACCELERATION_STRUCTURE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT
    set in slink:VkAccelerationStructureCreateInfoKHR::pname:createFlags
  * [[VUID-VkAccelerationStructureCaptureDescriptorDataInfoEXT-accelerationStructureNV-08092]]
    If pname:accelerationStructureNV is not dlink:VK_NULL_HANDLE then
    pname:accelerationStructureNV must: have been created with
    ename:VK_ACCELERATION_STRUCTURE_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_EXT
    set in slink:VkAccelerationStructureCreateInfoNV::pname:info.flags
  * [[VUID-VkAccelerationStructureCaptureDescriptorDataInfoEXT-accelerationStructure-08093]]
    If pname:accelerationStructure is not dlink:VK_NULL_HANDLE then
    pname:accelerationStructureNV must: be dlink:VK_NULL_HANDLE
  * [[VUID-VkAccelerationStructureCaptureDescriptorDataInfoEXT-accelerationStructureNV-08094]]
    If pname:accelerationStructureNV is not dlink:VK_NULL_HANDLE then
    pname:accelerationStructure must: be dlink:VK_NULL_HANDLE
****

include::{generated}/validity/structs/VkAccelerationStructureCaptureDescriptorDataInfoEXT.adoc[]
--
endif::VK_NV_ray_tracing,VK_KHR_acceleration_structure[]

[open,refpage='VkOpaqueCaptureDescriptorDataCreateInfoEXT',desc='Structure specifying opaque capture descriptor data',type='structs']
--
The sname:VkOpaqueCaptureDescriptorDataCreateInfoEXT structure is defined
as:

include::{generated}/api/structs/VkOpaqueCaptureDescriptorDataCreateInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:opaqueCaptureDescriptorData is a pointer to an
    application-allocated buffer containing opaque capture data retrieved
    using flink:vkGetBufferOpaqueCaptureDescriptorDataEXT,
    flink:vkGetImageOpaqueCaptureDescriptorDataEXT,
    flink:vkGetImageViewOpaqueCaptureDescriptorDataEXT,
ifdef::VK_ARM_tensors[]
    flink:vkGetTensorOpaqueCaptureDescriptorDataARM,
    flink:vkGetTensorViewOpaqueCaptureDescriptorDataARM,
endif::VK_ARM_tensors[]
    flink:vkGetSamplerOpaqueCaptureDescriptorDataEXT, or
    flink:vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT.

During replay, opaque descriptor capture data can: be specified by adding a
sname:VkOpaqueCaptureDescriptorDataCreateInfoEXT structure to the relevant
pname:pNext chain of a slink:VkBufferCreateInfo, slink:VkImageCreateInfo,
slink:VkImageViewCreateInfo, slink:VkSamplerCreateInfo,
ifdef::VK_ARM_tensors[]
slink:VkTensorCreateInfoARM, slink:VkTensorViewCreateInfoARM,
endif::VK_ARM_tensors[]
slink:VkAccelerationStructureCreateInfoNV or
slink:VkAccelerationStructureCreateInfoKHR structure.

ifdef::VK_EXT_descriptor_heap[]
When providing opaque capture data for an image, if the pname:pNext chain of
slink:VkImageCreateInfo
ifdef::VK_ARM_tensors[]
or slink:VkTensorCreateInfoARM
endif::VK_ARM_tensors[]
contains an instance of both this structure and
slink:VkOpaqueCaptureDataCreateInfoEXT, they should: both specify data from
the same original resource.
If they have capture data from different original resources, resource
creation is much more likely to fail.
endif::VK_EXT_descriptor_heap[]


include::{generated}/validity/structs/VkOpaqueCaptureDescriptorDataCreateInfoEXT.adoc[]
--

ifdef::VK_ARM_tensors[]
[open,refpage='vkGetTensorOpaqueCaptureDescriptorDataARM',desc='Get tensor opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for a tensor, call:

include::{generated}/api/protos/vkGetTensorOpaqueCaptureDescriptorDataARM.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a slink:VkTensorCaptureDescriptorDataInfoARM
    structure specifying the tensor.
  * pname:pData is a pointer to a user-allocated buffer where the data will
    be written.

.Valid Usage
****
  * [[VUID-vkGetTensorOpaqueCaptureDescriptorDataARM-descriptorBufferCaptureReplay-09702]]
    The <<features-descriptorBuffer, pname:descriptorBufferCaptureReplay>>
    and <<features-descriptorBufferTensorDescriptors,
    pname:descriptorBufferTensorDescriptors>> features must: be enabled
  * [[VUID-vkGetTensorOpaqueCaptureDescriptorDataARM-pData-09703]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferTensorPropertiesARM::pname:tensorCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetTensorOpaqueCaptureDescriptorDataARM-device-09704]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetTensorOpaqueCaptureDescriptorDataARM.adoc[]
--

[open,refpage='VkTensorCaptureDescriptorDataInfoARM',desc='Structure specifying a tensor for descriptor capture',type='structs']
--
Information about the tensor to get descriptor buffer capture data for is
passed in a sname:VkTensorCaptureDescriptorDataInfoARM structure:

include::{generated}/api/structs/VkTensorCaptureDescriptorDataInfoARM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:tensor is the sname:VkTensorARM handle of the tensor to get opaque
    capture data for.

.Valid Usage
****
  * [[VUID-VkTensorCaptureDescriptorDataInfoARM-tensor-09705]]
    If pname:tensor is not dlink:VK_NULL_HANDLE then pname:tensor must: have
    been created with
    ename:VK_TENSOR_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM set in
    slink:VkTensorCreateInfoARM::pname:flags
****

include::{generated}/validity/structs/VkTensorCaptureDescriptorDataInfoARM.adoc[]
--

[open,refpage='vkGetTensorViewOpaqueCaptureDescriptorDataARM',desc='Get tensor view opaque capture descriptor data',type='protos']
--
To get the opaque capture descriptor data for a tensor view, call:

include::{generated}/api/protos/vkGetTensorViewOpaqueCaptureDescriptorDataARM.adoc[]

  * pname:device is the logical device that gets the data.
  * pname:pInfo is a pointer to a
    slink:VkTensorViewCaptureDescriptorDataInfoARM structure specifying the
    tensor view.
  * pname:pData is a pointer to a user-allocated buffer where the data will
    be written.

.Valid Usage
****
  * [[VUID-vkGetTensorViewOpaqueCaptureDescriptorDataARM-descriptorBufferCaptureReplay-09706]]
    The <<features-descriptorBuffer, pname:descriptorBufferCaptureReplay>>
    and <<features-descriptorBufferTensorDescriptors,
    pname:descriptorBufferTensorDescriptors>> features must: be enabled
  * [[VUID-vkGetTensorViewOpaqueCaptureDescriptorDataARM-pData-09707]]
    pname:pData must: point to a buffer that is at least
    slink:VkPhysicalDeviceDescriptorBufferTensorPropertiesARM::pname:tensorViewCaptureReplayDescriptorDataSize
    bytes in size
  * [[VUID-vkGetTensorViewOpaqueCaptureDescriptorDataARM-device-09708]]
    If pname:device was created with multiple physical devices, then the
    <<features-bufferDeviceAddressMultiDevice,
    pname:bufferDeviceAddressMultiDevice>> feature must: be enabled
****

include::{generated}/validity/protos/vkGetTensorViewOpaqueCaptureDescriptorDataARM.adoc[]
--

[open,refpage='VkTensorViewCaptureDescriptorDataInfoARM',desc='Structure specifying a tensor view for descriptor capture',type='structs']
--
Information about the tensor view to get descriptor buffer capture data for
is passed in a sname:VkTensorViewCaptureDescriptorDataInfoARM structure:

include::{generated}/api/structs/VkTensorViewCaptureDescriptorDataInfoARM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:tensorView is the sname:VkTensorViewARM handle of the tensor view
    to get opaque capture data for.

.Valid Usage
****
  * [[VUID-VkTensorViewCaptureDescriptorDataInfoARM-tensorView-09709]]
    If pname:tensorView is not dlink:VK_NULL_HANDLE then pname:tensorView
    must: have been created with
    ename:VK_TENSOR_VIEW_CREATE_DESCRIPTOR_BUFFER_CAPTURE_REPLAY_BIT_ARM set
    in slink:VkTensorViewCreateInfoARM::pname:flags
****

include::{generated}/validity/structs/VkTensorViewCaptureDescriptorDataInfoARM.adoc[]
--

endif::VK_ARM_tensors[]
