// Copyright 2025-2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[[images]]
= Images

Images are specialized resources that have multi-dimensional access rather
than the typical linear access to memory.
These resources allow implementations to optimize the memory layout for
common access patterns, by mapping multi-dimensional coordinates to an
implementation-dependent offset in the underlying memory.

Additionally, images are homogeneous, with every discrete coordinate
associated with data that is in the same format as the data associated with
any other coordinate.
Each set of data associated with one of these coordinates is referred to in
this specification as a _texel_.
A texel can consist of up to 4 separate components, labeled as
[eq]#(R,G,B,A)# in this chapter.

[NOTE]
====
This terminology is historical; texel is a combination of the words
pass:a,q[{texture-bold-tex}] and "`**el**ement`", and [eq]#(R,G,B,A)# are
abbreviations for **R**ed, **G**reen, **B**lue, and **A**lpha.
Early interactive computer graphics only supported operations that allowed
image data to be used to add color "`texture`" to rendered objects, which is
just a small subset of what the image operations on images described here
enable.
These terms are deeply embedded in the industry, and so are still used here
by convention, despite images being used in far more varied ways than they
were in the past.
====

Some image formats identify components as [eq]#D# for **d**epth, [eq]#S# for
**s**tencil, or [eq]#X# for padding elements.
Image format components identified as [eq]#D# are treated as [eq]#R#, and
[eq]#S# components are treated as [eq]#G# for the purpose of image accesses.
[eq]#X# components are ignored when reading, and may: be modified in
implementation-dependent ways when writing to that texel.

The coordinates used to identify a texel are six-dimensional, made up of the
following integer indices:

  * [eq]#x# - The first spatial index
  * [eq]#y# - The second spatial index
  * [eq]#z# - The third spatial index
  * [eq]#layer# - The array index for arrayed images
  * [eq]#sample# - The sample index
  * [eq]#level# - The detail level

Each image is constructed with a number of texels in each dimension, with
the integer size in each dimension for that image identified as:

  * [eq]#width# - The number of [eq]#x# indices
  * [eq]#height# - The number of [eq]#y# indices
  * [eq]#depth# - The number of [eq]#z# indices
  * [eq]#layers# - The number of layers
  * [eq]#samples# - The number of samples
  * [eq]#levels# - The number of detail levels

Of these sizes, the number of [eq]#levels# is somewhat unique - each further
level reduces the number of indices in each of the [eq]#x#, [eq]#y#, and
[eq]#z# dimensions by half, according to these formulae:

  * [eq]#width~level~ = max(1, {lfloor}width / 2^level^{rfloor})#
  * [eq]#height~level~ = max(1, {lfloor}height / 2^level^{rfloor})#
  * [eq]#depth~level~ = max(1, {lfloor}depth / 2^level^{rfloor})#

An image will have no more than one level where all of the above dimensions
are set to 1.
See <<resources-image-mip-level-sizing, Image Mip Level Sizing>> for more
details.

The Vulkan specification allows the creation of resources with fewer
dimensions than this (e.g. texel buffers); these can be considered
equivalent to an image with all dimensions specified, with the missing
dimensions having a size of 1, and an implicit coordinate value of 0.

These parameters are set for an image during <<resources-images, image
creation>>, and are adjusted when accessing an image through an
<<resources-image-views, image view>>.


ifdef::VK_COMPUTE_VERSION_1_0[]
[[images-coordinate-validation]]
== Image Coordinate Validation

When accessing an image, a set of [eq]#(x,y,z,layer,sample,level)#
coordinates are used to indicate which texel is accessed.
These coordinates are first checked to see if they refer to texels within
the image dimensions, according to the following equations:

  * [eq]#x < width~level~#
  * [eq]#y < height~level~#
  * [eq]#z < depth~level~#
  * [eq]#layer < layers#
  * [eq]#sample < samples#
  * [eq]#level < levels#

If any of these equations evaluates to false, the coordinate is considered
<<shaders-execution-memory-access-bounds, out of bounds>>, otherwise they
are _in bounds_.


[[images-reads]]
== Image Reads

Image reads use a set of [eq]#(x,y,z,layer,sample,level)# coordinates,
validated as per <<images-coordinate-validation, Image Coordinate
Validation>>, and return a converted value for the texel at that coordinate.
If the coordinates are out of bounds, behavior of the read is as described
in <<shaders-execution-memory-access-bounds, Shader Out-of-Bounds Memory
Access>>.
ifndef::VKSC_VERSION_1_0[]
If the coordinates are in bounds, but the texel is not backed by memory,
behavior of the read is as described in <<sparsememory-accessing-unbound>>.
endif::VKSC_VERSION_1_0[]
Otherwise, the read proceeds as follows.


[[images-texel-decode]]
=== Texel Decode

The formatted value of the texel at the [eq]#(x,y,z,layer,sample,level)#
coordinate is read and decoded according to the procedures outlined in the
<<data-format, Khronos Data Format Specification>>.

For sRGB formats, the [eq]#(R,G,B,A)# components are first converted as if
they are etext:UNORM formats, and then sRGB to linear conversion is
performed on the converted [eq]#(R,G,B)# components, as described in the
"`sRGB EOTF`" section of the <<data-format, Khronos Data Format
Specification>>.


[[images-component-substitution]]
=== Component Substitution

If after conversion, less than four of the [eq]#(R,G,B,A)# components are
present, missing components are substituted by the components of
[eq]#(0,0,0,1)# for missing [eq]#(R,G,B,A)# components, respectively.


[[images-component-encoding]]
=== Numeric Encoding

The values are encoded according to the bit width and
<<formats-numericformat, numeric format>> of each component:

  * Components with a fixed-point numeric format or with a floating-point
    numeric format and a bit width less than or equal to 32 are encoded into
    the <<ieee-754, IEEE-754>> binary32 format.
  * Components with a floating-point numeric format and a bit width greater
    than 32 are encoded into the <<ieee-754, IEEE-754>> binary64 format.
  * Components with an integer numeric format and a bit width less than or
    equal to 32 are directly encoded as 32-bit integer values with the same
    signedness.
  * Components with an integer numeric format and a bit width greater than
    32 are directly encoded as 64-bit integer values with the same
    signedness.

These values are then returned as the result of the image read.


[[images-writes]]
== Image Writes

Image writes also use a set of [eq]#(x,y,z,layer,sample,level)# coordinates,
validated as per <<images-coordinate-validation, Image Coordinate
Validation>>, and with a [eq]#value# to be written.
If the coordinates are out of bounds, behavior of the write is as described
in <<shaders-execution-memory-access-bounds>>.
ifndef::VKSC_VERSION_1_0[]
If the coordinates are in bounds, but the texel is not backed by memory, the
write is silently discarded.
endif::VKSC_VERSION_1_0[]
Otherwise, an image write is performed as follows:


[[images-texel-encode]]
=== Texel Encode
If the image format is sRGB, a linear to sRGB conversion is applied to the
[eq]#(R,G,B)# components of [eq]#value# as described in the "`sRGB EOTF`"
section of the <<data-format, Khronos Data Format Specification>>.

The converted [eq]#(R,G,B)# and original [eq]#A# values are then encoded to
the image format according to the procedures outlined in the <<data-format,
Khronos Data Format Specification>>.
Components not present in the image format are discarded.

The final value is then written to the texel at
[eq]#(x,y,z,layer,sample,level)#.

[[images-spirv]]
== SPIR-V Image Access

Images are represented in SPIR-V by variables with the
{spirvspec}#OpTypeImage[OpTypeImage] type, and operated on by
{spirvspec}#Image[image instructions].

Images are mapped to a shader using image views, which define access to a
subset of the base image resource, specified by
slink:VkImageSubresourceRange.


[[images-spirv-reads]]
=== SPIR-V Image Read Instructions

Texels can: be <<images-reads, read from an image>> using
{spirvspec}#OpImageRead[OpImageRead] or
{spirvspec}#OpImageSparseRead[OpImageSparseRead].
The elements of the _Coordinate_ operand and the optional code:Sample
{spirvspec}#Image_Operands[image operand] map to
<<images-coordinate-validation, image coordinates>>, modified by the
parameters of the image view used, as:

  * [eq]#x = code:u#
  * [eq]#y = code:v#
  * [eq]#z = code:w#
  * [eq]#layer = code:array_layer#
  * [eq]#sample = code:Sample#
  * [eq]#level = 0#

Any index missing in the instruction is implicitly set to 0.

After the coordinates are validated, some indices are offset before
performing the access as follows:

  * [eq]#layer += slink:VkImageSubresourceRange::pname:baseArrayLayer#
  * [eq]#level += slink:VkImageSubresourceRange::pname:baseMipLevel#
ifdef::VK_EXT_image_sliced_view_of_3d[]
  * [eq]#z += slink:VkImageViewSlicedCreateInfoEXT::sliceOffset#
endif::VK_EXT_image_sliced_view_of_3d[]


[[images-spirv-writes]]
=== SPIR-V Image Write Instructions

Texels can: be <<images-writes, written to an image>> using
{spirvspec}#OpImageWrite[OpImageWrite].
The elements of the _Coordinate_ operand and the optional code:Sample
{spirvspec}#Image_Operands[image operand] map to
<<images-coordinate-validation, image coordinates>>, modified by the
parameters of the image view used, in the same ways as for
<<images-spirv-reads, image reads>>.


[[images-spirv-atomics]]
=== SPIR-V Image Atomic Instructions

{spirvspec}#Atomic[SPIR-V atomic instructions] operate on pointers rather
than texels, but can: be used with texels via
{spirvspec}#OpImageTexelPointer[OpImageTexelPointer].
{spirvspec}#OpImageTexelPointer[OpImageTexelPointer] can: be used to obtain
a valid pointer to a specific texel in an image.
The elements of the _Coordinate_ operand and the optional code:Sample
{spirvspec}#Image_Operands[image operand] map to
<<images-coordinate-validation, image coordinates>>, modified by the
parameters of the image view used, in the same ways as for
<<images-spirv-reads, image reads>>.
The resulting pointer can: be used to access the identified texel, with
atomic operations potentially <<images-reads, reading>> and <<images-writes,
writing>> to that texel.


[[images-spirv-queries]]
=== SPIR-V Image Query Instructions

Query operations return properties of an image, allowing the accessible size
of each dimension of an image to be queried from within a shader.
Query operations do not access any texels in the image.

  * code:OpImageQuerySizeLod returns the values of [eq]#width~level~#,
    [eq]#height~level~#, [eq]#depth~level~#, and [eq]#layers# for the image
    at a specified [eq]#level#, where [eq]#level# is equal to the sum of the
    code:Level code:of code:Detail operand and
    slink:VkImageSubresourceRange::baseMipLevel.
ifdef::VK_EXT_image_sliced_view_of_3d[]
    If the image is not a sampled image and
    slink:VkImageViewSlicedCreateInfoEXT::pname:sliceCount is not set to
    ename:VK_REMAINING_3D_SLICES_EXT, pname:sliceCount will be returned in
    place of [eq]#depth~level~#.
    If the image is not a sampled image and
    slink:VkImageViewSlicedCreateInfoEXT::pname:sliceCount is set to
    ename:VK_REMAINING_3D_SLICES_EXT, the value returned will be equal to
    [eq]#depth~level~ :minus:
    slink:VkImageViewSlicedCreateInfoEXT::pname:sliceOffset#.
endif::VK_EXT_image_sliced_view_of_3d[]
    If code:Level code:of code:Detail is greater than
    slink:VkImageSubresourceRange::pname:levelCount, the result is
    undefined:.
  * code:OpImageQuerySize is equivalent to code:OpImageQuerySizeLod with
    [eq]#level# set to slink:VkImageSubresourceRange::baseMipLevel.
  * code:OpImageQueryLevels returns the value of
    slink:VkImageSubresourceRange::levelCount specified for the image view
    used.
  * code:OpImageQuerySamples returns the value of [eq]#samples# for the
    image.

[NOTE]
====
code:OpImageQueryLod is performed as a sampling operation, so is not
included here.
====

ifdef::VK_EXT_robustness2,VK_KHR_robustness2[]
If the descriptor bound to the image is a null descriptor, all values
returned by the above queries are replaced with 0.
endif::VK_EXT_robustness2,VK_KHR_robustness2[]

ifdef::VK_QCOM_image_processing[]
If the image is a <<textures-weightimage,weight image>>, all values returned
by the above queries are undefined:.
endif::VK_QCOM_image_processing[]


[[images-spirv-sampling]]
=== SPIR-V Image Sampling Instructions

Sampling operations can: also be performed on images, typically in
conjunction with a <<samplers,sampler>>, as defined in the
<<textures,Sampling>> chapter.
endif::VK_COMPUTE_VERSION_1_0[]
