// Copyright (c) 2019-2020 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

[[partitioned-tlas]]
== Partitioned Top Level Acceleration Structures

Partitioned Top Level Acceleration Structures (PTLAS) allow efficient reuse
of previously constructed sections of the top level acceleration structure
by eliminating a full rebuild when only a few instances are modified.
This reduces build times and supports handling a higher number of instances,
making it more suitable for large and complex scenes.

PTLAS organizes instances into partitions, enabling a two-stage build
process: first, it constructs an acceleration structure for each partition
by grouping the instances within it, and second, it combines these partition
structures into a single acceleration structure, similar to the current
top-level acceleration structure.

To maintain compatibility, PTLAS behaves identically to the current
top-level acceleration structure from the perspective of ray tracing shaders
and pipelines.

[[ptlas-global-partition]]
PTLAS includes a unique global partition that operates independently of
other partitions.
Instances can: be assigned to this global partition just like they would to
regular partitions.
The global partition is well-suited for frequently updated instances, such
as animated characters.
During the build process, instances in the global partition are treated as
if they belong to individual partitions, without increasing the maximum
partition count.
However, instances in the global partition may still impact build
performance.
Once these instances become stable, they should be moved to a spatially
optimized, non-global partition to lower build costs and minimize trace
performance issues.

[[ptlas-partition-translation]]
To handle large worlds requiring more precision than 32-bit floating-point
numbers offer, PTLAS offers efficient partition translation.
Typically, applications maintain precision by placing the world center near
the camera.
Partition translation allows an additional translation of instances during
construction without changing their stored transforms.
This method stores instance transforms relative to partitions, applying a
translation to achieve accurate world positions.
Higher precision is maintained using smaller floating-point numbers until
the structure is built.
World space coordinates can: also be updated efficiently without rebuilding
the entire PTLAS.
Partition translation requires extra memory for untranslated instance
transforms and must: be explicitly enabled with
slink:VkPartitionedAccelerationStructureFlagsNV::pname:enablePartitionTranslation
flag.

[open,refpage='vkGetPartitionedAccelerationStructuresBuildSizesNV',desc='Retrieve the buffer allocation requirements for partitioned acceleration structure command',type='protos']
--
To determine the memory requirements for a PTAS, call:

include::{generated}/api/protos/vkGetPartitionedAccelerationStructuresBuildSizesNV.adoc[]

  * pname:device is the logical device that owns the acceleration structure.
  * pname:pInfo is a pointer to a
    slink:VkPartitionedAccelerationStructureInstancesInputNV structure
    containing parameters required for the memory requirements query.
  * pname:pSizeInfo is a pointer to a
    slink:VkAccelerationStructureBuildSizesInfoKHR structure which returns
    the size required for an acceleration structure and the sizes required
    for the scratch buffers, given the build parameters.
    The size requirements for a scratch buffer may: be zero.


.Valid Usage
****
  * [[VUID-vkGetPartitionedAccelerationStructuresBuildSizesNV-partitionedAccelerationStructure-10534]]
    The <<features-partitionedAccelerationStructure,
    sname:VkPhysicalDevicePartitionedAccelerationStructureFeaturesNV::pname:partitionedAccelerationStructure>>
    feature must: be enabled
****

include::{generated}/validity/protos/vkGetPartitionedAccelerationStructuresBuildSizesNV.adoc[]
--


[open,refpage='VkPartitionedAccelerationStructureInstancesInputNV',desc='Parameters describing a PTLAS structure',type='structs']
--
:refpage: VkPartitionedAccelerationStructureInstancesInputNV

The slink:VkPartitionedAccelerationStructureInstancesInputNV structure is
defined as:

include::{generated}/api/structs/VkPartitionedAccelerationStructureInstancesInputNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of tlink:VkBuildAccelerationStructureFlagsKHR
    specifying flags for the PTLAS build operation.
  * pname:instanceCount is the number of instances in this PTLAS.
  * pname:maxInstancePerPartitionCount is the maximum number of instances
    per partition in the PTLAS.
  * pname:partitionCount is the number of partitions in the PTLAS.
  * pname:maxInstanceInGlobalPartitionCount is maximum number of instances
    in the <<ptlas-global-partition, global partition>>.

If the pname:pNext chain includes a
slink:VkPartitionedAccelerationStructureFlagsNV structure, then that
structure specifies additional flags for the PTLAS.

.Valid Usage
****
  * [[VUID-VkPartitionedAccelerationStructureInstancesInputNV-partitionCount-10535]]
    The sum of pname:partitionCount and
    pname:maxInstanceInGlobalPartitionCount must: be less than or equal to
    slink:VkPhysicalDevicePartitionedAccelerationStructurePropertiesNV::pname:maxPartitionCount
****

include::{generated}/validity/structs/VkPartitionedAccelerationStructureInstancesInputNV.adoc[]
--


[open,refpage='VkPartitionedAccelerationStructureFlagsNV',desc='Structure describing additional flags for PTLAS',type='structs']
--
:refpage: VkPartitionedAccelerationStructureFlagsNV

The slink:VkPartitionedAccelerationStructureFlagsNV structure is defined as:

include::{generated}/api/structs/VkPartitionedAccelerationStructureFlagsNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:enablePartitionTranslation specifies if a
    <<ptlas-partition-translation, partition translation>> may: be applied
    with
    slink:VkPartitionedAccelerationStructureWritePartitionTranslationDataNV.

include::{generated}/validity/structs/VkPartitionedAccelerationStructureFlagsNV.adoc[]
--


[open,refpage='vkCmdBuildPartitionedAccelerationStructuresNV',desc='Command for building a PTLAS',type='protos']
--
To build a partitioned top level acceleration structure, call:

include::{generated}/api/protos/vkCmdBuildPartitionedAccelerationStructuresNV.adoc[]

  * pname:commandBuffer is the command buffer into which the command is
    recorded.
  * pname:pBuildInfo is a pointer to a
    slink:VkBuildPartitionedAccelerationStructureInfoNV structure containing
    parameters required for building a PTLAS.

Accesses to the acceleration structure scratch memory as identified by the
slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:scratchData must:
be <<synchronization-dependencies,synchronized>> with the
ename:VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR
<<synchronization-pipeline-stages, pipeline stage>> and an
<<synchronization-access-types, access type>> of
(ename:VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR |
ename:VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR).

Accesses to each
slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:srcAccelerationStructureData
and
slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:dstAccelerationStructureData
must: be <<synchronization-dependencies,synchronized>> with the
ename:VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR
<<synchronization-pipeline-stages, pipeline stage>> and an
<<synchronization-access-types, access type>> of
ename:VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR or
ename:VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR, as appropriate.

Accesses to memory with input data as identified by any used values of
slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:srcInfos and
slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:srcInfosCount
must: be <<synchronization-dependencies,synchronized>> with the
ename:VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR
<<synchronization-pipeline-stages, pipeline stage>> and an
<<synchronization-access-types, access type>> of
ename:VK_ACCESS_INDIRECT_COMMAND_READ_BIT.

.Valid Usage
****
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-partitionedAccelerationStructure-10536]]
    The <<features-partitionedAccelerationStructure,
    sname:VkPhysicalDevicePartitionedAccelerationStructureFeaturesNV::pname:partitionedAccelerationStructure>>
    feature must: be enabled
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10537]]
    The count specified in pname:pBuildInfo->input.instanceCount for the
    build operation must: not exceed the value provided in
    pname:pInfo->instanceCount when calling
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV to determine
    the memory size
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10538]]
    The count specified in
    pname:pBuildInfo->input.maxInstancePerPartitionCount for the build
    operation must: not exceed the value provided in
    pname:pInfo->maxInstancePerPartitionCount when calling
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV to determine
    the memory size
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10539]]
    The count specified in pname:pBuildInfo->input.partitionCount for the
    build operation must: not exceed the value provided in
    pname:pInfo->partitionCount when calling
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV to determine
    the memory size
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10540]]
    The count specified in
    pname:pBuildInfo->input.maxInstanceInGlobalPartitionCount for the build
    operation must: not exceed the value provided in
    pname:pInfo->maxInstanceInGlobalPartitionCount when calling
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV to determine
    the memory size
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10541]]
    The scratch memory for the partitioned acceleration structure build
    specified in pname:pBuildInfo->scratchData must: be larger than or equal
    to the scratch size queried with
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10542]]
    pname:pBuildInfo->scratchData must: be aligned to `256` bytes
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10543]]
    The destination memory of the partitioned acceleration structure build
    specified in pname:pBuildInfo->dstAccelerationStructureData must: be
    larger than or equal to the size queried with
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10544]]
    pname:pBuildInfo->srcAccelerationStructureData must: be aligned to `256`
    bytes
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10545]]
    pname:pBuildInfo->dstAccelerationStructureData must: be aligned to `256`
    bytes
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10546]]
    The number of inputs specified in pname:pBuildInfo->srcInfos must: be
    greater than or equal to pname:pBuildInfo->srcInfosCount
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10547]]
    The memory region containing the acceleration structure at address
    pname:pBuildInfo->srcAccelerationStructureData must: not overlap with
    scratch memory region at address pname:pBuildInfo->scratchData
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10548]]
    The memory region containing the acceleration structure at address
    pname:pBuildInfo->dstAccelerationStructureData must: not overlap with
    scratch memory region at address pname:pBuildInfo->scratchData
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10549]]
    The memory regions containing the acceleration structures at addresses
    pname:pBuildInfo->srcAccelerationStructureData and
    pname:pBuildInfo->dstAccelerationStructureData must: not overlap with
    each other
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10550]]
    pname:pBuildInfo->scratchData must: be a device address allocated to the
    application from a buffer created with the
    ename:VK_BUFFER_USAGE_STORAGE_BUFFER_BIT usage flag set
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10551]]
    pname:pBuildInfo->srcInfos and pname:pBuildInfo->srcInfosCount must: be
    device addresses allocated to the application from buffers created with
    the
    ename:VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR
    usage flag set
  * [[VUID-vkCmdBuildPartitionedAccelerationStructuresNV-pBuildInfo-10552]]
    pname:pBuildInfo->srcAccelerationStructureData and
    pname:pBuildInfo->dstAccelerationStructureData must: be a device
    addresses allocated to the application from buffers created with the
    ename:VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR usage flag
    set
****

include::{generated}/validity/protos/vkCmdBuildPartitionedAccelerationStructuresNV.adoc[]
--

[open,refpage='VkBuildPartitionedAccelerationStructureInfoNV',desc='Structure describing build parameters for a PTLAS',type='structs']
--
:refpage: VkBuildPartitionedAccelerationStructureInfoNV

The slink:VkBuildPartitionedAccelerationStructureInfoNV structure is defined
as:

include::{generated}/api/structs/VkBuildPartitionedAccelerationStructureInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:input is a
    slink:VkPartitionedAccelerationStructureInstancesInputNV structure
    describing the instance and partition count information in the PTLAS.
  * pname:srcAccelerationStructureData is `NULL` or an address of a
    previously built PTLAS.
    If non-`NULL`, the PTLAS stored at this address is used as a basis to
    create new PTLAS.
  * pname:dstAccelerationStructureData is the address to store the built
    PTLAS.
  * pname:scratchData is the device address of scratch memory that will be
    used during PTLAS build.
  * pname:srcInfos is the device address of an array of
    slink:VkBuildPartitionedAccelerationStructureIndirectCommandNV
    structures describing the type of operation to perform.
  * pname:srcInfosCount is a device address containing the size of
    pname:srcInfos array.

Members pname:srcAccelerationStructureData and
pname:dstAccelerationStructureData may: be the same or different.
If they are the same, the update happens in-place.
Otherwise, the destination acceleration structure is updated and the source
is not modified.

.Valid Usage
****
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-scratchData-10558]]
    If the pname:buildScratchSize member of the
    slink:VkAccelerationStructureBuildSizesInfoKHR structure returned from a
    call to flink:vkGetPartitionedAccelerationStructuresBuildSizesNV is not
    `0`, then pname:scratchData must: be a valid device address
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-scratchData-10559]]
    Memory at pname:scratchData must: be equal or larger than the
    slink:VkAccelerationStructureBuildSizesInfoKHR::pname:buildScratchSize
    value returned from
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV with the same
    build parameters
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-srcAccelerationStructureData-10560]]
    If pname:srcAccelerationStructureData is not `NULL`, it must: have
    previously been built as a PTLAS
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-dstAccelerationStructureData-10561]]
    pname:dstAccelerationStructureData must: not be `NULL`
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-dstAccelerationStructureData-10562]]
    Memory at pname:dstAccelerationStructureData must: be equal or larger
    than the
    slink:VkAccelerationStructureBuildSizesInfoKHR::pname:accelerationStructureSize
    value returned from
    flink:vkGetPartitionedAccelerationStructuresBuildSizesNV with the same
    build parameters
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-srcInfosCount-10563]]
    pname:srcInfosCount must: be 4-byte aligned
  * [[VUID-VkBuildPartitionedAccelerationStructureInfoNV-srcInfos-10564]]
    Each element of pname:srcInfos array must: have a unique
    slink:VkBuildPartitionedAccelerationStructureIndirectCommandNV::pname:opType
****

include::{generated}/validity/structs/VkBuildPartitionedAccelerationStructureInfoNV.adoc[]
--


[open,refpage='VkBuildPartitionedAccelerationStructureIndirectCommandNV',desc='Structure describing PTLAS operation to perform',type='structs']
--
:refpage: VkBuildPartitionedAccelerationStructureIndirectCommandNV

The slink:VkBuildPartitionedAccelerationStructureIndirectCommandNV structure
is defined as:

include::{generated}/api/structs/VkBuildPartitionedAccelerationStructureIndirectCommandNV.adoc[]

  * pname:opType is a elink:VkPartitionedAccelerationStructureOpTypeNV
    describing the type of operation.
  * pname:argCount the number of structures in pname:argData array.
  * pname:argData is an array of slink:VkStridedDeviceAddressNV structures
    containing the write or update data for instances and partitions in the
    PTLAS.
    The structure is dependent on pname:opType as shown in the table below.
[options="header"]
|====
| pname:opType | Format of pname:argData
| ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_INSTANCE_NV |slink:VkPartitionedAccelerationStructureWriteInstanceDataNV
| ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_UPDATE_INSTANCE_NV |slink:VkPartitionedAccelerationStructureUpdateInstanceDataNV
| ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_PARTITION_TRANSLATION_NV |slink:VkPartitionedAccelerationStructureWritePartitionTranslationDataNV
|====

.Valid Usage
****
  * [[VUID-VkBuildPartitionedAccelerationStructureIndirectCommandNV-argData-10565]]
    An instance index must: not be referenced by more than one structure in
    pname:argData
****

include::{generated}/validity/structs/VkBuildPartitionedAccelerationStructureIndirectCommandNV.adoc[]
--

[open,refpage='VkPartitionedAccelerationStructureOpTypeNV',desc='Enum providing the type of PTLAS operation to perform',type='enums']
--
Values which can: be set in elink:VkPartitionedAccelerationStructureOpTypeNV
are:

include::{generated}/api/enums/VkPartitionedAccelerationStructureOpTypeNV.adoc[]

  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_INSTANCE_NV is
    used to assign a transformed bottom level acceleration structure to an
    instance and partition.
    This is similar to slink:VkAccelerationStructureInstanceKHR that defines
    the properties and transformations for a single instance in
    non-partitioned TLAS.
    Any partition that contains at least one of the affected instances will
    have their internal acceleration structure rebuilt.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_UPDATE_INSTANCE_NV
    specifies that an instance will be updated with a new bottom level
    acceleration structure.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_OP_TYPE_WRITE_PARTITION_TRANSLATION_NV
    specifies that a partition will be assigned a
    <<ptlas-partition-translation, translation vector>>.
--


[open,refpage='VkPartitionedAccelerationStructureWriteInstanceDataNV',desc='Structure describing instance data to write in PTLAS',type='structs']
--
:refpage: VkPartitionedAccelerationStructureWriteInstanceDataNV

The slink:VkPartitionedAccelerationStructureWriteInstanceDataNV structure is
defined as:

include::{generated}/api/structs/VkPartitionedAccelerationStructureWriteInstanceDataNV.adoc[]

  * pname:transform is a slink:VkTransformMatrixKHR structure describing the
    transformation to be applied to the instance in PTLAS.
  * pname:explicitAABB specifies an axis aligned bounding box representing
    the maximum extent of any vertex within the used acceleration structure
    after applying the instance-to-world transformation.
    The <<ptlas-partition-translation, partition translation>> is not
    applied to the bounding box.
  * pname:instanceID is a user specified constant assigned to an instance in
    the PTLAS.
  * pname:instanceMask is a 8-bit mask assigned to the instance that may: be
    used to include or reject group of instances.
  * pname:instanceContributionToHitGroupIndex is a 24-bit per application
    specified instance value added in the indexing into the shader binding
    table to fetch the hit group to use.
  * pname:instanceFlags is a bitmask of
    tlink:VkPartitionedAccelerationStructureInstanceFlagsNV specifying flags
    an instance in the PTLAS.
  * pname:instanceIndex is the index of the instance within the PTLAS.
  * pname:partitionIndex is the index of the partition to which this
    instance belongs.
    <<ptlas-global-partition, Global partitions>> are referred to by
    ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV.
  * pname:accelerationStructure is the device address of the bottom level
    acceleration structure or a clustered bottom level acceleration
    structure that is being instanced.
    This instance is disabled if the device address is `0`.

.Valid Usage
****
  * [[VUID-VkPartitionedAccelerationStructureWriteInstanceDataNV-instanceMask-10566]]
    The most significant 24 bits of pname:instanceMask must: be `0`
  * [[VUID-VkPartitionedAccelerationStructureWriteInstanceDataNV-instanceContributionToHitGroupIndex-10567]]
    The most significant 8 bits of pname:instanceContributionToHitGroupIndex
    must: be `0`
  * [[VUID-VkPartitionedAccelerationStructureWriteInstanceDataNV-instanceIndex-10568]]
    pname:instanceIndex must: be less than
    slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:input.instanceCount
  * [[VUID-VkPartitionedAccelerationStructureWriteInstanceDataNV-partitionIndex-10569]]
    pname:partitionIndex must: be less than
    slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:input.partitionCount
  * [[VUID-VkPartitionedAccelerationStructureWriteInstanceDataNV-explicitAABB-10570]]
    pname:explicitAABB must: be a valid bounding box if instance was created
    with flag
    ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV
    set

****

include::{generated}/validity/structs/VkPartitionedAccelerationStructureWriteInstanceDataNV.adoc[]
--

[open,refpage='VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV',desc='Sentinel for global acceleration structure partitions',type='consts']
--
ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV is a
special constant value used for partitioned acceleration structures to
specify global partitions.

include::{generated}/api/enums/VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV.adoc[]
--

[open,refpage='VkPartitionedAccelerationStructureUpdateInstanceDataNV',desc='Structure describing instance data to update in PTLAS',type='structs']
--
:refpage: VkPartitionedAccelerationStructureUpdateInstanceDataNV

The slink:VkPartitionedAccelerationStructureUpdateInstanceDataNV structure
is defined as:

include::{generated}/api/structs/VkPartitionedAccelerationStructureUpdateInstanceDataNV.adoc[]

  * pname:instanceIndex is the index of the instance being updated.
  * pname:instanceContributionToHitGroupIndex is a 24-bit per instance value
    added in the indexing into the shader binding table to fetch the hit
    group to use.
  * pname:accelerationStructure is the device address of the bottom level
    acceleration structure or a clustered bottom level acceleration
    structure whose instance is being updated.
    The instance is disabled if the device address is `0`.

If the instance was originally disabled by specifying a `0` in
slink:VkPartitionedAccelerationStructureWriteInstanceDataNV::pname:accelerationStructure,
it can not be updated to a new acceleration structure as the instance may:
have been permanently disabled by the implementation.

To avoid a refit, the new acceleration structure must: be within the
bounding box specified by
slink:VkPartitionedAccelerationStructureWriteInstanceDataNV::pname:explicitAABB
when the instance was first created.

.Valid Usage
****
  * [[VUID-VkPartitionedAccelerationStructureUpdateInstanceDataNV-instanceContributionToHitGroupIndex-10571]]
    The most significant 8 bits of pname:instanceContributionToHitGroupIndex
    must: be `0`
  * [[VUID-VkPartitionedAccelerationStructureUpdateInstanceDataNV-None-10572]]
    The instance must: have either been created with flag
    ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV
    or did not have an acceleration structure assigned with
    slink:VkPartitionedAccelerationStructureWriteInstanceDataNV
  * [[VUID-VkPartitionedAccelerationStructureUpdateInstanceDataNV-instanceIndex-10573]]
    pname:instanceIndex must: be less than
    slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:input.instanceCount
****

include::{generated}/validity/structs/VkPartitionedAccelerationStructureUpdateInstanceDataNV.adoc[]
--

[open,refpage='VkPartitionedAccelerationStructureInstanceFlagBitsNV',desc='Bitmask specifying flags for PTLAS instances',type='enums']
--
Bits which can: be set in
slink:VkPartitionedAccelerationStructureWriteInstanceDataNV::pname:instanceFlags,
specifying flags for instances, are:

include::{generated}/api/enums/VkPartitionedAccelerationStructureInstanceFlagBitsNV.adoc[]

  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FACING_CULL_DISABLE_BIT_NV
    disables face culling for this instance.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_TRIANGLE_FLIP_FACING_BIT_NV
    specifies that the <<ray-traversal-culling-face, facing determination>>
    for geometry in this instance is inverted.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_OPAQUE_BIT_NV
    causes this instance to act as though ename:VK_GEOMETRY_OPAQUE_BIT_KHR
    were specified on all geometries referenced by this instance.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_FORCE_NO_OPAQUE_BIT_NV
    causes this instance to act as though ename:VK_GEOMETRY_OPAQUE_BIT_KHR
    were not specified on all geometries referenced by this instance.
  * ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_INSTANCE_FLAG_ENABLE_EXPLICIT_BOUNDING_BOX_NV
    enables use of an explicit bounding box for this instance.
--

[open,refpage='VkPartitionedAccelerationStructureInstanceFlagsNV',desc='Bitmask of VkPartitionedAccelerationStructureInstanceFlagBitsNV',type='flags']
--
include::{generated}/api/flags/VkPartitionedAccelerationStructureInstanceFlagsNV.adoc[]

tname:VkPartitionedAccelerationStructureInstanceFlagsNV is a bitmask type
for setting a mask of zero or more
elink:VkPartitionedAccelerationStructureInstanceFlagBitsNV.
--


[open,refpage='VkPartitionedAccelerationStructureWritePartitionTranslationDataNV',desc='Structure describing partition translation data to write in PTLAS',type='structs']
--
:refpage: VkPartitionedAccelerationStructureWritePartitionTranslationDataNV

The slink:VkPartitionedAccelerationStructureWritePartitionTranslationDataNV
structure is defined as:

include::{generated}/api/structs/VkPartitionedAccelerationStructureWritePartitionTranslationDataNV.adoc[]

  * pname:partitionIndex is the index of partition to write.
    <<ptlas-global-partition, Global partition>> is referred to by
    ename:VK_PARTITIONED_ACCELERATION_STRUCTURE_PARTITION_INDEX_GLOBAL_NV.
  * pname:partitionTranslation sets the <<ptlas-partition-translation,
    translation vector>> for this partition.
    When tracing this partition, the contained instances will behave as if
    the partition translation was added to the translation component of the
    instance transform.
    This translation vector is also added to the instances in the partition
    that had their bounding box specified.

.Valid Usage
****
  * [[VUID-VkPartitionedAccelerationStructureWritePartitionTranslationDataNV-partitionIndex-10574]]
    pname:partitionIndex must: be less than
    slink:VkBuildPartitionedAccelerationStructureInfoNV::pname:input.partitionCount
  * [[VUID-VkPartitionedAccelerationStructureWritePartitionTranslationDataNV-enablePartitionTranslation-10575]]
    The partitioned acceleration structure must: have the
    slink:VkPartitionedAccelerationStructureFlagsNV::pname:enablePartitionTranslation
    flag set
****

include::{generated}/validity/structs/VkPartitionedAccelerationStructureWritePartitionTranslationDataNV.adoc[]
--

