// Copyright 2018-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[video-encode-operations]]
== Video Encode Operations

Before the application can start recording Vulkan command buffers for the
Video Encode Operations, it must: do the following, beforehand:

  . Ensure that the implementation can encode the Video Content by querying
    the supported codec operations and profiles using
    flink:vkGetPhysicalDeviceQueueFamilyProperties2.
  . By using flink:vkGetPhysicalDeviceVideoFormatPropertiesKHR and providing
    one or more video profiles, choose the Vulkan formats supported by the
    implementation.
    The formats for <<encode-input-picture,input>> and
    <<reference-picture,reference>> pictures must: be queried and chosen
    separately.
    Refer to the section on <<video-format-capabilities,Video Format
    Capabilities>>.
  . Before creating an image to be used as a video picture resource, obtain
    the supported image creation parameters by querying with
    flink:vkGetPhysicalDeviceFormatProperties2 and
    flink:vkGetPhysicalDeviceImageFormatProperties2 using one of the
    reported formats and adding slink:VkVideoProfileListInfoKHR to the
    pname:pNext chain of slink:VkFormatProperties2.
    When querying the parameters with
    flink:vkGetPhysicalDeviceImageFormatProperties2 for images targeting
    <<encode-input-picture,input>> and <<reference-picture,reference (DPB)>>
    pictures, the slink:VkPhysicalDeviceImageFormatInfo2::pname:usage field
    should contain ename:VK_IMAGE_USAGE_VIDEO_ENCODE_SRC_BIT_KHR and
    ename:VK_IMAGE_USAGE_VIDEO_ENCODE_DPB_BIT_KHR, respectively.
  . Create none, some, or all of the required <<VkImage,images>> for the
    <<encode-input-picture,input>> and <<reference-picture,reference>>
    pictures.
    More Video Picture Resources can: be created at some later point if
    needed while processing the content to be encoded.
    Also, if the size of the picture to be encoded is expected to change,
    the images can: be created based on the maximum expected content size.
  . Create the <<video-session,video session>> to be used for video encode
    operations.
    Before creating the Encode Video Session, the encode capabilities
    should: be queried with flink:vkGetPhysicalDeviceVideoCapabilitiesKHR to
    obtain the limits of the parameters allowed by the implementation for a
    particular codec profile.
  . Bind memory resources with the encode video session by calling
    flink:vkBindVideoSessionMemoryKHR.
    The video session cannot: be used until memory resources are allocated
    and bound to it.
    In order to determine the required memory sizes and heap types of the
    device memory allocations, flink:vkGetVideoSessionMemoryRequirementsKHR
    should: be called.
  . Create one or more <<video-session-parameters,Video Session Parameter
    objects>> for use across command buffer recording operations, if
    required by the codec extension in use.
    These objects must: be created against a <<video-session,video session>>
    with the parameters required by the codec.
    Each <<video-session-parameters,Video Session Parameter object>> created
    is a child object of the associated <<video-session, Session object>>
    and cannot: be bound in the command buffer with any other
    <<video-session,Session Object>>.


The recording of Video Encode Commands against a Vulkan Command Buffer
consists of the following sequence:

  . flink:vkCmdBeginVideoCodingKHR starts the recording of one or more Video
    Encode operations in the command buffer.
    For each Video Encode Command operation, a Video Session must: be bound
    to the command buffer within this command.
    This command establishes a Vulkan Video Encode Context that consists of
    the bound Video Session Object, Session Parameters Object, and the
    required Video Picture Resources.
    The established Video Encode Context is in effect until the
    flink:vkCmdEndVideoCodingKHR command is recorded.
    If more Video Encode operations are to be required after the
    flink:vkCmdEndVideoCodingKHR command, another Video Encode Context can:
    be started with the flink:vkCmdBeginVideoCodingKHR command.
  . flink:vkCmdEncodeVideoKHR specifies one or more frames to be encoded.
    The slink:VkVideoEncodeInfoKHR parameters, and the codec extension
    structures chained to this, specify the details of the encode operation.
  . flink:vkCmdControlVideoCodingKHR records operations against the encoded
    data, encoding device, or the Video Session state.
  . flink:vkCmdEndVideoCodingKHR signals the end of the recording of the
    Vulkan Video Encode Context, as established by
    flink:vkCmdBeginVideoCodingKHR.

In addition to the above, the following commands can: be recorded between
flink:vkCmdBeginVideoCodingKHR and flink:vkCmdEndVideoCodingKHR:

  * Query operations
  * Global Memory Barriers
  * Buffer Memory Barriers
  * Image Memory Barriers (these must: be used to transition the Video
    Picture Resources to the proper
    ename:VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR and
    ename:VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR layouts).
  * Pipeline Barriers
  * Events
  * Timestamps
  * Device Groups (device mask)

The following Video Encode related commands must: be recorded *outside* the
Vulkan Video Encode Context established with the
flink:vkCmdBeginVideoCodingKHR and flink:vkCmdEndVideoCodingKHR commands:

  * Sparse Memory Binding
  * Copy Commands
  * Clear Commands


[[encode-input-picture]]
=== Encode Input Picture

The primary source of input pixels for the video encoding process is the
_Encode Input Picture_, represented by a slink:VkImageView.
It may: also be a direct target of
ifdef::VK_KHR_video_decode_queue[]
video decode,
endif::VK_KHR_video_decode_queue[]
graphics, or compute operations
ifdef::VK_KHR_surface[]
, or with <<wsi, Window System Integration>> APIs
endif::VK_KHR_surface[]
.


=== Capabilities

[open,refpage='VkVideoEncodeCapabilitiesKHR',desc='Structure specifying encode capabilities',type='structs']
--
When calling flink:vkGetPhysicalDeviceVideoCapabilitiesKHR with
pname:pVideoProfile->videoCodecOperation specified as one of the encode
operation bits, the slink:VkVideoEncodeCapabilitiesKHR structure must: be
included in the pname:pNext chain of the slink:VkVideoCapabilitiesKHR
structure to retrieve capabilities specific to video encoding.

The sname:VkVideoEncodeCapabilitiesKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeCapabilitiesKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkVideoEncodeCapabilityFlagBitsKHR
    describing supported encoding features.
  * pname:rateControlModes is a bitmask of
    elink:VkVideoEncodeRateControlModeFlagBitsKHR indicating supported rate
    control modes.
  * pname:maxRateControlLayers indicates the maximum number of rate control
    layers supported.
  * pname:maxBitrate indicates the maximum supported bitrate.
  * pname:maxQualityLevels indicates the number of discrete video encode
    quality levels supported.
    Implementations must: report at least 1.
  * pname:encodeInputPictureGranularity indicates the granularity at which
    <<encode-input-picture,encode input picture>> data is encoded.
  * pname:supportedEncodeFeedbackFlags is a bitmask of
    elink:VkVideoEncodeFeedbackFlagBitsKHR values specifying the supported
    flags for <<queries-video-encode-feedback,video encode feedback
    queries>>.

Implementations must: include support for at least
ename:VK_VIDEO_ENCODE_FEEDBACK_BITSTREAM_BUFFER_OFFSET_BIT_KHR and
ename:VK_VIDEO_ENCODE_FEEDBACK_BITSTREAM_BYTES_WRITTEN_BIT_KHR in
pname:supportedEncodeFeedbackFlags.

The input content and encode resolution (specified in
slink:VkVideoEncodeInfoKHR::pname:codedExtent) may not be aligned with the
codec-specific coding block size.
For example, the input content may be 1920x1080 and the coding block size
may be 16x16 pixel blocks.
In this example, the content is horizontally aligned with the coding block
size, but not vertically aligned with the coding block size.
Encoding of the last row of blocks may be impacted by contents of the input
image in pixel rows 1081 to 1088 (the next vertical alignment with the
coding block size).
In general, to ensure efficient encoding for the last row/column of blocks,
and/or to ensure consistent encoding results between repeated encoding of
the same input content, these extra pixel rows/columns should be filled to
known values up to the coding block size alignment before encoding
operations are performed.
Some implementations support performing auto-fill of unaligned pixels beyond
a specific alignment for the purposes of encoding, which is reported in
pname:encodeInputPictureGranularity.
For example, if an implementation reports 1x1 in
pname:encodeInputPictureGranularity, then the implementation will perform
auto-fill for any unaligned pixels beyond the encode resolution up to the
next coding block size.
For a coding block size of 16x16, if the implementation reports 16x16 in
pname:encodeInputPictureGranularity, then it is the application's
responsibility to fill any unaligned pixels, if desired.
When the application does not fill these unaligned pixels, there may: be an
impact on the encoding efficiency but there will be no effect on the
validity of the generated bitstream.
If the implementation reports 8x8 in pname:encodeInputPictureGranularity,
then for the 1920x1080 example, since the content is aligned to 8 pixels
vertically, the implementation will auto-fill pixel rows 1081 to 1088 (up to
the 16x16 coding block size in the example).
The auto-fill value(s) are implementation-specific.
The auto-fill value(s) are not written to the input image memory, but are
used as part of the encoding operation on the input image.

include::{generated}/validity/structs/VkVideoEncodeCapabilitiesKHR.adoc[]
--

[open,refpage='VkVideoEncodeCapabilityFlagsKHR',desc='Bitmask of VkVideoEncodeCapabilityFlagBitsKHR',type='flags']
--
include::{generated}/api/flags/VkVideoEncodeCapabilityFlagsKHR.adoc[]

tname:VkVideoEncodeCapabilityFlagsKHR is a bitmask type for setting a mask
of zero or more elink:VkVideoEncodeCapabilityFlagBitsKHR.
--

[open,refpage='VkVideoEncodeCapabilityFlagBitsKHR',desc='Video encode capability flags',type='enums']
--
Bits which may: be set in slink:VkVideoEncodeCapabilitiesKHR::pname:flags,
indicating the encoding tools supported, are:

include::{generated}/api/enums/VkVideoEncodeCapabilityFlagBitsKHR.adoc[]

  * ename:VK_VIDEO_ENCODE_CAPABILITY_PRECEDING_EXTERNALLY_ENCODED_BYTES_BIT_KHR
    indicates that the implementation supports the use of
    slink:VkVideoEncodeInfoKHR::pname:precedingExternallyEncodedBytes.
--


=== Video Encode Quality Levels

[open,refpage='vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR',desc='Query video encode quality level properties',type='protos']
--
To query properties for a specific video encode quality level supported by a
video encode profile, call:

include::{generated}/api/protos/vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR.adoc[]

  * pname:physicalDevice is the physical device to query the video encode
    quality level properties for.
  * pname:pQualityLevelInfo is a pointer to a
    slink:VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR structure
    specifying the video encode profile and quality level to query
    properties for.
  * pname:pQualityLevelProperties is a pointer to a
    slink:VkVideoEncodeQualityLevelPropertiesKHR structure in which the
    properties are returned.

include::{generated}/validity/protos/vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR.adoc[]
--


[open,refpage='VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR',desc='Structure describing the video encode profile and quality level to query properties for',type='structs']
--
The sname:VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR structure is
defined as:

include::{generated}/api/structs/VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pVideoProfile is a pointer to a slink:VkVideoProfileInfoKHR
    structure specifying the video profile to query the video encode quality
    level properties for.
  * pname:qualityLevel is the video encode quality level to query properties
    for.

include::{generated}/validity/structs/VkPhysicalDeviceVideoEncodeQualityLevelInfoKHR.adoc[]
--


[open,refpage='VkVideoEncodeQualityLevelPropertiesKHR',desc='Structure describing the video encode quality level properties',type='structs']
--
The sname:VkVideoEncodeQualityLevelPropertiesKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeQualityLevelPropertiesKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:preferredRateControlMode is a
    elink:VkVideoEncodeRateControlModeFlagBitsKHR value indicating the
    preferred rate control mode to use with the video encode quality level.
  * pname:preferredRateControlLayerCount indicates the preferred number of
    rate control layers to use with the quality level.

include::{generated}/validity/structs/VkVideoEncodeQualityLevelPropertiesKHR.adoc[]
--


[open,refpage='VkVideoEncodeQualityLevelInfoKHR',desc='Structure specifying used video encode quality level',type='structs']
--
The sname:VkVideoEncodeQualityLevelInfoKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeQualityLevelInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:qualityLevel is the used video encode quality level.

This structure can: be specified in the following places:

  * In the pname:pNext chain of slink:VkVideoSessionParametersCreateInfoKHR
    to specify the video encode quality level to use for a video session
    parameters object created for a video encode session.
    If no instance of this structure is included in the pname:pNext chain of
    slink:VkVideoSessionParametersCreateInfoKHR, then the video session
    parameters object is created with a video encode quality level of zero.
  * In the pname:pNext chain of slink:VkVideoCodingControlInfoKHR to change
    the video encode quality level state of the bound video session.

include::{generated}/validity/structs/VkVideoEncodeQualityLevelInfoKHR.adoc[]
--


=== Retrieving Encoded Session Parameters

Any codec-specific parameters stored in video session parameters objects
may: need to be separately encoded and included in the final video bitstream
data, depending on the used video compression standard.
In such cases the application must: call the
flink:vkGetEncodedVideoSessionParametersKHR command to retrieve the encoded
parameter data from the used video session parameters object in order to be
able to produce a compliant video bitstream.

[open,refpage='vkGetEncodedVideoSessionParametersKHR',desc='Get encoded parameter sets from a video session parameters object',type='protos']
--
Encoded parameter data can: be retrieved from a video session parameters
object created with a video encode operation using the command:

include::{generated}/api/protos/vkGetEncodedVideoSessionParametersKHR.adoc[]

  * pname:device is the logical device that owns the video session
    parameters object.
  * pname:pVideoSessionParametersInfo is a pointer to a
    slink:VkVideoEncodeSessionParametersGetInfoKHR structure specifying the
    parameters of the encoded parameter data to retrieve.
  * pname:pFeedbackInfo is either `NULL` or a pointer to a
    slink:VkVideoEncodeSessionParametersFeedbackInfoKHR structure in which
    feedback about the requested parameter data is returned.
  * pname:pDataSize is a pointer to a code:size_t value related to the
    amount of encode parameter data returned, as described below.
  * pname:pData is either `NULL` or a pointer to a buffer to write the
    encoded parameter data to.

If pname:pData is `NULL`, then the size of the encoded parameter data, in
bytes, that can: be retrieved is returned in pname:pDataSize.
Otherwise, pname:pDataSize must: point to a variable set by the application
to the size of the buffer, in bytes, pointed to by pname:pData, and on
return the variable is overwritten with the number of bytes actually written
to pname:pData.
If pname:pDataSize is less than the size of the encoded parameter data that
can: be retrieved, then no data will be written to pname:pData, zero will be
written to pname:pDataSize, and ename:VK_INCOMPLETE will be returned instead
of ename:VK_SUCCESS, to indicate that no encoded parameter data was
returned.

If pname:pFeedbackInfo is not `NULL` then the members of the
slink:VkVideoEncodeSessionParametersFeedbackInfoKHR structure and any
additional structures included in its pname:pNext chain that are applicable
to the video session parameters object specified in
pname:pVideoSessionParametersInfo::pname:videoSessionParameters will be
filled with feedback about the requested parameter data on all successful
calls to this command.

[NOTE]
.Note:
====
This includes the cases when pname:pData is `NULL` or when
ename:VK_INCOMPLETE is returned by the command, and enables the application
to determine whether the implementation overrode any of the requested video
session parameters without actually needing to retrieve the encoded
parameter data itself.
====

include::{generated}/validity/protos/vkGetEncodedVideoSessionParametersKHR.adoc[]
--

[open,refpage='VkVideoEncodeSessionParametersGetInfoKHR',desc='Structure specifying parameters for retrieving encoded video session parameter data',type='structs']
--
The sname:VkVideoEncodeSessionParametersGetInfoKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeSessionParametersGetInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:videoSessionParameters is the slink:VkVideoSessionParametersKHR
    object to retrieve encoded parameter data from.

Depending on the used video encode operation, additional codec-specific
structures may: need to be included in the pname:pNext chain of this
structure to identify the specific video session parameters to retrieve
encoded parameter data for, as described in the corresponding sections.

include::{generated}/validity/structs/VkVideoEncodeSessionParametersGetInfoKHR.adoc[]
--

[open,refpage='VkVideoEncodeSessionParametersFeedbackInfoKHR',desc='Structure providing feedback about the requested video session parameters',type='structs']
--
The sname:VkVideoEncodeSessionParametersFeedbackInfoKHR structure is defined
as:

include::{generated}/api/structs/VkVideoEncodeSessionParametersFeedbackInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:hasOverrides indicates whether any of the requested parameter data
    were overridden by the implementation.

Depending on the used video encode operation, additional codec-specific
structures may: need to be included in the pname:pNext chain of this
structure to capture feedback information about the requested parameter
data, as described in the corresponding sections.

include::{generated}/validity/structs/VkVideoEncodeSessionParametersFeedbackInfoKHR.adoc[]
--


=== Video Encode Commands

[open,refpage='vkCmdEncodeVideoKHR',desc='Encode operation for bitstream generation',type='protos']
--
To launch video encode operations, call:

include::{generated}/api/protos/vkCmdEncodeVideoKHR.adoc[]

  * pname:commandBuffer is the command buffer to be filled with this
    function for encoding to generate a bitstream.
  * pname:pEncodeInfo is a pointer to a slink:VkVideoEncodeInfoKHR
    structure.

Each call issues one or more video encode operations.
The implicit parameter pname:opCount corresponds to the number of video
encode operations issued by the command.
After calling this command, the
<<queries-operation-active-query-index,active query index>> of each
<<queries-operation-active,active>> query is incremented by pname:opCount.

Currently each call to this command results in the issue of a single video
encode operation.

.Valid Usage
****
  * [[VUID-vkCmdEncodeVideoKHR-opCount-07174]]
    For each <<queries-operation-active,active>> query, the
    <<queries-operation-active-query-index,active query index>>
    corresponding to the query type of that query plus pname:opCount must:
    be less than or equal to the
    <<queries-operation-last-activatable-query-index,last activatable query
    index>> corresponding to the query type of that query plus one
****

include::{generated}/validity/protos/vkCmdEncodeVideoKHR.adoc[]
--

[open,refpage='VkVideoEncodeInfoKHR',desc='Structure to chain codec-specific structures to',type='structs']
--
The sname:VkVideoEncodeInfoKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is a pointer to a structure extending this structure.
    A codec-specific extension structure must: be chained to specify what
    bitstream unit to generate with this encode operation.
  * pname:flags is reserved for future use.
  * pname:dstBuffer is the destination video bitstream buffer to write the
    encoded bitstream to.
  * pname:dstBufferOffset is the starting offset in bytes from the start of
    pname:dstBuffer to write the encoded bitstream to.
    pname:dstBufferOffset's value must: be aligned to
    slink:VkVideoCapabilitiesKHR::pname:minBitstreamBufferOffsetAlignment,
    as reported by the implementation.
  * pname:dstBufferRange is the maximum size in bytes of the encoded
    bitstream written to pname:dstBuffer, starting from
    pname:dstBufferOffset.
    pname:dstBufferRange's value must: be aligned to
    slink:VkVideoCapabilitiesKHR::pname:minBitstreamBufferSizeAlignment, as
    reported by the implementation.
  * pname:srcPictureResource is the Picture Resource of the
    <<encode-input-picture,Input Picture>> to be encoded by the operation.
  * pname:pSetupReferenceSlot is a pointer to a
    slink:VkVideoReferenceSlotInfoKHR structure used for generating a
    reconstructed reference slot and Picture Resource.
    pname:pSetupReferenceSlot->slotIndex specifies the slot index number to
    use as a target for producing the Reconstructed (DPB) data.
    pname:pSetupReferenceSlot must: be one of the entries provided in
    slink:VkVideoBeginCodingInfoKHR via the pname:pReferenceSlots within the
    flink:vkCmdBeginVideoCodingKHR command that established the Vulkan Video
    Encode Context for this command.
  * pname:referenceSlotCount is the number of Reconstructed Reference
    Pictures that will be used when this encoding operation is executing.
  * pname:pReferenceSlots is `NULL` or a pointer to an array of
    slink:VkVideoReferenceSlotInfoKHR structures that will be used when this
    encoding operation is executing.
    Each entry in pname:pReferenceSlots must: be one of the entries provided
    in slink:VkVideoBeginCodingInfoKHR via the pname:pReferenceSlots within
    the flink:vkCmdBeginVideoCodingKHR command that established the Vulkan
    Video Encode Context for this command.
  * pname:precedingExternallyEncodedBytes is the number of bytes externally
    encoded for insertion in the active video encode session overall
    bitstream prior to the bitstream that will be generated by the
    implementation for this instance of sname:VkVideoEncodeInfoKHR.
    The value provided is used to update the implementation's rate control
    algorithm for the rate control layer this instance of
    sname:VkVideoEncodeInfoKHR belongs to, by accounting for the bitrate
    budget consumed by these externally encoded bytes.
    See slink:VkVideoEncodeRateControlInfoKHR for additional information
    about encode rate control.

The coded size of the encode operation is specified in pname:codedExtent of
pname:srcPictureResource.

Multiple flink:vkCmdEncodeVideoKHR commands may: be recorded within a Vulkan
Video Encode Context.
The execution of each flink:vkCmdEncodeVideoKHR command will result in
generating codec-specific bitstream units.
These bitstream units are generated consecutively into the bitstream buffer
specified in pname:dstBuffer of a sname:VkVideoEncodeInfoKHR structure
within the flink:vkCmdBeginVideoCodingKHR command.
The produced bitstream is the sum of all these bitstream units, including
any padding between the bitstream units.
Any bitstream padding must: be filled with data compliant to the codec
standard so as not to cause any syntax errors during decoding of the
bitstream units with the padding included.
The range of the bitstream buffer written can: be queried via
<<queries-video-encode-feedback, video encode feedback queries>>.

.Valid Usage
****
  * [[VUID-VkVideoEncodeInfoKHR-None-07012]]
    The bound video session must: not be in <<video-session-uninitialized,
    uninitialized>> state at the time the command is executed on the device
****

include::{generated}/validity/structs/VkVideoEncodeInfoKHR.adoc[]
--

[open,refpage='VkVideoEncodeFlagsKHR',desc='Reserved for future use',type='flags']
--
include::{generated}/api/flags/VkVideoEncodeFlagsKHR.adoc[]

tlink:VkVideoEncodeFlagsKHR is a bitmask type for setting a mask, but is
currently reserved for future use.
--

[open,refpage='VkVideoEncodeRateControlInfoKHR',desc='Structure to set encode stream rate control parameters',type='structs']
--
The sname:VkVideoEncodeRateControlInfoKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeRateControlInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is reserved for future use.
  * pname:rateControlMode is a elink:VkVideoEncodeRateControlModeFlagBitsKHR
    value specifying the encode stream rate control mode.
  * pname:layerCount specifies the number of rate control layers in the
    video encode stream.
  * pname:pLayers is a pointer to an array of
    slink:VkVideoEncodeRateControlLayerInfoKHR structures specifying the
    rate control configurations of pname:layerCount rate control layers.
  * pname:virtualBufferSizeInMs is the leaky bucket model virtual buffer
    size in milliseconds, with respect to peak bitrate.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR or
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.
    For example, virtual buffer size is (pname:virtualBufferSizeInMs {times}
    pname:maxBitrate / 1000).
  * pname:initialVirtualBufferSizeInMs is the initial occupancy in
    milliseconds of the virtual buffer in the leaky bucket model.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR or
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.

Including this structure in the pname:pNext chain of
slink:VkVideoCodingControlInfoKHR and including
ename:VK_VIDEO_CODING_CONTROL_ENCODE_RATE_CONTROL_BIT_KHR in
slink:VkVideoCodingControlInfoKHR::pname:flags will define stream rate
control settings for video encoding.

Additional structures providing codec-specific rate control parameters may:
need to be included in the pname:pNext chain of
sname:VkVideoCodingControlInfoKHR depending on the codec profile the bound
video session was created with and the parameters specified in
sname:VkVideoEncodeRateControlInfoKHR (see <<video-coding-control,Video
Coding Control>>).

To ensure that the video session is properly initialized with stream-level
rate control settings, the application must: call
flink:vkCmdControlVideoCodingKHR with stream-level rate control settings at
least once in execution order before the first flink:vkCmdEncodeVideoKHR
command that is executed after video session reset.
If not provided, default implementation-specific stream rate control
settings will be used.

Stream rate control settings can: also be re-initialized during an active
video encoding session.
The re-initialization takes effect whenever the
sname:VkVideoEncodeRateControlInfoKHR structure is included in the
pname:pNext chain of the slink:VkVideoCodingControlInfoKHR structure in the
call to flink:vkCmdControlVideoCodingKHR, and only impacts
flink:vkCmdEncodeVideoKHR operations that follow in execution order.

include::{generated}/validity/structs/VkVideoEncodeRateControlInfoKHR.adoc[]
--

[open,refpage='VkVideoEncodeRateControlFlagsKHR',desc='Reserved for future use',type='flags']
--
include::{generated}/api/flags/VkVideoEncodeRateControlFlagsKHR.adoc[]

tname:VkVideoEncodeRateControlFlagsKHR is a bitmask type for setting a mask,
but currently reserved for future use.
--

[open,refpage='VkVideoEncodeRateControlModeFlagBitsKHR',desc='Video encode rate control modes',type='enums']
--
The rate control modes are defined with the following enums:

include::{generated}/api/enums/VkVideoEncodeRateControlModeFlagBitsKHR.adoc[]

  * ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_DEFAULT_KHR specifies the use of
    implementation-specific rate control.
  * ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_DISABLED_BIT_KHR specifies that
    rate control is disabled and any quality control parameters for the
    encoding are provided on a per-picture basis.
    In this mode implementations will encode pictures independently of the
    output bitrate of prior video encode operations.
ifdef::VK_EXT_video_encode_h264[]
    When using an H.264 encode profile, implementations will use the QP
    values specified in the slink:VkVideoEncodeH264RateControlInfoEXT
    structure for the encoded picture.
endif::VK_EXT_video_encode_h264[]
ifdef::VK_EXT_video_encode_h265[]
    When using an H.265 encode profile, implementations will use the QP
    values specified in the slink:VkVideoEncodeH265RateControlInfoEXT
    structure for the encoded picture.
endif::VK_EXT_video_encode_h265[]
  * ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR specifies the use of
    constant bitrate rate control mode.
  * ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR specifies the use of
    variable bitrate rate control mode.
--

[open,refpage='VkVideoEncodeRateControlModeFlagsKHR',desc='Bitmask of VkVideoEncodeRateControlModeFlagBitsKHR', type='flags']
--
include::{generated}/api/flags/VkVideoEncodeRateControlModeFlagsKHR.adoc[]

tname:VkVideoEncodeRateControlModeFlagsKHR is a bitmask type for setting a
mask of zero or more elink:VkVideoEncodeRateControlModeFlagBitsKHR.
--

[open,refpage='VkVideoEncodeRateControlLayerInfoKHR',desc='Structure to set encode per-layer rate control parameters',type='structs']
--
The sname:VkVideoEncodeRateControlLayerInfoKHR structure is defined as:

include::{generated}/api/structs/VkVideoEncodeRateControlLayerInfoKHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is a pointer to a structure extending this structure.
  * pname:averageBitrate is the average bitrate in bits/second.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR or
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.
  * pname:maxBitrate is the peak bitrate in bits/second.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.
  * pname:frameRateNumerator is the numerator of the frame rate.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR or
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.
  * pname:frameRateDenominator is the denominator of the frame rate.
    Valid when rate control mode is
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_CBR_BIT_KHR or
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_VBR_BIT_KHR.

A codec-specific structure specifying additional per-layer rate control
settings must: be chained to sname:VkVideoEncodeRateControlLayerInfoKHR.
If multiple rate control layers are enabled
(slink:VkVideoEncodeRateControlInfoKHR::pname:layerCount is greater than 1),
then the chained codec-specific extension structure also identifies the
specific video coding layer its parent
sname:VkVideoEncodeRateControlLayerInfoKHR applies to.
If multiple rate control layers are enabled, the number of rate control
layers must: match the number of video coding layers.
The specification for an encode codec-specific extension would describe how
multiple video coding layers are enabled for the corresponding codec.

Per-layer rate control settings for all enabled rate control layers must: be
initialized or re-initialized whenever stream rate control settings are
provided via slink:VkVideoEncodeRateControlInfoKHR.
This is done by specifying settings for all enabled rate control layers in
slink:VkVideoEncodeRateControlInfoKHR::pname:pLayers.

It is possible for an application to enable multiple video coding layers
(via codec-specific extensions to encoding operations) while only enabling a
single layer of rate control for the entire video stream.
To achieve this, pname:layerCount in slink:VkVideoEncodeRateControlInfoKHR
must: be set to 1, and the single sname:VkVideoEncodeRateControlLayerInfoKHR
provided in pname:pLayers would apply to all encoded segments of the video
stream, regardless of which codec-defined video coding layer they belong to.
In this case, the implementation decides bitrate distribution across video
coding layers (if applicable to the specified stream rate control mode).

include::{generated}/validity/structs/VkVideoEncodeRateControlLayerInfoKHR.adoc[]
--

