// Copyright (c) 2024 Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[anti-lag]]
=== Anti-Lag

The apiext:VK_AMD_anti_lag extension lowers latency between receiving input
and displaying on the screen.
It adds a command to indicate when input is being processed for a frame, and
when that frame's images are presented.

[open,refpage='vkAntiLagUpdateAMD',desc='Provide information to reduce latency',type='protos']
--
To lower latency, call:

ifdef::VK_AMD_anti_lag[]
include::{generated}/api/protos/vkAntiLagUpdateAMD.adoc[]
endif::VK_AMD_anti_lag[]

  * pname:device is the logical device
  * pname:pData is a pointer to a slink:VkAntiLagDataAMD structure
    containing latency reduction parameters.

This command should be executed immediately before the application processes
user input.
If pname:pData is not `NULL` and
slink:VkAntiLagDataAMD::pname:presentationInfo is not `NULL`, this command
should: be executed again before flink:vkQueuePresentKHR, with
pname:pPresentationInfo set to matching values.

.Valid Usage
****
  * [[VUID-vkAntiLagUpdateAMD-antiLag-10061]]
    The <<features-antiLag, pname:antiLag>> feature must: be enabled
****

include::{generated}/validity/protos/vkAntiLagUpdateAMD.adoc[]
--

[open,refpage='VkAntiLagDataAMD',desc='Structure specifying the parameters for vkAntiLagUpdateAMD',type='structs']
--
The sname:VkAntiLagDataAMD structure is defined as:

include::{generated}/api/structs/VkAntiLagDataAMD.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:mode is a elink:VkAntiLagModeAMD value specifying the anti-lag
    status.
  * pname:maxFPS is the framerate limit, in frames per second, used by the
    application.
    This limit will be imposed if anti-lag is enabled.
    If the application tries to render faster, the framerate will be reduced
    to match this limit.
    A value of 0 will disable the limit.
  * pname:pPresentationInfo is a pointer to a
    slink:VkAntiLagPresentationInfoAMD structure containing information
    about the application stage.

This structure specifies anti-lag parameters.

include::{generated}/validity/structs/VkAntiLagDataAMD.adoc[]
--

[open,refpage='VkAntiLagModeAMD',desc='Set the status of the anti-lag feature',type='enums']
--
Possible values of slink:VkAntiLagDataAMD::pname:mode, specifying the
anti-lag status, are:

include::{generated}/api/enums/VkAntiLagModeAMD.adoc[]

  * ename:VK_ANTI_LAG_MODE_DRIVER_CONTROL_AMD specifies that anti-lag will
    be enabled or disabled depending on driver settings.
  * ename:VK_ANTI_LAG_MODE_ON_AMD specifies that anti-lag will be enabled.
  * ename:VK_ANTI_LAG_MODE_OFF_AMD specifies that anti-lag will be disabled.
--

[open,refpage='VkAntiLagPresentationInfoAMD',desc='Structure specifying information about stage',type='structs']
--
The sname:VkAntiLagPresentationInfoAMD structure is defined as:

include::{generated}/api/structs/VkAntiLagPresentationInfoAMD.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:stage is a elink:VkAntiLagStageAMD value specifying the current
    application stage.
  * pname:frameIndex is set just before the application processes input data
    (ename:VK_ANTI_LAG_STAGE_INPUT_AMD).
    The same pname:frameIndex value should: be set before the frame with
    current input data will be presented by flink:vkQueuePresentKHR
    (ename:VK_ANTI_LAG_STAGE_PRESENT_AMD).
    This should: be done for each frame.

This structure specifies information about the presentation stage for which
anti-lag parameters are being set.

include::{generated}/validity/structs/VkAntiLagPresentationInfoAMD.adoc[]
--

[open,refpage='VkAntiLagStageAMD',desc='Report the application stage',type='enums']
--
Possible values of slink:VkAntiLagPresentationInfoAMD::pname:stage,
specifying the current application stage, are:

include::{generated}/api/enums/VkAntiLagStageAMD.adoc[]

  * ename:VK_ANTI_LAG_STAGE_INPUT_AMD specifies the stage before processing
    input.
  * ename:VK_ANTI_LAG_STAGE_PRESENT_AMD specifies the stage before
    flink:vkQueuePresentKHR.
--
