// Copyright (c) 2022-2025 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

[[memory-decompression]]
= Memory Decompression

Commands that can: be used to decompress memory between one or more memory
regions are flink:vkCmdDecompressMemoryEXT,
ifdef::VK_NV_memory_decompression[]
flink:vkCmdDecompressMemoryNV, flink:vkCmdDecompressMemoryIndirectCountNV,
endif::VK_NV_memory_decompression[]
and flink:vkCmdDecompressMemoryIndirectCountEXT.

[open,refpage='vkCmdDecompressMemoryEXT',desc='Decompress data between memory regions',type='protos']
--

To decompress memory containing compressed data, call:

include::{generated}/api/protos/vkCmdDecompressMemoryEXT.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:pDecompressMemoryInfoEXT is a pointer to a
    slink:VkDecompressMemoryInfoEXT structure describing the decompression
    parameters.

.Valid Usage
****
  * [[VUID-vkCmdDecompressMemoryEXT-memoryDecompression-11761]]
    The <<features-memoryDecompression, pname:memoryDecompression>> feature
    must: be enabled
****
include::{generated}/validity/protos/vkCmdDecompressMemoryEXT.adoc[]

--

[open,refpage='VkDecompressMemoryInfoEXT',desc='Structure specifying decompression memory info',type='structs']
--
:refpage: VkDecompressMemoryInfoEXT

The sname:VkDecompressMemoryInfoEXT structure is defined as:

include::{generated}/api/structs/VkDecompressMemoryInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:decompressionMethod is a bitmask of
    elink:VkMemoryDecompressionMethodFlagBitsEXT with a single bit set
    specifying the method used to decompress data.
  * pname:regionCount is the number of regions to decompress.
  * pname:pRegions is a pointer to an array of
    slink:VkDecompressMemoryRegionEXT structures specifying the regions to
    decompress.

Each memory region specified in pname:pRegions is decompressed from the
source to the destination address based on the decompression method
specified in pname:decompressionMethod.
If any of the specified source and destination regions overlap in memory,
then the results of decompression are undefined:.

.Valid Usage
****
include::{chapters}/commonvalidity/decompression_method_common.adoc[]
  * [[VUID-VkDecompressMemoryInfoEXT-decompressionMethod-11762]]
    If pname:decompressionMethod is
    ename:VK_MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_EXT, then for each
    element of pname:pRegions, pname:decompressedSize must: be less than or
    equal to 65536 bytes
  * [[VUID-VkDecompressMemoryInfoEXT-decompressionMethod-11763]]
    pname:decompressionMethod must: be a valid bit specified in
    sname:VkPhysicalDeviceMemoryDecompressionPropertiesEXT::pname:decompressionMethods
****

include::{generated}/validity/structs/VkDecompressMemoryInfoEXT.adoc[]
--

[open,refpage='VkDecompressMemoryRegionEXT',desc='Structure specifying decompression region',type='structs']
--
:refpage: VkDecompressMemoryRegionEXT

The sname:VkDecompressMemoryRegionEXT structure is defined as:

include::{generated}/api/structs/VkDecompressMemoryRegionEXT.adoc[]

  * pname:srcAddress is the address where compressed data is stored.
  * pname:dstAddress is the destination address where decompressed data will
    be written.
  * pname:compressedSize is the size of compressed data in bytes.
  * pname:decompressedSize is the size of decompressed data in bytes.

Accesses to compressed and decompressed data specified in pname:srcAddress
and pname:dstAddress must: be <<synchronization-dependencies,synchronized>>
with the ename:VK_PIPELINE_STAGE_2_MEMORY_DECOMPRESSION_BIT_EXT
<<synchronization-pipeline-stages, pipeline stage>> with
<<synchronization-access-types, access type>> of
ename:VK_ACCESS_2_MEMORY_DECOMPRESSION_READ_BIT_EXT or
ename:VK_ACCESS_2_MEMORY_DECOMPRESSION_WRITE_BIT_EXT.

.Valid Usage
****
include::{chapters}/commonvalidity/decompress_memory_region_common.adoc[]
  * [[VUID-VkDecompressMemoryRegionEXT-srcAddress-11764]]
    The underlying buffer for pname:srcAddress must: have the
    ename:VK_BUFFER_USAGE_2_MEMORY_DECOMPRESSION_BIT_EXT bit set in its
    usage flag
  * [[VUID-VkDecompressMemoryRegionEXT-dstAddress-11765]]
    The underlying buffer for pname:dstAddress must: have the
    ename:VK_BUFFER_USAGE_2_MEMORY_DECOMPRESSION_BIT_EXT bit set in its
    usage flag
****

include::{generated}/validity/structs/VkDecompressMemoryRegionEXT.adoc[]
--

ifdef::VK_NV_memory_decompression[]

To decompress memory containing compressed data, call:

include::{generated}/api/protos/vkCmdDecompressMemoryNV.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:decompressRegionCount is the number of memory regions to
    decompress.
  * pname:pDecompressMemoryRegions is a pointer to an array of
    pname:decompressRegionCount slink:VkDecompressMemoryRegionNV structures
    specifying decompression parameters.

Each region specified in pname:pDecompressMemoryRegions is decompressed from
the compressed to decompressed region based on the decompression method
specified in slink:VkDecompressMemoryRegionNV::pname:decompressionMethod.
If the regions containing compressed and decompressed data overlap, the
decompression behavior is undefined:.

.Valid Usage
****
  * [[VUID-vkCmdDecompressMemoryNV-None-07684]]
    The <<features-memoryDecompression, pname:memoryDecompression>> feature
    must: be enabled
****

include::{generated}/validity/protos/vkCmdDecompressMemoryNV.adoc[]

[open,refpage='VkDecompressMemoryRegionNV',desc='Structure specifying decompression region parameters',type='structs']
--
:refpage: VkDecompressMemoryRegionNV

The sname:VkDecompressMemoryRegionNV structure is defined as:

include::{generated}/api/structs/VkDecompressMemoryRegionNV.adoc[]

  * pname:srcAddress is the address where compressed data is stored.
  * pname:dstAddress is the destination address where decompressed data will
    be written.
  * pname:compressedSize is the size of compressed data in bytes.
  * pname:decompressedSize is the size of decompressed data in bytes.
  * pname:decompressionMethod is a bitmask of
    elink:VkMemoryDecompressionMethodFlagBitsNV with a single bit set
    specifying the method used to decompress data.

.Valid Usage
****
include::{chapters}/commonvalidity/decompression_method_common.adoc[]
include::{chapters}/commonvalidity/decompress_memory_region_common.adoc[]
  * [[VUID-{refpage}-decompressionMethod-09395]]
    If pname:decompressionMethod is
    ename:VK_MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_EXT, then
    pname:decompressedSize must: be less than or equal to 65536 bytes
  * [[VUID-vkCmdDecompressMemoryNV-memoryDecompression-11766]]
    The <<features-memoryDecompression, pname:memoryDecompression>> feature
    must: be enabled
****
--

endif::VK_NV_memory_decompression[]

[open,refpage='vkCmdDecompressMemoryIndirectCountEXT',desc='Indirect decompress data between memory regions',type='protos']
--
:refpage: vkCmdDecompressMemoryIndirectCountEXT

To decompress data between one or more memory regions by specifying
decompression parameters indirectly in a buffer, call:

include::{generated}/api/protos/vkCmdDecompressMemoryIndirectCountEXT.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:decompressionMethod is a bitmask of
    elink:VkMemoryDecompressionMethodFlagBitsEXT with a single bit set
    specifying the method used to decompress data.
  * pname:indirectCommandsAddress is the device address containing
    decompression parameters laid out as an array of
    slink:VkDecompressMemoryRegionEXT structures.
  * pname:indirectCommandsCountAddress is the device address containing a
    32-bit integer value specifying the decompression count.
  * pname:maxDecompressionCount is maximum number of decompressions that
    will be executed.
    The actual number of executed decompressions is the minimum of the count
    specified in pname:indirectCommandsCountAddress and
    pname:maxDecompressionCount.
  * pname:stride is the byte stride between successive sets of decompression
    parameters located starting from pname:indirectCommandsAddress.

Each region specified in pname:indirectCommandsAddress is decompressed from
the source to destination region based on the specified
pname:decompressionMethod.

.Valid Usage
****
include::{chapters}/commonvalidity/decompress_memory_indirect_common.adoc[]
include::{chapters}/commonvalidity/decompression_method_common.adoc[]
  * [[VUID-vkCmdDecompressMemoryIndirectCountEXT-stride-11767]]
    pname:stride must: be a multiple of `4` and must: be greater than or
    equal to sizeof(slink:VkDecompressMemoryRegionEXT)
  * [[VUID-vkCmdDecompressMemoryIndirectCountEXT-maxDecompressionCount-11768]]
    pname:maxDecompressionCount must: be less than or equal to
    sname:VkPhysicalDeviceMemoryDecompressionPropertiesEXT::pname:maxDecompressionIndirectCount
  * [[VUID-vkCmdDecompressMemoryIndirectCountEXT-decompressionMethod-11769]]
    If pname:decompressionMethod is
    ename:VK_MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_EXT, then all
    values in slink:VkDecompressMemoryRegionEXT::pname:decompressedSize
    must: be less than or equal to 65536 bytes
****

include::{generated}/validity/protos/vkCmdDecompressMemoryIndirectCountEXT.adoc[]
--

ifdef::VK_NV_memory_decompression[]

[open,refpage='vkCmdDecompressMemoryIndirectCountNV',desc='Indirect decompress data between memory regions',type='protos']
--
:refpage: vkCmdDecompressMemoryIndirectCountNV

To decompress data between one or more memory regions by specifying
decompression parameters indirectly in a buffer, call:

include::{generated}/api/protos/vkCmdDecompressMemoryIndirectCountNV.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:indirectCommandsAddress is the device address containing
    decompression parameters laid out as an array of
    slink:VkDecompressMemoryRegionNV structures.
  * pname:indirectCommandsCountAddress is the device address containing a
    32-bit integer value specifying the decompression count.
  * pname:stride is the byte stride between successive sets of decompression
    parameters located starting from pname:indirectCommandsAddress.

Each region specified in pname:indirectCommandsAddress is decompressed from
the source to destination region based on the specified
pname:decompressionMethod.

.Valid Usage
****
include::{chapters}/commonvalidity/decompress_memory_indirect_common.adoc[]
  * [[VUID-vkCmdDecompressMemoryIndirectCountNV-stride-11770]]
    pname:stride must: be a multiple of `4` and must: be greater than or
    equal to sizeof(slink:VkDecompressMemoryRegionNV)
****
--
endif::VK_NV_memory_decompression[]

[open,refpage='VkMemoryDecompressionMethodFlagBitsEXT',desc='List the supported memory decompression methods',type='enums']
--

Bits which can: be set in
sname:VkDecompressMemoryRegionEXT::pname:decompressionMethod
ifdef::VK_NV_memory_decompression[]
or sname:VkDecompressMemoryRegionNV::pname:decompressionMethod
endif::VK_NV_memory_decompression[]
specifying the decompression method to select, or returned in
sname:VkPhysicalDeviceMemoryDecompressionPropertiesEXT::pname:decompressionMethods
specifying the available decompression methods are:

include::{generated}/api/enums/VkMemoryDecompressionMethodFlagBitsEXT.adoc[]

ifdef::VK_NV_memory_decompression[]
or the equivalent

include::{generated}/api/enums/VkMemoryDecompressionMethodFlagBitsNV.adoc[]
endif::VK_NV_memory_decompression[]

  * ename:VK_MEMORY_DECOMPRESSION_METHOD_GDEFLATE_1_0_BIT_EXT specifies that
    the GDeflate 1.0 algorithm is used to decompress data.
--

[open,refpage='VkMemoryDecompressionMethodFlagsEXT',desc='Bitmask of VkMemoryDecompressionMethodFlagBitsEXT',type='flags']
--

include::{generated}/api/flags/VkMemoryDecompressionMethodFlagsEXT.adoc[]

ifdef::VK_NV_memory_decompression[]
or the equivalent

include::{generated}/api/flags/VkMemoryDecompressionMethodFlagsNV.adoc[]
endif::VK_NV_memory_decompression[]

tname:VkMemoryDecompressionMethodFlagsEXT is a bitmask type for specifying a
mask of one or more elink:VkMemoryDecompressionMethodFlagBitsEXT.
--
