// Copyright (c) 2014-2025 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentTimingsInfoEXT',desc='Array of VkPresentTimingInfoEXT to chain with VkPresentInfoKHR',type='structs']
--

When the <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>> or
<<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature is
enabled, an application can: instruct the presentation engine that an image
must: not be displayed earlier than a specified time, or for a minimum
duration, by including the sname:VkPresentTimingsInfoEXT structure in the
pname:pNext chain of the slink:VkPresentInfoKHR structure.

The sname:VkPresentTimingsInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimingsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:swapchainCount is the number of swapchains being presented to by
    this command.
  * pname:pTimingInfos is `NULL` or a pointer to an array of
    sname:VkPresentTimingInfoEXT elements with pname:swapchainCount entries.
    If not `NULL`, each element of pname:pTimingInfos contains timing
    information for the presentation of the image corresponding to the entry
    in the sname:VkPresentInfoKHR::pname:pImageIndices array.

.Valid Usage
****
  * pname:swapchainCount must: be equal to
    slink:VkPresentInfoKHR::pname:swapchainCount.
  * All swapchains in slink:VkPresentInfoKHR::pname:pSwapchains must: have
    been created with the slink:VkSwapchainCreateInfoKHR::pname:flags field
    containing ename:VK_SWAPCHAIN_CREATE_PRESENT_TIMING_BIT_EXT
  * For each member of sname:VkPresentInfoKHR::pname:pSwapchains, if the
    associated slink:VkPresentTimingInfoEXT::pname:targetTime is not zero,
    the swapchain's current present mode must: be
ifdef::VK_KHR_present_mode_fifo_latest_ready[]
    ename:VK_PRESENT_MODE_FIFO_LATEST_READY_KHR,
endif::VK_KHR_present_mode_fifo_latest_ready[]
    ename:VK_PRESENT_MODE_FIFO_KHR or
    ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
****

include::{generated}/validity/structs/VkPresentTimingsInfoEXT.adoc[]
--

[open,refpage='VkPresentTimingInfoEXT',desc='Specifies per-present timing information',type='structs']
--
The sname:VkPresentTimingInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimingInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkPresentTimingInfoFlagBitsEXT
    specifying options for how to interpret the timing information.
  * pname:targetTime is zero or a value specifying the target present
    time in nanoseconds of the presentation request.
  * pname:timeDomainId is the id of the time domain used to specify the
    absolute target present time and the timing results obtained in a
    subsequent flink:vkGetPastPresentationTimingEXT call for the current
    presentation request.
  * pname:presentStageQueries is a valid tlink:VkPresentStageFlagsEXT value
    indicating which present stages the presentation engine will collect
    timing information for.

If pname:targetTime is not zero, the implementation attempts to align the
ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT present stage of
that presentation request with the time specified in pname:targetTime
according to the time domain used. If
ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_NEAREST_REFRESH_CYCLE_BIT_EXT is not
set in pname:flags, it indicates that the application would strictly prefer
the image to not be visible before pname:targetTime has lapsed.

[NOTE]
====
Some platforms, due to hardware or system limitations, may: not be able to
accurately time pname:targetTime with the actual physical event of the image
becoming visible on the display. However, those timing capabilities may:
still be useful and result in improved animation quality.

As such, the <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>>
and <<features-presentAtRelativeTime, pname:presentAtRelativeTime>> features
do not provide a strict guarantee regarding the completion of the
ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT present stage
relative to the pname:targetTime, and implementations must: strive to make
it as consistent and accurate as possible.
====

[NOTE]
====
Applications that specify an absolute present time should: regularly rebase
their calculations for their next target time on the feedback from
flink:vkGetPastPresentationTimingEXT to compensate for accumulated precision
errors or potential clock drift. It is recommended that when targeting the
time of a vertical blanking period, applications set
ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_NEAREST_REFRESH_CYCLE_BIT_EXT
to allow the implementation to compensate for small precision errors that may
cause an image to be displayed one refresh cycle later than intended.
====

.Valid Usage
****
  * If pname:targetTime is not zero and pname:flags does not contain
    ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_RELATIVE_TIME_BIT_EXT, the
    <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>> feature
    must: be enabled.
  * If pname:targetTime is not zero and pname:flags contains
    ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_RELATIVE_TIME_BIT_EXT, the
    <<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature
    must: be enabled.
****

include::{generated}/validity/structs/VkPresentTimingInfoEXT.adoc[]
--

[open,refpage='VkPresentTimingInfoFlagBitsEXT',desc='Bitmask specifying present timing info flags',type='enums']
--
Bits which can: be set in slink:VkPresentTimingInfoEXT::pname:flags, specifying options
for how to interpret timing information:

include::{generated}/api/enums/VkPresentTimingInfoFlagBitsEXT.adoc[]

  * ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_RELATIVE_TIME_BIT_EXT specifies
    that sname:VkPresentTimingInfoEXT::pname:targetTime is to be interpreted
    as a relative time from the previous presentation's
    ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT stage. If the
    pname:swapchain has never been used to present an image, the provided
    pname:targetTime is ignored.
  * ename:VK_PRESENT_TIMING_INFO_PRESENT_AT_NEAREST_REFRESH_CYCLE_BIT_EXT
    specifies that the application would prefer the image to be presented
    earlier than the time specified in
    sname:VkPresentTimingInfoEXT::pname:targetTime if that time falls within
    the first half of a refresh cycle. In that case, the presentation engine
    may: choose to display the image at the start of that refresh cycle.
--

[open,refpage='VkPresentTimingInfoFlagsEXT',desc='Bitmask of VkPresentTimingInfoFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkPresentTimingInfoFlagsEXT.adoc[]

tname:VkPresentTimingInfoFlagsEXT is a bitmask type for setting a mask
of zero or more elink:VkPresentTimingInfoFlagBitsEXT.
--

[open,refpage='VkPresentStageFlagBitsEXT',desc='Bitmask specifying stages of the image presentation process',type='enums']
--

Presenting an image to the user typically involves multiple stages. Bits
which can: be set to specify present stages are:

include::{generated}/api/enums/VkPresentStageFlagBitsEXT.adoc[]

  * ename:VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT marks the end of the
    set of queue operations enqueued by flink:vkQueuePresentKHR on the provided
    sname:VkQueue for a presentation request.
  * ename:VK_PRESENT_STAGE_REQUEST_DEQUEUED_BIT_EXT is the stage after which
    the presentation request has been dequeued from the swapchain's internal
    presentation request queue, if any, as specified by the present mode
    associated with that request.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT is the stage after
    which data for the first pixel of the presentation request associated with
    the image has left the presentation engine for a display hardware.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT is the stage
    after which a display hardware has made the first pixel visible for the
    presentation request associated with the image to be presented.

[NOTE]
====
The set of queue operations delimited by
ename:VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT includes the wait for
the semaphores specified in slink:VkPresentInfoKHR::pname:pWaitSemaphores,
if any, and any work implicitly enqueued by the implementation.
====
--

[open,refpage='VkPresentStageFlagsEXT',desc='Bitmask of VkPresentStageFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkPresentStageFlagsEXT.adoc[]

tname:VkPresentStageFlagsEXT is a bitmask type for setting a mask of zero or
more elink:VkPresentStageFlagBitsEXT.
--
