// Copyright (c) 2014-2023 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentTimingsInfoEXT',desc='Array of VkPresentTimingInfoEXT to chain with VkPresentInfoKHR',type='structs']
--

When the <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>> or
<<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature is
enabled, an application can: instruct the presentation engine that an image
must: not be displayed earlier than a specified time, or for a minimum
duration, by including the sname:VkPresentTimingsInfoEXT structure in the
pname:pNext chain of the slink:VkPresentInfoKHR structure.

The sname:VkPresentTimingsInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimingsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:swapchainCount is the number of swapchains being presented to by
    this command.
  * pname:pTimingInfos is `NULL` or a pointer to an array of
    sname:VkPresentTimingInfoEXT elements with pname:swapchainCount entries.
    If not `NULL`, each element of pname:pTimingInfos contains timing
    information for the presentation of the image corresponding to the entry
    in the sname:VkPresentInfoKHR::pname:pImageIndices array.

The semantics of target presentation time or duration vary depending on the presentation mode:

  * ename:VK_PRESENT_MODE_FIFO_KHR.
    Tearing cannot: be observed.
    The first queued image is dequeued and presented if
    both: 1) its associated wait semaphore(s) have signaled, and 2)
    its target present time is less-than or equal-to the current time.
  * ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
    For images that are presented in time to be displayed at the next
    vertical blanking period, the semantics are identical as for
    ename:VK_PRESENT_MODE_FIFO_KHR.
    For images that are presented late, and are displayed after the start of
    the vertical blanking period (i.e. with tearing), the values of
    sname:VkPastPresentationTimingEXT may: be treated as if the image was
    displayed at the start of the vertical blanking period, or may: be
    treated the same as for ename:VK_PRESENT_MODE_IMMEDIATE_KHR.

Other presentation modes do not support a target presentation time or duration.

.Valid Usage
****
  * pname:swapchainCount must: be the same value as
    sname:VkPresentInfoKHR::pname:swapchainCount, where
    sname:VkPresentInfoKHR is in the pname:pNext chain of this
    sname:VkPresentTimingsInfoEXT structure.
  * For each member of sname:VkPresentInfoKHR::pname:pSwapchains, if the
    associated sname:VkPresentTimeEXT is non-zero, the current present mode
    must: be ename:VK_PRESENT_MODE_FIFO_KHR or
    ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
****

include::{generated}/validity/structs/VkPresentTimingsInfoEXT.adoc[]
--


[open,refpage='VkPresentTimingInfoEXT',desc='Specifies per-present timing information',type='structs']
--
The sname:VkPresentTimingInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimingInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:time is a sname:VkPresentTimeEXT specifying the target present
    time or duration of the presentation request.
  * pname:timeDomainId is the id of the time domain used to specify the
    absolute target present time and the timing results obtained in a
    subsequent flink:vkGetPastPresentationTimingEXT call for the current
    presentation request.
  * pname:presentStageQueries is a valid tlink:VkPresentStageFlagsEXT value
    indicating which present stages the presentation engine should collect
    timing information for.
  * pname:targetPresentStage is zero or a tlink:VkPresentStageFlagsEXT value
    specifying which present stage pname:time is targeting.
  * pname:presentAtRelativeTime specifies whether pname:time is to be
    interpreted as an absolute or a relative time value.
  * pname:presentAtNearestRefreshCycle is a flag indicating that the
    application would like the presentation engine to complete
    pname:targetPresentStage at the start of the refresh cycle that is
    closest to pname:time.

If pname:targetPresentStage is not zero, the presentation engine must: not
complete the target present stage before the absolute time specified in
pname:time according to the time domain used, unless
pname:presentAtNearestRefreshCycle is ename:VK_TRUE and pname:time falls
within the first half of a refresh cycle.

[NOTE]
.Note
====
Applications that use pname:targetPresentTime to specify an absolute present
time should: regularly rebase their calculations for their next target time
on the feedback from flink:vkGetPastPresentationTimingEXT to compensate for
accumulated precision errors or potential clock drift. It is recommended
that when targeting the time of a vertical blanking period, applications use
pname:presentAtNearestRefreshCycle to allow the implementation to compensate
for small precision errors that may cause an image to be displayed one
refresh cycle later than intended.
====

.Valid Usage
****
  * If pname:presentStageTarget is not zero, it must: specify one and only
    one stage.
  * pname:presentStageTarget must: not be
    ename:VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT
  * If pname:targetPresentStage is not zero, pname:presentAtRelativeTime must:
    be ename:VK_FALSE.
  * If pname:presentAtRelativeTime is ename:VK_TRUE, the
    <<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature
    must: be enabled.
****

include::{generated}/validity/structs/VkPresentTimingInfoEXT.adoc[]
--


[open,refpage='VkPresentTimeEXT',desc='Specifying when an image should be presented',type='structs']
--

The sname:VkPresentTimeEXT union is defined as:

include::{generated}/api/structs/VkPresentTimeEXT.adoc[]

  * pname:targetPresentTime, if non-zero, specifies the earliest time in
    nanoseconds the application wants the presentation engine to complete a
    specified target present stage. A value of zero specifies that the
    presentation engine may: display the image at any time allowed by the
    current present mode.
  * pname:presentDuration specifies the minimum duration in nanoseconds that
    must: separate the ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT
    present stages of the current and the next presentation requests, if any.

include::{generated}/validity/structs/VkPresentTimeEXT.adoc[]
--

[open,refpage='VkPresentStageFlagBitsEXT',desc='Bitmask specifying stages of the image presentation process',type='enums']
--

Presenting an image to the user typically involves multiple stages. Bits
which can: be set to specify present stages are:

include::{generated}/api/enums/VkPresentStageFlagBitsEXT.adoc[]

  * ename:VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT marks the end of the
    set of queue operations enqueued by flink:vkQueuePresentKHR on the provided
    sname:VkQueue for a presentation request.
  * ename:VK_PRESENT_STAGE_IMAGE_LATCHED_BIT_EXT is the stage after which the
    image associated with the presentation request has been latched by the
    presentation engine to create the presentation of a future refresh cycle.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT is the stage after
    which data for the first pixel of the presentation request associated with
    the image has left the presentation engine for a display hardware.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT is the stage
    after which a display hardware has made the first pixel visible for the
    presentation request associated with the image to be presented.

[NOTE]
.Note
====
The set of queue operations delimited by
ename:VK_PRESENT_STAGE_QUEUE_OPERATIONS_END_BIT_EXT includes the wait for
the semaphores specified in slink:VkPresentInfoKHR::pname:pWaitSemaphores,
if any, and any work implicitly enqueued by the implementation.
====
--

[open,refpage='VkPresentStageFlagsEXT',desc='Bitmask of VkPresentStageFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkPresentStageFlagsEXT.adoc[]

tname:VkPresentStageFlagsEXT is a bitmask type for setting a mask of zero or
more elink:VkPresentStageFlagBitsEXT.
--
