// Copyright (c) 2014-2023 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentTimesInfoEXT',desc='The earliest time each image should be presented',type='structs']
--

When the <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>> or
<<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature is
enabled, additional fields can: be specified that allow an application to
specify the earliest time that an image should: be displayed.
This allows an application to avoid stutter that is caused by an image being
displayed earlier than planned.
Such stuttering might occur with both fixed and variable-refresh-rate
displays, because stuttering occurs when the geometry is not correctly
positioned for when the image is displayed.
An application can: instruct the presentation engine that an image must:
not be displayed earlier than a specified time by including the
sname:VkPresentTimesInfoEXT structure in the pname:pNext chain of the
sname:VkPresentInfoKHR structure.

The sname:VkPresentTimesInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimesInfoEXT.adoc[]

  * pname:sType is the type of this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:swapchainCount is the number of swapchains being presented to by
    this command.
  * pname:pTimes is `NULL` or a pointer to an array of
    sname:VkPresentTimeEXT elements with pname:swapchainCount entries.
    If not `NULL`, each element of pname:pTimes contains the earliest present
    time or the minimum present duration for the image corresponding to the
    entry in the sname:VkPresentInfoKHR::pname:pImageIndices array.

The semantics of a specified target present time or duration only apply to
the following present modes:

  * ename:VK_PRESENT_MODE_FIFO_KHR.
    Tearing cannot be observed.
    The first queued image is dequeued and presented if
    both: 1) its associated wait semaphore(s) have signaled, and 2)
    its target present time is less-than or equal-to the current time.
  * ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
    For images that are presented in time to be displayed at the next
    vertical blanking period, the semantics are identical as for
    ename:VK_PRESENT_MODE_FIFO_KHR.
    For images that are presented late, and are displayed after the start of
    the vertical blanking period (i.e. with tearing), the values of
    sname:VkPastPresentationTimingEXT may: be treated as if the image was
    displayed at the start of the vertical blanking period, or may: be
    treated the same as for ename:VK_PRESENT_MODE_IMMEDIATE_KHR.

.Valid Usage
****
  * pname:swapchainCount must: be the same value as
    sname:VkPresentInfoKHR::pname:swapchainCount, where
    sname:VkPresentInfoKHR is in the pname:pNext chain of this
    sname:VkPresentTimesInfoEXT structure.
  * For each member of sname:VkPresentInfoKHR::pname:pSwapchains, if the
    associated sname:VkPresentTimeEXT is non-zero, the present mode must:
    be ename:VK_PRESENT_MODE_FIFO_KHR or
    ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
  * For each member of sname:VkPresentInfoKHR::pname:pSwapchains, if the
    associated sname:VkPresentTimeEXT is non-zero, the swapchain must: have
    been created with a non-zero
    sname:VkSwapchainPresentTimingCreateInfoEXT::pname:presentStageTarget
****

include::{generated}/validity/structs/VkPresentTimesInfoEXT.adoc[]
--

[open,refpage='VkPresentTimeEXT',desc='Specifying when an image should be presented',type='structs']
--

The sname:VkPresentTimeEXT union is defined as:

include::{generated}/api/structs/VkPresentTimeEXT.adoc[]

  * pname:targetPresentTime, if non-zero, specifies the earliest time the
    application wants the image to complete the swapchain's target present
    stage. A value of zero specifies that the presentation engine may:
    display the image at any time allowed by the current present mode.
  * pname:minPresentDuration, if non-zero, specifies the minimum duration in
    nanoseconds before which the next image presentation request can: reach
    the target present stage. A value of zero specifies that the
    presentation engine may: display the image for any duration allowed by
    the current present mode.

The contents of the sname:VkPresentTimeEXT union is interpreted depending on
the associated sname:VkPresentInfoKHR::pname:pSwapchains member creation
values. If
sname:VkSwapchainPresentTimingCreateInfoEXT::pname:presentAtRelativeTime was
ename:VK_FALSE when creating the pname:swapchain, pname:targetPresentTime is
used. Otherwise, pname:minPresentDuration is used.

pname:targetPresentTime is a time in nanoseconds, according to the
time-domain being used. The presentation engine must: not complete the
target present stage, specified in the associated swapchain
slink:VkSwapchainPresentTimingCreateInfoEXT::pname:presentStageTarget, at an
earlier time.

[NOTE]
.Note
====
Applications that use pname:targetPresentTime to specify an absolute present
time should: regularly rebase their calculations for their next target time
on the feedback from flink:vkGetPastPresentationTimingEXT to compensate for
accumulated precision errors or potential clock drift. It is recommended
that when targeting the time of a vertical blanking period, applications
subtract a small delta from pname:targetPresentTime as a margin for error.
====

include::{generated}/validity/structs/VkPresentTimeEXT.adoc[]
--

[open,refpage='VkPresentStageTimeEXT',desc='Associate a present stage with a timestamp',type='structs']
--
The sname:VkPresentStageTimeEXT structure is defined as:

include::{generated}/api/structs/VkPresentStageTimeEXT.adoc[]

  * pname:stage is a tlink:VkPresentStageFlagsEXT value specifying a present stage.
  * pname:time is a time in nanoseconds associated with the pname:stage.

include::{generated}/validity/structs/VkPresentStageTimeEXT.adoc[]
--

[open,refpage='VkPresentStageFlagBitsEXT',desc='Bitmask specifying stages of the image presentation process',type='enums']
--

Presenting an image to the user typically involves multiple stages. Bits
which can: be set to specify present stages are:

include::{generated}/api/enums/VkPresentStageFlagBitsEXT.adoc[]

  * ename:VK_PRESENT_STAGE_IMAGE_HANDOFF_BIT_EXT is the stage after which
    the presentation request of the image has been passed to a
    system-specific entity of the presentation engine that is outside the
    control of the Vulkan implementation. This stage is the only
    ename:VkPresentStageFlagBitsEXT that is required: to be supported.
  * ename:VK_PRESENT_STAGE_IMAGE_LATCHED_BIT_EXT is the stage after which the
    image associated with the presentation request has been latched by the
    presentation engine to create the presentation of a future refresh cycle.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_OUT_BIT_EXT is the stage after
    which data for the first pixel of the presentation request associated with
    the image has left the presentation engine for a display hardware.
  * ename:VK_PRESENT_STAGE_IMAGE_FIRST_PIXEL_VISIBLE_BIT_EXT is the stage
    after which a display hardware has made the first pixel visible for the
    presentation request associated with the image to be presented.

--

[open,refpage='VkPresentStageFlagsEXT',desc='Bitmask of VkPresentStageFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkPresentStageFlagsEXT.adoc[]

tname:VkPresentStageFlagsEXT is a bitmask type for setting a mask of zero or
more elink:VkPresentStageFlagBitsEXT.
--
