// Copyright (c) 2014-2022 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentTimesInfoEXT',desc='The earliest time each image should be presented',type='structs']
--

When the `<<VK_EXT_present_timing>>` extension is enabled, additional
fields can: be specified that allow an application to specify the earliest
time that an image should be displayed.
This allows an application to avoid stutter that is caused by an image being
displayed earlier than planned.
Such stuttering can occur with both fixed and variable-refresh-rate
displays, because stuttering occurs when the geometry is not correctly
positioned for when the image is displayed.
An application can: instruct the presentation engine that an image should
not be displayed earlier than a specified time by including the
sname:VkPresentTimesInfoEXT structure in the pname:pNext chain of the
sname:VkPresentInfoKHR structure.

The sname:VkPresentTimesInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimesInfoEXT.adoc[]

  * pname:sType is the type of this structure.
  * pname:pNext is `NULL` or a pointer to an extension-specific structure.
  * pname:swapchainCount is the number of swapchains being presented to by
    this command.
  * pname:pTimes is `NULL` or a pointer to an array of
    sname:VkPresentTimeEXT elements with pname:swapchainCount entries.
    If not `NULL`, each element of pname:pTimes contains the earliest time
    to present the image corresponding to the entry in the
    sname:VkPresentInfoKHR::pname:pImageIndices array.

.Valid Usage
****
  * pname:swapchainCount must: be the same value as
    sname:VkPresentInfoKHR::pname:swapchainCount, where
    sname:VkPresentInfoKHR is in the pname:pNext chain of this
    sname:VkPresentTimesInfoEXT structure.
****

include::{generated}/validity/structs/VkPresentTimesInfoEXT.adoc[]
--

[open,refpage='VkPresentTimeEXT',desc='Specifying when an image should be presented',type='structs']
--

The sname:VkPresentTimeEXT union contains either a
slink:VkAbsolutePresentTimeEXT or a slink:VkRelativePresentTimeEXT
structure, defined as:

include::{generated}/api/structs/VkPresentTimeEXT.adoc[]

include::{generated}/validity/structs/VkPresentTimeEXT.adoc[]
--

[open,refpage='VkAbsolutePresentTimeEXT',desc='Specifying the earliest time an image should be presented',type='structs']
--

The sname:VkAbsolutePresentTimeEXT structure is defined as:

include::{generated}/api/structs/VkAbsolutePresentTimeEXT.adoc[]

  * pname:presentID is an application-provided identification value.
    If non-zero, flink:vkGetPastPresentationTimingEXT will return a
    slink:VkPastPresentationTimingEXT struct with the timing information
    associated with the present to the associated swapchain for this
    call to flink:vkQueuePresentKHR, including this value being in the
    pname:presentID member of the slink:VkPastPresentationTimingEXT
    struct.
    In order to be useful to the application, it should: be unique within
    some period of time that is meaningful to the application.
  * pname:targetPresentTime, if non-zero, specifies the earliest time the
    application wants the image to be displayed to the user.
    pname:targetPresentTime is a time in nanoseconds, according to the
    time-domain being used.
    A value of zero specifies that the presentation engine may: display the
    image at any time.
  * pname:idealPresentTime provides an indication to the presentation
    engine of what the application desires its IPD to become.
    An application can: set pname:idealPresentTime to the same value
    as pname:targetPresentTime, indicating that the application
    desires its IPD to remain steady.
    A value earlier than
    pname:targetPresentTime indicates that the application desires to
    shorten its IPD.
    A value later than pname:targetPresentTime
    indicates that the application desires to lengthen its IPD.
    The presentation engine will provide feedback on this value in the
    data returned by flink:vkGetPastPresentationTimingEXT.
  * pname:presentSlop is the period of time in nanoseconds before
    pname:targetPresentTime that the presentation engine may: display
    the image.

If pname:targetPresentTime is non-zero, the presentation engine should:
not display the image to the user at a time earlier than
(pname:targetPresentTime - pname:presentSlop).

Setting pname:targetPresentTime to zero is useful when the application
desires to provide a non-zero pname:presentID in order to get back timing
information from flink:vkGetPastPresentationTimingEXT, but does not wish
to set a pname:targetPresentTime.

Providing a pname:presentSlop enables the application to indicate to the
presentation engine to display the image within this period if a vertical
blanking period occurs on FRR displays.

[NOTE]
.Note
====
The pname:presentSlop is used to avoid unintentionally missing a vertical
blanking period on FRR displays due to rounding errors or drift between
clocks.
A suggested value for pname:presentSlop is half the _Refresh Rate_.
====

include::{generated}/validity/structs/VkAbsolutePresentTimeEXT.adoc[]

--

[open,refpage='VkRelativePresentTimeEXT',desc='Specifying the minimum duration an image should be presented',type='structs']
--

The sname:VkRelativePresentTimeEXT structure is defined as:

include::{generated}/api/structs/VkRelativePresentTimeEXT.adoc[]

  * pname:presentID is an application-provided identification value.
    If non-zero, flink:vkGetPastPresentationTimingEXT will return a
    slink:VkPastPresentationTimingEXT struct with the timing information
    associated with the present to the associated swapchain for this
    call to flink:vkQueuePresentKHR, including this value being in the
    pname:presentID member of the slink:VkPastPresentationTimingEXT
    struct.
    In order to be useful to the application, it should: be unique within
    some period of time that is meaningful to the application.
  * pname:minPresentDuration, if non-zero, specifies the minimum duration
    in nanoseconds the application wants the image to be displayed to the
    user.
    A value of zero specifies that the presentation engine may: display the
    image for any duration.
  * pname:idealPresentDuration provides an indication to the presentation
    engine of what the application desires its IPD to become.
    An application can: set pname:idealPresentDuration to the same value
    as pname:minPresentDuration, indicating that the application
    desires its IPD to remain steady.
    A value smaller than
    pname:minPresentDuration indicates that the application desires to
    shorten its IPD.
    A value larger than pname:minPresentDuration
    indicates that the application desires to lengthen its IPD.
    The presentation engine will provide feedback on this value in the
    data returned by flink:vkGetPastPresentationTimingEXT.
  * pname:presentSlop is the period of time in nanoseconds before
    pname:minPresentDuration elapses that the presentation engine may:
    display the image.

If pname:minPresentDuration is non-zero, the presentation engine should:
display the image to the user for a minimum duration of
(pname:minPresentDuration - pname:presentSlop) nanoseconds.

Setting pname:minPresentDuration to zero is useful when the application
desires to provide a non-zero pname:presentID in order to get back timing
information from flink:vkGetPastPresentationTimingEXT, but does not wish
to set a pname:minPresentDuration.

Providing a pname:presentSlop enables the application to indicate to the
presentation engine to display the image within this period if a vertical
blanking period occurs on FRR displays.

[NOTE]
.Note
====
The pname:presentSlop is used to avoid unintentionally missing a vertical
blanking period on FRR displays due to rounding errors or drift between
clocks.
A suggested value for pname:presentSlop is half the _Refresh Rate_.
====

include::{generated}/validity/structs/VkRelativePresentTimeEXT.adoc[]

--
