// Copyright (c) 2014-2025 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

== Present Timing Queries

Traditional game and real-time-animation applications frequently use
ename:VK_PRESENT_MODE_FIFO_KHR so that presentable images are updated during
the vertical blanking period of a given refresh cycle (RC) of the
presentation engine's display.
On fixed refresh rate displays, this avoids the visual anomaly known as
tearing.

However, synchronizing the presentation of images with the RC does not
prevent all forms of visual anomalies.
Stuttering occurs when the geometry for each presentable image is not
accurately positioned for when that image will be displayed.
The geometry may appear to move too little some RCs, and too much for
others.
Sometimes the animation appears to freeze, when the same image is used for
more RCs than other images.

In order to minimize stuttering, an application needs to: 1) render and
present images at a consistent rate that is, on fixed refresh rate displays,
a multiple of the presentation engine's refresh rate; 2) correctly position
its geometry for when the presentable image will be displayed to the user.
The
ifdef::VK_EXT_present_timing[]
`apiext:VK_EXT_present_timing`
endif::VK_EXT_present_timing[]
ifdef::VK_EXT_present_timing+VK_GOOGLE_display_timing[or]
ifdef::VK_GOOGLE_display_timing[]
`apiext:VK_GOOGLE_display_timing`
endif::VK_GOOGLE_display_timing[]
extension allows an application to satisfy these needs.

The presentation engine's display typically refreshes the pixels that are
displayed to the user on a periodic basis. This period may: be fixed (Fixed
Refresh Rate, FRR) or variable (Variable Refresh Rate, VRR).

ifdef::VK_EXT_present_timing[]
[open,refpage='vkSetSwapchainPresentTimingQueueSizeEXT',desc='Allocate memory for the swapchain-internal timing results queue',type='protos']
--
In order to collect timing information about presentation, a swapchain needs
an internal queue to store asynchronously updated results until applications
collect them.

To allocate the swapchain's internal timing results queue, call:

include::{generated}/api/protos/vkSetSwapchainPresentTimingQueueSizeEXT.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to allocate a results queue for.
  * pname:size is the requested number of slots in the internal results queue.

If this function is called multiple times, the internal queue is reallocated
to fit the new pname:size. If the new pname:size is less than the current
number of outstanding results, ename:VK_NOT_READY is returned and no allocation
is performed.

.Valid Usage
****
  * pname:swapchain must: have been created with
    sname:VkSwapchainCreateInfoKHR::pname:flags containing
    ename:VK_SWAPCHAIN_CREATE_PRESENT_TIMING_BIT_EXT
****

include::{generated}/validity/protos/vkSetSwapchainPresentTimingQueueSizeEXT.adoc[]
--

[open,refpage='vkGetSwapchainTimingPropertiesEXT',desc='Obtain the display timing properties of the PE\'s display',type='protos']
--

The implementation maintains an internal monotonically increasing counter
which updates when the presentation engine's timing properties are modified.

To query the presentation engine's current timing properties for a given
swapchain, call:

include::{generated}/api/protos/vkGetSwapchainTimingPropertiesEXT.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to obtain timing properties for.
  * pname:pSwapchainTimingProperties is a pointer to an instance of the
    slink:VkSwapchainTimingPropertiesEXT structure.
  * pname:pSwapchainTimingPropertiesCounter is `NULL` or a pointer to a
    64-bit unsigned integer set by the implementation to the current value of
    the swapchain's internal timing properties counter.

If fname:vkGetSwapchainTimingPropertiesEXT returns ename:VK_NOT_READY, the
implementation was not able to determine the current refresh cycle
duration. Some platforms may: not provide timing properties until after at least
one image has been presented to the pname:swapchain. If timing properties change
for the pname:swapchain, these platforms may: not provide updated results until
after at least one additional image has been presented to the pname:swapchain.

include::{generated}/validity/protos/vkGetSwapchainTimingPropertiesEXT.adoc[]
--

[open,refpage='VkSwapchainTimingPropertiesEXT',desc='Structure containing the RC duration of a display',type='structs']
--

The sname:VkSwapchainTimingPropertiesEXT structure is defined as:

include::{generated}/api/structs/VkSwapchainTimingPropertiesEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:refreshDuration is zero or an indication of the duration
    of a refresh cycle.
  * pname:refreshInterval is a duration in nanoseconds indicating the interval
    between refresh cycle durations.

If pname:refreshInterval is the same as pname:refreshDuration, the
presentation engine is operating in FRR mode. In this case,
pname:refreshDuration is the number of nanoseconds from the start of one refresh
cycle to the start of the next refresh cycle.

If pname:refreshInterval is zero, the presentation engine is operating in VRR
mode, and pname:refreshDuration is the minimum number of nanoseconds from the
start of one refresh cycle to the start of the next refresh cycle.

If pname:refreshDuration and pname:refreshInterval are not zero,
pname:refreshInterval is a factor of pname:refreshDuration.

include::{generated}/validity/structs/VkSwapchainTimingPropertiesEXT.adoc[]
--

[NOTE]
====
The rate at which an application renders and presents new images is known as
the image present rate (IPR, a.k.a. frame rate).  The inverse of IPR, or the
duration between each image present, is the image present duration (IPD).

In order to provide a smooth, stutter-free animation on non-VRR displays, an
application needs its IPD to be a multiple of pname:refreshInterval that is
at least equal to pname:refreshDuration.

For example, if a FRR display has a set 60Hz refresh rate, where
pname:refreshDuration is equal to pname:refreshInterval,
pname:refreshDuration will be a value in nanoseconds that is approximately
equal to 16.67ms. In such a case, an application will want an IPD of 16.67ms
(1X multiplier of pname:refreshInterval), or 33.33ms (2X multiplier of
pname:refreshInterval), or 50.0ms (3X multiplier of pname:refreshInterval),
etc.

In order to determine a target IPD for a display (i.e. a multiple of
pname:refreshInterval), an application needs to determine when its images
are actually displayed.

Consider an application that has an initial target IPD of 16.67ms (1X
multiplier of pname:refreshDuration). It will therefore position the
geometry of a new image 16.67ms later than the previous image.

If this application is running on slower hardware, so that it actually takes
20ms to render each new image, the images will not be displayed to the user
every 16.67ms, nor every 20ms, which will create visual anomalies.
In this case, it is better for the application to adjust its target IPD to
33.33ms (i.e. a 2X multiplier of pname:refreshDuration), and tell the
presentation engine to not present images any sooner than every 33.33ms.
This will allow the geometry to be correctly positioned for each presentable
image.

On VRR displays, where pname:refreshInterval is zero, applications should: target
an IPD that is at least equal to pname:refreshDuration.

Adjustments to an application's IPD may be needed because different views of
an application's geometry can take different amounts of time to render.
For example, looking at the sky may take less time to render than looking at
multiple, complex items in a room.

In general, it is good to not frequently change IPD, as that can cause
visual anomalies.

Adjustments to a larger IPD because of late images should happen quickly,
but adjustments to a smaller IPD should only happen if the periodic
feedback of slink:VkPastPresentationTimingEXT values indicates that the
target IPD can be durably achieved.
====

[open,refpage='vkGetSwapchainTimeDomainPropertiesEXT',desc='Obtain the time domains supported by the PE for the swapchain',type='protos']
--
The implementation maintains an internal monotonically increasing counter which
updates when the presentation engine's list of supported time domains for a
swapchain is modified.

To query the time domains supported by the presentation engine for a given swapchain,
call:

include::{generated}/api/protos/vkGetSwapchainTimeDomainPropertiesEXT.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to obtain time domain properties for.
  * pname:pSwapchainTimeDomainProperties is a pointer to an instance of the
    slink:VkSwapchainTimeDomainPropertiesEXT structure.
  * pname:pTimeDomainsCounter is `NULL` or a pointer to a 64-bit unsigned
    integer set by the implementation to the current value of the
    swapchain's internal time domain properties counter.

If upon return slink:VkSwapchainTimeDomainPropertiesEXT::pname:timeDomainCount
is smaller than the number of time domains supported for the given
pname:swapchain, ename:VK_INCOMPLETE will be returned instead of
ename:VK_SUCCESS to indicate that not all the available values were returned.

include::{generated}/validity/protos/vkGetSwapchainTimeDomainPropertiesEXT.adoc[]
--

[open,refpage='VkSwapchainTimeDomainPropertiesEXT',desc='List of available time domains for a swapchain',type='structs']
--

The sname:VkSwapchainTimeDomainPropertiesEXT structure is defined as:

include::{generated}/api/structs/VkSwapchainTimeDomainPropertiesEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:timeDomainCount is an integer related to the number of time domains
    available or queried, as described below.
  * pname:pTimeDomains is a pointer to an array of elink:VkTimeDomainEXT values
    representing time domains that are available for the swapchain.
  * pname:pTimeDomainIds is a pointer to an array of unique identifiers for each
    time domain.

When calling flink:vkGetSwapchainTimeDomainPropertiesEXT, if pname:pTimeDomains
is `NULL` and pname:pTimeDomainIds is `NULL`, then the number of time domains
supported for the given pname:swapchain is returned in
pname:timeDomainCount. Otherwise, pname:timeDomainCount must: specify the number
of elements in the pname:pTimeDomains, pname:pTimeDomainIds, or both arrays, and
on return the variable is overwritten with the number of values actually written
to either array.

[NOTE]
====
Due to the dynamic nature of their underlying sname:VkSurfaceKHR properties,
swapchains may need to expose multiple swapchain-local opaque time domains using
the same elink:VkTimeDomainEXT value over time, for example when a surface is
moved from one display hardware to another. Arbitrary identifiers, provided in
pname:timeDomainIds, are used by the implementation to differentiate opaque time
domains of identical scopes.
====

include::{generated}/validity/structs/VkSwapchainTimeDomainPropertiesEXT.adoc[]
--

[open,refpage='vkGetPastPresentationTimingEXT',desc='Obtain timing of previously-presented images',type='protos']
--

Because of the asynchronous nature of the presentation engine, the timing
information for a given flink:vkQueuePresentKHR command may: only becomes
available some time after the presentation has occurred.
These time values should: be asynchronously queried, and are returned if
available.
All time values are in nanoseconds, according to the time-domain being used.

To asynchronously query the presentation engine for newly-available timing
information about one or more previous presents to a given swapchain, call:

include::{generated}/api/protos/vkGetPastPresentationTimingEXT.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:pPastPresentationTimingInfo is a pointer to an instance of
    the slink:VkPastPresentationTimingInfoEXT structure.
  * pname:pPastPresentationTimingProperties is a pointer to an instance
    of the slink:VkPastPresentationTimingPropertiesEXT structure.

If upon return the value of
sname:VkPastPresentationTimingPropertiesEXT::pname:presentationTimingCount is
less than the number of available timing records for the given
sname:VkPastPresentationTimingInfoEXT::pname:swapchain, ename:VK_INCOMPLETE is
returned instead of ename:VK_SUCCESS to indicate that not all the available
values were returned.

Timing information may: become available out of order with regards to their
associated presentation request submission order.

Upon return, zero or more slots of the pname:swapchain internal timing results
queue, equal to the number of entries written to
sname:VkPastPresentationTimingPropertiesEXT::pname:pPresentationTimings for
which pname:reportComplete is ename:VK_TRUE, are made available for future
fname:vkQueuePresentKHR calls. Elements of pname:pPresentationTimings are
arranged in ascending order of present ids.

There is no requirement for any precise timing relationship between the
completion of a present stage and the availability of any associated timing
information. However, results must: be made available in finite time.

As an exception to the normal rules for objects which are externally
synchronized, pname:swapchain may: be
simultaneously used by other threads in calls to functions other than
flink:vkDestroySwapchainKHR and flink:vkCreateSwapchainKHR with pname:swapchain
used as an pname:oldSwapchain. Access to the swapchain timing information must:
be atomic within the implementation.

include::{generated}/validity/protos/vkGetPastPresentationTimingEXT.adoc[]
--

[open,refpage='VkPastPresentationTimingInfoEXT',desc='Structure specifying swapchain present timing query parameters',type='structs']
--

The sname:VkPastPresentationTimingInfoEXT structure is defined as:

include::{generated}/api/structs/VkPastPresentationTimingInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkPastPresentationTimingFlagBitsEXT
    specifying options for queries of past presentation timing information.
  * pname:swapchain is the swapchain to obtain presentation timing
    information for.

include::{generated}/validity/structs/VkPastPresentationTimingInfoEXT.adoc[]
--

[open,refpage='VkPastPresentationTimingFlagsEXT',desc='Bitmask of VkPastPresentationTimingFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkPastPresentationTimingFlagsEXT.adoc[]

tname:VkPastPresentationTimingFlagsEXT is a bitmask type for setting a mask
of zero or more elink:VkPastPresentationTimingFlagBitsEXT.
--

[open,refpage='VkPastPresentationTimingFlagBitsEXT',desc='Bitmask specifying past presentation timing query flags',type='enums']
--
Bits which can: be set in slink:VkPastPresentationTimingInfoEXT::pname:flags, specifying options
for queries of past presentation timing information, are:

include::{generated}/api/enums/VkPastPresentationTimingFlagBitsEXT.adoc[]

  * ename:VK_PAST_PRESENTATION_TIMING_ALLOW_PARTIAL_RESULTS_BIT_EXT specifies
    that flink:vkGetPastPresentationTimingEXT may: return partial results for
    presentation requests that have not completed all requested present stages.
  * ename:VK_PAST_PRESENTATION_TIMING_ALLOW_OUT_OF_ORDER_RESULTS_BIT_EXT
    specifies that flink:vkGetPastPresentationTimingEXT may: return results
    out of order with respect to the presentation order.
--

[open,refpage='VkPastPresentationTimingPropertiesEXT',desc='Structure containing details about a swapchain past presentation activity',type='structs']
--

The sname:VkPastPresentationTimingPropertiesEXT structure is defined as:

include::{generated}/api/structs/VkPastPresentationTimingPropertiesEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:timingPropertiesCounter is a 64-bit unsigned integer set by the
    implementation to the current value of the swapchain's internal timing
    properties counter.
  * pname:timeDomainsCounter is a 64-bit unsigned integer set by the
    implementation to the current value of the swapchain's internal time
    domains list counter.
  * pname:presentationTimingCount is an integer related to the number of number
    of slink:VkPastPresentationTimingEXT structures available or queried, as
    described below.
  * pname:pPresentationTimings is `NULL` or a pointer to an array
    of slink:VkPastPresentationTimingEXT structures.

When calling flink:vkGetPastPresentationTimingEXT, if pname:pPresentationTimings
is `NULL`, then the number of available timing records for the given
pname:swapchain is returned in pname:presentationTimingCount. Otherwise,
pname:presentationTimingCount must: specify the number of elements in the
pname:pPresentationTimings array, and on return the variable is overwritten with
the number of structures actually written to pname:pPresentationTimings.

fname:vkGetPastPresentationTimingEXT may: return incomplete results,
containing only information for a subset of the requested present
stages. Further calls to fname:vkGetPastPresentationTimingEXT will keep
providing all available results for a previously incomplete entry until it
is complete.

The implementation must: return a slink:VkPastPresentationTimingEXT for
every flink:vkQueuePresentKHR referencing pname:swapchain where a non-zero
slink:VkPresentTimingInfoEXT::pname:presentStageQueries was specified and at
least one present stage has available results.

include::{generated}/validity/structs/VkPastPresentationTimingPropertiesEXT.adoc[]
--

[NOTE]
====
The presentation engine may: change the timing properties of the pname:swapchain
for a variety of reasons.

This may: occur, for example, if the window system changes its mode, including
the refresh rate of the display.
Another example is if an application's surface is being composited with other
windows of a window system, and then the surface's window becomes a borderless,
full-screen window.
While composited, the timing properties may: be FRR, and while full-screen, the
timing properties may: be VRR.

The available time domains for a swapchain may: change for similar or identical
reasons. Therefore, it is possible that the same event will cause both the
swapchain's internal timing properties counter and time domains list counter to
update.
====

[open,refpage='VkPastPresentationTimingEXT',desc='Structure containing timing information about a previously-presented image',type='structs']
--

The sname:VkPastPresentationTimingEXT structure is defined as:

include::{generated}/api/structs/VkPastPresentationTimingEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentId is zero or an application-provided value that was given
    to a previous fname:vkQueuePresentKHR command via
    slink:VkPresentId2KHR::pname:pPresentIds.
  * pname:targetTime is the application-provided target absolute or relative
    time of the associated presentation request in
    slink:VkPresentTimingInfoEXT::pname:time.
  * pname:presentStageCount is a count of items contained in
    pname:pPresentStages.
  * pname:pPresentStages a pointer to an array of
    slink:VkPresentStageTimeEXT providing timing information for the
    presentation request associated with pname:presentId.
  * pname:timeDomain is the time domain used by the presentation
    engine to report times in pname:pPresentStages.
  * pname:timeDomainId is the id associated with pname:timeDomain.
  * pname:reportComplete is ename:VK_TRUE if the presentation engine
    has reported all the requested results in pname:pPresentStages.

If pname:presentId is not zero, pname:presentStageCount must: be set by the
application to be at least equal to the number of present stages specified
in slink:VkPresentTimingInfoEXT::pname:presentStagesQueries for the
associated flink:vkQueuePresentKHR call. Otherwise, pname:presentStageCount
must: be at least equal to the highest number of present stages queried
among all presentation requests for which there are outstanding results.

Timing information for some present stages may: have a time value of 0,
indicating that results for that present stage are not available.

For systems with multiple entities operating within the presentation engine,
such as multiple displays, pname:pPresentStages will return timing results for
one entity which has been affected by the presentation.

pname:timeDomainId may: be different than the time domain that was specified in
slink:VkPresentTimingInfoEXT::pname:timeDomainId if the requirements for using
this time domain could not be met at the time the presentation engine processed
the presentation request. In such a case, the presentation engine may: pick a
time domain to fall back to, if one is available, and report results in that
domain. Applications can: continue to use this fallback time domain in future
flink:vkQueuePresentKHR calls, or they can: call
flink:vkGetSwapchainTimeDomainPropertiesEXT to choose from the currently
supported time domains.

include::{generated}/validity/structs/VkPastPresentationTimingEXT.adoc[]
--

[open,refpage='VkPresentStageTimeEXT',desc='Associate a present stage with a timestamp',type='structs']
--
The sname:VkPresentStageTimeEXT structure is defined as:

include::{generated}/api/structs/VkPresentStageTimeEXT.adoc[]

  * pname:stage is a tlink:VkPresentStageFlagsEXT value specifying a present stage.
  * pname:time is a time in nanoseconds associated with the pname:stage.

include::{generated}/validity/structs/VkPresentStageTimeEXT.adoc[]
--
endif::VK_EXT_present_timing[]

ifdef::VK_GOOGLE_display_timing[]
include::{chapters}/VK_GOOGLE_display_timing/queries.adoc[]
endif::VK_GOOGLE_display_timing[]
