// Copyright 2018-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[opticalflow]]
= Optical Flow


== Optical Flow Queues

`apiext:VK_NV_optical_flow` adds a optical flow queue type bit
ename:VK_QUEUE_OPTICAL_FLOW_BIT_NV to elink:VkQueueFlagBits.
Optical flow operations are supported by queues with an advertised queue
capability of ename:VK_QUEUE_OPTICAL_FLOW_BIT_NV.
As in the case of other queue types, an application must: use
flink:vkGetPhysicalDeviceQueueFamilyProperties to query whether the physical
device has support for the Optical Flow Queue.
When the implementation reports the ename:VK_QUEUE_OPTICAL_FLOW_BIT_NV bit
for a queue family, it advertises general support for Vulkan queue
operations described in <<devsandqueues, Devices and Queues>>.


[[opticalflow-formats]]
== Optical Flow Image Formats

[open,refpage='vkGetPhysicalDeviceOpticalFlowImageFormatsNV',desc='Query image formats for optical flow',type='protos']
--
To enumerate the supported image formats for a specific optical flow usage,
call:

include::{generated}/api/protos/vkGetPhysicalDeviceOpticalFlowImageFormatsNV.adoc[]

  * pname:physicalDevice is the physical device being queried.
  * [[opticalflow-getimageformat-pOpticalFlowImageFormatInfo]]
    pname:pOpticalFlowImageFormatInfo is a pointer to a
    slink:VkOpticalFlowImageFormatInfoNV structure specifying the optical
    flow usage for which information is returned.
  * [[opticalflow-getimageformat-pFormatCount]] pname:pFormatCount is a
    pointer to an integer related to the number of optical flow properties
    available or queried, as described below.
  * [[opticalflow-getimageformat-pImageFormatProperties]]
    pname:pImageFormatProperties is a pointer to an array of
    slink:VkOpticalFlowImageFormatPropertiesNV structures in which supported
    formats and image parameters are returned.

If pname:pImageFormatProperties is `NULL`, then the number of optical flow
properties supported for the given pname:physicalDevice is returned in
pname:pFormatCount.
Otherwise, pname:pFormatCount must point to a variable set by the user to
the number of elements in the pname:pImageFormatProperties array, and on
return the variable is overwritten with the number of values actually
written to pname:pImageFormatProperties.
If the value of pname:pFormatCount is less than the number of optical flow
properties supported, at most pname:pFormatCount values will be written to
pname:pImageFormatProperties, and ename:VK_INCOMPLETE will be returned
instead of ename:VK_SUCCESS, to indicate that not all the available values
were returned.
Before creating an image to be used as a optical flow frame, obtain the
supported image creation parameters by querying with
flink:vkGetPhysicalDeviceFormatProperties2 and
flink:vkGetPhysicalDeviceImageFormatProperties2 using one of the reported
formats and adding slink:VkOpticalFlowImageFormatInfoNV to the pname:pNext
chain of slink:VkPhysicalDeviceImageFormatInfo2.
When querying the parameters with
flink:vkGetPhysicalDeviceImageFormatProperties2 for images used for optical
flow operations, the slink:VkOpticalFlowImageFormatInfoNV::pname:usage field
should contain one or more of the bits defined in
elink:VkOpticalFlowUsageFlagBitsNV.

include::{generated}/validity/protos/vkGetPhysicalDeviceOpticalFlowImageFormatsNV.adoc[]

[NOTE]
.Note
====
ename:VK_FORMAT_B8G8R8A8_UNORM, ename:VK_FORMAT_R8_UNORM and
ename:VK_FORMAT_G8_B8R8_2PLANE_420_UNORM are initially supported for images
with <<opticalflow-usage,optical usage>>
ename:VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV.

ename:VK_FORMAT_R16G16_S10_5_NV is initially supported for images with
<<opticalflow-usage,optical flow usage>>
ename:VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV,
ename:VK_OPTICAL_FLOW_USAGE_HINT_BIT_NV and
ename:VK_OPTICAL_FLOW_USAGE_GLOBAL_FLOW_BIT_NV.

ename:VK_FORMAT_R8_UINT and ename:VK_FORMAT_R32_UINT are initially supported
for images with <<opticalflow-usage,optical flow usage>>
ename:VK_OPTICAL_FLOW_USAGE_COST_BIT_NV.
It is recommended to use ename:VK_FORMAT_R8_UINT because of the lower
bandwidth.
====
--

[open,refpage='VkOpticalFlowImageFormatInfoNV',desc='Structure describing optical flow image format info',type='structs']
--
The slink:VkOpticalFlowImageFormatInfoNV structure is defined as:

include::{generated}/api/structs/VkOpticalFlowImageFormatInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * [[opticalflow-usage]] pname:usage is a bitmask of
    elink:VkOpticalFlowUsageFlagBitsNV describing the intended optical flow
    usage of the image.

include::{generated}/validity/structs/VkOpticalFlowImageFormatInfoNV.adoc[]
--

[open,refpage='VkOpticalFlowUsageFlagBitsNV',desc='Bits specifying usage for optical flow operations',type='enums']
--
Bits which can: be set in slink:VkOpticalFlowImageFormatInfoNV::pname:usage,
controlling optical flow usage, are:

include::{generated}/api/enums/VkOpticalFlowUsageFlagBitsNV.adoc[]

  * ename:VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV specifies that the image can:
    be used as input or reference frame for an optical flow operation.
  * ename:VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV specifies that the image can:
    be used as output flow vector map for an optical flow operation.
  * ename:VK_OPTICAL_FLOW_USAGE_HINT_BIT_NV specifies that the image can: be
    used as hint flow vector map for an optical flow operation.
  * ename:VK_OPTICAL_FLOW_USAGE_COST_BIT_NV specifies that the image can: be
    used as output cost map for an optical flow operation.
  * ename:VK_OPTICAL_FLOW_USAGE_GLOBAL_FLOW_BIT_NV specifies that the image
    can: be used as global flow vector for an optical flow operation.
--

[open,refpage='VkOpticalFlowUsageFlagsNV',desc='Bitmask of VkOpticalFlowUsageFlagBitsNV',type='flags']
--
include::{generated}/api/flags/VkOpticalFlowUsageFlagsNV.adoc[]

tname:VkOpticalFlowUsageFlagsNV is a bitmask type for setting a mask of zero
or more elink:VkOpticalFlowUsageFlagBitsNV.
--

[open,refpage='VkOpticalFlowImageFormatPropertiesNV',desc='Structure describing properties of an optical flow image format',type='structs']
--
The slink:VkOpticalFlowImageFormatPropertiesNV structure is defined as:

include::{generated}/api/structs/VkOpticalFlowImageFormatPropertiesNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * [[opticalflow-format]] pname:format is a elink:VkFormat that specifies
    the format that can be used with the specified optical flow image
    usages.

include::{generated}/validity/structs/VkOpticalFlowImageFormatPropertiesNV.adoc[]
--


[[opticalflow-session]]
== Optical Flow Session


[[opticalflow-session-object]]
=== Optical Flow Session Object

[open,refpage='VkOpticalFlowSessionNV',desc='Opaque handle to an optical flow session object',type='handles']
--
Optical flow session objects are abstracted and represented by
slink:VkOpticalFlowSessionNV handles:

include::{generated}/api/handles/VkOpticalFlowSessionNV.adoc[]
--


[[opticalflow-session-creation]]
==== Creating an Optical Flow Session

[open,refpage='vkCreateOpticalFlowSessionNV',desc='Creates an optical flow session object',type='protos']
--
To create an optical flow session object, call:

include::{generated}/api/protos/vkCreateOpticalFlowSessionNV.adoc[]

  * pname:device is the logical device that creates the optical flow session
    object.
  * pname:pCreateInfo is a pointer to a
    slink:VkOpticalFlowSessionCreateInfoNV structure containing parameters
    specifying the creation of the optical flow session.
  * pname:pAllocator controls host memory allocation as described in the
    <<memory-allocation, Memory Allocation>> chapter.
  * pname:pSession is a pointer to a slink:VkOpticalFlowSessionNV handle
    specifying the optical flow session object which will be created by this
    function when it returns ename:VK_SUCCESS

include::{generated}/validity/protos/vkCreateOpticalFlowSessionNV.adoc[]
--

[open,refpage='VkOpticalFlowSessionCreateInfoNV',desc='Structure specifying parameters of a newly created optical flow session',type='structs']
--
The slink:VkOpticalFlowSessionCreateInfoNV structure is defined as:

include::{generated}/api/structs/VkOpticalFlowSessionCreateInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:width is the width in pixels of the input or reference frame to be
    bound to this optical flow session.
  * pname:height is the height in pixels of the input or reference frame to
    be bound to this optical flow session.
  * pname:imageFormat is the elink:VkFormat of the input and reference frame
    to be bound to this optical flow session.
  * pname:flowVectorFormat is the elink:VkFormat of the flow vector maps
    (output or hint) to be bound to this optical flow session.
  * pname:costFormat is the elink:VkFormat of the cost maps to be bound to
    this optical flow session.
  * pname:outputGridSize is exactly one bit of
    tlink:VkOpticalFlowGridSizeFlagsNV specifying the grid size of the
    output flow and cost maps to be bound to this optical flow session.
    The size of the output flow and cost maps is determined by
    sname:VkOpticalFlowSessionCreateInfoNV::pname:width and
    sname:VkOpticalFlowSessionCreateInfoNV::pname:height divided by
    sname:VkOpticalFlowSessionCreateInfoNV::pname:outputGridSize.
  * pname:hintGridSize is one exactly bit of
    tlink:VkOpticalFlowGridSizeFlagsNV specifying the grid size of the hint
    flow vector maps to be bound to this optical flow session.
    The size of the hint maps is determined by
    sname:VkOpticalFlowSessionCreateInfoNV::pname:width and
    sname:VkOpticalFlowSessionCreateInfoNV::pname:height divided by
    sname:VkOpticalFlowSessionCreateInfoNV::pname:hintGridSize.
  * pname:performanceLevel is the elink:VkOpticalFlowPerformanceLevelNV used
    for this optical flow session.
  * pname:flags are the tlink:VkOpticalFlowSessionCreateFlagsNV used for
    this optical flow session.

.Valid Usage
****
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-width-07581]]
    pname:width must: be greater than or equal to
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:minWidth and less
    than or equal to
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:maxWidth
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-height-07582]]
    pname:height must: be greater than or equal to
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:minHeight and less
    than or equal to
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:maxHeight
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-imageFormat-07583]]
    pname:imageFormat must: be one of the formats returned by
    flink:vkGetPhysicalDeviceOpticalFlowImageFormatsNV for
    ename:VK_OPTICAL_FLOW_USAGE_INPUT_BIT_NV
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flowVectorFormat-07584]]
    pname:flowVectorFormat must: be one of the formats returned by
    flink:vkGetPhysicalDeviceOpticalFlowImageFormatsNV for
    ename:VK_OPTICAL_FLOW_USAGE_OUTPUT_BIT_NV
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-costFormat-07585]]
    pname:costFormat must: be one of the formats returned by
    flink:vkGetPhysicalDeviceOpticalFlowImageFormatsNV for
    ename:VK_OPTICAL_FLOW_USAGE_COST_BIT_NV if
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV is set in
    pname:flags
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-outputGridSize-07586]]
    pname:outputGridSize must: be exactly one of the bits reported in
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:supportedOutputGridSizes
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-hintGridSize-07587]]
    pname:hintGridSize must: be exactly one of the bits reported in
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:supportedHintGridSizes
    if ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NV is set in
    pname:flags
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flags-07588]]
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NV must: not be set
    in pname:flags if
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:hintSupported is
    ename:VK_FALSE
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flags-07589]]
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV must: not be set
    in pname:flags if
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:costSupported is
    ename:VK_FALSE
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flags-07590]]
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_GLOBAL_FLOW_BIT_NV must: not
    be set in pname:flags if
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:globalFlowSupported
    is ename:VK_FALSE
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flags-07591]]
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV must: not be
    set in pname:flags if
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:maxNumRegionsOfInterest
    is 0
  * [[VUID-VkOpticalFlowSessionCreateInfoNV-flags-07592]]
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV must: not be
    set in pname:flags if
    sname:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:bidirectionalFlowSupported
    is ename:VK_FALSE
****

include::{generated}/validity/structs/VkOpticalFlowSessionCreateInfoNV.adoc[]
--

[open,refpage='VkOpticalFlowSessionCreatePrivateDataInfoNV',desc='Structure for NV internal use only',type='structs']
--
The slink:VkOpticalFlowSessionCreatePrivateDataInfoNV structure is for NV
internal use only and is defined as:

include::{generated}/api/structs/VkOpticalFlowSessionCreatePrivateDataInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:id is an identifier for data which is passed at a memory location
    specified in
    sname:VkOpticalFlowSessionCreatePrivateDataInfoNV::pname:pPrivateData.
  * pname:size is the size of data in bytes which is passed at a memory
    location specified in
    sname:VkOpticalFlowSessionCreatePrivateDataInfoNV::pname:pPrivateData.
  * pname:pPrivateData is a pointer to NV internal data.

include::{generated}/validity/structs/VkOpticalFlowSessionCreatePrivateDataInfoNV.adoc[]
--

[open,refpage='VkOpticalFlowGridSizeFlagBitsNV',desc='Bits specifying grid sizes for optical flow operations',type='enums']
--
Optical flow vectors are generated block-wise, one vector for each block of
NxN pixels (referred to as grid).

Bits which can: be set in
slink:VkOpticalFlowSessionCreateInfoNV::pname:outputGridSize and
slink:VkOpticalFlowSessionCreateInfoNV::pname:hintGridSize, or which are
returned in
slink:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:supportedOutputGridSizes
and
slink:VkPhysicalDeviceOpticalFlowPropertiesNV::pname:supportedHintGridSizes
controlling optical flow grid sizes, are:

include::{generated}/api/enums/VkOpticalFlowGridSizeFlagBitsNV.adoc[]

  * ename:VK_OPTICAL_FLOW_GRID_SIZE_1X1_BIT_NV specifies that grid is 1x1
    pixel.
  * ename:VK_OPTICAL_FLOW_GRID_SIZE_2X2_BIT_NV specifies that grid is 2x2
    pixel.
  * ename:VK_OPTICAL_FLOW_GRID_SIZE_4X4_BIT_NV specifies that grid is 4x4
    pixel.
  * ename:VK_OPTICAL_FLOW_GRID_SIZE_8X8_BIT_NV specifies that grid is 8x8
    pixel.
--

[open,refpage='VkOpticalFlowGridSizeFlagsNV',desc='Bitmask of VkOpticalFlowGridSizeFlagBitsNV',type='flags']
--
include::{generated}/api/flags/VkOpticalFlowGridSizeFlagsNV.adoc[]

tname:VkOpticalFlowGridSizeFlagsNV is a bitmask type for setting a mask of
zero or more elink:VkOpticalFlowGridSizeFlagBitsNV.
--

[open,refpage='VkOpticalFlowPerformanceLevelNV',desc='Optical flow performance level types',type='enums']
--
Optical flow exposes performance levels which the user can choose based on
the desired performance and quality requirement.

The optical flow performance level types are defined with the following:

include::{generated}/api/enums/VkOpticalFlowPerformanceLevelNV.adoc[]

  * ename:VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_SLOW_NV is a level with slower
    performance but higher quality.
  * ename:VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_MEDIUM_NV is a level with medium
    performance and medium quality.
  * ename:VK_OPTICAL_FLOW_PERFORMANCE_LEVEL_FAST_NV is a preset with higher
    performance but lower quality.
--

[open,refpage='VkOpticalFlowSessionCreateFlagBitsNV',desc='Bits specifying flags for optical flow session',type='enums']
--
Bits which can: be set in
slink:VkOpticalFlowSessionCreateInfoNV::pname:flags, controlling optical
flow session operations, are:

include::{generated}/api/enums/VkOpticalFlowSessionCreateFlagBitsNV.adoc[]

  * ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_HINT_BIT_NV specifies that a
    slink:VkImageView with external flow vectors will be used as hints in
    performing the motion search and must: be bound to
    ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV.
  * ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_COST_BIT_NV specifies that
    the cost for the forward flow is generated in a slink:VkImageView which
    must: be bound to ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV.
    Additionally, if
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV is also set,
    the cost for backward flow is generated in a slink:VkImageView which
    must: be bound to
    ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV.
    The cost is the confidence level of the flow vector for each grid in the
    frame.
    The Cost implies how (in)accurate the flow vector is.
    Higher cost value implies the flow vector to be less accurate and
    vice-versa.
  * ename:VK_OPTICAL_FLOW_SESSION_CREATE_ENABLE_GLOBAL_FLOW_BIT_NV specifies
    that a global flow vector is estimated from forward flow in a single
    pixel slink:VkImageView which must: be bound to
    ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV.
  * ename:VK_OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV specifies that
    regions of interest can: be specified in
    slink:VkOpticalFlowExecuteInfoNV.
  * ename:VK_OPTICAL_FLOW_SESSION_CREATE_BOTH_DIRECTIONS_BIT_NV specifies
    that backward flow is generated in addition to forward flow which is
    always generated.
--

[open,refpage='VkOpticalFlowSessionCreateFlagsNV',desc='Bitmask of VkOpticalFlowSessionCreateFlagBitsNV',type='flags']
--
tname:VkOpticalFlowSessionCreateFlagsNV is a bitmask type for setting a mask
of zero or more elink:VkOpticalFlowSessionCreateFlagBitsNV.

include::{generated}/api/flags/VkOpticalFlowSessionCreateFlagsNV.adoc[]
--


[[opticalflow-session-destruction]]
==== Destroying an Optical Flow Session

[open,refpage='vkDestroyOpticalFlowSessionNV',desc='Destroy optical flow session object',type='protos']
--
To destroy a optical flow session object, call:

include::{generated}/api/protos/vkDestroyOpticalFlowSessionNV.adoc[]

  * pname:device is the device that was used for the creation of the optical
    flow session.
  * pname:session is the optical flow session to be destroyed.
  * pname:pAllocator controls host memory allocation as described in the
    <<memory-allocation, Memory Allocation>> chapter.

include::{generated}/validity/protos/vkDestroyOpticalFlowSessionNV.adoc[]
--


[[opticalflow-session-binding-images]]
=== Binding Vulkan Image Views to an Optical Flow Session

[open,refpage='vkBindOpticalFlowSessionImageNV',desc='Bind image to an optical flow session',type='protos']
--
To bind a vulkan image to an optical flow session object, call:

include::{generated}/api/protos/vkBindOpticalFlowSessionImageNV.adoc[]

  * pname:device is the device which owns the optical flow session object
    pname:session.
  * pname:session is the optical flow session object to which the image view
    is to be bound.
  * pname:bindingPoint specifies the binding point
    elink:VkOpticalFlowSessionBindingPointNV to which the image view is
    bound.
  * pname:view is a slink:VkImageView to be bound.
  * layout must: specify the layout that the image subresources accessible
    from pname:view will be in at the time the optical flow vectors are
    calculated with flink:vkCmdOpticalFlowExecuteNV on a sname:VkDevice.

include::{generated}/validity/protos/vkBindOpticalFlowSessionImageNV.adoc[]
--

[open,refpage='VkOpticalFlowSessionBindingPointNV',desc='Binding points of an optical flow session',type='enums']
--
The optical flow session binding points are defined with the following:

include::{generated}/api/enums/VkOpticalFlowSessionBindingPointNV.adoc[]

  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_INPUT_NV specifies the
    binding point for the input frame.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_REFERENCE_NV specifies the
    binding point for the input reference frame.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_HINT_NV specifies the
    binding point for the optional external hint flow vectors.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_FLOW_VECTOR_NV specifies the
    binding point for output flow vectors of default forward flow calcution.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_FLOW_VECTOR_NV
    specifies the binding point for the optional output flow vector map of
    optional backward flow calcution.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_COST_NV specifies the
    binding point for the optional output cost map of default forward flow
    calcution.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_BACKWARD_COST_NV specifies
    the binding point for the optional output cost map of optional backward
    flow calcution.
  * ename:VK_OPTICAL_FLOW_SESSION_BINDING_POINT_GLOBAL_FLOW_NV specifies the
    binding point for the optional global flow value of default forward flow
    calcution.
--


[[opticalflow-operations]]
=== Optical Flow Execution

[open,refpage='vkCmdOpticalFlowExecuteNV',desc='Calculate optical flow vectors',type='protos']
--
Default direction of flow estimation is forward which calculates the optical
flow from input frame to reference frame.
Optionally backward flow estimation can be additionally calculated.
An output flow vector (Vx, Vy) means that current pixel (x, y) of input
frame can be found at location (x+Vx, y+Vy) in reference frame.
A backward flow vector (Vx, Vy) means that current pixel (x, y) of reference
frame can be found at location (x+Vx, y+Vy) in input frame.

To calculate optical flow vectors from two input frames, call:

include::{generated}/api/protos/vkCmdOpticalFlowExecuteNV.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:session is the optical flow session object on which this command
    is operating.
  * pname:pExecuteInfo Info is a pointer to a
    slink:VkOpticalFlowExecuteInfoNV.

include::{generated}/validity/protos/vkCmdOpticalFlowExecuteNV.adoc[]
--

[open,refpage='VkOpticalFlowExecuteInfoNV',desc='Structure specifying parameters of a optical flow vector calculation',type='structs']
--
The slink:VkOpticalFlowExecuteInfoNV structure is defined as:

include::{generated}/api/structs/VkOpticalFlowExecuteInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags are the tlink:VkOpticalFlowExecuteFlagsNV used for this
    command.
  * pname:regionCount is the number of regions of interest specified in
    pname:pRegions.
  * pname:pRegions is a pointer to pname:regionCount sname:VkRect2D regions
    of interest.

.Valid Usage
****
  * [[VUID-VkOpticalFlowExecuteInfoNV-regionCount-07593]]
    pname:regionCount must: be 0 if
    ename:VK_OPTICAL_FLOW_SESSION_CREATE_ALLOW_REGIONS_BIT_NV was not set
    for sname:VkOpticalFlowSessionNV on which this command is operating
****

include::{generated}/validity/structs/VkOpticalFlowExecuteInfoNV.adoc[]
--

[open,refpage='VkOpticalFlowExecuteFlagBitsNV',desc='Bits specifying flags for a optical flow vector calculation',type='enums']
--
Bits which can: be set in slink:VkOpticalFlowExecuteInfoNV::pname:flags,
controlling optical flow execution, are:

include::{generated}/api/enums/VkOpticalFlowExecuteFlagBitsNV.adoc[]

  * ename:VK_OPTICAL_FLOW_EXECUTE_DISABLE_TEMPORAL_HINTS_BIT_NV specifies
    that temporal hints from previously generated flow vectors are not used.
    If temporal hints are enabled, optical flow vectors from previous
    flink:vkCmdOpticalFlowExecuteNV call are automatically used as hints for
    the current flink:vkCmdOpticalFlowExecuteNV call, to take advantage of
    temporal correlation in a video sequence.
    Temporal hints should be disabled if there is a-priori knowledge of no
    temporal correlation (e.g. a scene change, independent successive frame
    pairs).
--

[open,refpage='VkOpticalFlowExecuteFlagsNV',desc='Bitmask of VkOpticalFlowExecuteFlagBitsNV',type='flags']
--
tname:VkOpticalFlowExecuteFlagsNV is a bitmask type for setting a mask of
zero or more elink:VkOpticalFlowExecuteFlagBitsNV.

include::{generated}/api/flags/VkOpticalFlowExecuteFlagsNV.adoc[]
--
