// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

The following commands can be used to copy between host memory and images.
Bytes in host memory and texels in images are accessed as specified in
<<copies-buffers-images,Copying Data Between Buffers and Images>>, with
buffers replaced with host memory.

[NOTE]
====
Copies to and from an image on the host are not internally synchronized.
Simultaneous access (involving writes) to overlapping image memory on the
host constitutes a <<memory-model-access-data-race,data race>>.
====

[open,refpage='vkCopyMemoryToImage',desc='Copy data from host memory into an image',type='protos',alias='vkCopyMemoryToImageEXT']
--
:refpage: vkCopyMemoryToImage

To copy data from host memory to an image object, call:

ifdef::VK_VERSION_1_4[]
include::{generated}/api/protos/vkCopyMemoryToImage.adoc[]
endif::VK_VERSION_1_4[]

ifdef::VK_VERSION_1_4+VK_EXT_host_image_copy[or the equivalent command]

ifdef::VK_EXT_host_image_copy[]
include::{generated}/api/protos/vkCopyMemoryToImageEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:device is the device which owns
    pname:pCopyMemoryToImageInfo->dstImage.
  * pname:pCopyMemoryToImageInfo is a pointer to a
    slink:VkCopyMemoryToImageInfo structure describing the copy parameters.

This command is functionally similar to flink:vkCmdCopyBufferToImage2,
except it is executed on the host and reads from host memory instead of a
buffer.
The memory of pname:pCopyMemoryToImageInfo->dstImage is accessed by the host
as if <<memory-coherent, coherent>>.

[NOTE]
====
Because queue submissions <<synchronization-submission-host-writes,
automatically make host memory visible to the device>>, there would not be a
need for a memory barrier before using the results of this copy operation on
the device.
====

include::{generated}/validity/protos/vkCopyMemoryToImage.adoc[]
--

[open,refpage='VkCopyMemoryToImageInfo',desc='Structure specifying parameters of host memory to image copy command',type='structs',alias='VkCopyMemoryToImageInfoEXT']
--
:refpage: VkCopyMemoryToImageInfo
:imageparam: dstImage
:imagesubresource: imageSubresource
:imageoffset: imageOffset
:imageextent: imageExtent
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

The sname:VkCopyMemoryToImageInfo structure is defined as:

include::{generated}/api/structs/VkCopyMemoryToImageInfo.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/structs/VkCopyMemoryToImageInfoEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBits values
    describing additional copy parameters.
  * pname:dstImage is the destination image.
  * pname:dstImageLayout is the layout of the destination image subresources
    for the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkMemoryToImageCopy
    structures specifying the regions to copy.

fname:vkCopyMemoryToImage does not check whether the device memory
associated with pname:dstImage is currently in use before performing the
copy.
The application must: guarantee that any previously submitted command that
reads from or writes to the copy regions has completed before the host
performs the copy.

Copy regions for the image must: be aligned to a multiple of the texel block
extent in each dimension, except at the edges of the image, where region
extents must: match the edge of the image.

.Valid Usage
****
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_single_sampled_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_not_both_image_common.adoc[]
  * [[VUID-VkCopyMemoryToImageInfo-dstImageLayout-09059]]
    pname:dstImageLayout must: specify the current layout of the image
    subresources of pname:dstImage specified in pname:pRegions
  * [[VUID-VkCopyMemoryToImageInfo-dstImageLayout-09060]]
    pname:dstImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyProperties::pname:pCopyDstLayouts
  * [[VUID-VkCopyMemoryToImageInfo-flags-09393]]
    If pname:flags includes ename:VK_HOST_IMAGE_COPY_MEMCPY, for each region
    in pname:pRegions, pname:memoryRowLength and pname:memoryImageHeight
    must: both be 0
****

include::{generated}/validity/structs/VkCopyMemoryToImageInfo.adoc[]
--

[open,refpage='VkMemoryToImageCopy',desc='Structure specifying a host memory to image copy operation',type='structs',alias='VkMemoryToImageCopyEXT']
--
:refpage: VkMemoryToImageCopy
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

Each element of slink:VkCopyMemoryToImageInfo::pname:pRegions is a structure
defined as:

include::{generated}/api/structs/VkMemoryToImageCopy.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/structs/VkMemoryToImageCopyEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pHostPointer is the host memory address which is the source of the
    copy.
  * pname:memoryRowLength and pname:memoryImageHeight specify in texels a
    subregion of a larger two- or three-dimensional image in host memory,
    and control the addressing calculations.
    If either of these values is zero, that aspect of the host memory is
    considered to be tightly packed according to the pname:imageExtent.
  * pname:imageSubresource is a slink:VkImageSubresourceLayers used to
    specify the specific image subresources of the image used for the source
    or destination image data.
  * pname:imageOffset selects the initial pname:x, pname:y, pname:z offsets
    in texels of the sub-region of the destination image data.
  * pname:imageExtent is the size in texels of the image to copy in
    pname:width, pname:height and pname:depth.

This structure is functionally similar to slink:VkBufferImageCopy2, except
it defines host memory as the source of copy instead of a buffer.
In particular, the same data packing rules and restrictions as that
structure apply here as well.

.Valid Usage
****
  * [[VUID-VkMemoryToImageCopy-pHostPointer-09061]]
    pname:pHostPointer must: point to memory that is large enough to contain
    all memory locations that are accessed according to
    <<copies-buffers-images-addressing,Buffer and Image Addressing>>, for
    each element of pname:pRegions
  * [[VUID-VkMemoryToImageCopy-pRegions-09062]]
    The union of all source regions, and the union of all destination
    regions, specified by the elements of pname:pRegions, must: not overlap
    in memory
include::{chapters}/commonvalidity/buffer_or_memory_image_copy_common.adoc[]
****

include::{generated}/validity/structs/VkMemoryToImageCopy.adoc[]
--

[open,refpage='vkCopyImageToMemory',desc='Copy image data into host memory',type='protos',alias='vkCopyImageToMemoryEXT']
--
:refpage: vkCopyImageToMemory

To copy data from an image object to host memory, call:

ifdef::VK_VERSION_1_4[]
include::{generated}/api/protos/vkCopyImageToMemory.adoc[]
endif::VK_VERSION_1_4[]

ifdef::VK_VERSION_1_4+VK_EXT_host_image_copy[or the equivalent command]

ifdef::VK_EXT_host_image_copy[]
include::{generated}/api/protos/vkCopyImageToMemoryEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:device is the device which owns
    pname:pCopyImageToMemoryInfo->srcImage.
  * pname:pCopyImageToMemoryInfo is a pointer to a
    slink:VkCopyImageToMemoryInfo structure describing the copy parameters.

This command is functionally similar to flink:vkCmdCopyImageToBuffer2,
except it is executed on the host and writes to host memory instead of a
buffer.
The memory of pname:pCopyImageToMemoryInfo->srcImage is accessed by the host
as if <<memory-coherent, coherent>>.

[NOTE]
====
If the device has written to the image memory, it is not automatically made
available to the host.
Before this copy command can be called, a memory barrier for this image
must: have been issued on the device with the second
<<synchronization-dependencies-scopes, synchronization scope>> including
ename:VK_PIPELINE_STAGE_HOST_BIT and ename:VK_ACCESS_HOST_READ_BIT.
====

include::{generated}/validity/protos/vkCopyImageToMemory.adoc[]
--

[open,refpage='VkCopyImageToMemoryInfo',desc='Structure specifying parameters of an image to host memory copy command',type='structs',alias='VkCopyImageToMemoryInfoEXT']
--
:refpage: VkCopyImageToMemoryInfo
:imageparam: srcImage
:imagesubresource: imageSubresource
:imageoffset: imageOffset
:imageextent: imageExtent
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

The sname:VkCopyImageToMemoryInfo structure is defined as:

include::{generated}/api/structs/VkCopyImageToMemoryInfo.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/structs/VkCopyImageToMemoryInfoEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBits values
    describing additional copy parameters.
  * pname:srcImage is the source image.
  * pname:srcImageLayout is the layout of the source image subresources for
    the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkImageToMemoryCopy
    structures specifying the regions to copy.

fname:vkCopyImageToMemory does not check whether the device memory
associated with pname:srcImage is currently in use before performing the
copy.
The application must: guarantee that any previously submitted command that
writes to the copy regions has completed before the host performs the copy.

Copy regions for the image must: be aligned to a multiple of the texel block
extent in each dimension, except at the edges of the image, where region
extents must: match the edge of the image.

.Valid Usage
****
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_single_sampled_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_not_both_image_common.adoc[]
  * [[VUID-VkCopyImageToMemoryInfo-srcImageLayout-09064]]
    pname:srcImageLayout must: specify the current layout of the image
    subresources of pname:srcImage specified in pname:pRegions
  * [[VUID-VkCopyImageToMemoryInfo-srcImageLayout-09065]]
    pname:srcImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyProperties::pname:pCopySrcLayouts
  * [[VUID-VkCopyImageToMemoryInfo-flags-09394]]
    If pname:flags includes ename:VK_HOST_IMAGE_COPY_MEMCPY, for each region
    in pname:pRegions, pname:memoryRowLength and pname:memoryImageHeight
    must: both be 0
****

include::{generated}/validity/structs/VkCopyImageToMemoryInfo.adoc[]
--

[open,refpage='VkImageToMemoryCopy',desc='Structure specifying an image to host memory copy operation',type='structs',alias='VkImageToMemoryCopyEXT']
--
:refpage: VkImageToMemoryCopy
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

Each element of slink:VkCopyImageToMemoryInfo::pname:pRegions is a structure
defined as:

include::{generated}/api/structs/VkImageToMemoryCopy.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/structs/VkImageToMemoryCopyEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pHostPointer is the host memory address which is the destination
    of the copy.
  * pname:memoryRowLength and pname:memoryImageHeight specify in texels a
    subregion of a larger two- or three-dimensional image in host memory,
    and control the addressing calculations.
    If either of these values is zero, that aspect of the host memory is
    considered to be tightly packed according to the pname:imageExtent.
  * pname:imageSubresource is a slink:VkImageSubresourceLayers used to
    specify the specific image subresources of the image used for the source
    or destination image data.
  * pname:imageOffset selects the initial pname:x, pname:y, pname:z offsets
    in texels of the sub-region of the source image data.
  * pname:imageExtent is the size in texels of the image to copy in
    pname:width, pname:height and pname:depth.

This structure is functionally similar to slink:VkBufferImageCopy2, except
it defines host memory as the target of copy instead of a buffer.
In particular, the same data packing rules and restrictions as that
structure apply here as well.

.Valid Usage
****
  * [[VUID-VkImageToMemoryCopy-pHostPointer-09066]]
    pname:pHostPointer must: point to memory that is large enough to contain
    all memory locations that are accessed according to
    <<copies-buffers-images-addressing,Buffer and Image Addressing>>, for
    each element of pname:pRegions
  * [[VUID-VkImageToMemoryCopy-pRegions-09067]]
    The union of all source regions, and the union of all destination
    regions, specified by the elements of pname:pRegions, must: not overlap
    in memory
include::{chapters}/commonvalidity/buffer_or_memory_image_copy_common.adoc[]
****

include::{generated}/validity/structs/VkImageToMemoryCopy.adoc[]
--

[open,refpage='VkHostImageCopyFlagBits',desc='Bitmask specifying additional copy parameters',type='enums',alias='VkHostImageCopyFlagBitsEXT']
--
Bits which can: be set in slink:VkCopyMemoryToImageInfo::pname:flags,
slink:VkCopyImageToMemoryInfo::pname:flags, and
slink:VkCopyImageToImageInfo::pname:flags, specifying additional copy
parameters are:

include::{generated}/api/enums/VkHostImageCopyFlagBits.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/enums/VkHostImageCopyFlagBitsEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * ename:VK_HOST_IMAGE_COPY_MEMCPY specifies that no memory layout
    swizzling is to be applied during data copy.
    For copies between memory and images, this flag indicates that image
    data in host memory is swizzled in exactly the same way as the image
    data on the device.
    Using this flag indicates that the implementations may: use a simple
    memory copy to transfer the data between the host memory and the device
    memory.
    The format of the swizzled data in host memory is platform dependent and
    is not defined in this specification.
--

[open,refpage='VkHostImageCopyFlags',desc='Bitmask of VkHostImageCopyFlagBits',type='flags',alias='VkHostImageCopyFlagsEXT']
--
include::{generated}/api/flags/VkHostImageCopyFlags.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/flags/VkHostImageCopyFlagsEXT.adoc[]
endif::VK_EXT_host_image_copy[]

tname:VkHostImageCopyFlags is a bitmask type for setting a mask of zero or
more elink:VkHostImageCopyFlagBits.
--
[open,refpage='vkCopyImageToImage',desc='Copy image data using the host',type='protos',alias='vkCopyImageToImageEXT']
--
:refpage: vkCopyImageToImage

To copy data from an image object to another image object using the host,
call:

ifdef::VK_VERSION_1_4[]
include::{generated}/api/protos/vkCopyImageToImage.adoc[]
endif::VK_VERSION_1_4[]

ifdef::VK_VERSION_1_4+VK_EXT_host_image_copy[or the equivalent command]

ifdef::VK_EXT_host_image_copy[]
include::{generated}/api/protos/vkCopyImageToImageEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:device is the device which owns
    pname:pCopyImageToImageInfo->srcImage and
    pname:pCopyImageToImageInfo->dstImage.
  * pname:pCopyImageToImageInfo is a pointer to a
    slink:VkCopyImageToImageInfo structure describing the copy parameters.

This command is functionally similar to flink:vkCmdCopyImage2, except it is
executed on the host.
The memory of pname:pCopyImageToImageInfo->srcImage and
pname:pCopyImageToImageInfo->dstImage is accessed by the host as if
<<memory-coherent, coherent>>.

[NOTE]
====
If the device has written to the memory of
pname:pCopyImageToImageInfo->srcImage, it is not automatically made
available to the host.
Before this copy command can be called, a memory barrier for this image
must: have been issued on the device with the second
<<synchronization-dependencies-scopes, synchronization scope>> including
ename:VK_PIPELINE_STAGE_HOST_BIT and ename:VK_ACCESS_HOST_READ_BIT.

Because queue submissions <<synchronization-submission-host-writes,
automatically make host memory visible to the device>>, there would not be a
need for a memory barrier before using the results of this copy operation in
pname:pCopyMemoryToImageInfo->dstImage on the device.
====

include::{generated}/validity/protos/vkCopyImageToImage.adoc[]
--

[open,refpage='VkCopyImageToImageInfo',desc='Structure specifying parameters of an image to image host copy command',type='structs',alias='VkCopyImageToImageInfoEXT']
--
:refpage: VkCopyImageToImageInfo

The sname:VkCopyImageToImageInfo structure is defined as:

include::{generated}/api/structs/VkCopyImageToImageInfo.adoc[]

ifdef::VK_EXT_host_image_copy[]
or the equivalent

include::{generated}/api/structs/VkCopyImageToImageInfoEXT.adoc[]
endif::VK_EXT_host_image_copy[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBits values
    describing additional copy parameters.
  * pname:srcImage is the source image.
  * pname:srcImageLayout is the layout of the source image subresources for
    the copy.
  * pname:dstImage is the destination image.
  * pname:dstImageLayout is the layout of the destination image subresources
    for the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkImageCopy2 structures
    specifying the regions to copy.

fname:vkCopyImageToImage does not check whether the device memory associated
with pname:srcImage or pname:dstImage is currently in use before performing
the copy.
The application must: guarantee that any previously submitted command that
writes to the copy regions has completed before the host performs the copy.

.Valid Usage
****
  * [[VUID-VkCopyImageToImageInfo-srcImage-09069]]
    pname:srcImage and pname:dstImage must: have been created with identical
    image creation parameters

:imageparam: srcImage
:imagesubresource: srcSubresource
:imageoffset: srcOffset
:imageextent: extent
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]

:imageparam: dstImage
:imagesubresource: dstSubresource
:imageoffset: dstOffset
:imageextent: extent
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
  * [[VUID-VkCopyImageToImageInfo-srcImageLayout-09070]]
    pname:srcImageLayout must: specify the current layout of the image
    subresources of pname:srcImage specified in pname:pRegions
  * [[VUID-VkCopyImageToImageInfo-dstImageLayout-09071]]
    pname:dstImageLayout must: specify the current layout of the image
    subresources of pname:dstImage specified in pname:pRegions
  * [[VUID-VkCopyImageToImageInfo-srcImageLayout-09072]]
    pname:srcImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyProperties::pname:pCopySrcLayouts
  * [[VUID-VkCopyImageToImageInfo-dstImageLayout-09073]]
    pname:dstImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyProperties::pname:pCopyDstLayouts
****

include::{generated}/validity/structs/VkCopyImageToImageInfo.adoc[]
--
