// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

The following commands can be used to copy between host memory and images.

[open,refpage='vkCopyMemoryToImageEXT',desc='Copy data from host memory into an image',type='protos']
--
:refpage: vkCopyMemoryToImageEXT

To copy data from host memory to an image object, call:

include::{generated}/api/protos/vkCopyMemoryToImageEXT.adoc[]

  * pname:device is the device which owns
    pname:pCopyMemoryToImageInfo->dstImage.
  * pname:pCopyMemoryToImageInfo is a pointer to a
    slink:VkCopyMemoryToImageInfoEXT structure describing the copy
    parameters.

This command is functionally similar to flink:vkCmdCopyBufferToImage2,
except it is executed on the host and reads from host memory instead of a
buffer.
The memory of pname:pCopyMemoryToImageInfo->dstImage is accessed by the host
as if <<memory-coherent, coherent>>.

[NOTE]
.Note
====
Because queue submissions <<synchronization-submission-host-writes,
automatically make host memory visible to the device>>, there would not be a
need for a memory barrier before using the results of this copy operation on
the device.
====

.Valid Usage
****
  * [[VUID-vkCopyMemoryToImageEXT-hostImageCopy-09058]]
    The <<features-hostImageCopy, pname:hostImageCopy>> feature must: be
    enabled
****

include::{generated}/validity/protos/vkCopyMemoryToImageEXT.adoc[]
--

[open,refpage='VkCopyMemoryToImageInfoEXT',desc='Structure specifying parameters of host memory to image copy command',type='structs']
--
:refpage: VkCopyMemoryToImageInfoEXT
:imageparam: dstImage
:imagesubresource: imageSubresource
:imageoffset: imageOffset
:imageextent: imageExtent
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

The sname:VkCopyMemoryToImageInfoEXT structure is defined as:

include::{generated}/api/structs/VkCopyMemoryToImageInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBitsEXT values
    describing additional copy parameters.
  * pname:dstImage is the destination image.
  * pname:dstImageLayout is the layout of the destination image subresources
    for the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkMemoryToImageCopyEXT
    structures specifying the regions to copy.

fname:vkCopyMemoryToImageEXT does not check whether the device memory
associated with pname:dstImage is currently in use before performing the
copy.
The application must: guarantee that any previously submitted command that
reads from or writes to the copy regions has completed before the host
performs the copy.

Copy regions for the image must: be aligned to a multiple of the texel block
extent in each dimension, except at the edges of the image, where region
extents must: match the edge of the image.

.Valid Usage
****
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_single_sampled_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_not_both_image_common.adoc[]
  * [[VUID-VkCopyMemoryToImageInfoEXT-dstImageLayout-09059]]
    pname:dstImageLayout must: specify the current layout of the image
    subresources of pname:dstImage specified in pname:pRegions
  * [[VUID-VkCopyMemoryToImageInfoEXT-dstImageLayout-09060]]
    pname:dstImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyPropertiesEXT::pname:pCopyDstLayouts
  * [[VUID-VkCopyMemoryToImageInfoEXT-flags-09393]]
    If pname:flags includes ename:VK_HOST_IMAGE_COPY_MEMCPY_EXT, for each
    region in pname:pRegions, pname:memoryRowLength and
    pname:memoryImageHeight must: both be 0
****

include::{generated}/validity/structs/VkCopyMemoryToImageInfoEXT.adoc[]
--

[open,refpage='VkMemoryToImageCopyEXT',desc='Structure specifying a host memory to image copy operation',type='structs']
--
:refpage: VkMemoryToImageCopyEXT
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

Each element of slink:VkCopyMemoryToImageInfoEXT::pname:pRegions is a
structure defined as:

include::{generated}/api/structs/VkMemoryToImageCopyEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pHostPointer is the host memory address which is the source of the
    copy.
  * pname:memoryRowLength and pname:memoryImageHeight specify in texels a
    subregion of a larger two- or three-dimensional image in host memory,
    and control the addressing calculations.
    If either of these values is zero, that aspect of the host memory is
    considered to be tightly packed according to the pname:imageExtent.
  * pname:imageSubresource is a slink:VkImageSubresourceLayers used to
    specify the specific image subresources of the image used for the source
    or destination image data.
  * pname:imageOffset selects the initial pname:x, pname:y, pname:z offsets
    in texels of the sub-region of the destination image data.
  * pname:imageExtent is the size in texels of the image to copy in
    pname:width, pname:height and pname:depth.

This structure is functionally similar to slink:VkBufferImageCopy2, except
it defines host memory as the source of copy instead of a buffer.
In particular, the same data packing rules and restrictions as that
structure apply here as well.

.Valid Usage
****
  * [[VUID-VkMemoryToImageCopyEXT-pHostPointer-09061]]
    pname:pHostPointer must: point to memory that is large enough to contain
    all memory locations that are accessed according to
    <<copies-buffers-images-addressing,Buffer and Image Addressing>>, for
    each element of pname:pRegions
  * [[VUID-VkMemoryToImageCopyEXT-pRegions-09062]]
    The union of all source regions, and the union of all destination
    regions, specified by the elements of pname:pRegions, must: not overlap
    in memory
include::{chapters}/commonvalidity/buffer_or_memory_image_copy_common.adoc[]
****

include::{generated}/validity/structs/VkMemoryToImageCopyEXT.adoc[]
--

[open,refpage='vkCopyImageToMemoryEXT',desc='Copy image data into host memory',type='protos']
--
:refpage: vkCopyImageToMemoryEXT

To copy data from an image object to host memory, call:

include::{generated}/api/protos/vkCopyImageToMemoryEXT.adoc[]

  * pname:device is the device which owns
    pname:pCopyImageToMemoryInfo->srcImage.
  * pname:pCopyImageToMemoryInfo is a pointer to a
    slink:VkCopyImageToMemoryInfoEXT structure describing the copy
    parameters.

This command is functionally similar to flink:vkCmdCopyImageToBuffer2,
except it is executed on the host and writes to host memory instead of a
buffer.
The memory of pname:pCopyImageToMemoryInfo->srcImage is accessed by the host
as if <<memory-coherent, coherent>>.

[NOTE]
.Note
====
If the device has written to the image memory, it is not automatically made
available to the host.
Before this copy command can be called, a memory barrier for this image
must: have been issued on the device with the second
<<synchronization-dependencies-scopes, synchronization scope>> including
ename:VK_PIPELINE_STAGE_HOST_BIT and ename:VK_ACCESS_HOST_READ_BIT.
====

.Valid Usage
****
  * [[VUID-vkCopyImageToMemoryEXT-hostImageCopy-09063]]
    The <<features-hostImageCopy, pname:hostImageCopy>> feature must: be
    enabled
****

include::{generated}/validity/protos/vkCopyImageToMemoryEXT.adoc[]
--

[open,refpage='VkCopyImageToMemoryInfoEXT',desc='Structure specifying parameters of an image to host memory copy command',type='structs']
--
:refpage: VkCopyImageToMemoryInfoEXT
:imageparam: srcImage
:imagesubresource: imageSubresource
:imageoffset: imageOffset
:imageextent: imageExtent
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

The sname:VkCopyImageToMemoryInfoEXT structure is defined as:

include::{generated}/api/structs/VkCopyImageToMemoryInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBitsEXT values
    describing additional copy parameters.
  * pname:srcImage is the source image.
  * pname:srcImageLayout is the layout of the source image subresources for
    the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkImageToMemoryCopyEXT
    structures specifying the regions to copy.

fname:vkCopyImageToMemoryEXT does not check whether the device memory
associated with pname:srcImage is currently in use before performing the
copy.
The application must: guarantee that any previously submitted command that
writes to the copy regions has completed before the host performs the copy.

Copy regions for the image must: be aligned to a multiple of the texel block
extent in each dimension, except at the edges of the image, where region
extents must: match the edge of the image.

.Valid Usage
****
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_single_sampled_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_not_both_image_common.adoc[]
  * [[VUID-VkCopyImageToMemoryInfoEXT-srcImageLayout-09064]]
    pname:srcImageLayout must: specify the current layout of the image
    subresources of pname:srcImage specified in pname:pRegions
  * [[VUID-VkCopyImageToMemoryInfoEXT-srcImageLayout-09065]]
    pname:srcImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyPropertiesEXT::pname:pCopySrcLayouts
  * [[VUID-VkCopyImageToMemoryInfoEXT-flags-09394]]
    If pname:flags includes ename:VK_HOST_IMAGE_COPY_MEMCPY_EXT, for each
    region in pname:pRegions, pname:memoryRowLength and
    pname:memoryImageHeight must: both be 0
****

include::{generated}/validity/structs/VkCopyImageToMemoryInfoEXT.adoc[]
--

[open,refpage='VkImageToMemoryCopyEXT',desc='Structure specifying an image to host memory copy operation',type='structs']
--
:refpage: VkImageToMemoryCopyEXT
:bufferrowlength: memoryRowLength
:bufferimageheight: memoryImageHeight

Each element of slink:VkCopyImageToMemoryInfoEXT::pname:pRegions is a
structure defined as:

include::{generated}/api/structs/VkImageToMemoryCopyEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pHostPointer is the host memory address which is the destination
    of the copy.
  * pname:memoryRowLength and pname:memoryImageHeight specify in texels a
    subregion of a larger two- or three-dimensional image in host memory,
    and control the addressing calculations.
    If either of these values is zero, that aspect of the host memory is
    considered to be tightly packed according to the pname:imageExtent.
  * pname:imageSubresource is a slink:VkImageSubresourceLayers used to
    specify the specific image subresources of the image used for the source
    or destination image data.
  * pname:imageOffset selects the initial pname:x, pname:y, pname:z offsets
    in texels of the sub-region of the source image data.
  * pname:imageExtent is the size in texels of the image to copy in
    pname:width, pname:height and pname:depth.

This structure is functionally similar to slink:VkBufferImageCopy2, except
it defines host memory as the target of copy instead of a buffer.
In particular, the same data packing rules and restrictions as that
structure apply here as well.

.Valid Usage
****
  * [[VUID-VkImageToMemoryCopyEXT-pHostPointer-09066]]
    pname:pHostPointer must: point to memory that is large enough to contain
    all memory locations that are accessed according to
    <<copies-buffers-images-addressing,Buffer and Image Addressing>>, for
    each element of pname:pRegions
  * [[VUID-VkImageToMemoryCopyEXT-pRegions-09067]]
    The union of all source regions, and the union of all destination
    regions, specified by the elements of pname:pRegions, must: not overlap
    in memory
include::{chapters}/commonvalidity/buffer_or_memory_image_copy_common.adoc[]
****

include::{generated}/validity/structs/VkImageToMemoryCopyEXT.adoc[]
--

[open,refpage='VkHostImageCopyFlagBitsEXT',desc='Bitmask specifying additional copy parameters',type='enums']
--
Bits which can: be set in slink:VkCopyMemoryToImageInfoEXT::pname:flags,
slink:VkCopyImageToMemoryInfoEXT::pname:flags, and
slink:VkCopyImageToImageInfoEXT::pname:flags, specifying additional copy
parameters are:

include::{generated}/api/enums/VkHostImageCopyFlagBitsEXT.adoc[]

  * ename:VK_HOST_IMAGE_COPY_MEMCPY_EXT specifies that no memory layout
    swizzling is to be applied during data copy.
    For copies between memory and images, this flag indicates that image
    data in host memory is swizzled in exactly the same way as the image
    data on the device.
    Using this flag indicates that the implementations may: use a simple
    memory copy to transfer the data between the host memory and the device
    memory.
    The format of the swizzled data in host memory is platform dependent and
    is not defined in this specification.
--

[open,refpage='VkHostImageCopyFlagsEXT',desc='Bitmask of VkHostImageCopyFlagBitsEXT',type='flags']
--
include::{generated}/api/flags/VkHostImageCopyFlagsEXT.adoc[]

tname:VkHostImageCopyFlagsEXT is a bitmask type for setting a mask of zero
or more elink:VkHostImageCopyFlagBitsEXT.
--
[open,refpage='vkCopyImageToImageEXT',desc='Copy image data using the host',type='protos']
--
:refpage: vkCopyImageToImageEXT

To copy data from an image object to another image object using the host,
call:

include::{generated}/api/protos/vkCopyImageToImageEXT.adoc[]

  * pname:device is the device which owns
    pname:pCopyImageToImageInfo->srcImage and
    pname:pCopyImageToImageInfo->dstImage.
  * pname:pCopyImageToImageInfo is a pointer to a
    slink:VkCopyImageToImageInfoEXT structure describing the copy
    parameters.

This command is functionally similar to flink:vkCmdCopyImage2, except it is
executed on the host.
The memory of pname:pCopyImageToImageInfo->srcImage and
pname:pCopyImageToImageInfo->dstImage is accessed by the host as if
<<memory-coherent, coherent>>.

[NOTE]
.Note
====
If the device has written to the memory of
pname:pCopyImageToImageInfo->srcImage, it is not automatically made
available to the host.
Before this copy command can be called, a memory barrier for this image
must: have been issued on the device with the second
<<synchronization-dependencies-scopes, synchronization scope>> including
ename:VK_PIPELINE_STAGE_HOST_BIT and ename:VK_ACCESS_HOST_READ_BIT.

Because queue submissions <<synchronization-submission-host-writes,
automatically make host memory visible to the device>>, there would not be a
need for a memory barrier before using the results of this copy operation in
pname:pCopyMemoryToImageInfo->dstImage on the device.
====

.Valid Usage
****
  * [[VUID-vkCopyImageToImageEXT-hostImageCopy-09068]]
    The <<features-hostImageCopy, pname:hostImageCopy>> feature must: be
    enabled
****

include::{generated}/validity/protos/vkCopyImageToImageEXT.adoc[]
--

[open,refpage='VkCopyImageToImageInfoEXT',desc='Structure specifying parameters of an image to image host copy command',type='structs']
--
:refpage: VkCopyImageToImageInfoEXT

The sname:VkCopyImageToImageInfoEXT structure is defined as:

include::{generated}/api/structs/VkCopyImageToImageInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkHostImageCopyFlagBitsEXT values
    describing additional copy parameters.
  * pname:srcImage is the source image.
  * pname:srcImageLayout is the layout of the source image subresources for
    the copy.
  * pname:dstImage is the destination image.
  * pname:dstImageLayout is the layout of the destination image subresources
    for the copy.
  * pname:regionCount is the number of regions to copy.
  * pname:pRegions is a pointer to an array of slink:VkImageCopy2 structures
    specifying the regions to copy.

fname:vkCopyImageToImageEXT does not check whether the device memory
associated with pname:srcImage or pname:dstImage is currently in use before
performing the copy.
The application must: guarantee that any previously submitted command that
writes to the copy regions has completed before the host performs the copy.

.Valid Usage
****
  * [[VUID-VkCopyImageToImageInfoEXT-srcImage-09069]]
    pname:srcImage and pname:dstImage must: have been created with identical
    image creation parameters

:imageparam: srcImage
:imagesubresource: srcSubresource
:imageoffset: srcOffset
:imageextent: extent
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]

:imageparam: dstImage
:imagesubresource: dstSubresource
:imageoffset: dstOffset
:imageextent: extent
include::{chapters}/commonvalidity/copy_memoryimage_to_imagememory_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_common.adoc[]
include::{chapters}/commonvalidity/copy_anyimage_to_imageany_no_rotation_common.adoc[]
include::{chapters}/commonvalidity/copy_bufferimage_to_imagebuffer_common.adoc[]
  * [[VUID-VkCopyImageToImageInfoEXT-srcImageLayout-09070]]
    pname:srcImageLayout must: specify the current layout of the image
    subresources of pname:srcImage specified in pname:pRegions
  * [[VUID-VkCopyImageToImageInfoEXT-dstImageLayout-09071]]
    pname:dstImageLayout must: specify the current layout of the image
    subresources of pname:dstImage specified in pname:pRegions
  * [[VUID-VkCopyImageToImageInfoEXT-srcImageLayout-09072]]
    pname:srcImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyPropertiesEXT::pname:pCopySrcLayouts
  * [[VUID-VkCopyImageToImageInfoEXT-dstImageLayout-09073]]
    pname:dstImageLayout must: be one of the image layouts returned in
    slink:VkPhysicalDeviceHostImageCopyPropertiesEXT::pname:pCopyDstLayouts
****

include::{generated}/validity/structs/VkCopyImageToImageInfoEXT.adoc[]
--
