// Copyright 2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[present-metering]]
=== Present Metering

[open,refpage='VkSetPresentConfigNV',desc='Structure specifying present metering configuration',type='structs']
--

Present Metering evenly paces out the next pname:numFramesPerBatch
flink:vkQueuePresentKHR presents.
This gives smoother pacing between presents in applications with frame
generation integrations.

The sname:VkSetPresentConfigNV structure is defined as:

include::{generated}/api/structs/VkSetPresentConfigNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:numFramesPerBatch is the number of frames to batch
  * pname:presentConfigFeedback will return the success or error status

The metering configuration applies to all swapchains in the array in
slink:VkPresentInfoKHR.
The configuration specified by sname:VkSetPresentConfigNV applies to the
next pname:numFramesPerBatch calls to flink:vkQueuePresentKHR and needs to
be updated every pname:numFramesPerBatch presents.

.Valid Usage
****
  * [[VUID-VkSetPresentConfigNV-numFramesPerBatch-10581]]
    pname:numFramesPerBatch must: not be larger than 8
****

include::{generated}/validity/structs/VkSetPresentConfigNV.adoc[]
--
