// Copyright (c) 2020-2023 Huawei Technologies Co. Ltd.
//
// SPDX-License-Identifier: CC-BY-4.0

[[drawing-cluster-culling-shading]]
== Programmable Cluster Culling Shading

In this drawing approach, cluster are generated by the cluster culling
shader stage.
It operates similarly to <<dispatch, dispatching compute>> as the shaders
make use of workgroups.

ifdef::VK_HUAWEI_cluster_culling_shader[]
[open,refpage='vkCmdDrawClusterHUAWEI',desc='Draw cluster culling work items',type='protos']
--
:refpage: vkCmdDrawClusterHUAWEI

To record a cluster culling shader drawing command, call:

include::{generated}/api/protos/vkCmdDrawClusterHUAWEI.adoc[]

  * pname:commandBuffer is the command buffer into which the command will be
    recorded.
  * pname:groupCountX is the number of local workgroups to dispatch in the X
    dimension.
  * pname:groupCountY is the number of local workgroups to dispatch in the Y
    dimension.
  * pname:groupCountZ is the number of local workgroups to dispatch in the Z
    dimension.

When the command is executed,a global workgroup consisting of
groupCountX*groupCountY*groupCountZ local workgroup is assembled.
Note that the cluster culling shader pipeline only accepts
fname:vkCmdDrawClusterHUAWEI and flink:vkCmdDrawClusterIndirectHUAWEI as
drawing commands.

.Valid Usage
****
include::{chapters}/commonvalidity/draw_common.adoc[]
include::{chapters}/commonvalidity/draw_mesh_common.adoc[]
ifdef::VK_NV_mesh_shader,VK_EXT_mesh_shader[]
  * [[VUID-vkCmdDrawClusterHUAWEI-None-07819]]
    The pname:pipelineStatistics member used to create any active
    <<queries-pipestats, Pipeline Statistics Query>> must: not contain
    ename:VK_QUERY_PIPELINE_STATISTIC_TASK_SHADER_INVOCATIONS_BIT_EXT, or
    ename:VK_QUERY_PIPELINE_STATISTIC_MESH_SHADER_INVOCATIONS_BIT_EXT
endif::VK_NV_mesh_shader,VK_EXT_mesh_shader[]
  * [[VUID-vkCmdDrawClusterHUAWEI-groupCountX-07820]]
    pname:groupCountX must: be less than or equal to
    sname:VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI::pname:maxWorkGroupCount[0]
  * [[VUID-vkCmdDrawClusterHUAWEI-groupCountY-07821]]
    pname:groupCountY must: be less than or equal to
    sname:VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI::pname:maxWorkGroupCount[1]
  * [[VUID-vkCmdDrawClusterHUAWEI-groupCountZ-07822]]
    pname:groupCountZ must: be less than or equal to
    sname:VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI::pname:maxWorkGroupCount[2]
  * [[VUID-vkCmdDrawClusterHUAWEI-ClusterCullingHUAWEI-07823]]
    The current pipeline bound to ename:VK_PIPELINE_BIND_POINT_GRAPHICS
    must: contain a shader stage using the code:ClusterCullingHUAWEI
    {ExecutionModel}
****

include::{generated}/validity/protos/vkCmdDrawClusterHUAWEI.adoc[]
--

[open,refpage='vkCmdDrawClusterIndirectHUAWEI',desc='Issue an indirect cluster culling draw into a command buffer',type='protos']
--
:refpage: vkCmdDrawClusterIndirectHUAWEI

To record an indirect cluster culling drawing command, call:

include::{generated}/api/protos/vkCmdDrawClusterIndirectHUAWEI.adoc[]

  * pname:commandBuffer is the command buffer into which the command is
    recorded.
  * pname:buffer is the buffer containing draw parameters.
  * pname:offset is the byte offset into pname:buffer where parameters
    begin.

fname:vkCmdDrawClusterIndirectHUAWEI behaves similarly to
flink:vkCmdDrawClusterHUAWEI except that the parameters are read by the
device from a buffer during execution.
The parameters of the dispatch are encoded in a
slink:VkDispatchIndirectCommand structure taken from buffer starting at
offset.Note the cluster culling shader pipeline only accepts
flink:vkCmdDrawClusterHUAWEI and fname:vkCmdDrawClusterIndirectHUAWEI as
drawing commands.

.Valid Usage
****
include::{chapters}/commonvalidity/draw_common.adoc[]
include::{chapters}/commonvalidity/draw_mesh_common.adoc[]
include::{chapters}/commonvalidity/draw_indirect_drawcount.adoc[]
  * [[VUID-vkCmdDrawClusterIndirectHUAWEI-ClusterCullingHUAWEI-07824]]
    The current pipeline bound to ename:VK_PIPELINE_BIND_POINT_GRAPHICS
    must: contain a shader stage using the code:ClusterCullingHUAWEI
    {ExecutionModel}.
  * [[VUID-vkCmdDrawClusterIndirectHUAWEI-offset-07918]]
    pname:offset must: be a multiple of
    slink:VkPhysicalDeviceClusterCullingShaderPropertiesHUAWEI::pname:indirectBufferOffsetAlignment
****

include::{generated}/validity/protos/vkCmdDrawClusterIndirectHUAWEI.adoc[]
--
endif::VK_HUAWEI_cluster_culling_shader[]
