// Copyright 2022-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Vulkan Documentation

include::{config}/attribs.adoc[]
include::{generated}/specattribs.adoc[]

== About

Welcome the the official Vulkan Documentation site. This is your starting point 
for all things related to the https://www.vulkan.org[Vulkan] low-level graphics
api. It combines different ecosystem documentation components into a convenient
single site, meaning information is linked between these components and can
easily be discovered using the global search.

== Navigate this site

The site is organized in "`components`". The left navigation sidebar links to 
pages in the current component. The bottom-left button switches between components.

The top navigation has links to all "`components`" and related external docmentation.
It also allows for searching within this site. If the "`In this component`" box is
checked, search will be restricted to the current component. Otherwise, all components 
of the site are searched.

On pages with multiple sections, a right navigation sidebar links to sections in the 
current page.

== What's included

=== Vulkan specification

=== Vulkan feature descriptions

=== Vulkan guide

=== Vulkan samples

=== Vulkan tutorial

== How to get started with Vulkan

=== Requirements

=== Vulkan SDK

== Getting help

== Versioning

This build of the site includes the Vulkan {SPECREVISION} API specification
{APITITLE}, generated on {SPECDATE} {SPECREMARK}.

== Feedback

If you need to report a problem or want tobuild the site yourself, start with the
link:https://github.com/KhronosGroup/Vulkan-Site/[Vulkan-Site] repository on
GitHub.
