// Copyright 2022-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Vulkan Documentation

include::{config}/attribs.adoc[]
include::{generated}/specattribs.adoc[]


== About

link:https://docs.vulkan.org/[This site] gathers together several key Vulkan
documents including specifications, extension proposals, guides, tutorials
and samples into a single site.
This allows searching and cross-linking across documents, to help navigate
quickly to the information you need for developing Vulkan-based
applications.

For more information about and resources for using the Vulkan graphics API,
see the Vulkan developer website at https://vulkan.org .

This build of the site includes the Vulkan {SPECREVISION} API specification
{APITITLE}, generated on {SPECDATE} {SPECREMARK}.


== Navigation

The site is organized in "`components`" (Antora terminology for
specifications and other documents), each containing many "`pages`" (Antora
terminology for a chapter of a specification, or other distinct piece of
content for other components).

The left navigation sidebar links to pages in the current component.

The right navigation sidebar links to sections in the current page.

The bottom-left button switches between components.

The top navigation bar contains a text searchbox.
If the "`In this component`" box is checked, search will be restricted to
the current component.
Otherwise, all components of the site are searched.


== Site Information

link:https://docs.vulkan.org/[This site] is generated using the
link:https://docs.antora.org/[Antora] static site generator.

If you need to report a problem or build the site yourself, start with the
link:https://github.com/KhronosGroup/Vulkan-Site/[Vulkan-Site] repository on
GitHub.
