// Copyright 2022-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

= Vulkan Documentation

include::{config}/attribs.adoc[]
include::{generated}/specattribs.adoc[]

== About

Welcome the the official Documentation site for the cross-platform Vulkan graphics
api. This is your starting point for all things related to https://www.vulkan.org[Vulkan].
It combines multiple ecosystem documentation components into a convenient
single site, meaning information is linked between these components and can
easily be discovered using the global search.

== Navigate this site

The site is organized into "`components`". The left navigation sidebar links to 
pages in the current component. The bottom-left button switches between components.

The top navigation has links to all "`components`" and related external documentation.
It also allows for searching within this site. If the "`In this component`" box is
checked, search will be restricted to the current component. Otherwise, all components 
of the site are searched.

On pages with multiple sections, a right navigation sidebar links to sections in the 
current page.

== What's included

=== Vulkan specification

xref:spec:introduction.adoc[The Vulkan specification] describes the Vulkan Application Programming Interface (API). Vulkan is a C99 API designed for explicit control of low-level graphics and compute functionality.

The specification is aimed at implementors of Vulkan and at developers that already know the basics of Vulkan and want to read up on more advanced topics.

=== Vulkan feature descriptions

xref:features:index.adoc[The Vulkan feature descriptions] include extension documents that
are written outlining the proposed API for new extensions. They are the base for the
final extension specification and contain supplementary documentation. 

It is closely related to the Vulkan specification and can help to understand
why an extension or a feature have been implemented in a certain way.

=== Vulkan guide

xref:guide:index.adoc[The Vulkan Guide] is designed to help developers get up and going with the world of Vulkan. It is aimed to be a light read that leads to many other useful links depending on what a developer is looking for. All information is intended to help better fill the gaps about the many nuances of the Vulkan ecosystem including peripheral topics like shading languages.

The Guide is a good starting point for first time Vulkan developers.

=== Vulkan samples

xref:samples:index.adoc[The Vulkan Samples] are a collection of resources to help you develop optimized Vulkan applications. These C++ samples demonstrate a wide range of Vulkan's functionality. From writing a first "Hello triangle" sample to rendering complex scenes, doing GPU based work and using hardware accelerated ray tracing, these samples are trying to help developers learn how to use Vulkan.

=== Vulkan tutorial

xref:tutorial:index.adoc[The Vulkan tutorial] will teach you the basics of using Vulkan. It'll help you get started with the API and teaches you how to get your first graphics and compute programs up and running using the C++ programming language.

The Tutorial is aimed at people starting with Vulkan. If you are new to Vulkan, this should be your starting point.

=== GLSL documentation

Although Vulkan consumes shaders in SPIR-V, one of the most widely used shading languages is xref:glsl:index.adoc[GLSL]. This part of the documentation site contains the GLSL shading language specification with Vulkan specific extensions.

== How to get started with Vulkan

=== Requirements

Vulkan is a available on a xref:guide:platforms.adoc[wide range of platforms]. To develop with it, you first need an implementation that supports Vulkan. Most systems nowadays support Vulkan out of the box, as support ships via graphics cards drivers.

For actually writing code that uses Vulkan, you need bindings for your programming language like the https://github.com/KhronosGroup/Vulkan-Headers[C bindings] (that also work with C++) or the https://github.com/KhronosGroup/Vulkan-Hpp[C{pp} bindings] that offers a C{pp} based interface to the API.

=== Vulkan SDK

While not a requirement for developing Vulkan application, the https://www.lunarg.com/vulkan-sdk/[LunarG Vulkan SDK] is a convenient package of components and tools to help with developing Vulkan applications. Using the SDK is recommended.

=== First Vulkan program

The https://vulkan.lunarg.com/doc/sdk/1.4.309.0/windows/getting_started.html[Vulkan SDK] contains C and C{pp} project templates for Microsoft Visual Studio that can be used as a starting point for writing Vulkan programs.

Another option is to follow the xref:tutorial:02_Development_environment.adoc[development environment chapter] of the xref:tutorial:index.adoc[The Vulkan tutorial] which has instructions for different platforms.

As a third option, the xref:samples:index.adoc[The Vulkan Samples] come with build system that supports different platforms and C++ based development environments.

== Getting help

== Versioning

This build of the site includes the Vulkan {SPECREVISION} API specification
{APITITLE}, generated on {SPECDATE} {SPECREMARK}.

== Feedback

If you need to report a problem or want to build the site yourself, start with the
link:https://github.com/KhronosGroup/Vulkan-Site/[Vulkan-Site] repository on
GitHub.
