// Copyright 2015-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[appendix]
[[deprecation]]
= Deprecation

Functionality in the specification such as commands and structures may: be
marked as deprecated, indicating that applications should: avoid using it.
A link to an explanatory section will be provided to explain how and why the
functionality was deprecated, what functionality replaces it (if any), and
what applications should: do instead.
Reasons for deprecating functionality may: include:

  * Newer functionality fulfills the same role
  * Does not work as originally intended
  * Functionality cannot continue to work with newer features

[NOTE]
====
Deprecation is tagged in the xml registry, with both core versions and
extensions able to express deprecation of any other interface.
All deprecations will be listed in this section, however only functionality
deprecated by a core version that is present will be emphasized with
warnings.
====

Deprecated functionality is *not* removed from the specification, such that
older applications will continue to run on the same API for its lifetime.
Applications may: wish to avoid deprecated functionality in favor of other
solutions.
Interactions with deprecated functionality will often be omitted when new
extensions or features are developed, so deprecated functionality may not
work with the latest features.

[NOTE]
====
Extensions can be deprecated in their entirety by a different mechanism, and
are marked as deprecated in their appendix.
See <<extendingvulkan-compatibility-deprecation, the Deprecation section of
the Extensions chapter>> for more information.
====


== Deprecated Functionality

When functionality is deprecated, an explanation of its deprecation will be
added to the below sections.

ifdef::VKSC_VERSION_1_0[]
This section is currently empty for Vulkan SC.
endif::VKSC_VERSION_1_0[]
ifndef::VKSC_VERSION_1_0[]
[NOTE]
====
This list is a work in progress - we intend to add other items to this
section over time; things such as shader modules (deprecated by
apiext:VK_KHR_maintenance5) and anything superseded by a new version of the
same functionality (e.g. apiext:VK_KHR_synchronization2).
====

ifdef::VK_VERSION_1_1[]
[[deprecation-gpdp2]]
=== Physical Device Queries: Deprecation via version 2

apiext:VK_KHR_get_physical_device_properties2 was incorporated into Vulkan
1.1, which introduced new versions of several physical device query
functions.
These provide the same functionality as the Vulkan 1.0 functionality but
with greater extensibility.

When querying device features, flink:vkGetPhysicalDeviceFeatures2 should: be
used instead of flink:vkGetPhysicalDeviceFeatures.
When enabling device features, slink:VkPhysicalDeviceFeatures2 should: be
provided in the pname:pNext chain of slink:VkDeviceCreateInfo instead of
using slink:VkDeviceCreateInfo::pNext:pEnabledFeatures.
endif::VK_VERSION_1_1[]

[[deprecation-version-macros]]
=== Version Macros: Deprecation via replacements including API variant

The version macros that do not take the API variant into account, such as
dlink:VK_MAKE_VERSION or dlink:VK_VERSION_MAJOR, are deprecated by those
that do, such as dlink:VK_MAKE_API_VERSION or dlink:VK_API_VERSION_MAJOR.

Instead of dlink:VK_API_VERSION, specific version defines (e.g.
dlink:VK_API_VERSION_1_0) or the dlink:VK_MAKE_API_VERSION macro should be
used instead.

[[deprecation-devicelayers]]
=== Device Layers: Deprecation via instance layers

Previous versions of this specification distinguished between instance and
device layers.
Instance layers were only able to intercept commands that operate on
sname:VkInstance and sname:VkPhysicalDevice, except they were not able to
intercept flink:vkCreateDevice.
Device layers were enabled for individual devices when they were created,
and could only intercept commands operating on that device or its child
objects.

Device-only layers are now deprecated, and this specification no longer
distinguishes between instance and device layers.
Layers are enabled during instance creation, and are able to intercept all
commands operating on that instance or any of its child objects.
At the time of deprecation there were no known device-only layers and no
compelling reason to create one.

ifdef::VK_VERSION_1_2[]
[[deprecation-renderpass2]]
=== Render Pass Functions: Deprecation via version 2

apiext:VK_KHR_create_renderpass2 was incorporated into Vulkan 1.2, which
introduced new versions of several render pass functions.
These provide the same functionality as the Vulkan 1.0 functionality but
with greater extensibility.

ifdef::VK_VERSION_1_4[]
[NOTE]
====
Render pass objects and all related commands are further
<<deprecation-dynamicrendering, deprecated by dynamic rendering>> in Vulkan
1.4.
====
endif::VK_VERSION_1_4[]
endif::VK_VERSION_1_2[]

ifdef::VK_VERSION_1_4[]
=== [[deprecation-dynamicrendering]]Render Pass Objects: Deprecation via dynamic rendering

In Vulkan 1.3, the apiext:VK_KHR_dynamic_rendering extension was promoted
into core, which added a new way to specify render passes without needing to
create slink:VkFramebuffer and slink:VkRenderPass objects.
However, subpass functionality had no equivalent, meaning dynamic rendering
was only suitable as a substitute for content not using subpasses.

In Vulkan 1.4 however, apiext:VK_KHR_dynamic_rendering_local_read was
promoted into core as well, which allows the expression of most subpass
functionality in core or extensions.
Any subpass functionality which was not replicated is still expressible but
requires applications to split work over multiple dynamic render pass
instances.
Functionality not covered with local reads would result in most or all
vendors splitting the subpass internally.

[NOTE]
====
apiext:VK_QCOM_render_pass_shader_resolve does not have equivalent
functionality exposed via dynamic rendering.
Use of deprecated functionality will be required to use that extension
unless/until replacements are created.
====

Outside of vendor extensions, applications are advised to make use of
flink:vkCmdBeginRendering and flink:vkCmdEndRendering to manage render
passes from this API version onward.
endif::VK_VERSION_1_4[]
endif::VKSC_VERSION_1_0[]
