// Copyright (c) 2021 Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_AMD_shader_early_and_late_fragment_tests.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-09-14
*Interactions and External Dependencies*::
  - This extension requires
    {spirv}/AMD/SPV_AMD_shader_early_and_late_fragment_tests.html[`SPV_AMD_shader_early_and_late_fragment_tests`]
  - This extension interacts with `apiext:VK_EXT_shader_stencil_export`
*Contributors*::
  - Tobias Hector, AMD

=== Description

This extension adds support for the
{spirv}/AMD/SPV_AMD_shader_early_and_late_fragment_tests.html[`SPV_AMD_shader_early_and_late_fragment_tests`]
extension, allowing shaders to explicitly opt in to allowing both early
_and_ late fragment tests with the code:EarlyAndLateFragmentTestsAMD
execution mode.

ifdef::VK_EXT_shader_stencil_export[]
If `apiext:VK_EXT_shader_stencil_export` is supported, additional execution
modes allowing early depth tests similar to code:DepthUnchanged,
code:DepthLess, and code:DepthGreater are provided.
endif::VK_EXT_shader_stencil_export[]

include::{generated}/interfaces/VK_AMD_shader_early_and_late_fragment_tests.adoc[]

=== Version History

  * Revision 1, 2021-09-14 (Tobias Hector)
  ** Initial draft
