// Copyright (c) 2024-2025 Arm Ltd.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_ARM_performance_counters_by_region.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-09-09
*IP Status*::
    No known IP claims.
*Contributors*::
  - Jan-Harald Fredriksen, Arm Ltd.
  - Lisa Wu, Arm Ltd.
  - Ting Wei, Arm Ltd.
  - Nikunj Patel, Arm Ltd.
  - Peter Harris, Arm Ltd.
  - Camden Mannett, Arm Ltd.

=== Description

This extension provides the ability to capture performance counters per
region ('tile').

It exposes an enumeration of the available counters, and a way to request
counters to be captured per render pass instance.

include::{generated}/interfaces/VK_ARM_performance_counters_by_region.adoc[]

=== Issues

[[appendix-performance-counters-by-region-security]]
==== What is the security model of this extension?

*RESOLVED*

The GPU hardware is able to run workloads from multiple applications
concurrently.
This introduces the possibility of side-channel leaks where one process can
observe the side effects (e.g., memory pressure) of work done in another
process.

To prevent such leaks when using this extension, the following is
guaranteed:

 . Command buffers that capture performance counters are automatically
   executed in an "`exclusive mode`", meaning that they do not run
   concurrently with workloads from any other process.
 . The physical device, at the level of hardware and firmware, guarantees
   that performance counters are only captured in "`exclusive mode`", and
   otherwise returns zero for all counters.

Additionally, this performance counter mechanism only exposes shader core
counters.
Counters related to the external memory system or interactions between
external memory and L2 caches are not available.

=== Version History

  * Revision 1, 2025-09-09 (Jan-Harald Fredriksen)
  ** Initial draft.
