// Copyright (c) 2022-2025 Arm Ltd.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_ARM_data_graph.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-06-18
*Interactions and External Dependencies*::
  - This extension requires {spirv}/EXT/SPV_ARM_graph.html[`SPV_ARM_graph`]
  - This extension interacts with `apiext:VK_EXT_mutable_descriptor_type`
  - This extension interacts with `apiext:VK_EXT_pipeline_protected_access`
  - This extension interacts with `apiext:VK_ARM_tensors`
  - This extension interacts with `apiext:VK_EXT_descriptor_buffer`
  - This extension interacts with `apiext:VK_KHR_maintenance6`
*IP Status*::
    No known IP claims.
*Contributors*::
  - Kévin Petit, Arm Ltd.
  - Emma Ben Yossef, Arm Ltd.
  - Stefano Bucciarelli, Arm Ltd.
  - Marco Cattani, Arm Ltd.
  - Aaron DeBattista, Arm Ltd.
  - Jan-Harald Fredriksen, Arm Ltd.
  - Einar Hov, Arm Ltd.
  - Robert Hughes, Arm Ltd.
  - Oualid Khelifi, Arm Ltd.
  - Derek Lamberti, Arm Ltd.
  - Chetan Mistry, Arm Ltd.
  - Georgios Teneketzis, Arm Ltd.

=== Description

This extension adds support for a new type of pipeline, data graph
pipelines, that provide an encapsulation construct for computational graphs
operating on full resources (e.g. ML/AI graphs, image processing pipelines,
etc).
This extension only supports tensor resources and does not define any
operations that can be used within those graphs.
These operations will be defined by separate extensions.

include::{generated}/interfaces/VK_ARM_data_graph.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-GraphARM,GraphARM>>

=== Issues

1) Should graph pipeline resource info structures be integrated into
   pipeline layouts? Would a new graph pipeline layout be a better fit?

*RESOLVED*: Graph pipeline resource info are passed separately at pipeline
creation time.

2) Do we need a new shader stage for graph pipelines for use in creating
descriptor set layouts?

*RESOLVED*: Currently using ename:VK_SHADER_STAGE_ALL.

3) Should this extension provide applications with a way of knowing which
   combinations of sparsity information implementations can take advantage
   of when processing graph constants?

*RESOLVED*: No.
Describing the exact combinations is in some cases complex and it is always
valid for implementations to ignore the sparsity information and treat the
data as dense.
Specific implementations can provide guidance to application writers if they
so desire and applications are encouraged to always provide sparsity
information that they have.

=== Version History

  * Revision 1, 2025-06-18 (Kévin Petit)
  ** Initial revision
