// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_extended_dynamic_state2.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-04-12
*IP Status*::
    No known IP claims.
*Contributors*::
  - Vikram Kushwaha, NVIDIA
  - Piers Daniell, NVIDIA
  - Jeff Bolz, NVIDIA

=== Description

This extension adds some more dynamic state to support applications that
need to reduce the number of pipeline state objects they compile and bind.

include::{generated}/interfaces/VK_EXT_extended_dynamic_state2.adoc[]

=== Promotion to Vulkan 1.3

This extension has been partially promoted.
The dynamic state enumerants ename:VK_DYNAMIC_STATE_DEPTH_BIAS_ENABLE_EXT,
ename:VK_DYNAMIC_STATE_PRIMITIVE_RESTART_ENABLE_EXT, and
ename:VK_DYNAMIC_STATE_RASTERIZER_DISCARD_ENABLE_EXT; and the corresponding
entry points in this extension are included in core Vulkan 1.3, with the EXT
suffix omitted.
The enumerants and entry points for dynamic logic operation and patch
control points are not promoted, nor is the feature structure.
Extension interfaces that were promoted remain available as aliases of the
core functionality.

=== Version History

  * Revision 1, 2021-04-12 (Vikram Kushwaha)
  ** Internal revisions
