// Copyright (c) 2020 Simon Ser
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_physical_device_drm.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-11-07
*IP Status*::
    No known IP claims.
*Contributors*::
  - Simon Ser

=== Description

This extension provides new facilities to query DRM properties for physical
devices, enabling users to match Vulkan physical devices with DRM nodes on
Linux.

Its functionality closely overlaps with
`EGL_EXT_device_drm`^<<VK_EXT_physical_device_drm-fn1,1>>^.
Unlike the EGL extension, this extension does not expose a string containing
the name of the device file and instead exposes device minor numbers.

DRM defines multiple device node types.
Each physical device can only be associated with a single underlying DRM
device, which has one primary node and may have one render node.

A physical device always has the primary node if it is associated with a DRM
device. It may have no render node if e.g. it uses a software rendering engine.

To query DRM properties for a physical device, chain
slink:VkPhysicalDeviceDrmPropertiesEXT to slink:VkPhysicalDeviceProperties2.

[NOTE]
====
This extension only returns the primary node and render node from the same
DRM device for a Vulkan physical device. Implementations should not return the
primary node and render node from different DRM devices.
====

include::{generated}/interfaces/VK_EXT_physical_device_drm.adoc[]

=== References

  . [[VK_EXT_physical_device_drm-fn1]]
    https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_drm.txt[`EGL_EXT_device_drm`]

=== Version History

  * Revision 2, 2024-11-07
  ** Clarification about the meaning of the primary node
  ** Clarification to not advertise more than one DRM device

  * Revision 1, 2021-06-09
  ** First stable revision
