// Copyright 2021-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_image_view_min_lod.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-11-09
*IP Status*::
    No known IP claims.
*Contributors*::
  - Joshua Ashton, Valve
  - Hans-Kristian Arntzen, Valve
  - Samuel Iglesias Gonsalvez, Igalia
  - Tobias Hector, AMD
  - Faith Ekstrand, Intel
  - Tom Olson, ARM

=== Description

This extension allows applications to clamp the minimum LOD value during
<<textures-image-level-selection,Image Level(s) Selection>>,
<<textures-gather,Texel Gathering>> and
<<textures-integer-coordinate-operations,Integer Texel Coordinate
Operations>> with a given slink:VkImageView by
slink:VkImageViewMinLodCreateInfoEXT::pname:minLod.

This extension may be useful to restrict a slink:VkImageView to only mips
which have been uploaded, and the use of fractional pname:minLod can be
useful for smoothly introducing new mip levels when using linear mipmap
filtering.

include::{generated}/interfaces/VK_EXT_image_view_min_lod.adoc[]

=== Version History

  * Revision 1, 2021-07-06 (Joshua Ashton)
  ** Initial version
