// Copyright 2024-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_shader_ocp_microscaling_types.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-04-29
*IP Status*::
    No known IP claims.
*Contributors*::
  - Kévin Petit, Arm Ltd.
  - Vikram Tarikere, Imagination Technologies
  - Jeff Bolz, NVIDIA
  - Craig Graham, Samsung

=== Description

This extension enables support for the floating-point data types defined in
the Open Compute Project (OCP) Microscaling Formats specification.

include::{generated}/interfaces/VK_EXT_shader_ocp_microscaling_types.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-Float4EXT,Float4EXT>>
  * <<spirvenv-capabilities-table-Float6EXT,Float6EXT>>
  * <<spirvenv-capabilities-table-Float8UnsignedE8M0EXT,Float8UnsignedE8M0EXT>>
  * <<spirvenv-capabilities-table-MXInt8EXT,MXInt8EXT>>
  * <<spirvenv-capabilities-table-BitcastExtractEXT,BitcastExtractEXT>>

=== Issues

1) How does this extension add support for microscaling?

*RESOLVED*: It does not directly do so.
This extension just introduces basic support for the data types used for
microscaling but it does not add any support for microscaled tensors or
operations on microscaled data.
Reading miscroscaled data and converting it to other formats such as FP16 or
FP32 can be implemented in shaders with the new types provided by this
extension but these new types cannot for example be used directly in matrix
multiplication operations.

2) What conversions to/from the newly-added types should be supported?

*RESOLVED*: This extension will only add conversions from the newly-added
types to a restricted list of existing larger floating-point types.
Conversions from existing types to the newly-added types would require
complex logic and are not expected to be as useful.
Conversions between integer types and the newly-added types are not expected
to be generally useful either.


=== Version History

  * Revision 1, 2026-04-29 (Kévin Petit)
  ** Initial draft
