// Copyright 2022-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_pipeline_protected_access.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-07-28
*Contributors*::
  - Shahbaz Youssefi, Google
  - Jörg Wagner, Arm
  - Ralph Potter, Samsung
  - Daniel Koch, NVIDIA

=== Description

This extension allows protected memory access to be specified per pipeline
as opposed to per device.
Through the usage of this extension, any performance penalty paid due to
access to protected memory will be limited to the specific pipelines that
make such accesses.

include::{generated}/interfaces/VK_EXT_pipeline_protected_access.adoc[]

=== Promotion to Vulkan 1.4

Functionality in this extension is included in core Vulkan 1.4 with the EXT
suffix omitted.
The original type, enum and command names are still available as aliases of
the core functionality.

=== Version History

  * Revision 1, 2022-07-28 (Shahbaz Youssefi)
  ** Internal revisions
