// Copyright 2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_present_mode_fifo_latest_ready.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-05-28
*IP Status*::
    No known IP claims.
*Contributors*::
  - James Jones, NVIDIA
  - Lionel Duc, NVIDIA

=== Description

This device extension adds a new present mode,
ename:VK_PRESENT_MODE_FIFO_LATEST_READY_EXT.

This tear-free present mode behaves much like
ename:VK_PRESENT_MODE_FIFO_KHR, except that each vertical blanking period
dequeues consecutive present requests until the latest ready is found to
update the current image.

While this seems similar in concept to ename:VK_PRESENT_MODE_MAILBOX_KHR,
the fundamental difference is that the processing of the present requests is
done during vblank.
From the application perspective, this means for example, that in a
flip-based model, a single vblank may: cause multiple swapchain images to be
released at once, while ename:VK_PRESENT_MODE_MAILBOX_KHR may: continuously
be releasing images as new requests become ready.

This additional present mode is useful when using a time-based present API.

include::{generated}/interfaces/VK_EXT_present_mode_fifo_latest_ready.adoc[]

=== Version History

  * Revision 1, 2024-05-28 (Lionel Duc)
  ** Internal revisions
