// Copyright (c) 2020 Simon Ser
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_physical_device_drm.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-06-09
*IP Status*::
    No known IP claims.
*Contributors*::
  - Simon Ser

=== Description

This extension provides new facilities to query DRM properties for physical
devices, enabling users to match Vulkan physical devices with DRM nodes on
Linux.

Its functionality closely overlaps with
`EGL_EXT_device_drm`^<<VK_EXT_physical_device_drm-fn1,1>>^.
Unlike the EGL extension, this extension does not expose a string containing
the name of the device file and instead exposes device minor numbers.

DRM defines multiple device node types.
Each physical device can only be associated with a single underlying DRM
device, which may have one primary node and one render node.

Physical devices may have no primary node (e.g. it is not associated with a
DRM device) or may have no render node (e.g. if it uses a software rendering
engine), or may have neither (e.g. if it is a software rendering engine not
associated with any DRM device).

Note: This extension only returns primary node and render node from the same
DRM device for a Vulkan physical device. Implementations should not return
primary node and render node from different DRM devices.

To query DRM properties for a physical device, chain
slink:VkPhysicalDeviceDrmPropertiesEXT to slink:VkPhysicalDeviceProperties2.

include::{generated}/interfaces/VK_EXT_physical_device_drm.adoc[]

=== References

  . [[VK_EXT_physical_device_drm-fn1]]
    https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_drm.txt[`EGL_EXT_device_drm`]

=== Version History

  * Revision 2, 2024-11-07
  ** Clarification about the meaning of the primary node
  ** Clarification to not advertise more than one DRM device

  * Revision 1, 2021-06-09
  ** First stable revision
