// Copyright 2019-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_texel_buffer_alignment.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2019-06-06
*IP Status*::
    No known IP claims.
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

This extension adds more expressive alignment requirements for uniform and
storage texel buffers.
Some implementations have single texel alignment requirements that cannot be
expressed via
slink:VkPhysicalDeviceLimits::pname:minTexelBufferOffsetAlignment.

include::{generated}/interfaces/VK_EXT_texel_buffer_alignment.adoc[]

=== Promotion to Vulkan 1.3

Functionality in this extension is included in core Vulkan 1.3, with the EXT
suffix omitted.
However, only the properties structure is promoted.
The feature structure is not promoted and pname:texelBufferAlignment is
enabled if using a Vulkan 1.3 instance.
The original type name is still available as an alias of the core
functionality.

=== Version History

  * Revision 1, 2019-06-06 (Jeff Bolz)
  ** Initial draft
