// Copyright (c) 2018-2026 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_shader_subgroup_partitioned.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-11-12
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/nv/GL_NV_shader_subgroup_partitioned.txt[`GL_NV_shader_subgroup_partitioned`]
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

This extension enables support for a new class of
<<shaders-group-operations, group operations>> on <<shaders-scope-subgroup,
subgroups>> via the
{GLSLregistry}/nv/GL_NV_shader_subgroup_partitioned.txt[`GL_NV_shader_subgroup_partitioned`]
GLSL extension and
{spirv}/EXT/SPV_EXT_shader_subgroup_partitioned.html[`SPV_EXT_shader_subgroup_partitioned`]
SPIR-V extension.
Support for these new operations is advertised via the
ename:VK_SUBGROUP_FEATURE_PARTITIONED_BIT_EXT bit.
Note that there is not a new GLSL extension since
`SPV_EXT_shader_subgroup_partitioned` is compatible with
`SPV_NV_shader_subgroup_partitioned`, so the
`GL_NV_shader_subgroup_partitioned` GLSL extension can still be used.

This extension requires Vulkan 1.1, for general subgroup support.

include::{generated}/interfaces/VK_EXT_shader_subgroup_partitioned.adoc[]

=== Version History

  * Revision 1, 2025-11-12 (Jeff Bolz)
  ** Promoted from `apiext:VK_NV_shader_subgroup_partitioned`
