// Copyright 2017-2022 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_device_fault.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-03-10
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ralph Potter, Samsung
  - Stuart Smith, AMD
  - Jan-Harald Fredriksen, ARM
  - Mark Bellamy, ARM
  - Andrew Ellem, Google
  - Alex Walters, IMG
  - Jeff Bolz, NVIDIA
  - Baldur Karlsson, Valve

=== Description

Device loss can be triggered by a variety of issues, including invalid API
usage, implementation errors, or hardware failures.

This extension introduces a new command: flink:vkGetDeviceFaultInfoEXT,
which may be called subsequent to a ename:VK_ERROR_DEVICE_LOST error code
having been returned by the implementation.
This command allows developers to query for additional information on GPU
faults which may have caused device loss, and to generate binary crash
dumps, which may be loaded into external tools for further diagnosis.

include::{generated}/interfaces/VK_EXT_device_fault.adoc[]

=== Version History

  * Revision 2, 2023-04-05 (Ralph Potter)
  ** Restored two missing members to the XML definition of
     VkDeviceFaultVendorBinaryHeaderVersionOneEXT.
     No functional change to the specification.
  * Revision 1, 2020-10-19 (Ralph Potter)
  ** Initial revision
