// Copyright 2019-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_shader_demote_to_helper_invocation.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2019-06-01
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/ext/GLSL_EXT_demote_to_helper_invocation.txt[`GL_EXT_demote_to_helper_invocation`]
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

This extension adds Vulkan support for the
{spirv}/EXT/SPV_EXT_demote_to_helper_invocation.html[`SPV_EXT_demote_to_helper_invocation`]
SPIR-V extension.
That SPIR-V extension provides a new instruction
code:OpDemoteToHelperInvocationEXT allowing shaders to "`demote`" a fragment
shader invocation to behave like a helper invocation for its duration.
The demoted invocation will have no further side effects and will not output
to the framebuffer, but remains active and can participate in computing
derivatives and in <<shaders-group-operations, group operations>>.
This is a better match for the "`discard`" instruction in HLSL.

include::{generated}/interfaces/VK_EXT_shader_demote_to_helper_invocation.adoc[]

=== New SPIR-V Capability

  * <<spirvenv-capabilities-table-DemoteToHelperInvocationEXT,
    code:DemoteToHelperInvocationEXT>>

=== Promotion to Vulkan 1.3

Functionality in this extension is included in core Vulkan 1.3, with the EXT
suffix omitted.
The original type, enum and command names are still available as aliases of
the core functionality.

=== Version History

  * Revision 1, 2019-06-01 (Jeff Bolz)
  ** Initial draft
