// Copyright 2024-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_cooperative_matrix_maintenance1.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-06-05
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/ext/GLSL_EXT_cooperative_matrix_maintenance1.txt[`GLSL_EXT_cooperative_matrix_maintenance1`]
*Contributors*::
  - Jeff Bolz, NVIDIA
  - Karthik Vaidyanathan, NVIDIA
  - Matthew Netsch, Qualcomm Technologies, Inc
  - Mariusz Merecki, Intel
  - Kévin Petit, Arm Ltd.

=== Description

This extension adds several new features building on the cooperative matrix
types added in VK_KHR_cooperative_matrix.
The goal is to add and accelerate features beyond just simple GEMM kernels,
including adding support for type/use conversions, reductions, per-element
operations, and conversion of an element index to a matrix coordinate.

The new functionality is defined by the
{spirv}/EXT/SPV_EXT_cooperative_matrix_maintenance1.html[`SPV_EXT_cooperative_matrix_maintenance1`]
SPIR-V extension and can be used with the
{GLSLregistry}/ext/GLSL_EXT_cooperative_matrix_maintenance1.txt[`GLSL_EXT_cooperative_matrix_maintenance1`]
GLSL extension.

This extension also provides a new command to query the properties of
cooperative matrices, which can be easily extended by other extensions in
the future.
The new query also includes inputs for the desired subgroup size and (when
used together with extensions that support workgroup scope cooperative
matrices, such as VK_NV_cooperative_matrix2) the number of invocations in
the local workgroup, allowing implementations to expose properties that are
optimal or compatible only with specific subgroup sizes or local workgroup
sizes.

include::{generated}/interfaces/VK_EXT_cooperative_matrix_maintenance1.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-CooperativeMatrixReductionsEXT,CooperativeMatrixReductionsEXT>>
  * <<spirvenv-capabilities-table-CooperativeMatrixConversionsEXT,CooperativeMatrixConversionsEXT>>
  * <<spirvenv-capabilities-table-CooperativeMatrixPerElementOperationsEXT,CooperativeMatrixPerElementOperationsEXT>>
  * <<spirvenv-capabilities-table-CooperativeMatrixGetCoordinateEXT,CooperativeMatrixGetCoordinateEXT>>

=== Issues

=== Version History

  * Revision 1, 2025-10-14 (Jeff Bolz)
  ** Initial revision
