// Copyright 2025-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_memory_decompression.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-01-23
*Contributors*::
  - Vikram Kushwaha, NVIDIA
  - Daniel Koch, NVIDIA
  - Jeff Bolz, NVIDIA
  - Christoph Kubisch, NVIDIA
  - Piers Daniell, NVIDIA
  - Spencer Fricke, LunarG


=== Description

This extension adds support for performing memory to memory decompression.

include::{generated}/interfaces/VK_EXT_memory_decompression.adoc[]

=== Issues

1) How does an app know the minimum size that pname:decompressedSize should
be set to?

*RESOLVED*: When decompressing, data is typically processed in chunks.
For example, with GDeflate 1.0, data is streamed in 64 KB blocks, but the
final block may be smaller.
The exact size of this last block depends on the compression method and
original data size and so it must be stored in the compressed bitstream so
that the decompressor can set pname:decompressedSize correctly.
It is still ok for the last block to take up all 64 KB, but setting it too
low will cause issues and is undefined behavior.
It is a known limitation that the validation layers will not be able to
detect the minimum size of pname:decompressedSize unless it decides to
implement each decompression method specification.

=== Version History

  * Revision 1, 2025-01-23 (Daniel Koch)
  ** Initial draft
