// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_image_compression_control.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-05-02
*IP Status*::
    No known IP claims.
*Contributors*::
  - Jan-Harald Fredriksen, Arm
  - Graeme Leese, Broadcom
  - Andrew Garrard, Imagination
  - Lisa Wu, Arm
  - Peter Kohaut, Arm

=== Description

This extension enables fixed-rate image compression and adds the ability to
control when this kind of compression can be applied.
Many implementations support some form of framebuffer compression.
This is typically transparent to applications as lossless compression
schemes are used.
With fixed-rate compression, the compression is done at a defined bitrate.
Such compression algorithms generally produce results that are visually
lossless, but the results are typically not bit-exact when compared to a
non-compressed result.
The implementation may not be able to use the requested compression rate in
all cases.
This extension adds a query that can be used to determine the compression
scheme and rate that was applied to an image.

include::{generated}/interfaces/VK_EXT_image_compression_control.adoc[]

=== Version History

  * Revision 1, 2022-05-02 (Jan-Harald Fredriksen)
  ** Initial draft
