// Copyright 2022-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_legacy_dithering.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-03-31
*Contributors*::
  - Shahbaz Youssefi, Google
  - Graeme Leese, Broadcom
  - Jan-Harald Fredriksen, Arm

=== Description

This extension exposes a hardware feature used by some vendors to implement
OpenGL's dithering.
The purpose of this extension is to support layering OpenGL over Vulkan, by
allowing the layer to take advantage of the same hardware feature and
provide equivalent dithering to OpenGL applications.

include::{generated}/interfaces/VK_EXT_legacy_dithering.adoc[]

=== Version History

  * Revision 1, 2022-03-31 (Shahbaz Youssefi)
  ** Internal revisions

=== Issues

1) In OpenGL, the dither state can change dynamically.
Should this extension add a pipeline state for dither?

*RESOLVED*: No.
Changing dither state is rarely, if ever, done during rendering.
Every surveyed Android application either entirely disables dither,
explicitly enables it, or uses the default state (which is enabled).
Additionally, on some hardware dither can only be specified in a render pass
granularity, so a change in dither state would necessarily need to cause a
render pass break.
This extension considers dynamic changes in OpenGL dither state a
theoretical situation, and expects the layer to break the render pass in
such a situation without any practical downsides.
