// Copyright 2014-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_image_tiling_control.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-06-19
*Interactions and External Dependencies*::
  - Interacts with apiext:VK_KHR_maintenance4
  - Interacts with apiext:VK_KHR_maintenance5
  - Interacts with apiext:VK_EXT_image_drm_format_modifier
*IP Status*::
    No known IP claims.
*Contributors*::
  - Noah Fredriks, AMD
  - Stu Smith, AMD
  - Tobias Hector, AMD
  - Hans-Kristian Arntzen, Valve
  - Ralph Potter, Samsung
  - James Jones, NVIDIA
  - Lionel Landwerlin, Intel
  - Daniel Story, Nintendo

=== Description

This extension provides per-image selection of optimal tiling arrangements
by extending slink:VkImageCreateInfo with
slink:VkImageTilingControlCreateInfoEXT when multiple arrangements are
supported by the implementation.

ename:VK_IMAGE_TILING_CONTROL_DEFAULT_EXT can: be set to use the tiling
arrangement that is the same selection as with the
slink:VkImageTilingControlCreateInfoEXT structure omitted.

ename:VK_IMAGE_TILING_CONTROL_MIN_SIZE_EXT can: be set to minimize memory
size requirements with reduced consideration for memory access performance.

ename:VK_IMAGE_TILING_CONTROL_MAX_PERFORMANCE_EXT can: be set to maximize
memory access performance with reduced consideration for increases in memory
size requirements.

include::{generated}/interfaces/VK_EXT_image_tiling_control.adoc[]

=== Version History

  * Revision 1, 2026-06-19 (Noah Fredriks)
  ** Initial revision
