// Copyright 2020-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_ycbcr_2plane_444_formats.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-07-28
*IP Status*::
    No known IP claims.
*Contributors*::
  - Piers Daniell, NVIDIA
  - Ping Liu, Intel

=== Description

This extension adds some {YCbCr} formats that are in common use for video
encode and decode, but were not part of the
`apiext:VK_KHR_sampler_ycbcr_conversion` extension.

include::{generated}/interfaces/VK_EXT_ycbcr_2plane_444_formats.adoc[]

=== Promotion to Vulkan 1.3

This extension has been partially promoted.
The format enumerants introduced by the extension are included in core
Vulkan 1.3, with the EXT suffix omitted.
However, runtime support for these formats is optional in core Vulkan 1.3,
while if this extension is supported, runtime support is mandatory.
The feature structure is not promoted.
The original enum names are still available as aliases of the core
functionality.

=== Version History

  * Revision 1, 2020-03-08 (Piers Daniell)
  ** Initial draft
