// Copyright (c) 2021-2022 The Brenwill Workshop Ltd.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_EXT_metal_objects.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-05-28
*IP Status*::
    No known IP claims.
*Contributors*::
  - Bill Hollings, The Brenwill Workshop Ltd.
  - Dzmitry Malyshau, Mozilla Corp.

=== Description

In a Vulkan implementation that is layered on top of Metal on Apple device
platforms, this extension provides the ability to import and export the
underlying Metal objects associated with specific Vulkan objects.

As detailed in the
https://github.com/KhronosGroup/Vulkan-Docs/tree/main/proposals/VK_EXT_metal_objects.adoc[extension
proposal document], this extension adds one new Vulkan command,
flink:vkExportMetalObjectsEXT, to export underlying Metal objects from
Vulkan objects, and supports importing the appropriate existing Metal
objects when creating Vulkan objects of types slink:VkDeviceMemory,
slink:VkImage, slink:VkSemaphore, and slink:VkEvent,

The intent is that this extension will be advertised and supported only on
implementations that are layered on top of Metal on Apple device platforms.

include::{generated}/interfaces/VK_EXT_metal_objects.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2022-05-28 (Bill Hollings)
  ** Initial draft.
  ** Incorporated feedback from review by the Vulkan Working Group.
     Renamed many structures, moved import/export of MTLBuffer to
     VkDeviceMemory, added export of MTLSharedEvent, added import of
     MTLSharedEvent for VkSemaphore and VkEvent, and changed used bit mask
     fields to individual bit fields to simplify Valid Usage rules.
