// Copyright 2021-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_GOOGLE_surfaceless_query.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-08-03
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ian Elliott, Google
  - Shahbaz Youssefi, Google
  - James Jones, NVIDIA

=== Description

This extension allows the flink:vkGetPhysicalDeviceSurfaceFormatsKHR and
flink:vkGetPhysicalDeviceSurfacePresentModesKHR functions to accept
dlink:VK_NULL_HANDLE as their pname:surface parameter, allowing potential
surface formats, color spaces and present modes to be queried without
providing a surface.
Identically, flink:vkGetPhysicalDeviceSurfaceFormats2KHR,
flink:vkGetPhysicalDeviceSurfacePresentModes2EXT, and
flink:vkGetPhysicalDeviceSurfaceCapabilities2KHR would accept
dlink:VK_NULL_HANDLE in
slink:VkPhysicalDeviceSurfaceInfo2KHR::pname:surface.
*This can only be supported on platforms where the results of these queries
are surface-agnostic and a single presentation engine is the implicit target
of all present operations*.

include::{generated}/interfaces/VK_GOOGLE_surfaceless_query.adoc[]

=== Version History

  * Revision 1, 2021-12-14 (Shahbaz Youssefi)
  ** Internal revisions
  * Revision 2, 2022-08-03 (Shahbaz Youssefi)
  ** Precisions to which parts of the query responses are defined when
     surfaceless
