// Copyright 2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_extended_flags.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-12-17
*IP Status*::
    No known IP claims.
*Contributors*::
  - Andreas Süßenbach, NVIDIA
  - Daniel Koch, NVIDIA
  - Daniel Rakos, RasterGrid
  - Jon Leech, Independent
  - Matthew Netsch, QUALCOMM
  - Noah Fredriks, AMD
  - Spencer Fricke, LunarG
  - Ting Wei, ARM
  - Žiga Markuš, LunarG

=== Description

This extension adds a new elink:VkFormatFeatureFlagBits4KHR format feature
flag type, supporting up to 64 additional flags beyond those defined by
elink:VkFormatFeatureFlagBits2; and a new slink:VkFormatProperties4KHR
structure to extend slink:VkFormatProperties2.
The new structure does not replace format feature flag bits specified by
existing commands and structures, unlike slink:VkFormatProperties3.
Instead, it adds new flags to the existing APIs.
Initially, no new format flag bits are defined.

This extension also adds a new elink:VkImageCreateFlagBits2KHR image create
flag type, supporting up to 32 additional flags, and a new
slink:VkImageCreateFlags2CreateInfoKHR structure to extend
slink:VkImageCreateInfo and other commands that specify image create flag
bits.
The new structure duplicates image create flag bits specified by existing
commands and structures, while also adding up to 32 new flags.
All the existing elink:VkImageCreateFlagBits are given corresponding
elink:VkImageCreateFlagBits2KHR bits with the same meaning.
Initially, no new image create flag bits are defined.

This extension also adds a new elink:VkImageUsageFlagBits2KHR image usage
flag type, supporting up to 32 additional flags, and a new
slink:VkImageUsageFlags2CreateInfoKHR structure to extend
slink:VkImageCreateInfo and other commands that specify image usage flag
bits.
The new structure duplicates image usage flag bits specified by existing
commands and structures, while also adding up to 32 new flags.
All the existing elink:VkImageUsageFlagBits are given corresponding
elink:VkImageUsageFlagBits2KHR bits with the same meaning.
Initially, no new image usage flag bits are defined.

The extension is infrastructure used because the API is running out of
available bits in the elink:VkFormatFeatureFlagBits2 and
elink:VkImageUsageFlagBits types, and will soon thereafter run out of bits
in elink:VkImageCreateFlagBits.

Finally, this extension adds all the same 64-bit flag types first introduced
by apiext:VK_KHR_maintenance5.
This will allow API variants like Vulkan SC to support the extended flags
without requiring other, unrelated functionality of
apiext:VK_KHR_maintenance5.

include::{generated}/interfaces/VK_KHR_extended_flags.adoc[]

=== Version History

  * Revision 0.1, 2025-12-17 (Jon Leech)
  ** Initial draft
  * Revision 0.2, 2026-01-19 (Jon Leech)
  ** Add VkImageCreateFlags2KHR and import 64-bit flags types from
     VK_KHR_maintenance5.
  * Revision 0.3, 2026-02-14 (Jon Leech)
  ** Add a feature structure.
