// Copyright 2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_maintenance7.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-01-30

*Interactions and External Dependencies*::

*Contributors*::
  - Mike Blumenkrantz, Valve
  - Hans-Kristian Arntzen, Valve
  - Pan Gao, Huawei
  - Tobias Hector, AMD
  - Jon Leech, Khronos
  - Daniel Story, Nintendo
  - Shahbaz Youssefi, Google
  - Yiwei Zhang, Google
  - Matthew Netsch, Qualcomm

=== Description

apiext:VK_KHR_maintenance7 adds a collection of minor features, none of
which would warrant an entire extension of their own.

The proposed new features are as follows:

  * Add a property query to determine if a framebuffer writes to depth or
    stencil aspect does not trigger a write access in the sibling aspect.
    For example, this allows sampling stencil aspect as a texture while
    rendering to the sibling depth attachment and vice-versa given
    appropriate image layouts.
  * Add a way to query information regarding the underlying devices in
    environments where the Vulkan implementation is provided through layered
    implementations.
    For example, running on Mesa/Venus, driver ID is returned as
    ename:VK_DRIVER_ID_MESA_VENUS, but it can be necessary to know what the
    real driver under the hood is.
    The new slink:VkPhysicalDeviceLayeredApiPropertiesKHR structure can be
    used to gather information regarding layers underneath the top-level
    physical device.
  * Promote ename:VK_RENDERING_CONTENTS_INLINE_BIT_EXT and
    ename:VK_SUBPASS_CONTENTS_INLINE_AND_SECONDARY_COMMAND_BUFFERS_EXT to
    KHR
  * Add a limit to report the maximum total count of dynamic uniform buffers
    and dynamic storage buffers that can be included in a pipeline layout.
  * Require that for an unsigned integer query, the 32-bit result value
    must: be equal to the 32 least significant bits of the equivalent 64-bit
    result value.
  * Add query for robust access support when using fragment shading rate
    attachments

include::{generated}/interfaces/VK_KHR_maintenance7.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2024-01-30 (Jon Leech)
  ** Initial revision
