// Copyright 2017-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_vulkan_memory_model.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2018-12-10
*IP Status*::
    No known IP claims.
*Contributors*::
  - Jeff Bolz, NVIDIA
  - Alan Baker, Google
  - Tobias Hector, AMD
  - David Neto, Google
  - Robert Simpson, Qualcomm Technologies, Inc.
  - Brian Sumner, AMD

=== Description

The apiext:VK_KHR_vulkan_memory_model extension allows use of the features
guarded by the code:VulkanMemoryModel, code:VulkanMemoryModelDeviceScope,
and code:VulkanMemoryModelAvailabilityVisibilityChains capabilities in
shader modules.
The <<memory-model,Vulkan Memory Model>> formally defines how to synchronize
memory accesses to the same memory locations performed by multiple shader
invocations.

[NOTE]
====
Version 3 of the spec added a member
(pname:vulkanMemoryModelAvailabilityVisibilityChains) to
slink:VkPhysicalDeviceVulkanMemoryModelFeaturesKHR, which is an incompatible
change from version 2.
====

=== Promotion to Vulkan 1.2

All functionality in this extension is included in core Vulkan 1.2, with the
KHR suffix omitted.
However, if Vulkan 1.2 is supported and this extension is not, the
code:vulkanMemoryModel capability is optional.
The original type, enum and command names are still available as aliases of
the core functionality.

include::{generated}/interfaces/VK_KHR_vulkan_memory_model.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-VulkanMemoryModel,
    code:VulkanMemoryModelKHR>>

=== Version History

  * Revision 1, 2018-06-24 (Jeff Bolz)
  ** Initial draft
  * Revision 3, 2018-12-10 (Jeff Bolz)
  ** Add vulkanMemoryModelAvailabilityVisibilityChains member to the
     VkPhysicalDeviceVulkanMemoryModelFeaturesKHR structure.
