// Copyright 2017-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_device_fault.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-03-18
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ralph Potter, Samsung
  - Craig Graham, Samsung
  - Stuart Smith, AMD
  - Jan-Harald Fredriksen, ARM
  - Mark Bellamy, ARM
  - Andrew Ellem, Google
  - Alex Walters, IMG
  - Jeff Bolz, NVIDIA
  - Baldur Karlsson, Valve
  - Adrian Ravai, Samsung
  - Peter Gal, Samsung
  - Matthew Netsch, QUALCOMM
  - Tobias Hector, AMD
  - Alan Harrison, AMD
  - Vikram Tarikere, IMG
  - Jon Leech, Khronos
  - Samuel Pitoiset, Valve

=== Description

Device loss can be triggered by a variety of issues, including invalid API
usage, implementation errors, or hardware failures.
This extension introduces two new commands:

- flink:vkGetDeviceFaultReportsKHR
- flink:vkGetDeviceFaultDebugInfoKHR

flink:vkGetDeviceFaultReportsKHR allows developers to query for additional
information on GPU faults which may have caused device loss, and to generate
binary crash dumps, which may be loaded into external tools for further
diagnosis.
Additionally this command allows developers to query for additional
information on GPU faults which were internally recovered by the
implementation.

flink:vkGetDeviceFaultReportsKHR differs from flink:vkGetDeviceFaultInfoEXT
in that it can be called at any time, is able to report faults which do not
result in ename:VK_ERROR_DEVICE_LOST and allows the caller to wait for such
an error to occur.

flink:vkGetDeviceFaultDebugInfoKHR provides a separate interface which must:
only be called when a device loss has occurred to provide extended GPU
vendor specific crash post-mortem information.

include::{generated}/interfaces/VK_KHR_device_fault.adoc[]

=== Version History

  * Revision 0, 2024-03-01 (Ralph Potter)
  ** Internal Revision
  * Revision 1, 2025-06-10 (Craig Graham)
  ** Revised API to support async fault queries.
