// Copyright 2020-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_zero_initialize_workgroup_memory.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2020-11-18
*Interactions and External Dependencies*::
  - Promoted to Vulkan 1.3 Core
*IP Status*::
    No known IP claims.
*Contributors*::
  - Alan Baker, Google
  - Jeff Bolz, Nvidia
  - Faith Ekstrand, Intel

=== Description

This extension allows the use of a null constant initializer on shader
Workgroup memory variables, allowing implementations to expose any special
hardware or instructions they may have.
Zero initialization is commonly used by applications running untrusted
content (e.g. web browsers) as way of defeating memory-scraping attacks.

include::{generated}/interfaces/VK_KHR_zero_initialize_workgroup_memory.adoc[]

=== Promotion to Vulkan 1.3

Functionality in this extension is included in core Vulkan 1.3, with the KHR
suffix omitted.
The original type, enum and command names are still available as aliases of
the core functionality.

=== Version History

  * Revision 1, 2020-11-18 (Alan Baker)
  ** Internal draft version

