// Copyright 2023-2024 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_maintenance6.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-08-03

*Interactions and External Dependencies*::
  - Interacts with `apiext:VK_EXT_robustness2`

*Contributors*::
  - Jon Leech, Khronos
  - Stu Smith, AMD
  - Mike Blumenkrantz, Valve
  - Ralph Potter, Samsung
  - James Fitzpatrick, Imagination Technologies
  - Piers Daniell, NVIDIA
  - Daniel Story, Nintendo

=== Description

apiext:VK_KHR_maintenance6 adds a collection of minor features, none of
which would warrant an entire extension of their own.

The new features are as follows:

  * slink:VkBindMemoryStatusKHR may be included in the pname:pNext chain of
    slink:VkBindBufferMemoryInfo and slink:VkBindImageMemoryInfo, allowing
    applications to identify individual resources for which memory binding
    failed during calls to flink:vkBindBufferMemory2 and
    flink:vkBindImageMemory2.
  * A new property pname:fragmentShadingRateClampCombinerInputs to indicate
    if an implementation clamps the inputs to fragment shading rate combiner
    operations.
  * dlink:VK_NULL_HANDLE is allowed to be used when binding an index buffer,
    instead of a valid slink:VkBuffer handle.
    When the <<features-nullDescriptor, pname:nullDescriptor>> feature is
    enabled, every index fetched results in a value of zero.
  * A new property pname:maxCombinedImageSamplerDescriptorCount to indicate
    the maximum number of descriptors needed for any of the
    <<formats-requiring-sampler-ycbcr-conversion, formats that require a
    sampler {YCbCr} conversion>> supported by the implementation.
  * A new property pname:blockTexelViewCompatibleMultipleLayers indicating
    whether ename:VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT is allowed
    to be used with pname:layerCount > 1
  * pname:pNext extensible *2 versions of all descriptor binding commands.

include::{generated}/interfaces/VK_KHR_maintenance6.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2023-08-01 (Jon Leech)
  ** Initial revision
