// Copyright 2023-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_video_encode_quantization_map.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-09-23
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ahmed Abdelkhalek, AMD
  - Benjamin Cheng, AMD
  - Srinath Kumarapuram, NVIDIA
  - Tony Zlatinski, NVIDIA
  - Ping Liu, Intel
  - Daniel Rakos, RasterGrid
  - Lynne Iribarren, Independent

=== Description

This extension builds upon the `apiext:VK_KHR_video_encode_queue` extension
by enabling fine grained control of codec-specific quantization parameters
in video encode operations.

More specifically, it adds support for quantization maps:

  * Quantization delta maps to directly control the relative value of
    quantization parameter values on a per-block basis for all rate control
    modes (including when rate control is disabled).
  * Emphasis maps to indirectly control the relative quantization parameter
    values on a per-block basis when rate control is not disabled and the
    rate control mode is not configured to the implementation-defined
    default mode.

This extension is to be used in conjunction with other codec specific video
encode extensions that specify the codec specific quantization parameters
these maps control.

include::{generated}/interfaces/VK_KHR_video_encode_quantization_map.adoc[]

=== Version History

  * Revision 1, 2024-08-21 (Daniel Rakos)
  ** Internal revisions
  * Revision 2, 2024-09-23 (Daniel Rakos)
  ** Added interactions with VK_KHR_video_encode_av1
