// Copyright 2017-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_shader_fma.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-06-10
*Contributors*::
  - Graeme Leese, Broadcom

=== Description

This extension allows applications to use the SPV_KHR_fma extension to
obtain correctly-rounded results for fused-multiply add (fma) operations.

Fused-multiply add is a building block of many high-precision numerical
functions.
It provides better accuracy than separate operations, because of the removal
of the intermediate rounding step, and often costs less than the pair of
separate operations.

Vulkan currently exposes an fma primitive that can give the reduced cost,
but it is not guaranteed to be a fused operation, so the accuracy cannot be
relied on.
For applications which require the high accuracy, therefore, the operation
must be emulated or the algorithm changed so as not to require fma.
This is often vastly more costly, even though fma is supported in much of
the underlying hardware.

include::{generated}/interfaces/VK_KHR_shader_fma.adoc[]

=== Version History

  * Revision 1, 2025-06-10 (Graeme Leese)
  ** Initial draft
