// Copyright 2023-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_video_maintenance1.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-07-27
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ahmed Abdelkhalek, AMD
  - Aidan Fabius, Core Avionics & Industrial Inc.
  - Ping Liu, Intel
  - Lynne Iribarren, Independent
  - Srinath Kumarapuram, NVIDIA
  - Tony Zlatinski, NVIDIA
  - Daniel Rakos, RasterGrid

=== Description

`VK_KHR_video_maintenance1` adds a collection of minor video coding
features, none of which would warrant an entire extension of their own.

The new features are as follows:

  * Allow creating buffers that can be used in video coding operations,
    independent of the used video profile, using the new buffer creation
    flag ename:VK_BUFFER_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR.
  * Allow creating images that can be used as decode output or encode input
    pictures, independent of the used video profile, using the new image
    creation flag ename:VK_IMAGE_CREATE_VIDEO_PROFILE_INDEPENDENT_BIT_KHR.
  * Allow specifying queries used by video coding operations as part of the
    video coding command parameters, instead of using begin/end query when
    the video session is created using the new video session creation flag
    ename:VK_VIDEO_SESSION_CREATE_INLINE_QUERIES_BIT_KHR.

include::{generated}/interfaces/VK_KHR_video_maintenance1.adoc[]

=== Version History

  * Revision 1, 2023-07-27 (Daniel Rakos)
  ** internal revisions
