// Copyright 2021-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_format_feature_flags2.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-07-01
*IP Status*::
    No known IP claims.
*Contributors*::
  - Lionel Landwerlin, Intel
  - Faith Ekstrand, Intel
  - Tobias Hector, AMD
  - Spencer Fricke, Samsung Electronics
  - Graeme Leese, Broadcom
  - Jan-Harald Fredriksen, ARM

=== Description

This extension adds a new elink:VkFormatFeatureFlagBits2KHR 64bits format
feature flag type to extend the existing elink:VkFormatFeatureFlagBits which
is limited to 31 flags.
At the time of this writing 29 bits of elink:VkFormatFeatureFlagBits are
already used.

Because slink:VkFormatProperties2 is already defined to extend the Vulkan
1.0 flink:vkGetPhysicalDeviceFormatProperties entry point, this extension
defines a new slink:VkFormatProperties3KHR to extend the
slink:VkFormatProperties.

On top of replicating all the bits from elink:VkFormatFeatureFlagBits,
elink:VkFormatFeatureFlagBits2KHR adds the following bits :

  * ename:VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT_KHR and
    ename:VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT_KHR indicate
    that an implementation supports respectively reading and writing a given
    elink:VkFormat through storage operations without specifying the format
    in the shader.

  * ename:VK_FORMAT_FEATURE_2_SAMPLED_IMAGE_DEPTH_COMPARISON_BIT_KHR
    indicates that an implementation supports depth comparison performed by
    code:OpImage*Dref* instructions on a given elink:VkFormat.
    Previously the result of executing a code:OpImage*Dref* instruction on
    an image view, where the pname:format was not one of the depth/stencil
    formats with a depth component, was undefined.
    This bit clarifies on which formats such instructions can be used.

Prior to version 2 of this extension, implementations exposing the
<<features-shaderStorageImageReadWithoutFormat,
pname:shaderStorageImageReadWithoutFormat>> and
<<features-shaderStorageImageWriteWithoutFormat,
pname:shaderStorageImageWriteWithoutFormat>> features may not report
ename:VK_FORMAT_FEATURE_2_STORAGE_READ_WITHOUT_FORMAT_BIT_KHR and
ename:VK_FORMAT_FEATURE_2_STORAGE_WRITE_WITHOUT_FORMAT_BIT_KHR in
slink:VkFormatProperties3KHR::pname:bufferFeatures.
Despite this, buffer reads/writes are supported as intended by the original
features.

include::{generated}/interfaces/VK_KHR_format_feature_flags2.adoc[]

=== Promotion to Vulkan 1.3

Functionality in this extension is included in core Vulkan 1.3, with the KHR
suffix omitted.
The original type, enum and command names are still available as aliases of
the core functionality.

=== Version History

  * Revision 2, 2022-07-20 (Lionel Landwerlin)
  ** Clarify that
     VK_FORMAT_FEATURE_2_STORAGE_(READ|WRITE)_WITHOUT_FORMAT_BIT also apply
     to buffer views.
  * Revision 1, 2020-07-21 (Lionel Landwerlin)
  ** Initial draft
