// Copyright 2024-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_shader_untyped_pointers.adoc[]

*Last Modified Date*::
    2024-03-26
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
  - Requires the
    {spirv}/KHR/SPV_KHR_untyped_pointers.html[`SPV_KHR_untyped_pointers`]
    SPIR-V extension.
*Contributors*::
  - Alan Baker, Google
  - Jan-Harald Fredriksen, Arm
  - Tom Olson, Arm
  - Spencer Fricke, LunarG
  - Shahbaz Youssefi, Google
  - Tobias Hector, AMD

This extension adds Vulkan support for the
{spirv}/KHR/SPV_KHR_untyped_pointers.html[`SPV_KHR_untyped_pointers`] SPIR-V
extension.
It provides an alternative to strongly-typed pointers.
Untyped pointers allow shader authors to reinterpret data accessed through
memory and atomic instructions versus the data type declared in the variable
without extra conversion instructions.
Untyped pointers also provide an efficient translation from templated
load/store operations in high-level languages and simplify shaders that
support operations, but not storage, on smaller data types (e.g. 16-bit
floating-point types).

include::{generated}/interfaces/VK_KHR_shader_untyped_pointers.adoc[]

=== Version History

  * Revision 1, 2024-03-26 (Alan Baker)
  ** Internal draft version


