// Copyright 2017-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_shader_float_controls2.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-05-16
*Interactions and External Dependencies*::
  - This extension requires
    {spirv}/KHR/SPV_KHR_float_controls2.html[`SPV_KHR_float_controls2`].
*Contributors*::
  - Graeme Leese, Broadcom

=== Description

This extension enables use of the more expressive fast floating-point math
flags in the SPV_KHR_float_controls2 extension.
These flags give finer- grained control over which optimizations compilers
may apply, potentially speeding up execution while retaining correct
results.

The extension also adds control over the fast-math modes to the GLSL
extended instruction set, making these operations more consistent with
SPIR-V and allowing their use in situations where floating-point conformance
is important.

include::{generated}/interfaces/VK_KHR_shader_float_controls2.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-FloatControls2,FloatControls2>>

=== Version History

  * Revision 1, 2023-05-16 (Graeme Leese)
  ** Initial draft
