// Copyright 2021-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_portability_enumeration.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-06-02
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
  - Interacts with `apiext:VK_KHR_portability_subset`
*Contributors*::
  - Lenny Komow, LunarG
  - Charles Giessen, LunarG

=== Description

This extension allows applications to control whether devices that expose
the `apiext:VK_KHR_portability_subset` extension are included in the results
of physical device enumeration.
Since devices which support the `apiext:VK_KHR_portability_subset` extension
are not fully conformant Vulkan implementations, the Vulkan loader does not
report those devices unless the application explicitly asks for them.
This prevents applications which may not be aware of non-conformant devices
from accidentally using them, as any device which supports the
`apiext:VK_KHR_portability_subset` extension mandates that the extension
must be enabled if that device is used.

This extension is implemented in the loader.

include::{generated}/interfaces/VK_KHR_portability_enumeration.adoc[]

=== Version History

  * Revision 1, 2021-06-02 (Lenny Komow)
  ** Initial version
