// Copyright 2026 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_maintenance11.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-09-09

*Interactions and External Dependencies*::

*Contributors*::
  - Mike Blumenkrantz, Valve
  - Piers Daniell, NVIDIA
  - Hans-Kristian Arntzen, Valve
  - Caterina Shablia, Collabora

=== Description

apiext:VK_KHR_maintenance11 adds a collection of minor features, none of
which would warrant an entire extension of their own.

The new features are as follows:

  * Add D3D compatibility for mismatch between code:Arrayed in shaders and
    the arrayness of the underlying descriptor when the descriptor contains
    a single array layer
  * Clarify the pipeline depth clipping state when the pipeline is created
    without ename:VK_DYNAMIC_STATE_DEPTH_CLIP_ENABLE_EXT being set and the
    slink:VkPipelineRasterizationDepthClipStateCreateInfoEXT struct is not
    present
  * Add ename:VK_SHADER_CREATE_INDEPENDENT_SETS_BIT_KHR to enable shader
    object functionality to mimic
    ename:VK_PIPELINE_LAYOUT_CREATE_INDEPENDENT_SETS_BIT_EXT used for
    graphics pipeline libraries, including a new pipeline layout creation
    flag ename:VK_PIPELINE_LAYOUT_CREATE_NO_TASK_SHADER_BIT_KHR to ensure
    pipeline layouts used with shader objects also created with
    ename:VK_SHADER_CREATE_NO_TASK_SHADER_BIT_EXT to be compatible
  * Allow pname:queueFamilyIndexCount of 1 in slink:VkBufferCreateInfo,
    slink:VkImageCreateInfo,
    slink:VkPhysicalDeviceImageDrmFormatModifierInfoEXT,
    slink:VkTensorCreateInfoARM when pname:sharingMode is
    ename:VK_SHARING_MODE_CONCURRENT.
  * Require pname:minImageTransferGranularity to be [eq]#(1,1,1)# even on
    transfer-only queues and add pname:optimalImageTransferGranularity queue
    family property to communicate the performance bump for copies not
    aligned to the optimal granularity.
  * When copying between a buffer and an image on a transfer-only queue, do
    not require pname:bufferOffset to be a multiple of 4.

include::{generated}/interfaces/VK_KHR_maintenance11.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2025-09-09 (Mike Blumenkrantz)
  ** Initial revision
