// Copyright 2023-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_KHR_video_maintenance2.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-10-14
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ahmed Abdelkhalek, AMD
  - Benjamin Cheng, AMD
  - Aidan Fabius, Lynx
  - Ping Liu, Intel
  - Lynne Iribarren, Independent
  - Srinath Kumarapuram, NVIDIA
  - Tony Zlatinski, NVIDIA
  - Daniel Rakos, RasterGrid

=== Description

`VK_KHR_video_maintenance2` adds a collection of minor video coding
features, none of which would warrant an entire extension of their own.

The new features are as follows:

  * Allow video coding control commands (such as video session reset) to be
    issued without the need for a bound video session parameters object for
    video decode operations that would otherwise require the use of video
    session parameters objects.
  * Allow applications to specify codec-specific parameter sets inline for
    each decode operation instead of having to construct video session
    parameters objects.
  * Require support for
    ename:VK_VIDEO_ENCODE_RATE_CONTROL_MODE_DISABLED_BIT_KHR in all
    applicable video encode profiles.
  * Provide additional guarantees on Video Std parameters that the encoder
    implementation will not override.

include::{generated}/interfaces/VK_KHR_video_maintenance2.adoc[]

=== Version History

  * Revision 1, 2024-10-14 (Daniel Rakos)
  ** internal revisions
