// Copyright 2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_MESA_image_alignment_control.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-05-03
*IP Status*::
    No known IP claims.
*Contributors*::
  - Hans-Kristian Arntzen, Valve

=== Description

This extension allows applications to request a narrower alignment for
images than an implementation would otherwise require.
Some implementations internally support multiple image layouts in
ename:VK_IMAGE_TILING_OPTIMAL, each with different alignment requirements
and performance trade-offs.
In some API layering use cases such as D3D12, it is beneficial to be able to
control the alignment, since certain alignments for placed resources are
guaranteed to be supported, and emulating that expectation requires
unnecessary padding of allocations.

slink:VkImageAlignmentControlCreateInfoMESA can: be chained to
slink:VkImageCreateInfo, requesting that the alignment is no more than the
provided alignment.
If the requested alignment is not supported for a given
slink:VkImageCreateInfo, a larger alignment may: be returned.

While something similar could be achieved with
`apiext:VK_EXT_image_drm_format_modifier` in theory, this is not the
intended way to use that extension.
Format modifiers are generally used for externally shareable images, and
would not be platform portable.
It is also a cumbersome API to use just to lower the alignment.

include::{generated}/interfaces/VK_MESA_image_alignment_control.adoc[]

=== Version History

  * Revision 1, 2024-04-05 (Hans-Kristian Arntzen)
  ** Initial specification
