// Copyright 2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_MESA_fragment_coverage_mask.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-05-06
*Contributors*::
  - Michal Krol, Broadcom
  - Brian Paul, Broadcom
  - Roland Scheidegger, Broadcom

=== Description

This extension adds support for the code:FragmentCoverageMESA capability
from the `SPV_MESA_fragment_coverage_mask` SPIR-V extension to Vulkan,
introducing a new fragment shader input built-in,
code:FragmentCoverageMaskMESA, that contains the complete set of samples
covered by a fragment regardless of the fragment shader's execution mode.

The existing code:SampleMask input is masked to only include the bits
corresponding to the sample(s) being processed by the current invocation
when the fragment shader executes in a per-sample shading mode.
This makes it impossible for the shader to determine the entire set of
samples covered by the fragment, which in turn makes it difficult to port
shaders that rely on the equivalent input coverage mask available in other
APIs such as D3D10.

The code:FragmentCoverageMaskMESA built-in always contains the full
coverage mask, equivalent to the input coverage mask available in those
APIs, where each set bit represents a sample covered by the fragment.

include::{generated}/interfaces/VK_MESA_fragment_coverage_mask.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-FragmentCoverageMESA,
    code:FragmentCoverageMESA>>

=== Version History

  * Revision 1, 2026-05-06 (Michal Krol)
  ** Initial revision
