// Copyright (c) 2018-2021 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NVX_binary_import.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-04-09
*Contributors*::
  - Eric Werness, NVIDIA
  - Liam Middlebrook, NVIDIA

=== Description

This extension allows applications to import CuBIN binaries and execute
them.

[NOTE]
====
There is currently no specification language written for this extension.
The links to APIs defined by the extension are to stubs that only include
generated content such as API declarations and implicit valid usage
statements.
====

include::{generated}/interfaces/VK_NVX_binary_import.adoc[]

ifndef::isrefpage[]

=== Stub API References

[open,refpage='VkCuFunctionNVX',desc='Stub description of VkCuFunctionNVX',type='handles']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/handles/VkCuFunctionNVX.adoc[]
--

[open,refpage='VkCuModuleNVX',desc='Stub description of VkCuModuleNVX',type='handles']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/handles/VkCuModuleNVX.adoc[]
--

[open,refpage='vkCreateCuFunctionNVX',desc='Stub description of vkCreateCuFunctionNVX',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkCreateCuFunctionNVX.adoc[]

include::{generated}/validity/protos/vkCreateCuFunctionNVX.adoc[]
--

[open,refpage='VkCuFunctionCreateInfoNVX',desc='Stub description of VkCuFunctionCreateInfoNVX',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkCuFunctionCreateInfoNVX.adoc[]

include::{generated}/validity/structs/VkCuFunctionCreateInfoNVX.adoc[]
--

[open,refpage='vkDestroyCuFunctionNVX',desc='Stub description of vkDestroyCuFunctionNVX',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkDestroyCuFunctionNVX.adoc[]

include::{generated}/validity/protos/vkDestroyCuFunctionNVX.adoc[]
--

[open,refpage='vkCreateCuModuleNVX',desc='Stub description of vkCreateCuModuleNVX',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkCreateCuModuleNVX.adoc[]

include::{generated}/validity/protos/vkCreateCuModuleNVX.adoc[]
--

[open,refpage='VkCuModuleCreateInfoNVX',desc='Stub description of VkCuModuleCreateInfoNVX',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkCuModuleCreateInfoNVX.adoc[]

include::{generated}/validity/structs/VkCuModuleCreateInfoNVX.adoc[]
--

[open,refpage='vkDestroyCuModuleNVX',desc='Stub description of vkDestroyCuModuleNVX',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkDestroyCuModuleNVX.adoc[]

include::{generated}/validity/protos/vkDestroyCuModuleNVX.adoc[]
--

[open,refpage='vkCmdCuLaunchKernelNVX',desc='Stub description of vkCmdCuLaunchKernelNVX',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkCmdCuLaunchKernelNVX.adoc[]

include::{generated}/validity/protos/vkCmdCuLaunchKernelNVX.adoc[]
--

[open,refpage='VkCuLaunchInfoNVX',desc='Stub description of VkCuLaunchInfoNVX',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkCuLaunchInfoNVX.adoc[]

include::{generated}/validity/structs/VkCuLaunchInfoNVX.adoc[]
--

endif::isrefpage[]

=== Version History

  * Revision 1, 2021-04-09 (Eric Werness)
  ** Internal revisions
