// Copyright 2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_cooperative_matrix2.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-08-01
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/nv/GLSL_NV_cooperative_matrix2.txt[`GLSL_NV_cooperative_matrix2`]
*Contributors*::
  - Jeff Bolz, NVIDIA
  - Karthik Vaidyanathan, NVIDIA

=== Description

This extension adds several new features building on the cooperative matrix
types added in VK_KHR_cooperative_matrix.
The goal is to add and accelerate features beyond just simple GEMM kernels,
including adding support for type/use conversions, reductions, per-element
operations, and tensor addressing, and also to improve usability and
out-of-the-box performance by adding support for more flexible matrix sizes,
and workgroup scope matrices with compiler-managed staging through shared
memory.

The new functionality is defined by the
{spirv}/NV/SPV_NV_tensor_addressing.html[`SPV_NV_tensor_addressing`] and
{spirv}/NV/SPV_NV_cooperative_matrix2.html[`SPV_NV_cooperative_matrix2`]
SPIR-V extensions and can be used with the
{GLSLregistry}/nv/GLSL_NV_cooperative_matrix2.txt[`GLSL_NV_cooperative_matrix2`]
GLSL extension.

This extension includes support for enumerating the matrix types and
dimensions that are supported by the implementation, and which specific
features are supported.

include::{generated}/interfaces/VK_NV_cooperative_matrix2.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-TensorAddressingNV,TensorAddressingNV>>
  * <<spirvenv-capabilities-table-CooperativeMatrixReductionsNV,CooperativeMatrixReductionsNV>>
  * <<spirvenv-capabilities-table-CooperativeMatrixConversionsNV,CooperativeMatrixConversionsNV>>
  * <<spirvenv-capabilities-table-CooperativeMatrixPerElementOperationsNV,CooperativeMatrixPerElementOperationsNV>>
  * <<spirvenv-capabilities-table-CooperativeMatrixTensorAddressingNV,CooperativeMatrixTensorAddressingNV>>
  * <<spirvenv-capabilities-table-CooperativeMatrixBlockLoadsNV,CooperativeMatrixBlockLoadsNV>>

=== Issues

=== Version History

  * Revision 1, 2024-08-01 (Jeff Bolz)
  ** Initial revision
