// Copyright 2025-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_external_compute_queue.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-03-24
*Contributors*::
  - Chris Lentini, NVIDIA
  - Eric Werness, NVIDIA
  - James Jones, NVIDIA
  - Jeff Juliano, NVIDIA
  - Liam Middlebrook, NVIDIA
  - Lionel Duc, NVIDIA

=== Description

This extension gives applications the ability to join compatible external
compute APIs to a sname:VkDevice.
In this way, the extension allows an application to achieve simultaneous
execution between work submitted from these compatible external APIs and
work that has been submitted through the Vulkan API.

At device creation time, an application must: supply a
slink:VkExternalComputeQueueDeviceCreateInfoNV.
This communicates to the implementation the maximum number of external
queues that the application can: create at once.
This information may: be used by the implementation to aid in decisions made
during device creation.

After device creation, the function flink:vkCreateExternalComputeQueueNV is
used by an application to create a new sname:VkExternalComputeQueueNV
object.
The sname:VkExternalComputeQueueNV object holds information and reserves
resources necessary for a compatible external API to be able to join a
sname:VkDevice.
This information can be queried through the
flink:vkGetExternalComputeQueueDataNV function, returning an opaque blob of
data which can be passed to compatible external APIs.
The application must: finally call flink:vkDestroyExternalComputeQueueNV
when it is done in order to release the reserved resources.

This extension introduces a new properties structure,
slink:VkPhysicalDeviceExternalComputeQueuePropertiesNV, which can be queried
through flink:vkGetPhysicalDeviceProperties2.
The structure provides information on functional limits to the extension as
well as a way of querying the size of the application allocated memory which
must: be passed to the flink:vkGetExternalComputeQueueDataNV function.

When creating a sname:VkExternalComputeQueueNV through
flink:vkCreateExternalComputeQueueNV, the
slink:VkExternalComputeQueueCreateInfoNV structure requires an application
to supply a sname:VkQueue to aid in external compute queue creation.
The supplied sname:VkQueue is a strong scheduling hint about which queue it
expects to submit graphics workloads to and with which it expects
simultaneous execution of compute workloads submitted through the external
API.

include::{generated}/interfaces/VK_NV_external_compute_queue.adoc[]

[NOTE]
====
While the external queue is now a part of a sname:VkDevice, idling the
device through flink:vkDeviceWaitIdle does not wait for the external queue.
Draining the work on an external queue must: be done through its own
external API.
External queues must: be idled before destroying the associated
sname:VkDevice.
====

[NOTE]
====
In general, synchronization and resource sharing between the external API
and Vulkan must still be accomplished via existing cross-API interop
mechanisms.
====

=== Issues


=== Version History

  * Revision 1, 2024-05-20 (Chris Lentini)
  ** Internal revisions
