// Copyright (c) 2023-2024 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_display_stereo.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-11-20
*Contributors*::
  - Russell Chou, NVIDIA
  - Jeff Juliano, NVIDIA
  - James Jones, NVIDIA

=== Description

This extension allows the application to choose which type of 3D stereo
hardware it wants to use so the driver can configure it properly.
This configuration is useful for swapchains created from display surfaces
because some environments do not have an intermediate windowing system
available for easy configuration.
This extension will override any stereo type configuration in the windowing
system.

For HDMI 3D, only some display modes support stereo rendering, and a new
structure is needed to expose that information to the application.

include::{generated}/interfaces/VK_NV_display_stereo.adoc[]

=== Version History

  * Revision 1, 2024-11-20 (Russell Chou)
  ** Initial release
