// Copyright 2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_cooperative_matrix_decode_vector.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-04-30
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/nv/GLSL_NV_cooperative_matrix_decode_vector.txt[`GLSL_NV_cooperative_matrix_decode_vector`]
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

This extension adds a device feature for the SPIR-V
code:CooperativeMatrixDecodeVectorNV capability and the
{spirv}/NV/SPV_NV_cooperative_matrix_decode_vector.html[`SPV_NV_cooperative_matrix_decode_vector`]
SPIR-V extension.

When enabled, shaders may use an optional *decode vector* operand with
code:OpCooperativeMatrixLoadTensorNV (see that SPIR-V extension) to load
multiple block-adjacent elements per decode callback invocation.

An implementation must: also support
slink:VkPhysicalDeviceCooperativeMatrix2FeaturesNV::pname:cooperativeMatrixBlockLoads
when exposing this extension.

include::{generated}/interfaces/VK_NV_cooperative_matrix_decode_vector.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-CooperativeMatrixDecodeVectorNV,CooperativeMatrixDecodeVectorNV>>

=== Issues

=== Version History

  * Revision 1, 2026-04-30 (Jeff Bolz)
  ** Initial revision
