// Copyright (c) 2021 NVIDIA Corporation.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_linear_color_attachment.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2021-12-02
*Interactions and External Dependencies*::
  - This extension requires `apiext:VK_KHR_format_feature_flags2`
*Contributors*::
  - Pat Brown, NVIDIA
  - Piers Daniell, NVIDIA
  - Sourav Parmar, NVIDIA

=== Description

This extension expands support for using ename:VK_IMAGE_TILING_LINEAR images
as color attachments when all the color attachments in the render pass
instance have ename:VK_IMAGE_TILING_LINEAR tiling.
This extension adds a new flag bit
ename:VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV that extends the
existing elink:VkFormatFeatureFlagBits2KHR bits.
This flag can: be set for renderable color formats in the
slink:VkFormatProperties3KHR::pname:linearTilingFeatures format properties
structure member.
Formats with the ename:VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV
flag may: be used as color attachments as long as all the color attachments
in the render pass instance have ename:VK_IMAGE_TILING_LINEAR tiling, and
the formats their images views are created with have
slink:VkFormatProperties3KHR::pname:linearTilingFeatures which include
ename:VK_FORMAT_FEATURE_2_LINEAR_COLOR_ATTACHMENT_BIT_NV.
This extension supports both dynamic rendering and traditional render
passes.

include::{generated}/interfaces/VK_NV_linear_color_attachment.adoc[]

=== Version History

  * Revision 1, 2021-11-29 (sourav parmar)
  ** Initial draft
