// Copyright (c) 2020-2022 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_external_memory_sci_buf.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-04-12
*Contributors*::
  - Kai Zhang, NVIDIA
  - Jeff Bolz, NVIDIA
  - Jonathan McCaffrey, NVIDIA
  - Daniel Koch, NVIDIA

[[NvSciBuf-extension-page]]
=== Description
This extension enables an application to access external memory via
stext:NvSciBufObj.
To import a stext:NvSciBufObj to slink:VkDeviceMemory, applications need to:

  * Create an unreconciled stext:NvSciBufAttrList via
    stext:NvSciBufAttrListCreate()
  * Fill in the private attribute list via
    flink:vkGetPhysicalDeviceSciBufAttributesNV()
  * Fill in the public attribute list via stext:NvSciBufAttrListSetAttrs()
  * Reconcile the stext:NvSciBufAttrList via
    stext:NvSciBufAttrListReconcile()
  * Create a stext:NvSciBufObj via stext:NvSciBufObjAlloc()
  * Import the stext:NvSciBufObj to a slink:VkDeviceMemory by chaining
    slink:VkImportMemorySciBufInfoNV structure to the command
    flink:vkAllocateMemory.

For details of the stext:NvSciBuf APIs and data structures, see the
https://developer.nvidia.com/docs/drive/drive-os/latest/linux/sdk/api%5Freference/group%5F%5Fnvsci%5F%5Ftop.html[`NvStreams
Documentation`].

include::{generated}/interfaces/VK_NV_external_memory_sci_buf.adoc[]

=== Issues

1) What should we call this extension?

RESOLVED.
The external API is stext:NvSciBuf, but the Vulkan convention is to append
the vendor suffix at the end of an identifier.
Using stext:NvSciBufNV seems awkward, so we have chosen to use just the
stext:SciBuf portion of the name in Vulkan commands and tokens.
Since this is for interacting with memory objects allocated from outside
Vulkan, we use "external_memory" in the name, similar to
apiext:VK_KHR_external_memory_fd.
To avoid an explosion of extensions, we include the capability to import and
export memory in one extension but include separate features in case
implementations only implement (or safety certify) a subset.

2) What changed in revision 2?

RESOLVED.
The slink:VkPhysicalDeviceExternalSciBufFeaturesNV struct was renamed to
slink:VkPhysicalDeviceExternalMemorySciBufFeaturesNV to follow naming
conventions (previous names retained as aliases), and drop const on
pname:pNext pointer.


=== Version History

  * Revision 1, 2022-04-12 (Kai Zhang, Daniel Koch)
  ** Internal revisions
  * Revision 2, 2023-01-03 (Daniel Koch)
  ** fix the feature structure to address naming convention and cts
     autogeneration issues
