// Copyright (c) 2026 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_push_constant_bank.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-09-15
*Contributors*::
  - Pat Brown, NVIDIA
  - Piers Daniell, NVIDIA
  - Rodrigo Locatti, NVIDIA
  - Daniel Story, Nintendo

=== Description

The apiext:VK_NV_push_constant_bank extension allows applications to specify
a bank and offset for push constants, enabling more flexible push constant
management in descriptor heap scenarios where shaders are able to access
different root descriptors.

Traditional push constants are placed in a default location, but this
extension allows applications to specify which hardware constant bank to use
and at what offset within that bank.
This provides greater control over memory layout and enables more efficient
use of hardware resources in advanced descriptor heap configurations.

The extension integrates with apiext:VK_EXT_descriptor_heap by allowing
sname:VkPushConstantBankInfoNV structures to be chained to
sname:VkDescriptorSetAndBindingMappingEXT, sname:VkPushDataInfoEXT,
sname:VkPushConstantsInfo, or sname:VkIndirectCommandsLayoutTokenEXT
structures, specifying the hardware bank where push constants should be
placed as part of the descriptor heap mapping configuration or push data
operations.

Key features include:

  * Bank and offset specification for push constant placement
  * Integration with descriptor heap mapping through structure chaining
  * Support for GLSL shader qualifiers for bank and offset specification in
    SPIR-V
  * Validation of bank bounds and alignment requirements
  * Compatibility with existing push constant API

The number of available push constant banks is implementation-dependent and
can be queried through separate limits in
sname:VkPhysicalDevicePushConstantBankPropertiesNV:
pname:maxGraphicsPushConstantBanks and pname:maxComputePushConstantBanks for
non-descriptor heap usage, and pname:maxGraphicsPushDataBanks and
pname:maxComputePushDataBanks for descriptor heap scenarios.
Applications must ensure bank indices remain within the appropriate
implementation-defined range based on the shader type and usage context.

Shader support for banks and member offsets are defined by the
{spirv}/NV/SPV_NV_push_constant_bank.html[`SPV_NV_push_constant_bank`]
SPIR-V extension, which can be used with the
{GLSLregistry}/nv/GLSL_NV_push_constant_bank.txt[`GLSL_NV_push_constant_bank`]
GLSL extension.

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-PushConstantBanksNV,
    code:PushConstantBanksNV>>

=== New SPIR-V Decorations

  * <<shaders-pushconstant-decorations-banknv, code:BankNV>>
  * <<shaders-pushconstant-decorations-memberoffsetnv, code:MemberOffsetNV>>

include::{generated}/interfaces/VK_NV_push_constant_bank.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2025-09-15 (NVIDIA Vassili Nikolaev)
  ** Initial draft
