// Copyright 2023-2024 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_per_stage_descriptor_set.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-10-16
*IP Status*::
    No known IP claims.
*Contributors*::
  - Daniel Story, Nintendo

=== Description

This extension introduces a new descriptor set layout creation flag that
allows bindings in a descriptor set to be scoped to each shader stage.
This means that shaders bound at the same time may: use completely different
descriptor set layouts without any restrictions on compatibility, and that
the descriptor limits that would otherwise apply to the union of all stages
together instead apply to each stage individually.
It also means that descriptors shared by multiple stages must: be bound to
each stage or set of stages that use a unique descriptor set layout using
their specific per stage descriptor set layout(s).

This extension also allows each of the new descriptor binding functions from
VK_KHR_maintenance6 to have their slink:VkPipelineLayout member be
optionally set to dlink:VK_NULL_HANDLE, in which case the pipeline layout
information is taken from a slink:VkPipelineLayoutCreateInfo structure in
the pname:pNext chain.
This enables descriptors to be directly bound using descriptor set layouts
without applications needing to create and manage slink:VkPipelineLayout
objects at command recording time.

include::{generated}/interfaces/VK_NV_per_stage_descriptor_set.adoc[]

=== Issues

None

=== Version History

  * Revision 1, 2023-10-16 (Piers Daniell)
  ** Initial draft
