// Copyright (c) 2024-2025 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_cluster_acceleration_structure.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2024-09-09
*Contributors*::
  - Vikram Kushwaha, NVIDIA
  - Eric Werness, NVIDIA
  - Christoph Kubisch, NVIDIA
  - Jan Schmid, NVIDIA
  - Pyarelal Knowles, NVIDIA

=== Description

Acceleration structure build times can become a bottleneck in ray tracing
applications dealing with extensive dynamic geometry.
This extension addresses the problem by enabling applications to construct
bottom-level acceleration structures (BLAS) from pre-generated acceleration
structures based on clusters of triangles (CLAS), leading to significant
improvements in build times.

It provides a host-side query function to fetch the requirements and a
versatile multi-indirect call for managing cluster geometry.
This call enables applications to generate cluster geometry, construct
Cluster BLAS from CLAS lists, and move or copy CLAS and BLAS.
By sourcing inputs from device memory and processing multiple elements
simultaneously, the call reduces the host-side costs associated with
traditional acceleration structure functions.


This extension adds support for the following SPIR-V extension in Vulkan:

  * `SPV_NV_cluster_acceleration_structure`

include::{generated}/interfaces/VK_NV_cluster_acceleration_structure.adoc[]

=== New or Modified Built-In Variables

  * <<interfaces-builtin-variables-clusteridnv,code:ClusterIDNV>>

=== New SPIR-V Capability

  * <<spirvenv-capabilities-table-RayTracingClusterAccelerationStructureNV,
    code:RayTracingClusterAccelerationStructureNV>>

=== Version History

  * Revision 4, 2025-07-16 (Vikram Kushwaha)
  ** Adding build flag to enable OMM in cluster acceleration structure
  * Revision 3, 2025-06-18 (Vikram Kushwaha)
  ** Adding a OpType to get template's index data
  * Revision 2, 2024-09-09 (Vikram Kushwaha)
  ** Changes to some structures causing incompatibility with Revision 1
  * Revision 1, 2024-08-29 (Vikram Kushwaha)
  ** Initial draft




