// Copyright (c) 2021 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_ray_tracing_invocation_reorder.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-11-02
*Interactions and External Dependencies*::
  - This extension requires
    {spirv}/NV/SPV_NV_shader_invocation_reorder.html[`SPV_NV_shader_invocation_reorder`]
  - This extension provides API support for
    {GLSLregistry}/nv/GLSL_NV_shader_invocation_reorder.txt[`GL_NV_shader_invocation_reorder`]
*Contributors*::
  - Eric Werness, NVIDIA
  - Ashwin Lele, NVIDIA

=== Description

The ray tracing pipeline API provides some ability to reorder for locality,
but it is useful to have more control over how the reordering happens and
what information is included in the reordering.
The shader API provides a hit object to contain result information from the
hit which can be used as part of the explicit sorting plus options that
contain an integer for hint bits to use to add more locality.

include::{generated}/interfaces/VK_NV_ray_tracing_invocation_reorder.adoc[]

=== Version History

  * Revision 1, 2020-09-12 (Eric Werness, Ashwin Lele)
  ** Initial external release
