// Copyright (c) 2018-2022 NVIDIA Corporation.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_present_barrier.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-05-16
*Contributors*::
  - Liya Li, Nvidia
  - Martin Schwarzer, Nvidia
  - Andy Wolf, Nvidia
  - Ian Williams, Nvidia
  - Ben Morris, Nvidia
  - James Jones, Nvidia
  - Jeff Juliano, Nvidia

=== Description

This extension adds support for synchronizing corresponding presentation
requests across multiple swapchains using the _present barrier_.

include::{generated}/interfaces/VK_NV_present_barrier.adoc[]

=== Issues
1) Is there a query interface to check if a swapchain is using the present
barrier?

*RESOLVED*.
There is no such query interface.
When creating a swapchain, an application can specify to use the _present
barrier_, and if the swapchain is created successfully, this swapchain will
be using the present barrier.

2) Do we need an extra interface to set up the present barrier across
distributed systems?

*RESOLVED*.
If the required hardware is presented in the system, and all settings for
the physical synchronization with other systems are set up, an
implementation manages the configuration automatically when creating a
swapchain, without any extra calls from the application.

=== Version History

  * Revision 1, 2022-07-20
  ** Initial version

