// Copyright (c) 2018-2020 NVIDIA Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_scissor_exclusive.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-01-18
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
    None
*Contributors*::
  - Pat Brown, NVIDIA
  - Jeff Bolz, NVIDIA
  - Piers Daniell, NVIDIA
  - Daniel Koch, NVIDIA

=== Description

This extension adds support for an exclusive scissor test to Vulkan.
The exclusive scissor test behaves like the scissor test, except that the
exclusive scissor test fails for pixels inside the corresponding rectangle
and passes for pixels outside the rectangle.
If the same rectangle is used for both the scissor and exclusive scissor
tests, the exclusive scissor test will pass if and only if the scissor test
fails.

Version 2 of this extension introduces
ename:VK_DYNAMIC_STATE_EXCLUSIVE_SCISSOR_ENABLE_NV and
flink:vkCmdSetExclusiveScissorEnableNV.
Applications that use this dynamic state must ensure the implementation
advertises at least pname:specVersion `2` of this extension.

include::{generated}/interfaces/VK_NV_scissor_exclusive.adoc[]

=== Issues

1) For the scissor test, the viewport state must be created with a matching
number of scissor and viewport rectangles.
Should we have the same requirement for exclusive scissors?

*RESOLVED*: For exclusive scissors, we relax this requirement and allow an
exclusive scissor rectangle count that is either zero or equal to the number
of viewport rectangles.
If you pass in an exclusive scissor count of zero, the exclusive scissor
test is treated as disabled.

=== Version History

  * Revision 2, 2023-01-18 (Piers Daniell)
  ** Add dynamic state for explicit exclusive scissor enables

  * Revision 1, 2018-07-31 (Pat Brown)
  ** Internal revisions
