// Copyright 2019-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_NV_descriptor_pool_overallocation.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-08-30
*Contributors*::
  - Jeff Bolz, NVIDIA

=== Description

There are scenarios where the application does not know ahead of time how
many descriptor sets it may need to allocate from a descriptor pool, or how
many descriptors of any of the descriptor types it may need to allocate from
the descriptor pool.

This extension gives applications the ability to request the implementation
allow more sets or descriptors to be allocated than initially specified at
descriptor pool creation time, subject to available resources.

The ename:VK_DESCRIPTOR_POOL_CREATE_ALLOW_OVERALLOCATION_SETS_BIT_NV flag
lets the application allocate more than
slink:VkDescriptorPoolCreateInfo::pname:maxSets descriptor sets, and the
ename:VK_DESCRIPTOR_POOL_CREATE_ALLOW_OVERALLOCATION_POOLS_BIT_NV lets the
application allocate more descriptors than initially specified by
slink:VkDescriptorPoolSize::pname:descriptorCount for any descriptor types.

include::{generated}/interfaces/VK_NV_descriptor_pool_overallocation.adoc[]

=== Version History

  * Revision 1, 2023-08-30 (Piers Daniell)
  ** Internal revisions
