// Copyright (c) 2023 Blackberry Limited
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QNX_external_memory_screen_buffer.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-05-17
*IP Status*::
    No known IP claims.
*Contributors*::
  - Mike Gorchak, QNX / Blackberry Limited
  - Aaron Ruby, QNX / Blackberry Limited

=== Description

This extension enables an application to import QNX Screen
code:_screen_buffer objects created outside of the Vulkan device into Vulkan
memory objects, where they can be bound to images and buffers.

Some code:_screen_buffer images have implementation-defined _external
formats_ that may: not correspond to Vulkan formats.
Sampler {YCbCr} conversion can: be used to sample from these images and
convert them to a known color space.

code:_screen_buffer is strongly typed, so naming the handle type is
redundant.
The internal layout and therefore size of a code:_screen_buffer image may
depend on native usage flags that do not have corresponding Vulkan
counterparts.

include::{generated}/interfaces/VK_QNX_external_memory_screen_buffer.adoc[]

=== Issues

=== Version History

  * Revision 1, 2023-05-17 (Mike Gorchak)
  ** Initial version
