// Copyright 2021-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_tile_memory_heap.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-05-05
*Interactions and External Dependencies*::
  - Interacts with `apiext:VK_QCOM_tile_properties`
  - Interacts with `apiext:VK_QCOM_tile_shading`
*Contributors*::
  - Patrick Boyle, Qualcomm Technologies, Inc.
  - Matthew Netsch, Qualcomm Technologies, Inc.
  - Srihari Babu Alla, Qualcomm Technologies, Inc.
  - Kevin Matlage, Qualcomm Technologies, Inc.

=== Description

This extension adds a new memory heap which allows applications to allocate
and manage tile memory.
A tile memory heap is denoted by the new
ename:VK_MEMORY_HEAP_TILE_MEMORY_BIT_QCOM property.
Memory contents within this heap behave differently than other heaps and
only persist its memory contents within a command buffer submission batch
boundary.
This boundary may be extended to a queue submit boundary by querying
pname:queueSubmitBoundary in the new
sname:VkPhysicalDeviceTileMemoryHeapPropertiesQCOM structure.

Tile memory from this heap can be bound to VkImages or VkBuffers.
The following new usage flags ename:VK_IMAGE_USAGE_TILE_MEMORY_BIT_QCOM,
ename:VK_BUFFER_USAGE_TILE_MEMORY_BIT_QCOM,
ename:VK_BUFFER_USAGE_2_TILE_MEMORY_BIT_QCOM were added for this.
A new extended structure is added to get memory requirements for tile memory
sname:VkTileMemoryRequirementsQCOM.

A new command is added to bind tile memory to a command buffer in order to
access and persist tile memory contents while executing commands
flink:vkCmdBindTileMemoryQCOM.

This extension can be used in combination with
apiext:VK_QCOM_tile_properties with the new structure
slink:VkTileMemorySizeInfoQCOM.

=== Issues

None.

include::{generated}/interfaces/VK_QCOM_tile_memory_heap.adoc[]

=== Version History

  * Revision 1, 2025-03-26 (Patrick Boyle)
  ** Initial version
