// Copyright (c) 2026 Qualcomm Technologies, Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_shader_multiple_wait_queues.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-05-04
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/qcom/GLSL_QCOM_multiple_wait_queues.txt[`GLSL_QCOM_multiple_wait_queues`]

*Contributors*::
  - Matthew Netsch, Qualcomm Technologies, Inc.
  - Elina Kamenetskaya, Qualcomm Technologies, Inc.
  - Wooyoung Kim, Qualcomm Technologies, Inc.

=== Description

This extension adds a new loop control hint to the SPIR-V execution
environment, instructing the compiler that it should use multiple wait
queues to optimize a loop.

This can improve performance for loops that have high latency instructions
such as for `apiext:VK_KHR_cooperative_matrix` operations, by allowing the
compiler to issue instructions for future iterations while waiting for the
current iteration to complete.

include::{generated}/interfaces/VK_QCOM_shader_multiple_wait_queues.adoc[]

=== Version History

  * Revision 1, 2026-05-04 (Matthew Netsch)
