// Copyright (c) 2025 Qualcomm Technologies, Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_image_processing3.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-05-08
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/qcom/GLSL_QCOM_image_processing3.txt[`GL_QCOM_image_processing3`]
  - Interacts with `apiext:VK_QCOM_tile_shading`
  - Interacts with `apiext:VK_QCOM_image_processing`
  - Interacts with `apiext:VK_QCOM_image_processing2`

*Contributors*::
  - Matthew Netsch, Qualcomm Technologies, Inc.
  - Jonathan Wicks, Qualcomm Technologies, Inc.
  - Liang Li, Qualcomm Technologies, Inc.
  - Wooyoung Kim, Qualcomm Technologies, Inc.

=== Description

This extension introduces a new SPIR-V built-in function to support
predefined image gather operations used in popular image processing
algorithms such as super resolution upscaling and contrast-adaptive
sharpening.

The `OpImageGatherQCOM` instruction supports the following modes:

  * `GatherH2QCOM` - produces an image gather with an extra horizontal
    offset
  * `GatherV2QCOM` - produces an image gather with an extra vertical offset.
                      Combined with `OpImageGather` and `GatherH2QCOM`, this
                      is useful for creating a 12-tap filter for upscaling.
  * `GatherDQCOM` - produces an image gather by sampling the cardinal
                      offsets.
                      Combined with a point sample of the center texel, this
                      is useful for creating a 5-tap sharpening filter (eg.
                      CAS).
  * `Gather4x1QCOM` - produces an image gather by sampling 4 texels in a
                      horizontal row.
                      This is useful for kernels requiring vectorized loads,
                      and can help with cache locality for linear access.

Each of the image processing instructions operate on the same sampled images
that the `OpImage*Gather` instructions support with the exception of
cube-maps, depth comparison, `ConstOffsets`, and sparse residency check.

Implementations of this extension should support these operations natively
at the HW instruction level, offering potential performance gains as well as
ease of development.

This extension also adds some block matching improvements over
`apiext:VK_QCOM_image_processing` and `apiext:VK_QCOM_image_processing2` by
exposing more formats and wrap modes.

include::{generated}/interfaces/VK_QCOM_image_processing3.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-ImageGatherLinearQCOM,ImageGatherLinearQCOM>>
  * <<spirvenv-capabilities-table-ImageGatherExtendedModesQCOM,ImageGatherExtendedModesQCOM>>

=== Version History

  * Revision 1, 2026-05-08 (Matthew Netsch)
