// Copyright 2025-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_elapsed_timer_query.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-05-08
*Interactions and External Dependencies*::
  - Interacts with `apiExt:VK_KHR_calibrated_timestamps`
  - Interacts with `apiExt:VK_KHR_maintenance7`
  - Interacts with `apiExt:VK_EXT_transform_feedback`
*Contributors*::
  - Matthew Netsch, Qualcomm Technologies, Inc
  - Jacob Garcia, Qualcomm Technologies, Inc
  - Patrick Boyle, Qualcomm Technologies, Inc

=== Description

This extension adds a new query type to write out the elapsed time between a
set of commands, providing similar functionality to `GL_ARB_timer_query`.

There is no existing solution on tilers for measuring commands inside render
pass instances, as comparing query timestamps will not give valid results.

This extension, solves the issue by adding a new query type that can be used
to measure time between a begin and end query and works inside render pass
instances.
The implementation is responsible for accumulating the correct elapsed time
for the commands across all tiles.

include::{generated}/interfaces/VK_QCOM_elapsed_timer_query.adoc[]

=== Issues

(1) How to handle overflows?
--
  * Resolved: While ename:VK_QUERY_RESULT_WITH_STATUS_BIT_KHR could have
    been used to indicate an overflow, it is difficult for an implementation
    to detect this.
    The accumulation occurs on the device, and overflow detection requires
    calculations prior to accumulation which may not be supported by the
    device.
    Instead, if the application rejects outliers as part of the profiling
    process, this issue should be exceedingly rare.
    If an application is sensitive to this in production, it will need to
    implement some mechanism to reject bad results.
    For example, measuring the timestamp before and after the render pass
    could give a clue about an overflow.
--

=== Version History

  * Revision 1, 2026-05-08 (Matthew Netsch)
  ** Initial revision
