// Copyright 2021-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_cooperative_matrix_conversion.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-01-28
*Interactions and External Dependencies*::
  - This extension provides API support for
    {GLSLregistry}/qcom/GLSL_QCOM_cooperative_matrix_conversion.txt[`GLSL_QCOM_cooperative_matrix_conversion`]
*Contributors*::
  - Matthew Netsch, Qualcomm Technologies, Inc
  - Elina Kamenetskaya, Qualcomm Technologies, Inc
  - Alex Bourd, Qualcomm Technologies, Inc
  - Ruihao Zhang, Qualcomm Technologies, Inc
  - Wooyoung Kim, Qualcomm Technologies, Inc

=== Description

This extension adds support for new SPIR-V shader instructions that allow
loading and storing a cooperative matrix without needing to stage through
shared memory and to allow bit casting arrays.

These instructions are defined by the
{spirv}/QCOM/SPV_QCOM_cooperative_matrix_conversion.html[`SPV_QCOM_cooperative_matrix_conversion`]
SPIR-V extension and can be used with the
{GLSLregistry}/qcom/GLSL_QCOM_cooperative_matrix_conversion.txt[`GLSL_QCOM_cooperative_matrix_conversion`]
GLSL extension.

include::{generated}/interfaces/VK_QCOM_cooperative_matrix_conversion.adoc[]

=== New SPIR-V Capabilities

  * <<spirvenv-capabilities-table-CooperativeMatrixConversionQCOM,CooperativeMatrixConversionQCOM>>

=== Version History

  * Revision 1, 2026-01-28 (Matthew Netsch)
  ** Initial draft
