// Copyright 2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_filter_cubic_weights.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-06-23
*Contributors*::
  - Jeff Leger, Qualcomm Technologies, Inc.
  - Jonathan Wicks, Qualcomm Technologies, Inc.

=== Description

This extension extends cubic filtering by adding the ability to select a set
of weights.
Without this extension, the weights used in cubic filtering are limited to
those corresponding to a Catmull-Rom spline.
This extension adds support for 3 additional spline weights.

This extension adds a new structure that can: be added to the pname:pNext
chain of slink:VkSamplerCreateInfo that can: be used to specify which set of
cubic weights are used in cubic filtering.
A similar structure can be added to the pname:pNext chain of
slink:VkBlitImageInfo2 to specify cubic weights used in a blit operation.

With this extension weights corresponding to the following additional
splines can be selected for cubic filtered sampling and blits:

  * Zero Tangent Cardinal
  * B-Spline
  * Mitchell-Netravali

include::{generated}/interfaces/VK_QCOM_filter_cubic_weights.adoc[]

=== Version History

  * Revision 1, 2023-06-23 (jleger)
  ** Initial version
