// Copyright 2022-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_multiview_per_view_render_areas.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2023-01-10
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
  - This extension interacts with `apiext:VK_KHR_dynamic_rendering`
  - This extension interacts with `apiext:VK_QCOM_render_pass_transform`
*Contributors*::
  - Jeff Leger, Qualcomm
  - Jonathan Tinkham, Qualcomm
  - Jonathan Wicks, Qualcomm

=== Description

Certain use cases (e.g., side-by-side VR rendering) use multiview and render
to distinct regions of the framebuffer for each view.
On some implementations, there may be a performance benefit for providing
per-view render areas to the implementation.
Such per-view render areas can be used by the implementation to reduce the
pixels that are affected by attachment load, store, and multisample resolve
operations.

The extension enables a multiview render pass instance to define per-view
render areas.
For each view of a multiview render pass instance, only those pixels in the
per-view render area are affected by load, store and resolve operations.

include::{generated}/interfaces/VK_QCOM_multiview_per_view_render_areas.adoc[]

=== Issues

1) Do the per-view pname:renderAreas interact with
flink:vkGetRenderAreaGranularity ?

*RESOLVED*: There is no change.
The granularity returned by flink:vkGetRenderAreaGranularity also applies to
the per-view pname:renderAreas.

2) How does this extension interact with
`apiext:VK_QCOM_render_pass_transform`?

*RESOLVED*: When `apiext:VK_QCOM_render_pass_transform` is enabled, the
application provides render area in non-rotated coordinates which is rotated
by the implementation to the rotated coordinate system.
When this extension is used in combination with
`apiext:VK_QCOM_render_pass_transform`, then the pname:renderArea provided
in slink:VkRenderingInfo::pname:renderArea,
slink:VkRenderPassBeginInfo::pname:renderArea, or
slink:VkCommandBufferInheritanceRenderPassTransformInfoQCOM::pname:renderArea
is rotated by the implementation.
The per-view render areas are not rotated.

3) How does this extension interact with
`apiext:VK_QCOM_multiview_per_view_viewports`

*RESOLVED*: There is no direct interaction.
The per-view viewports and the per-view renderAreas are orthogonal features.

4) When a per-view pname:renderArea is specified, must multiview rendering
for each view of a multiview render pass be contained within the per-view
pname:renderArea?

*RESOLVED*: Yes, and the `apiext:VK_QCOM_multiview_per_view_viewports` may
help here since it provides per-view scissors.

5) When per-view render areas are specified, what purpose if any do
slink:VkRenderPassBeginInfo::pname:renderArea and
slink:VkRenderingInfo::pname:renderArea serve?

*RESOLVED*: The per-view pname:renderArea effectively overrides the
per-renderpass pname:renderArea.
The per-view pname:renderArea defines the regions of the attachments that
are effected by load, store, and multisample resolve operations.
A valid implementation could ignore the per-renderpass pname:renderArea.
However, as an aid to the implementation, the application must set the
per-renderpass pname:renderArea to an area that is at least as large as the
union of all the per-view render areas.
Pixels that are within the per-renderpass pname:renderArea but not within
any per-view render area must not be affected by load, store, or multisample
resolve operations.

=== Version History

  * Revision 1, 2023-01-10 (Jeff Leger)
