// Copyright 2025-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_QCOM_queue_perf_hint.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-02-26
*IP Status*::
    No known IP claims.
*Interactions and External Dependencies*::
  - Interacts with `apiext:VK_KHR_internally_synchronized_queues`
*Contributors*::
  - Matthew Netsch, Qualcomm Technologies, Inc

=== Description

This extension exposes power constraints to the application, allowing it to
provide hints for influencing the device's clock frequency.

These hints are sname:VkQueue state and are persistent across the life of
the queue until the app updates or removes the constraint.
The kernel combines the constraints across the active queues from all
processes to determine the actual clock frequency levels.

include::{generated}/interfaces/VK_QCOM_queue_perf_hint.adoc[]

=== Issues

None.

=== Version History

  * Revision 1, 2026-02-26 (Matthew Netsch)
