// Copyright 2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_SEC_throttle_hint.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-04-09
*IP Status*::
    No known IP claims.
*Contributors*::
  - Jonghyuk Eun, Samsung
  - Minyoung Son, Samsung
  - Jihyoung Hong, Samsung
  - Pavan Lanka, Samsung
  - Ralph Potter, Samsung


=== Description

This extension is intended to convey throttle hints to the device, but does
not specify the throttling behavior or any minimum guarantees.
This extension is intended to communicate information from layered API
implementations such as ANGLE to internal proprietary system schedulers.

It has no behavioral implications beyond enabling more intelligent behavior
from the system scheduler.

Application developers should avoid using this extension.
It is documented solely for the benefit of tools and layer developers, who
may need to manipulate pname:pNext chains that include these structures.

[NOTE]
====
There is currently no specification language written for this extension.
The links to APIs defined by the extension are to stubs that only include
generated content such as API declarations and implicit valid usage
statements.
====

[NOTE]
====
This extension is only intended for use in specific embedded environments
with known implementation details, and is therefore undocumented.
====

include::{generated}/interfaces/VK_SEC_throttle_hint.adoc[]

ifndef::isrefpage[]

=== Stub API References

[open,refpage='VkPhysicalDeviceThrottleHintFeaturesSEC',desc='Stub description of VkPhysicalDeviceThrottleHintFeaturesSEC',type='structs']
--
[[features-throttleHint]]
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkPhysicalDeviceThrottleHintFeaturesSEC.adoc[]

include::{generated}/validity/structs/VkPhysicalDeviceThrottleHintFeaturesSEC.adoc[]
--

[open,refpage='VkThrottleHintSubmitInfoSEC',desc='Stub description of VkThrottleHintSubmitInfoSEC',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkThrottleHintSubmitInfoSEC.adoc[]

include::{generated}/validity/structs/VkThrottleHintSubmitInfoSEC.adoc[]
--

[open,refpage='VkThrottleHintTypeSEC',desc='Stub description of VkThrottleHintTypeSEC',type='enums']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/enums/VkThrottleHintTypeSEC.adoc[]
--

endif::isrefpage[]

=== Version History

  * Revision 1, 2026-04-09 (Ralph Potter)
  ** Initial specification
