// Copyright 2014-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_SEC_ubm_surface.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-01-26
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ralph Potter, Samsung
  - Isaac Hong, Samsung
  - Jaeyoung Park, Samsung
  - Changhwan Lee, Samsung
  - Minji Choe, Samsung
  - Krzysztof Buben, Samsung
  - Mikolaj Chadzynski, Samsung
  - Bohdan Soproniuk, Samsung

=== Description

The `VK_SEC_ubm_surface` extension is an instance extension.
It provides a mechanism to create a slink:VkSurfaceKHR object (defined by
the `apiext:VK_KHR_surface` extension) that refers to a UBM
code:ubm_surface, as well as a query to determine support for rendering to a
UBM compositor.

include::{generated}/interfaces/VK_SEC_ubm_surface.adoc[]

=== Issues

1) Does UBM need a way to query for compatibility between a particular
physical device and a specific screen? This would be a more general query
than flink:vkGetPhysicalDeviceSurfaceSupportKHR: If it returned
ename:VK_TRUE, then the physical device could be assumed to support
presentation to any window on that screen.

*RESOLVED*: Yes.
flink:vkGetPhysicalDeviceUbmPresentationSupportSEC was added to address this
issue.

=== Version History

  * Revision 1, 2026-01-30 (Krzysztof Buben)
  ** Initial draft, based on the previous contents of VK_EXT_KHR_swapchain
     (later renamed VK_EXT_KHR_surface).
