// Copyright 2020-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_SEC_amigo_profiling.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-07-29
*IP Status*::
    No known IP claims.
*Contributors*::
  - Ralph Potter, Samsung
  - Sangrak Oh, Samsung
  - Jinku Kang, Samsung

=== Description

This extension is intended to communicate information from layered API
implementations such as ANGLE to internal proprietary system schedulers.
It has no behavioural implications beyond enabling more intelligent
behaviour from the system scheduler.

Application developers should avoid using this extension.
It is documented solely for the benefit of tools and layer developers, who
may need to manipulate pname:pNext chains that include these structures.

[NOTE]
.Note
====
There is currently no specification language written for this extension.
The links to APIs defined by the extension are to stubs that only include
generated content such as API declarations and implicit valid usage
statements.
====

[NOTE]
.Note
====
This extension is only intended for use in specific embedded environments
with known implementation details, and is therefore undocumented.
====

include::{generated}/interfaces/VK_SEC_amigo_profiling.adoc[]

ifndef::isrefpage[]

=== Stub API References

[open,refpage='VkPhysicalDeviceAmigoProfilingFeaturesSEC',desc='Stub description of VkPhysicalDeviceAmigoProfilingFeaturesSEC',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkPhysicalDeviceAmigoProfilingFeaturesSEC.adoc[]

include::{generated}/validity/structs/VkPhysicalDeviceAmigoProfilingFeaturesSEC.adoc[]
--

[open,refpage='VkAmigoProfilingSubmitInfoSEC',desc='Stub description of VkAmigoProfilingSubmitInfoSEC',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkAmigoProfilingSubmitInfoSEC.adoc[]

include::{generated}/validity/structs/VkAmigoProfilingSubmitInfoSEC.adoc[]
--

endif::isrefpage[]

=== Version History

  * Revision 1, 2022-07-29 (Ralph Potter)
  ** Initial specification
