// Copyright 2020-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_SEC_pipeline_cache_incremental_mode.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2025-06-24
*IP Status*::
    No known IP claims.
*Contributors*::
  - Chris Hambacher, Samsung
  - Mohan Maiya, Samsung
  - Brandon Schade, Samsung

=== Description
This extension allows layered implementations such as ANGLE to modify the
default behavior of VkPipelineCache to return only the incremental data from
the previous call to vkGetPipelineCacheData.
Application developers should avoid using this extension.

[NOTE]
====
There is currently no specification language written for this extension.
The links to APIs defined by the extension are to stubs that only include
generated content such as API declarations and implicit valid usage
statements.
====

[NOTE]
====
This extension is only intended for use in specific embedded environments
with known implementation details, and is therefore undocumented.
====

include::{generated}/interfaces/VK_SEC_pipeline_cache_incremental_mode.adoc[]

ifndef::isrefpage[]

=== Stub API References

[open,refpage='VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC',desc='Stub description of VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC',type='structs']
--
[[features-pipelineCacheIncrementalMode]]
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC.adoc[]

include::{generated}/validity/structs/VkPhysicalDevicePipelineCacheIncrementalModeFeaturesSEC.adoc[]
--

endif::isrefpage[]

=== Version History

  * Revision 1, 2025-06-24 (Chris Hambacher)
  ** Initial specification
