// Copyright 2020-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_VALVE_descriptor_set_host_mapping.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2022-02-22
*IP Status*::
    No known IP claims.
*Contributors*::
  - Hans-Kristian Arntzen, Valve

=== Description

This extension allows applications to directly query a host pointer for a
slink:VkDescriptorSet which can: be used to copy descriptors between
descriptor sets without the use of an API command.
Memory offsets and sizes for descriptors can: be queried from a
slink:VkDescriptorSetLayout as well.

[NOTE]
.Note
====
There is currently no specification language written for this extension.
The links to APIs defined by the extension are to stubs that only include
generated content such as API declarations and implicit valid usage
statements.
====

[NOTE]
.Note
====
This extension is only intended for use in specific embedded environments
with known implementation details, and is therefore undocumented.
====

include::{generated}/interfaces/VK_VALVE_descriptor_set_host_mapping.adoc[]

ifndef::isrefpage[]

=== Stub API References

[open,refpage='vkGetDescriptorSetLayoutHostMappingInfoVALVE',desc='Stub description of vkGetDescriptorSetLayoutHostMappingInfoVALVE',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkGetDescriptorSetLayoutHostMappingInfoVALVE.adoc[]

include::{generated}/validity/protos/vkGetDescriptorSetLayoutHostMappingInfoVALVE.adoc[]
--

[open,refpage='vkGetDescriptorSetHostMappingVALVE',desc='Stub description of vkGetDescriptorSetHostMappingVALVE',type='protos']
--
There is currently no specification language written for this command.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/protos/vkGetDescriptorSetHostMappingVALVE.adoc[]

include::{generated}/validity/protos/vkGetDescriptorSetHostMappingVALVE.adoc[]
--

[open,refpage='VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE',desc='Stub description of VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE.adoc[]

include::{generated}/validity/structs/VkPhysicalDeviceDescriptorSetHostMappingFeaturesVALVE.adoc[]
--

[open,refpage='VkDescriptorSetBindingReferenceVALVE',desc='Stub description of VkDescriptorSetBindingReferenceVALVE',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkDescriptorSetBindingReferenceVALVE.adoc[]

include::{generated}/validity/structs/VkDescriptorSetBindingReferenceVALVE.adoc[]
--

[open,refpage='VkDescriptorSetLayoutHostMappingInfoVALVE',desc='Stub description of VkDescriptorSetLayoutHostMappingInfoVALVE',type='structs']
--
There is currently no specification language written for this type.
This section acts only as placeholder and to avoid dead links in the
specification and reference pages.

include::{generated}/api/structs/VkDescriptorSetLayoutHostMappingInfoVALVE.adoc[]

include::{generated}/validity/structs/VkDescriptorSetLayoutHostMappingInfoVALVE.adoc[]
--

endif::isrefpage[]

=== Version History

  * Revision 1, 2022-02-22 (Hans-Kristian Arntzen)
  ** Initial specification
