// Copyright 2020-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

include::{generated}/meta/{refprefix}VK_VALVE_buffer_device_address_allocation_alignment.adoc[]

=== Other Extension Metadata

*Last Modified Date*::
    2026-08-26
*IP Status*::
    No known IP claims.
*Contributors*::
  - Hans-Kristian Arntzen, Valve
  - Connor Abbott, Valve

=== Description

This extension allows applications to specify the alignment of any buffer
device address allocation, beyond the current specification requirements
which only requires that the memory has enough alignment to satisfy any
alignment request the implementation may require on its own.

When layering some other APIs, e.g. D3D12, applications are sometimes able
to rely on the allocated buffer device address being aligned to a
potentially larger alignment than what the implementation would normally
allocate for.
Some applications rely on this implementation detail and will behave in
unexpected ways if tighter alignments are used.
flink:vkAllocateMemory as well as sparse buffer creation is affected by this
and this extension adds extra requirements on the implementation when
requested by application.

include::{generated}/interfaces/VK_VALVE_buffer_device_address_allocation_alignment.adoc[]

=== Version History

  * Revision 1, 2026-08-26 (Hans-Kristian Arntzen)
  ** Initial specification

