#!/usr/bin/env python3
#
# Copyright 2022-2024 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

"""Used to generate Antora `nav.adoc` for the Vulkan 'features' module.

Usage: `antora-nav-features.py [-root path] -component path [-roadmap path] files`

- `-root` is the root path (repository root, usually) relative to which
  files are processed. Defaults to current directory if not specified.
- `-component` is the path to the module and component in which converted
  files are written (e.g. the component directory under which pages/,
  partials/, images/, etc. are located).
- `-navfile` is the filename (not path) of the navigation file, and defaults
  to `nav.adoc` if not present
- `-roadmappath` is the path to the Vulkan Roadmap, which is grouped
  separately from the individual feature descriptions.
- `-templatepath` is the path to the proposal template, which is grouped
  separately from the individual extension feature descriptions.
  This argument is no longer used.
- Remaining arguments are paths to individual feature descriptions.

The only file generated is `component`/nav.adoc, which is the top-level
navigation file for the module.
All the input paths are turned into links within nav.adoc.
"""

import argparse
import importlib
import os
import sys
from pathlib import Path

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('-root', action='store', dest='root',
                        default=os.getcwd(),
                        help='Specify root directory under which files are located (default current directory)')
    parser.add_argument('-component', action='store', dest='component',
                        required=True,
                        help='Specify module / component directory in which the features navigation file "nav.adoc" is written')
    parser.add_argument('-navfile', action='store', dest='navfile',
                        default='nav.adoc', required=False,
                        help='Specify filename of features module navigation file (default nav.adoc)')
    parser.add_argument('-roadmappath', action='store', dest='roadmappath',
                        default=None, required=False,
                        help='Specify path to Roadmap.adoc containing the Vulkan 2022 Roadmap')
    parser.add_argument('-templatepath', action='store', dest='templatepath',
                        default=None, required=False,
                        help='Specify path to the template.adoc used to create new feature descriptions')
    parser.add_argument('files', metavar='filename', nargs='*',
                        help='Specify name of a single feature description to index')

    args = parser.parse_args()

    args.root = os.path.abspath(args.root)
    args.component = os.path.abspath(args.component)

    # Write the navigation file
    path = Path(args.component) / args.navfile

    try:
        fp = open(path, 'w', encoding='utf8')
    except:
        raise RuntimeError(f'Cannot write navigation file {path}')

    # Boilerplate

    print('// Copyright 2024 The Khronos Group Inc.',
          '// {}-License-Identifier: CC-BY-4.0'.format('SPDX'),
          '',
          '// This file is generated by the scripts/antora-nav-features.py script.',
          '// To make changes, modify that script.',
          '',
          ':chapters:',
          '',
          '* xref:index.adoc[Vulkan Roadmap and Feature Descriptions]',
          sep='\n', file=fp)

    # Roadmap
    if args.roadmappath is not None:
        relpath = os.path.relpath(os.path.abspath(args.roadmappath), args.root)
        print(f'* xref:{relpath}[Vulkan Roadmap]',
              sep='\n', file=fp)

    # Individual feature descriptions
    print('* Feature Descriptions', file=fp)
    features = set()
    for filename in args.files:
        relpath = os.path.relpath(os.path.abspath(filename), args.root)
        features.add(relpath)
    for relpath in sorted(features):
        print(f'** xref:{relpath}[]', file=fp)

    # Template
    if args.templatepath is not None:
        relpath = os.path.relpath(os.path.abspath(args.templatepath), args.root)
        print('* Extension Feature Descriptions',
              f'** xref:{relpath}[]',
              sep='\n', file=fp)

    fp.close()

