#!/bin/bash
# Copyright 2022-2025 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# runDocker - run the Khronos `asciidoctor-spec` Docker image with a local
# clone of the Vulkan specification repository. This must be invoked from
# the repository root directory.
# The following command-line tools are required to run this script:
#   awk dirname docker grep id realpath
# These are all normal Linux developer tools except for 'docker' itself.

# Determine path to repository root directory
scriptpath=$(dirname "$0")
repopath=$(realpath "$scriptpath/..")

# Get SHA256 of the asciidoctor-spec image build used by CI.
image=$(grep -m 1 khronosgroup/docker-images@sha256: "$repopath/.gitlab-ci.yml" |
  awk '{print $2}')

uid=$(id -u)
gid=$(id -g)
echo "Executing Docker with spec build image and mounted spec repository root:"

# If arguments are given, run them inside the container.
# Otherwise default to interactive shell.
if [ $# -gt 0 ]; then
  cmd="$*"
else
  cmd="/bin/bash"
fi

set -x
MSYS_NO_PATHCONV=1 docker run \
  --network=host \
  --user ${uid}:${gid} \
  -it --rm \
  -v "${repopath}:/vulkan" \
  $image /bin/bash -lc "$cmd"
