#!/bin/bash
# Copyright 2022-2024 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# runPodman - run the Khronos `asciidoctor-spec` Docker image with a local
# clone of the Vulkan specification repository. This must be invoked from
# the repository root directory.
# The following command-line tools are required to run this script:
#   awk dirname podman grep realpath
# These are all normal Linux developer tools except for 'podman' itself.

# Determine path to repository root directory
scriptpath=`dirname $0`
repopath=`realpath $scriptpath/..`

# Get SHA256 of the asciidoctor-spec image build used by CI.
image=`grep -m 1 khronosgroup/docker-images@sha256: $repopath/.gitlab-ci.yml | \
    awk '{print $2}'`
# The image is hosted on Dockerhub
image=docker.io/${image}

echo "Executing Podman with spec build image and mounted spec repository root:"

# --user runs as root in the unprivileged container, matching the FS user
# -it runs interactively and uses a pseudotty
# --rm removes the container on exit
# -v mounts the repository clone as /vulkan in the container
# $image is image to run
# /bin/bash drops into a shell in the container
set -x
podman run --network=host --user root -it --rm -v ${repopath}:/vulkan:Z $image /bin/bash
