# Do not edit this file, unless reserving a new VUID range
# VUID ranges reserved for branches
# Key is branch name, value is [ start, end, nextfree ]
# New reservations must be made by MR to main branch
vuidCounts = {
    'sc_1_0': [ 5000, 5199, 5156 ],
    'NV_private_vendor_info': [ 5130, 5134, 5130 ],
    'sc_main': [ 5200, 5999, 5203 ],
    'tobias/VK_EXT_hlsl_binding_semantics': [ 6818, 6843, 6818 ],
    'aqnuep1/video-encode-specs': [ 8201, 8399, 8378 ],
    'main': [ 8700, 10999, 10910 ],
    'stus/VK_KHR_maintenance5': [ 8762, 8861, 8809 ],
    'aqnuep1/VK_KHR_video_decode_av1': [ 9248, 9297, 9264 ],
    'VK_KHR_pipeline_binary': [ 9602, 9627, 9623 ],
    'VK_EXT_depth_clamp_control': [ 9646, 9650, 9646 ],
    'VK_ARM_tensors_graph_tosa_neural_engine': [ 9682, 9999, 9682 ],
    'rpotter-VK_EXT_device_progress_marker-proposal': [ 10013, 10050, 10023 ],
    'cooperative_vector': [ 10073, 10125, 10102 ],
    'jbolz_coopmat2': [ 10163, 10180, 10170 ],
    'VK_KHR_maintenance8': [ 10200, 10240, 10219 ],
    'VK_KHR_shader_int4': [ 10361, 10381, 10361 ],
    'VK_EXT_device_generated_command': [ 11000, 11160, 11155 ],
    'VK_KHR_shader_untyped_pointers': [ 11161, 11199, 11161 ],
    'tobias-dh': [ 11200, 11399, 11200 ],
}
