#! /bin/bash
#
# Copyright 2023-2024 The Khronos Group Inc.
#
# SPDX-License-Identifier: Apache-2.0

echo "Note: If not already, run 'testBuild' first to generate gen-*/"

for build in gen-*; do
  if [ "$build" == gen-validusage ]; then continue; fi

  output=$build/out/html/vkspec-body.html
  expectation=expectations/${build#gen-}.html

  cp -f "$output" "$expectation"
done

cp -f gen-validusage/out/validation/validusage.json expectations/validusage.json
