// Copyright 2023 QNX Software Systems
//
// SPDX-License-Identifier: CC-BY-4.0

[[qnx-screen-buffer-external-memory]]
=== QNX Screen Buffer External Memory

[open,refpage='VkImportScreenBufferInfoQNX',desc='Import memory from a QNX Screen buffer',type='structs']
--
To import memory created outside of the current Vulkan instance from a QNX
Screen buffer, add a sname:VkImportScreenBufferInfoQNX structure to the
pname:pNext chain of the slink:VkMemoryAllocateInfo structure.
The sname:VkImportScreenBufferInfoQNX structure is defined as:

include::{generated}/api/structs/VkImportScreenBufferInfoQNX.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:buffer is a pointer to a code:struct code:_screen_buffer, the QNX
    Screen buffer to import

The implementation may: not acquire a reference to the imported Screen
buffer.
Therefore, the application must: ensure that the object referred to by
pname:buffer stays valid as long as the device memory to which it is
imported is being used.

.Valid Usage
****
  * [[VUID-VkImportScreenBufferInfoQNX-buffer-08966]]
    If pname:buffer is not `NULL`, QNX Screen Buffers must: be supported for
    import, as reported by slink:VkExternalImageFormatProperties or
    slink:VkExternalBufferProperties
  * [[VUID-VkImportScreenBufferInfoQNX-buffer-08967]]
    pname:buffer is not `NULL`, it must: be a pointer to
    <<memory-external-screen-buffer-validity,valid QNX Screen buffer>>

****

include::{generated}/validity/structs/VkImportScreenBufferInfoQNX.adoc[]
--

[open,refpage='vkGetScreenBufferPropertiesQNX',desc='Get Properties of External Memory QNX Screen Buffers',type='protos']
--
To determine the memory parameters to use when importing a QNX Screen
buffer, call:

include::{generated}/api/protos/vkGetScreenBufferPropertiesQNX.adoc[]

  * pname:device is the logical device that will be importing pname:buffer.
  * pname:buffer is the QNX Screen buffer which will be imported.
  * pname:pProperties is a pointer to a slink:VkScreenBufferPropertiesQNX
    structure in which the properties of pname:buffer are returned.

.Valid Usage
****
  * [[VUID-vkGetScreenBufferPropertiesQNX-buffer-08968]]
    pname:buffer must: be a <<memory-external-screen-buffer-validity,valid
    QNX Screen buffer>>
****

include::{generated}/validity/protos/vkGetScreenBufferPropertiesQNX.adoc[]
--

[open,refpage='VkScreenBufferPropertiesQNX',desc='Properties of External Memory QNX Screen Buffers',type='structs']
--
The sname:VkScreenBufferPropertiesQNX structure returned is defined as:

include::{generated}/api/structs/VkScreenBufferPropertiesQNX.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:allocationSize is the size of the external memory.
  * pname:memoryTypeBits is a bitmask containing one bit set for every
    memory type which the specified Screen buffer can: be imported as.

include::{generated}/validity/structs/VkScreenBufferPropertiesQNX.adoc[]
--

[open,refpage='VkScreenBufferFormatPropertiesQNX',desc='Structure describing the image format properties of a QNX Screen buffer',type='structs']
--
To obtain format properties of a QNX Screen buffer, include a
sname:VkScreenBufferFormatPropertiesQNX structure in the pname:pNext chain
of the slink:VkScreenBufferPropertiesQNX structure passed to
flink:vkGetScreenBufferPropertiesQNX.
This structure is defined as:

include::{generated}/api/structs/VkScreenBufferFormatPropertiesQNX.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:format is the Vulkan format corresponding to the Screen buffer's
    format or ename:VK_FORMAT_UNDEFINED if there is not an equivalent Vulkan
    format.
  * pname:externalFormat is an implementation-defined external format
    identifier for use with slink:VkExternalFormatQNX.
    It must: not be zero.
  * pname:screenUsage is an implementation-defined external usage identifier
    for the QNX Screen buffer.
  * pname:formatFeatures describes the capabilities of this external format
    when used with an image bound to memory imported from pname:buffer.
  * pname:samplerYcbcrConversionComponents is the component swizzle that
    should: be used in slink:VkSamplerYcbcrConversionCreateInfo.
  * pname:suggestedYcbcrModel is a suggested color model to use in the
    slink:VkSamplerYcbcrConversionCreateInfo.
  * pname:suggestedYcbcrRange is a suggested numerical value range to use in
    slink:VkSamplerYcbcrConversionCreateInfo.
  * pname:suggestedXChromaOffset is a suggested X chroma offset to use in
    slink:VkSamplerYcbcrConversionCreateInfo.
  * pname:suggestedYChromaOffset is a suggested Y chroma offset to use in
    slink:VkSamplerYcbcrConversionCreateInfo.

If the QNX Screen buffer has one of the formats listed in the
<<memory-external-qnx-screen-buffer-formats,QNX Screen Format Equivalence
table>>, then pname:format must: have the equivalent Vulkan format listed in
the table.
Otherwise, pname:format may: be ename:VK_FORMAT_UNDEFINED, indicating the
QNX Screen buffer can: only be used with an external format.
The pname:formatFeatures member must: include
ename:VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT and should: include
ename:VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT and
ename:VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT.

include::{generated}/validity/structs/VkScreenBufferFormatPropertiesQNX.adoc[]
--
