// Copyright (c) 2019-2020 NVIDIA Corporation
// Copyright (c) 2024 VALVE Corporation
//
// SPDX-License-Identifier: CC-BY-4.0

== Indirect Commands Generation and Execution

The generation of commands on the device requires a `preprocess` buffer.

ifdef::VK_EXT_device_generated_commands[]
[open,refpage='vkGetGeneratedCommandsMemoryRequirementsEXT',desc='Retrieve the buffer allocation requirements for generated commands',type='protos']
--
With `apiext:VK_EXT_device_generated_commands`, to retrieve the memory size
and alignment requirements of a particular execution state call:

include::{generated}/api/protos/vkGetGeneratedCommandsMemoryRequirementsEXT.adoc[]

  * pname:device is the logical device that owns the buffer.
  * pname:pInfo is a pointer to a
    slink:VkGeneratedCommandsMemoryRequirementsInfoEXT structure containing
    parameters required for the memory requirements query.
  * pname:pMemoryRequirements is a pointer to a slink:VkMemoryRequirements2
    structure in which the memory requirements of the buffer object are
    returned.

If the size returned is zero, the preprocessing step can be skipped for this
layout.

include::{generated}/validity/protos/vkGetGeneratedCommandsMemoryRequirementsEXT.adoc[]
--

[open,refpage='VkGeneratedCommandsMemoryRequirementsInfoEXT',desc='Structure specifying parameters for the reservation of preprocess buffer space',type='structs']
--
include::{generated}/api/structs/VkGeneratedCommandsMemoryRequirementsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:indirectExecutionSet is the indirect execution set to be used for
    binding shaders.
  * pname:indirectCommandsLayout is the slink:VkIndirectCommandsLayoutEXT
    that this buffer memory is intended to be used with.
  * pname:maxSequenceCount is the maximum number of sequences that this
    buffer memory can be used with.
  * pname:maxDrawCount is the maximum number of indirect draws that can be
    executed by any COUNT-type multi-draw indirect tokens.
    The draw count in the indirect buffer is clamped to this value for these
    token types.

If the action command token for the layout is not a COUNT-type multi-draw
indirect token, pname:maxDrawCount is ignored.

.Valid Usage
****
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-maxSequencesCount-11009]]
    pname:maxSequencesCount must: be less or equal to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectSequenceCount
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-indirectCommandsLayout-11010]]
    If pname:indirectCommandsLayout was created with a token sequence that
    contained the ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, pname:indirectExecutionSet must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-indirectCommandsLayout-11151]]
    If pname:indirectCommandsLayout was created with a token sequence that
    contained the ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, the shader stages used to create the initial shader state of
    pname:indirectExecutionSet must: equal the
    slink:VkIndirectCommandsExecutionSetTokenEXT::pname:shaderStages used to
    create pname:indirectCommandsLayout
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-indirectCommandsLayout-11011]]
    If pname:indirectCommandsLayout was not created with a token sequence
    that contained the
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT token,
    pname:indirectExecutionSet must: be dlink:VK_NULL_HANDLE
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-maxDrawCount-11146]]
    When not ignored, [eq]#pname:maxDrawCount {times}
    pname:maxSequenceCount# must: be less than [eq]#2^24#
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoEXT-indirectExecutionSet-11012]]
    If pname:indirectExecutionSet is dlink:VK_NULL_HANDLE,
ifdef::VK_EXT_shader_object[either]
    a slink:VkGeneratedCommandsPipelineInfoEXT
ifdef::VK_EXT_shader_object[or a slink:VkGeneratedCommandsShaderInfoEXT]
    must: be included in the pname:pNext chain
****

include::{generated}/validity/structs/VkGeneratedCommandsMemoryRequirementsInfoEXT.adoc[]
--

[open,refpage='VkGeneratedCommandsPipelineInfoEXT',desc='Structure specifying a pipeline for use with indirect command preprocessing',type='structs']
--
include::{generated}/api/structs/VkGeneratedCommandsPipelineInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pipeline is a valid pipeline object.

include::{generated}/validity/structs/VkGeneratedCommandsPipelineInfoEXT.adoc[]
--

ifdef::VK_EXT_shader_object[]
[open,refpage='VkGeneratedCommandsShaderInfoEXT',desc='Structure specifying shader objects for use with indirect command preprocessing',type='structs']
--
include::{generated}/api/structs/VkGeneratedCommandsShaderInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:shaderCount is the size of the pname:pShaders array.
  * pname:pShaders is a pointer to an array of shader objects.

.Valid Usage
****
  * [[VUID-VkGeneratedCommandsShaderInfoEXT-pShaders-11127]]
    pname:pShaders must: not contain more than one shader object for a given
    elink:VkShaderStageFlagBits stage
****

include::{generated}/validity/structs/VkGeneratedCommandsShaderInfoEXT.adoc[]
--
endif::VK_EXT_shader_object[]
endif::VK_EXT_device_generated_commands[]

ifdef::VK_NV_device_generated_commands[]
[open,refpage='vkGetGeneratedCommandsMemoryRequirementsNV',desc='Retrieve the buffer allocation requirements for generated commands',type='protos']
--
With `apiext:VK_NV_device_generated_commands`, to retrieve the memory size
and alignment requirements of a particular execution state call:

include::{generated}/api/protos/vkGetGeneratedCommandsMemoryRequirementsNV.adoc[]

  * pname:device is the logical device that owns the buffer.
  * pname:pInfo is a pointer to a
    slink:VkGeneratedCommandsMemoryRequirementsInfoNV structure containing
    parameters required for the memory requirements query.
  * pname:pMemoryRequirements is a pointer to a slink:VkMemoryRequirements2
    structure in which the memory requirements of the buffer object are
    returned.

.Valid Usage
****
  * [[VUID-vkGetGeneratedCommandsMemoryRequirementsNV-deviceGeneratedCommands-02906]]
    The <<features-deviceGeneratedCommandsNV,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV::pname:deviceGeneratedCommands>>
    feature must: be enabled
ifdef::VK_NV_device_generated_commands_compute[]
  * [[VUID-vkGetGeneratedCommandsMemoryRequirementsNV-pInfo-09074]]
    If pname:pInfo->pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, then the
    <<features-deviceGeneratedCompute,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV::pname:deviceGeneratedCompute>>
    feature must: be enabled
endif::VK_NV_device_generated_commands_compute[]
****

include::{generated}/validity/protos/vkGetGeneratedCommandsMemoryRequirementsNV.adoc[]
--

[open,refpage='VkGeneratedCommandsMemoryRequirementsInfoNV',desc='Structure specifying parameters for the reservation of preprocess buffer space',type='structs']
--
include::{generated}/api/structs/VkGeneratedCommandsMemoryRequirementsInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pipelineBindPoint is the elink:VkPipelineBindPoint of the
    pname:pipeline that this buffer memory is intended to be used with
    during the execution.
  * pname:pipeline is the slink:VkPipeline that this buffer memory is
    intended to be used with during the execution.
  * pname:indirectCommandsLayout is the slink:VkIndirectCommandsLayoutNV
    that this buffer memory is intended to be used with.
  * pname:maxSequencesCount is the maximum number of sequences that this
    buffer memory in combination with the other state provided can: be used
    with.

.Valid Usage
****
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoNV-maxSequencesCount-02907]]
    pname:maxSequencesCount must: be less or equal to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV::pname:maxIndirectSequenceCount
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoNV-pipelineBindPoint-09075]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_GRAPHICS, then pname:pipeline must: be a
    valid slink:VkPipeline handle
ifdef::VK_NV_device_generated_commands_compute[]
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoNV-pipelineBindPoint-09076]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, and the
    pname:indirectCommandsLayout was not created with a
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV token, then the
    pname:pipeline must: be a valid slink:VkPipeline handle
  * [[VUID-VkGeneratedCommandsMemoryRequirementsInfoNV-pipelineBindPoint-09077]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, and the
    pname:indirectCommandsLayout contains a
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV token, then the
    pname:pipeline must: be dlink:VK_NULL_HANDLE
endif::VK_NV_device_generated_commands_compute[]
****

include::{generated}/validity/structs/VkGeneratedCommandsMemoryRequirementsInfoNV.adoc[]
--

ifdef::VK_NV_device_generated_commands_compute[]

With `apiext:VK_NV_device_generated_commands`, to bind a compute pipeline in
<<device-generated-commands,Device-Generated Commands>>, an application
must: query the pipeline's device address.

[open,refpage='vkGetPipelineIndirectDeviceAddressNV',desc='Get pipeline\'s 64-bit device address',type='protos']
--
:refpage: vkGetPipelineIndirectDeviceAddressNV

To query a compute pipeline's 64-bit device address, call:

include::{generated}/api/protos/vkGetPipelineIndirectDeviceAddressNV.adoc[]

  * pname:device is the logical device on which the pipeline was created.
  * pname:pInfo is a pointer to a
    slink:VkPipelineIndirectDeviceAddressInfoNV structure specifying the
    pipeline to retrieve the address for.

.Valid Usage
****
  * [[VUID-vkGetPipelineIndirectDeviceAddressNV-deviceGeneratedComputePipelines-09078]]
    The <<features-deviceGeneratedComputePipelines,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV::pname:deviceGeneratedComputePipelines>>
    feature must: be enabled
****

include::{generated}/validity/protos/vkGetPipelineIndirectDeviceAddressNV.adoc[]
--

[open,refpage='VkPipelineIndirectDeviceAddressInfoNV',desc='Structure specifying the pipeline to query an address for',type='structs']
--
:refpage: VkPipelineIndirectDeviceAddressInfoNV

The sname:VkPipelineIndirectDeviceAddressInfoNV structure is defined as:

include::{generated}/api/structs/VkPipelineIndirectDeviceAddressInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pipelineBindPoint is a elink:VkPipelineBindPoint value specifying
    the type of pipeline whose device address is being queried.
  * pname:pipeline specifies the pipeline whose device address is being
    queried.

.Valid Usage
****
  * [[VUID-VkPipelineIndirectDeviceAddressInfoNV-pipelineBindPoint-09079]]
    The provided pname:pipelineBindPoint must: be of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE
  * [[VUID-VkPipelineIndirectDeviceAddressInfoNV-pipeline-09080]]
    pname:pipeline must: have been created with flag
    ename:VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV set
  * [[VUID-VkPipelineIndirectDeviceAddressInfoNV-pipeline-09081]]
    pname:pipeline must: have been created with a
    slink:VkComputePipelineIndirectBufferInfoNV structure specifying a valid
    address where its metadata will be saved
****
include::{generated}/validity/structs/VkPipelineIndirectDeviceAddressInfoNV.adoc[]
--

[open,refpage='vkGetPipelineIndirectMemoryRequirementsNV',desc='Get the memory requirements for the compute indirect pipeline',type='protos']
--
:refpage: vkGetPipelineIndirectMemoryRequirementsNV

To determine the memory requirements for a compute pipeline's metadata,
call:

include::{generated}/api/protos/vkGetPipelineIndirectMemoryRequirementsNV.adoc[]

  * pname:device is the logical device that owns the buffer.
  * pname:pCreateInfo is a slink:VkComputePipelineCreateInfo structure
    specifying the creation parameters of the compute pipeline whose memory
    requirements are being queried.
  * pname:pMemoryRequirements is a pointer to a slink:VkMemoryRequirements2
    structure in which the requested pipeline's memory requirements are
    returned.

If pname:pCreateInfo->pNext chain includes a pointer to a
slink:VkComputePipelineIndirectBufferInfoNV structure, then the contents of
that structure are ignored.

.Valid Usage
****
  * [[VUID-vkGetPipelineIndirectMemoryRequirementsNV-deviceGeneratedComputePipelines-09082]]
    The <<features-deviceGeneratedComputePipelines,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsComputeFeaturesNV::pname:deviceGeneratedComputePipelines>>
    feature must: be enabled
  * [[VUID-vkGetPipelineIndirectMemoryRequirementsNV-pCreateInfo-09083]]
    pname:pCreateInfo->flags must: include
    ename:VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV
****

include::{generated}/validity/protos/vkGetPipelineIndirectMemoryRequirementsNV.adoc[]
--
endif::VK_NV_device_generated_commands_compute[]
endif::VK_NV_device_generated_commands[]

ifdef::VK_EXT_device_generated_commands[]
[[device-generated-indirect-execution-sets]]
=== Indirect Execution Sets

[open,refpage='VkIndirectExecutionSetEXT',desc='Opaque handle to an indirect execution set object',type='handles']
--
Indirect Execution Sets contain sets of pipelines
ifdef::VK_EXT_shader_object[]
or shader objects
endif::VK_EXT_shader_object[]
which can be bound individually.

include::{generated}/api/handles/VkIndirectExecutionSetEXT.adoc[]

Indirect Execution Sets allow the device to bind different shaders and
pipeline states using <<device-generated-commands>>.

--

[open,refpage='vkCreateIndirectExecutionSetEXT',desc='Create an indirect execution set',type='protos']
--
:refpage: vkCreateIndirectExecutionSetEXT

Indirect Execution Sets are created by calling:

include::{generated}/api/protos/vkCreateIndirectExecutionSetEXT.adoc[]

  * pname:device is the logical device that creates the indirect execution
    set.
  * pname:pCreateInfo is a pointer to a
    slink:VkIndirectExecutionSetCreateInfoEXT structure containing
    parameters affecting creation of the indirect execution set.
  * pname:pAllocator controls host memory allocation as described in the
    <<memory-allocation, Memory Allocation>> chapter.
  * pname:pIndirectExecutionSet is a pointer to a
    slink:VkIndirectExecutionSetEXT handle in which the resulting indirect
    execution set is returned.

.Valid Usage
****
  * [[VUID-vkCreateIndirectExecutionSetEXT-deviceGeneratedCommands-11013]]
    The <<features-deviceGeneratedCommands,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesEXT::pname:deviceGeneratedCommands>>
    feature must: be enabled
****

include::{generated}/validity/protos/vkCreateIndirectExecutionSetEXT.adoc[]
--

[open,refpage='VkIndirectExecutionSetCreateInfoEXT',desc='Structure specifying parameters of a newly created indirect execution set',type='structs']
--
The sname:VkIndirectExecutionSetCreateInfoEXT structure is defined as:

include::{generated}/api/structs/VkIndirectExecutionSetCreateInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:type is a elink:VkIndirectExecutionSetInfoTypeEXT describing the
    type of set being created and determining which field of the pname:info
    union will be used.
  * pname:info is a slink:VkIndirectExecutionSetInfoEXT union containing
    layout information for the set.

.Valid Usage
****
  * [[VUID-VkIndirectExecutionSetCreateInfoEXT-maxIndirectShaderObjectCount-11014]]
    If
    sname:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectShaderObjectCount
    is zero
ifdef::VK_EXT_shader_object[]
    or the <<features-shaderObject, pname:shaderObject>> feature is not
    enabled
endif::VK_EXT_shader_object[]
    pname:type must: not be
    ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT
****

include::{generated}/validity/structs/VkIndirectExecutionSetCreateInfoEXT.adoc[]
--

[open,refpage='VkIndirectExecutionSetInfoTypeEXT',desc='Enum specifying allowed usage of an indirect execution set',type='enums']
--

Values which can: be set in
slink:VkIndirectExecutionSetCreateInfoEXT::pname:type, specifying contents
of an indirect execution set, are:

include::{generated}/api/enums/VkIndirectExecutionSetInfoTypeEXT.adoc[]

  * ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT specifies that
    the indirect execution set contains slink:VkPipeline objects.
ifdef::VK_EXT_shader_object[]
  * ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT specifies
    that the indirect execution set contains slink:VkShaderEXT objects.
endif::VK_EXT_shader_object[]
ifndef::VK_EXT_shader_object[]
  * ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT must: not
    be used.
endif::VK_EXT_shader_object[]
--

[open,refpage='VkIndirectExecutionSetInfoEXT',desc='Union specifying parameters of a newly created indirect execution set',type='structs']
--
The sname:VkIndirectExecutionSetInfoEXT union is defined as:

include::{generated}/api/structs/VkIndirectExecutionSetInfoEXT.adoc[]

  * pname:pPipelineInfo is a pointer to a
    slink:VkIndirectExecutionSetPipelineInfoEXT struct containing pipeline
    layout information for the set.
  * pname:pShaderInfo is a pointer to a
    slink:VkIndirectExecutionSetShaderInfoEXT struct containing shader
    object layout information for the set.

include::{generated}/validity/structs/VkIndirectExecutionSetInfoEXT.adoc[]
--

[open,refpage='VkIndirectExecutionSetPipelineInfoEXT',desc='Struct specifying parameters of a newly created indirect execution set containing only pipelines',type='structs']
--
The sname:VkIndirectExecutionSetPipelineInfoEXT structure is defined as:

include::{generated}/api/structs/VkIndirectExecutionSetPipelineInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:initialPipeline is the initial pipeline for the set.
    This pipeline will be automatically added to the set at index `0`.
  * pname:maxPipelineCount is the maximum number of pipelines stored in the
    set.

The characteristics of pname:initialPipeline will be used to validate all
pipelines added to the set even if they are removed from the set or
destroyed.

When an Indirect Execution Set created with pipelines is used,
pname:initialPipeline constitutes the initial shader state.

.Valid Usage
****
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-supportedIndirectCommandsShaderStagesPipelineBinding-11015]]
    If <<limits-supportedIndirectCommandsShaderStagesPipelineBinding,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStagesPipelineBinding>>
    does not contain ename:VK_SHADER_STAGE_COMPUTE_BIT, the
    ename:VkPipelineBindPoint of pname:initialPipeline must: not be
    ename:VK_PIPELINE_BIND_POINT_COMPUTE
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-supportedIndirectCommandsShaderStagesPipelineBinding-11016]]
    If <<limits-supportedIndirectCommandsShaderStagesPipelineBinding,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStagesPipelineBinding>>
    does not contain ename:VK_SHADER_STAGE_FRAGMENT_BIT, the
    ename:VkPipelineBindPoint of pname:initialPipeline must: not be
    ename:VK_PIPELINE_BIND_POINT_GRAPHICS
ifdef::VK_KHR_ray_tracing_pipeline[]
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-supportedIndirectCommandsShaderStagesPipelineBinding-11017]]
    If <<limits-supportedIndirectCommandsShaderStagesPipelineBinding,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStagesPipelineBinding>>
    does not contain ray tracing stages, the ename:VkPipelineBindPoint of
    pname:initialPipeline must: not be
    ename:VK_PIPELINE_BIND_POINT_RAY_TRACING_KHR
endif::VK_KHR_ray_tracing_pipeline[]
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-maxPipelineCount-11018]]
    pname:maxPipelineCount must: be between `1` and
    sname:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectPipelineCount
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-initialPipeline-11019]]
    pname:initialPipeline must: not use descriptors of type
    ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC or
    ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC
  * [[VUID-VkIndirectExecutionSetPipelineInfoEXT-initialPipeline-11153]]
    pname:initialPipeline must: have been created with
    ename:VK_PIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_EXT
****

include::{generated}/validity/structs/VkIndirectExecutionSetPipelineInfoEXT.adoc[]
--

[open,refpage='VkIndirectExecutionSetShaderInfoEXT',desc='Struct specifying parameters of a newly created indirect execution set containing only shader objects',type='structs']
--
The sname:VkIndirectExecutionSetShaderInfoEXT structure is defined as:

include::{generated}/api/structs/VkIndirectExecutionSetShaderInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:shaderCount is the number of members in the pname:pInitialShaders
    and pname:pSetLayoutInfos arrays.
  * pname:pInitialShaders is a pointer to an array containing a
    slink:VkShaderEXT object for each shader stage that will be used in the
    set.
    These shaders will be automatically added to the set beginning at index
    `0`.
  * pname:pSetLayoutInfos is a pointer to an array containing a
    slink:VkIndirectExecutionSetShaderLayoutInfoEXT used by each
    corresponding pname:pInitialShaders shader stage in the set.
  * pname:maxShaderCount is the maximum number of shader objects stored in
    the set.
  * pname:pushConstantRangeCount is the number of members in the
    pname:pPushConstantRanges array.
  * pname:pPushConstantRanges is a pointer to the array of
    slink:VkPushConstantRange ranges used by all shaders in the set.

The characteristics of pname:pInitialShaders will be used to validate all
shaders added to the set even if they are removed from the set or destroyed.

When an Indirect Execution Set created with shader objects is used,
pname:pInitialShaders constitutes the initial shader state.

.Valid Usage
****
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-pInitialShaders-11020]]
    All members of pname:pInitialShaders must: have a pname:stage supported
    by <<limits-supportedIndirectCommandsShaderStagesShaderBinding,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStagesShaderBinding>>
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-maxShaderCount-11021]]
    pname:maxShaderCount must: not be zero
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-maxShaderCount-11022]]
    pname:maxShaderCount must: be less than or equal to
    sname:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectShaderObjectCount
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-maxShaderCount-11036]]
    pname:maxShaderCount must: be greater than or equal to pname:shaderCount
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-stage-11023]]
    The pname:stage of each element in the pname:pInitialShaders array must:
    be unique
  * [[VUID-VkIndirectExecutionSetShaderInfoEXT-pInitialShaders-11154]]
    Each member of pname:pInitialShaders must: have been created with
    ename:VK_SHADER_CREATE_INDIRECT_BINDABLE_BIT_EXT
****

include::{generated}/validity/structs/VkIndirectExecutionSetShaderInfoEXT.adoc[]
--

[open,refpage='VkIndirectExecutionSetShaderLayoutInfoEXT',desc='Struct specifying descriptor layout parameters of a newly created indirect execution set containing only shader objects',type='structs']
--
The sname:VkIndirectExecutionSetShaderLayoutInfoEXT structure is defined as:

include::{generated}/api/structs/VkIndirectExecutionSetShaderLayoutInfoEXT.adoc[]

  * pname:setLayoutCount is the number of members in the pname:pSetLayouts
    array
  * pname:pSetLayouts is a pointer to an array containing
    slink:VkDescriptorSetLayout objects used by the shader stage.

.Valid Usage
****
  * [[VUID-VkIndirectExecutionSetShaderLayoutInfoEXT-pSetLayouts-11024]]
    All members of pname:pSetLayouts must: not contain descriptors of type
    ename:VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC or
    ename:VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC
****

include::{generated}/validity/structs/VkIndirectExecutionSetShaderLayoutInfoEXT.adoc[]
--

[open,refpage='vkDestroyIndirectExecutionSetEXT',desc='Destroy an indirect execution set',type='protos']
--
:refpage: vkDestroyIndirectExecutionSetEXT

Destroy an Indirect Execution Set by calling:

include::{generated}/api/protos/vkDestroyIndirectExecutionSetEXT.adoc[]

  * pname:device is the logical device that owns the indirect execution set.
  * pname:indirectExecutionSet is the indirect execution set to destroy.
  * pname:pAllocator controls host memory allocation as described in the
    <<memory-allocation, Memory Allocation>> chapter.

.Valid Usage
****
  * [[VUID-vkDestroyIndirectExecutionSetEXT-indirectExecutionSet-11025]]
    All submitted commands that refer to pname:indirectExecutionSet must:
    have completed execution
****

include::{generated}/validity/protos/vkDestroyIndirectExecutionSetEXT.adoc[]
--

[open,refpage='VkWriteIndirectExecutionSetPipelineEXT',desc='Struct specifying pipeline update information for an indirect execution set',type='structs']
--
The sname:VkWriteIndirectExecutionSetPipelineEXT struct is defined as:

include::{generated}/api/structs/VkWriteIndirectExecutionSetPipelineEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:index is the element of the set to update
  * pname:pipeline is the pipeline to store in the indirect execution set

.Valid Usage
****
  * [[VUID-VkWriteIndirectExecutionSetPipelineEXT-index-11026]]
    pname:index must: be less than the value of
    sname:VkIndirectExecutionSetPipelineInfoEXT::pname:maxPipelineCount used
    to create the set
  * [[VUID-VkWriteIndirectExecutionSetPipelineEXT-pipeline-11027]]
    pname:pipeline must: have been created with
    ename:VK_PIPELINE_CREATE_2_INDIRECT_BINDABLE_BIT_EXT
  * [[VUID-VkWriteIndirectExecutionSetPipelineEXT-index-11029]]
    pname:index must: not be referenced by submitted command buffers
  * [[VUID-VkWriteIndirectExecutionSetPipelineEXT-pipeline-11030]]
    The shader stages contained in pname:pipeline must: be supported by
    <<limits-supportedIndirectCommandsShaderStagesPipelineBinding,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStagesPipelineBinding>>
****

include::{generated}/validity/structs/VkWriteIndirectExecutionSetPipelineEXT.adoc[]
--

[open,refpage='VkWriteIndirectExecutionSetShaderEXT',desc='Struct specifying shader object update information for an indirect execution set',type='structs']
--
The sname:VkWriteIndirectExecutionSetShaderEXT struct is defined as:

include::{generated}/api/structs/VkWriteIndirectExecutionSetShaderEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:index is the element of the set to update
  * pname:shader is the shader to store in the indirect execution set

Shaders need not be stored in the Indirect Execution Set according to their
stage.
The only restriction for shader indices within a set is that the value of
the index must: be less than the maximum number of shaders in the set.

.Valid Usage
****
  * [[VUID-VkWriteIndirectExecutionSetShaderEXT-index-11031]]
    pname:index must: be less than
    sname:VkIndirectExecutionSetShaderInfoEXT::pname:maxShaderCount
  * [[VUID-VkWriteIndirectExecutionSetShaderEXT-shader-11032]]
    pname:shader must: have been created with
    ename:VK_SHADER_CREATE_INDIRECT_BINDABLE_BIT_EXT
  * [[VUID-VkWriteIndirectExecutionSetShaderEXT-pInitialShaders-11033]]
    A shader created with the same elink:VkShaderStageFlagBits must: have
    been passed in the
    sname:VkIndirectExecutionSetShaderInfoEXT::pname:pInitialShaders array
  * [[VUID-VkWriteIndirectExecutionSetShaderEXT-index-11034]]
    pname:index must: not be in use by submitted command buffers
****

include::{generated}/validity/structs/VkWriteIndirectExecutionSetShaderEXT.adoc[]
--

[open,refpage='vkUpdateIndirectExecutionSetPipelineEXT',desc='Update the contents of an indirect execution set',type='protos']
--
:refpage: vkUpdateIndirectExecutionSetPipelineEXT

Pipeline elements in an Indirect Execution Set can be updated by calling:

include::{generated}/api/protos/vkUpdateIndirectExecutionSetPipelineEXT.adoc[]

  * pname:device is the logical device that owns the indirect execution set.
  * pname:indirectExecutionSet is the indirect execution set being updated.
  * pname:executionSetWriteCount is the number of elements in the
    pname:pExecutionSetWrites array.
  * pname:pExecutionSetWrites is a pointer to an array of
    slink:VkWriteIndirectExecutionSetPipelineEXT structures describing the
    elements to update.

.Valid Usage
****
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-indirectExecutionSet-11035]]
    pname:indirectExecutionSet must: have been created with type
    ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-executionSetWriteCount-11037]]
    pname:executionSetWriteCount must: be less than or equal to
    sname:VkIndirectExecutionSetPipelineInfoEXT::pname:maxPipelineCount
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-pExecutionSetWrites-11042]]
    Each element in the pname:pExecutionSetWrites array must have a unique
    sname:VkWriteIndirectExecutionSetPipelineEXT::pname:index
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-None-11038]]
    Each member of the Indirect Execution Set referenced by the update
    command must: not be in use by the device
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-None-11039]]
    The layout of each pipeline in pname:pExecutionSetWrites must: be
    <<descriptorsets-compatibility,compatible>> with the
    pname:initialPipeline used to create the Indirect Execution Set
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-None-11040]]
    Each pipeline in the Indirect Execution Set must: have identically
    defined static and dynamic state values to the pname:initialPipeline
    used to create the Indirect Execution Set
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-initialPipeline-11147]]
    Each pipeline in the Indirect Execution Set must: have identically
    defined <<interfaces-fragmentoutput,fragment outputs interface>> to the
    pname:initialPipeline used to create the Indirect Execution Set
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-initialPipeline-11152]]
    Each pipeline in the Indirect Execution Set must: match the
    pname:initialPipeline used to create the Indirect Execution Set in its
    included shader stages
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-initialPipeline-11098]]
    Each pipeline in the Indirect Execution Set must: match the
    pname:initialPipeline used to create the Indirect Execution Set in its
    use of code:FragDepth
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-initialPipeline-11086]]
    Each pipeline in the Indirect Execution Set must: match the
    pname:initialPipeline used to create the Indirect Execution Set in its
    use of code:SampleMask
ifdef::VK_EXT_shader_stencil_export[]
  * [[VUID-vkUpdateIndirectExecutionSetPipelineEXT-initialPipeline-11085]]
    Each pipeline in the Indirect Execution Set must: match the
    pname:initialPipeline used to create the Indirect Execution Set in its
    use of code:StencilExportEXT
endif::VK_EXT_shader_stencil_export[]
****

include::{generated}/validity/protos/vkUpdateIndirectExecutionSetPipelineEXT.adoc[]
--

ifdef::VK_EXT_shader_object[]
[open,refpage='vkUpdateIndirectExecutionSetShaderEXT',desc='Update the contents of an indirect execution set',type='protos']
--
:refpage: vkUpdateIndirectExecutionSetShaderEXT

Shader object elements in an Indirect Execution Set can be updated by
calling:

include::{generated}/api/protos/vkUpdateIndirectExecutionSetShaderEXT.adoc[]

  * pname:device is the logical device that owns the indirect execution set.
  * pname:indirectExecutionSet is the indirect execution set being updated.
  * pname:executionSetWriteCount is the number of elements in the
    pname:pExecutionSetWrites array.
  * pname:pExecutionSetWrites is a pointer to an array of
    slink:VkWriteIndirectExecutionSetShaderEXT structures describing the
    elements to update.

.Valid Usage
****
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-indirectExecutionSet-11041]]
    pname:indirectExecutionSet must: have been created with type
    ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-pExecutionSetWrites-11043]]
    Each element in the pname:pExecutionSetWrites array must have a unique
    sname:VkWriteIndirectExecutionSetShaderEXT::pname:index
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-None-11044]]
    Each member of the Indirect Execution Set referenced by the update
    command must: not be in use by the device
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-pExecutionSetWrites-11140]]
    The descriptor layout of each shader in pname:pExecutionSetWrites must:
    be <<descriptorsets-compatibility,compatible>> with the initial layout
    info used to create the Indirect Execution Set
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-None-11148]]
    Each fragment shader element in the Indirect Execution Set must: have
    identically defined <<interfaces-fragmentoutput,fragment outputs
    interface>> to the initial shader state used to create the Indirect
    Execution Set
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-FragDepth-11054]]
    Each fragment shader element in the Indirect Execution Set must: match
    the initial shader state used to create the Indirect Execution Set in
    its use of code:FragDepth
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-SampleMask-11050]]
    Each fragment shader element in the Indirect Execution Set must: match
    the initial shader state used to create the Indirect Execution Set in
    its use of code:SampleMask
ifdef::VK_EXT_shader_stencil_export[]
  * [[VUID-vkUpdateIndirectExecutionSetShaderEXT-StencilExportEXT-11003]]
    Each fragment shader element in the Indirect Execution Set must: match
    the initial shader state used to create the Indirect Execution Set in
    its use of code:StencilExportEXT
endif::VK_EXT_shader_stencil_export[]
****

include::{generated}/validity/protos/vkUpdateIndirectExecutionSetShaderEXT.adoc[]
--
endif::VK_EXT_shader_object[]

It is legal to update an Indirect Execution Set that is in flight as long as
the element indices in pname:pExecutionSetWrites are not in use.
Any change to an indirect execution set requires recalculating memory
requirements by calling flink:vkGetGeneratedCommandsMemoryRequirementsEXT
for commands that use that modified state.
Commands that are in flight or those not using updated elements require no
changes.

The lifetimes of pipelines
ifdef::VK_EXT_shader_object[and shader objects]
contained in a set must: match or exceed the lifetime of the set.

endif::VK_EXT_device_generated_commands[]

ifdef::VK_NV_device_generated_commands[]
[open,refpage='vkCmdExecuteGeneratedCommandsNV',desc='Generate and execute commands on the device',type='protos']
--
:refpage: vkCmdExecuteGeneratedCommandsNV

With `apiext:VK_NV_device_generated_commands`, the actual generation of
commands as well as their execution on the device is handled as single
action with:

include::{generated}/api/protos/vkCmdExecuteGeneratedCommandsNV.adoc[]

  * pname:commandBuffer is the command buffer into which the command is
    recorded.
  * pname:isPreprocessed represents whether the input data has already been
    preprocessed on the device.
    If it is ename:VK_FALSE this command will implicitly trigger the
    preprocessing step, otherwise not.
  * pname:pGeneratedCommandsInfo is a pointer to a
    slink:VkGeneratedCommandsInfoNV structure containing parameters
    affecting the generation of commands.

If the ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NV
flag was used to create the
slink:VkGeneratedCommandsInfoNV::pname:indirectCommandsLayout then the order
of execution of individual draws through this command may: execute in any
order, and may: not necessarily be in the same order as specified in
slink:VkGeneratedCommandsInfoNV::pname:pStreams.

ifdef::VK_NV_device_generated_commands_compute[]
The order of execution of individual dispatches through this command may:
execute in any order and may: not necessarily be in the same order as
specified in slink:VkGeneratedCommandsInfoNV::pname:pStreams.
endif::VK_NV_device_generated_commands_compute[]

.Valid Usage
****
include::{chapters}/commonvalidity/draw_common.adoc[]
include::{chapters}/commonvalidity/draw_vertex_binding.adoc[]
ifdef::VK_VERSION_1_1[]
  * [[VUID-vkCmdExecuteGeneratedCommandsNV-commandBuffer-02970]]
    pname:commandBuffer must: not be a protected command buffer
endif::VK_VERSION_1_1[]
  * [[VUID-vkCmdExecuteGeneratedCommandsNV-isPreprocessed-02908]]
    If pname:isPreprocessed is ename:VK_TRUE then
    flink:vkCmdPreprocessGeneratedCommandsNV must: have already been
    executed on the device, using the same pname:pGeneratedCommandsInfo
    content as well as the content of the input buffers it references (all
    except slink:VkGeneratedCommandsInfoNV::pname:preprocessBuffer).
    Furthermore pname:pGeneratedCommandsInfo`s pname:indirectCommandsLayout
    must: have been created with the
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_NV bit
    set
  * [[VUID-vkCmdExecuteGeneratedCommandsNV-pipeline-02909]]
    slink:VkGeneratedCommandsInfoNV::pname:pipeline must: match the current
    bound pipeline at
    slink:VkGeneratedCommandsInfoNV::pname:pipelineBindPoint
ifdef::VK_EXT_transform_feedback[]
  * [[VUID-vkCmdExecuteGeneratedCommandsNV-None-02910]]
    Transform feedback must: not be active
endif::VK_EXT_transform_feedback[]
  * [[VUID-vkCmdExecuteGeneratedCommandsNV-deviceGeneratedCommands-02911]]
    The <<features-deviceGeneratedCommandsNV,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV::pname:deviceGeneratedCommands>>
    feature must: be enabled
****

include::{generated}/validity/protos/vkCmdExecuteGeneratedCommandsNV.adoc[]
--

[open,refpage='VkGeneratedCommandsInfoNV',desc='Structure specifying parameters for the generation of commands',type='structs']
--
:refpage:

The sname:VkGeneratedCommandsInfoNV is defined as:

include::{generated}/api/structs/VkGeneratedCommandsInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pipelineBindPoint is the elink:VkPipelineBindPoint used for the
    pname:pipeline.
  * pname:pipeline is the slink:VkPipeline used in the generation and
    execution process.
  * pname:indirectCommandsLayout is the slink:VkIndirectCommandsLayoutNV
    that provides the command sequence to generate.
  * pname:streamCount defines the number of input streams
  * pname:pStreams is a pointer to an array of pname:streamCount
    slink:VkIndirectCommandsStreamNV structures providing the input data for
    the tokens used in pname:indirectCommandsLayout.
  * pname:sequencesCount is the maximum number of sequences to reserve.
    If pname:sequencesCountBuffer is dlink:VK_NULL_HANDLE, this is also the
    actual number of sequences generated.
  * pname:preprocessBuffer is the slink:VkBuffer that is used for
    preprocessing the input data for execution.
    If this structure is used with flink:vkCmdExecuteGeneratedCommandsNV
    with its pname:isPreprocessed set to ename:VK_TRUE, then the
    preprocessing step is skipped and data in this buffer will not be
    modified.
    The contents and the layout of this buffer are opaque to applications
    and must: not be modified outside functions related to device-generated
    commands or copied to another buffer for reuse.
  * pname:preprocessOffset is the byte offset into pname:preprocessBuffer
    where the preprocessed data is stored.
  * pname:preprocessSize is the maximum byte size within the
    pname:preprocessBuffer after the pname:preprocessOffset that is
    available for preprocessing.
  * pname:sequencesCountBuffer is a sname:VkBuffer in which the actual
    number of sequences is provided as single code:uint32_t value.
  * pname:sequencesCountOffset is the byte offset into
    pname:sequencesCountBuffer where the count value is stored.
  * pname:sequencesIndexBuffer is a sname:VkBuffer that encodes the used
    sequence indices as code:uint32_t array.
  * pname:sequencesIndexOffset is the byte offset into
    pname:sequencesIndexBuffer where the index values start.

.Valid Usage
****
  * [[VUID-VkGeneratedCommandsInfoNV-pipeline-02912]]
    The provided pname:pipeline must: match the pipeline bound at execution
    time
  * [[VUID-VkGeneratedCommandsInfoNV-indirectCommandsLayout-02913]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV, then the
    pname:pipeline must: have been created with multiple shader groups
  * [[VUID-VkGeneratedCommandsInfoNV-indirectCommandsLayout-02914]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_SHADER_GROUP_NV, then the
    pname:pipeline must: have been created with
    ename:VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV set in
    sname:VkGraphicsPipelineCreateInfo::pname:flags
  * [[VUID-VkGeneratedCommandsInfoNV-indirectCommandsLayout-02915]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV, then the
    pname:pipeline's sname:VkPipelineLayout must: match the
    slink:VkIndirectCommandsLayoutTokenNV::pname:pushconstantPipelineLayout
  * [[VUID-VkGeneratedCommandsInfoNV-streamCount-02916]]
    pname:streamCount must: match the pname:indirectCommandsLayout's
    pname:streamCount
ifdef::VK_NV_device_generated_commands_compute[]
  * [[VUID-VkGeneratedCommandsInfoNV-pipelineBindPoint-09084]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, then the pname:pipeline must: have
    been created with the flag
    ename:VK_PIPELINE_CREATE_INDIRECT_BINDABLE_BIT_NV
  * [[VUID-VkGeneratedCommandsInfoNV-pipelineBindPoint-09085]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, then the pname:pipeline must: have
    been created with a slink:VkComputePipelineIndirectBufferInfoNV
    structure specifying a valid address where its metadata will be saved
  * [[VUID-VkGeneratedCommandsInfoNV-pipelineBindPoint-09086]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, then
    flink:vkCmdUpdatePipelineIndirectBufferNV must: have been called on that
    pipeline to save its metadata to a device address
  * [[VUID-VkGeneratedCommandsInfoNV-pipelineBindPoint-09087]]
    If pname:pipelineBindPoint is of type
    ename:VK_PIPELINE_BIND_POINT_COMPUTE, and if
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PIPELINE_NV is used, then
    pname:pipeline must: be dlink:VK_NULL_HANDLE
endif::VK_NV_device_generated_commands_compute[]
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesCount-02917]]
    pname:sequencesCount must: be less or equal to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV::pname:maxIndirectSequenceCount
    and
    slink:VkGeneratedCommandsMemoryRequirementsInfoNV::pname:maxSequencesCount
    that was used to determine the pname:preprocessSize
  * [[VUID-VkGeneratedCommandsInfoNV-preprocessBuffer-02918]]
    pname:preprocessBuffer must: have the
    ename:VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT bit set in its usage flag
  * [[VUID-VkGeneratedCommandsInfoNV-preprocessOffset-02919]]
    pname:preprocessOffset must: be aligned to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV::pname:minIndirectCommandsBufferOffsetAlignment
  * [[VUID-VkGeneratedCommandsInfoNV-preprocessBuffer-02971]]
    If pname:preprocessBuffer is non-sparse then it must: be bound
    completely and contiguously to a single sname:VkDeviceMemory object
  * [[VUID-VkGeneratedCommandsInfoNV-preprocessSize-02920]]
    pname:preprocessSize must: be at least equal to the memory requirement`s
    size returned by flink:vkGetGeneratedCommandsMemoryRequirementsNV using
    the matching inputs (pname:indirectCommandsLayout, ...) as within this
    structure
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesCountBuffer-02921]]
    pname:sequencesCountBuffer can: be set if the actual used count of
    sequences is sourced from the provided buffer.
    In that case the pname:sequencesCount serves as upper bound
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesCountBuffer-02922]]
    If pname:sequencesCountBuffer is not dlink:VK_NULL_HANDLE, its usage
    flag must: have the ename:VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT bit set
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesCountBuffer-02923]]
    If pname:sequencesCountBuffer is not dlink:VK_NULL_HANDLE,
    pname:sequencesCountOffset must: be aligned to
    sname:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV::pname:minSequencesCountBufferOffsetAlignment
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesCountBuffer-02972]]
    If pname:sequencesCountBuffer is not dlink:VK_NULL_HANDLE and is
    non-sparse then it must: be bound completely and contiguously to a
    single sname:VkDeviceMemory object
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesIndexBuffer-02924]]
    If pname:indirectCommandsLayout's
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NV is set,
    pname:sequencesIndexBuffer must: be set otherwise it must: be
    dlink:VK_NULL_HANDLE
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesIndexBuffer-02925]]
    If pname:sequencesIndexBuffer is not dlink:VK_NULL_HANDLE, its usage
    flag must: have the ename:VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT bit set
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesIndexBuffer-02926]]
    If pname:sequencesIndexBuffer is not dlink:VK_NULL_HANDLE,
    pname:sequencesIndexOffset must: be aligned to
    sname:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesNV::pname:minSequencesIndexBufferOffsetAlignment
  * [[VUID-VkGeneratedCommandsInfoNV-sequencesIndexBuffer-02973]]
    If pname:sequencesIndexBuffer is not dlink:VK_NULL_HANDLE and is
    non-sparse then it must: be bound completely and contiguously to a
    single sname:VkDeviceMemory object
ifdef::VK_NV_mesh_shader[]
  * [[VUID-VkGeneratedCommandsInfoNV-indirectCommandsLayout-07078]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_TASKS_NV, then the
    pname:pipeline must: contain a shader stage using the code:MeshNV
    {ExecutionModel}
endif::VK_NV_mesh_shader[]
ifdef::VK_EXT_mesh_shader[]
  * [[VUID-VkGeneratedCommandsInfoNV-indirectCommandsLayout-07079]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV, then the
    pname:pipeline must: contain a shader stage using the code:MeshEXT
    {ExecutionModel}
endif::VK_EXT_mesh_shader[]
****

include::{generated}/validity/structs/VkGeneratedCommandsInfoNV.adoc[]
--

Referencing the functions defined in <<indirectmdslayout>>,
fname:vkCmdExecuteGeneratedCommandsNV behaves as:

[source,c]
----
uint32_t sequencesCount = sequencesCountBuffer ?
      min(maxSequencesCount, sequencesCountBuffer.load_uint32(sequencesCountOffset) :
      maxSequencesCount;


cmdProcessAllSequences(commandBuffer, pipeline,
                       indirectCommandsLayout, pIndirectCommandsStreams,
                       sequencesCount,
                       sequencesIndexBuffer, sequencesIndexOffset);

// The stateful commands within indirectCommandsLayout will not
// affect the state of subsequent commands in the target
// command buffer (cmd)
----

[NOTE]
====
It is important to note that the values of all state related to the
pname:pipelineBindPoint used are undefined: after this command.
====

[open,refpage='vkCmdPreprocessGeneratedCommandsNV',desc='Performs preprocessing for generated commands',type='protos']
--
Commands can: be preprocessed prior execution using the following command:

include::{generated}/api/protos/vkCmdPreprocessGeneratedCommandsNV.adoc[]

  * pname:commandBuffer is the command buffer which does the preprocessing.
  * pname:pGeneratedCommandsInfo is a pointer to a
    slink:VkGeneratedCommandsInfoNV structure containing parameters
    affecting the preprocessing step.

.Valid Usage
****
ifdef::VK_VERSION_1_1[]
  * [[VUID-vkCmdPreprocessGeneratedCommandsNV-commandBuffer-02974]]
    pname:commandBuffer must: not be a protected command buffer
endif::VK_VERSION_1_1[]
  * [[VUID-vkCmdPreprocessGeneratedCommandsNV-pGeneratedCommandsInfo-02927]]
    pname:pGeneratedCommandsInfo`s pname:indirectCommandsLayout must: have
    been created with the
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_NV bit
    set
  * [[VUID-vkCmdPreprocessGeneratedCommandsNV-deviceGeneratedCommands-02928]]
    The <<features-deviceGeneratedCommandsNV,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesNV::pname:deviceGeneratedCommands>>
    feature must: be enabled
****

include::{generated}/validity/protos/vkCmdPreprocessGeneratedCommandsNV.adoc[]
--

ifdef::VK_NV_device_generated_commands_compute[]
The bound descriptor sets and push constants that will be used with indirect
command generation for the compute pipelines must: already be specified at
the time of preprocessing commands with
flink:vkCmdPreprocessGeneratedCommandsNV.
They must: not change until the execution of indirect commands is submitted
with flink:vkCmdExecuteGeneratedCommandsNV.

If push constants for the compute pipeline are also specified in the
slink:VkGeneratedCommandsInfoNV::pname:indirectCommandsLayout with
ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_NV token, then those
values override the push constants that were previously pushed for the
compute pipeline.

endif::VK_NV_device_generated_commands_compute[]
endif::VK_NV_device_generated_commands[]

ifdef::VK_EXT_device_generated_commands[]
[open,refpage='vkCmdExecuteGeneratedCommandsEXT',desc='Generate and execute commands on the device',type='protos']
--
:refpage: vkCmdExecuteGeneratedCommandsEXT

With `apiext:VK_EXT_device_generated_commands`, the actual generation of
commands as well as their execution on the device is handled as single
action with:

include::{generated}/api/protos/vkCmdExecuteGeneratedCommandsEXT.adoc[]

  * pname:commandBuffer is the command buffer into which the command is
    recorded.
  * pname:isPreprocessed represents whether the input data has already been
    preprocessed on the device.
    If it is ename:VK_FALSE this command will implicitly trigger the
    preprocessing step, otherwise not.
  * pname:pGeneratedCommandsInfo is a pointer to a
    slink:VkGeneratedCommandsInfoEXT structure containing parameters
    affecting the generation of commands.

If the ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_EXT
flag was used to create the
slink:VkGeneratedCommandsInfoEXT::pname:indirectCommandsLayout then the
execution of sequences through this command may: use implementation-defined
ordering which is not guaranteed to be coherent using the same input data.
It does not affect the order of token processing within a sequence.
This is the implied ordering with
ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT.

After a call to fname:vkCmdExecuteGeneratedCommandsEXT, command buffer state
will become undefined: according to the tokens executed.
This table specifies the relationship between tokens used and state
invalidation.

.Indirect Execution State Invalidation
[width="80%",cols="67%,33%",options="header",align="center"]
|===
|*Common Tokens* | *States Invalidated*
|ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT            | Bound shaders and pipelines
|ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT            | Push constant data
|ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT           | Push constant data
|ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXT             | Index buffer
|ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT            | Vertex buffer
|===

.Valid Usage
****
include::{chapters}/commonvalidity/draw_common.adoc[]
ifdef::VK_VERSION_1_1[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-commandBuffer-11045]]
    pname:commandBuffer must: not be a protected command buffer
endif::VK_VERSION_1_1[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11046]]
    If pname:isPreprocessed is ename:VK_TRUE and
    flink:vkGetGeneratedCommandsMemoryRequirementsEXT did not return a
    required size of zero then flink:vkCmdPreprocessGeneratedCommandsEXT
    must: have already been executed on the device before this command
    executes, and the preprocessing command must: have used the same
    pname:pGeneratedCommandsInfo content as well as the content of the input
    buffers it references (all except
    slink:VkGeneratedCommandsInfoEXT::pname:preprocessBuffer)
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11047]]
    If pname:isPreprocessed is ename:VK_TRUE then the
    pname:indirectCommandsLayout member of pname:pGeneratedCommandsInfo
    must: have been created with the
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXT bit
    set
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-indirectCommandsLayout-11141]]
    If the pname:indirectCommandsLayout member of
    pname:pGeneratedCommandsInfo was created with the
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXT bit
    set, then pname:isPreprocessed must: be ename:VK_TRUE
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-preprocessAddress-11142]]
    The contents of the pname:preprocessAddress member of
    pname:pGeneratedCommandsInfo must: not have been previously used to
    record another flink:vkCmdExecuteGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11048]]
    If pname:isPreprocessed is ename:VK_TRUE then the bound descriptor sets
    and push constants must: match identically with those bound during
    recording of the corresponding call to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-10198]]
    If pname:isPreprocessed is ename:VK_TRUE then the conditional render
    state and its predicate value must: match identically with the state and
    value set during execution of the corresponding call to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11049]]
    If pname:isPreprocessed is ename:VK_TRUE and the
    pname:indirectCommandsLayout member of pname:pGeneratedCommandsInfo
    contains a draw token, then the graphics state bound on
    pname:commandBuffer must: match identically with the graphics state
    bound on the pname:stateCommandBuffer passed to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11149]]
    If pname:isPreprocessed is ename:VK_TRUE, then the queue family index of
    pname:commandBuffer must: be the same as the queue family index used to
    allocate the pname:stateCommandBuffer passed to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11051]]
    If pname:isPreprocessed is ename:VK_TRUE and the
    pname:indirectCommandsLayout member of pname:pGeneratedCommandsInfo
    contains a dispatch token, then the compute state bound on
    pname:commandBuffer must: match identically with the compute state bound
    on the pname:stateCommandBuffer passed to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11052]]
    If pname:isPreprocessed is ename:VK_TRUE and the
    pname:indirectCommandsLayout member of pname:pGeneratedCommandsInfo
    contains a ray tracing token, then the ray tracing state bound on
    pname:commandBuffer must: match identically with the ray tracing state
    bound on the pname:stateCommandBuffer passed to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11150]]
    If pname:isPreprocessed is ename:VK_TRUE and the
    pname:indirectCommandsLayout member of pname:pGeneratedCommandsInfo
    contains a ray tracing token, the queue family index pname:commandBuffer
    was allocated from must: be the same queue family index used to allocate
    the pname:stateCommandBuffer passed to
    flink:vkCmdPreprocessGeneratedCommandsEXT
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-indirectCommandsLayout-11053]]
    If the token sequence of the passed
    slink:VkGeneratedCommandsInfoEXT::pname:indirectCommandsLayout contains
    a ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT token, the
    initial shader state of
    slink:VkGeneratedCommandsInfoEXT::pname:indirectExecutionSet must: be
    bound on pname:commandBuffer
ifdef::VK_EXT_shader_object[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-indirectCommandsLayout-11004]]
    If pname:indirectCommandsLayout was created with a token sequence that
    contained the ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token and pname:indirectExecutionSet was created using
    ename:VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT, every
    executed ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT token
    must: bind all the shader stages set in the
    slink:VkIndirectCommandsExecutionSetTokenEXT::pname:shaderStages used to
    create pname:indirectCommandsLayout
endif::VK_EXT_shader_object[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-isPreprocessed-11055]]
    If pname:isPreprocessed is ename:VK_TRUE and the token sequence of the
    passed slink:VkGeneratedCommandsInfoEXT::pname:indirectCommandsLayout
    contains a ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, the members of
    slink:VkGeneratedCommandsInfoEXT::pname:indirectExecutionSet accessed by
    this command must: not have been modified since the preprocess buffer
    was generated
ifdef::VK_EXT_fragment_density_map[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-indirectCommandsLayout-11056]]
    If the pname:indirectCommandsLayout member of
    pname:pGeneratedCommandsInfo contains a draw token, then the active
    render pass must: not have a specified fragment density map
endif::VK_EXT_fragment_density_map[]
ifdef::VK_EXT_transform_feedback[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-deviceGeneratedCommandsTransformFeedback-11057]]
    If
    <<limits-deviceGeneratedCommandsTransformFeedback,pname:deviceGeneratedCommandsTransformFeedback>>
    is not supported on device, transform feedback must: not be active
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-indirectExecutionSet-11058]]
    If transform feedback is active,
    slink:VkGeneratedCommandsInfoEXT::pname:indirectExecutionSet must: be
    dlink:VK_NULL_HANDLE
endif::VK_EXT_transform_feedback[]
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-deviceGeneratedCommands-11059]]
    The <<features-deviceGeneratedCommands,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesEXT::pname:deviceGeneratedCommands>>
    feature must: be enabled
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-supportedIndirectCommandsShaderStages-11060]]
    The bound shader stages must: be supported by
    <<limits-supportedIndirectCommandsShaderStages,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStages>>
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-supportedIndirectCommandsShaderStages-11061]]
    Only stages specified in <<limits-supportedIndirectCommandsShaderStages,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStages>>
    can: be set in pname:pGeneratedCommandsInfo->shaderStages
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-None-11062]]
    If a rendering pass is currently active, the view mask must: be `0`
  * [[VUID-vkCmdExecuteGeneratedCommandsEXT-commandBuffer-11143]]
    pname:commandBuffer must: not have been created with
    ename:VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT
****

include::{generated}/validity/protos/vkCmdExecuteGeneratedCommandsEXT.adoc[]
--

[open,refpage='VkGeneratedCommandsInfoEXT',desc='Structure specifying parameters for the generation of commands',type='structs']
--
:refpage:

The sname:VkGeneratedCommandsInfoEXT is defined as:

include::{generated}/api/structs/VkGeneratedCommandsInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:shaderStages is the mask of shader stages used by the commands.
  * pname:indirectExecutionSet is the indirect execution set to be used for
    binding shaders.
  * pname:indirectCommandsLayout is the slink:VkIndirectCommandsLayoutEXT
    that specifies the command sequence data.
  * pname:indirectAddress is an address that holds the indirect buffer data.
  * pname:indirectAddressSize is the size in bytes of indirect buffer data
    starting at pname:indirectAddress.
  * pname:preprocessAddress specifies a physical address of the
    sname:VkBuffer used for preprocessing the input data for execution.
    If this structure is used with flink:vkCmdExecuteGeneratedCommandsEXT
    with its pname:isPreprocessed set to ename:VK_TRUE, then the
    preprocessing step is skipped but data in this address may: still be
    modified.
    The contents and the layout of this address are opaque to applications
    and must: not be modified outside functions related to device-generated
    commands or copied to another buffer for reuse.
  * pname:preprocessSize is the maximum byte size within
    pname:preprocessAddress that is available for preprocessing.
  * pname:maxSequenceCount is used to determine the number of sequences to
    execute.
  * pname:sequenceCountAddress specifies an optional physical address of a
    single code:uint32_t value containing the requested number of sequences
    to execute.
  * pname:maxDrawCount is the maximum number of indirect draws that can be
    executed by any COUNT-type multi-draw indirect tokens.
    The draw count in the indirect buffer is clamped to this value for these
    token types.

If pname:sequenceCountAddress is not `NULL`, then pname:maxSequenceCount is
the maximum number of sequences that can be executed.
The actual number is `min(maxSequenceCount, *sequenceCountAddress)`.
If pname:sequenceCountAddress is `NULL`, then pname:maxSequenceCount is the
exact number of sequences to execute.

If the action command token for the layout is not a COUNT-type multi-draw
indirect token, pname:maxDrawCount is ignored.

.Valid Usage
****
  * [[VUID-VkGeneratedCommandsInfoEXT-preprocessAddress-11063]]
    If flink:vkGetGeneratedCommandsMemoryRequirementsEXT returns a non-zero
    size, pname:preprocessAddress must: not be `NULL`
  * [[VUID-VkGeneratedCommandsInfoEXT-preprocessAddress-11064]]
    sname:VkDeviceMemory objects bound to the underlying buffer for
    pname:preprocessAddress must: have been allocated using one of the
    memory types allowed in the pname:memoryTypeBits member of the
    slink:VkMemoryRequirements structure returned by
    flink:vkGetGeneratedCommandsMemoryRequirementsEXT
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11065]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT, then the
    pname:indirectExecutionSet's push constant layout must: contain the
    pname:updateRange specified in
    slink:VkIndirectCommandsPushConstantTokenEXT
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11066]]
    If the pname:indirectCommandsLayout uses a token of
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT, then the
    pname:indirectExecutionSet's push constant layout must: contain the
    pname:updateRange specified in
    slink:VkIndirectCommandsPushConstantTokenEXT
  * [[VUID-VkGeneratedCommandsInfoEXT-maxSequenceCount-11067]]
    pname:maxSequenceCount must: be less or equal to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectSequenceCount
    and
    slink:VkGeneratedCommandsMemoryRequirementsInfoEXT::pname:maxSequencesCount
    that was used to determine the pname:preprocessSize
  * [[VUID-VkGeneratedCommandsInfoEXT-sequenceCountAddress-11068]]
    If pname:sequenceCountAddress is not `NULL`, the value contained in the
    address must: be less or equal to
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:maxIndirectSequenceCount
    and
    slink:VkGeneratedCommandsMemoryRequirementsInfoEXT::pname:maxSequencesCount
    that was used to determine the pname:preprocessSize
  * [[VUID-VkGeneratedCommandsInfoEXT-maxSequenceCount-10246]]
    pname:maxSequenceCount must: not be zero
  * [[VUID-VkGeneratedCommandsInfoEXT-preprocessAddress-11069]]
    The underlying buffer for pname:preprocessAddress must: have the
    ename:VK_BUFFER_USAGE_2_PREPROCESS_BUFFER_BIT_EXT bit set in its usage
    flag
  * [[VUID-VkGeneratedCommandsInfoEXT-preprocessAddress-11070]]
    If the underlying buffer for pname:preprocessAddress is non-sparse then
    it must: be bound completely and contiguously to a single
    sname:VkDeviceMemory object
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11144]]
    If the pname:indirectCommandsLayout contains a
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT token, then the
    descriptor and push constant layout info provided either by
    pname:pipelineLayout or through a slink:VkPipelineLayoutCreateInfo in
    pname:pNext of the slink:VkIndirectCommandsLayoutCreateInfoEXT used to
    create pname:indirectCommandsLayout must: be
    <<descriptorsets-compatibility,compatible>> with the descriptor and push
    constant layout info used by pname:indirectExecutionSet
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11002]]
    If pname:indirectCommandsLayout was created with a token sequence that
    contained the ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, the shader stages used to create the initial shader state of
    pname:indirectExecutionSet must: equal the
    slink:VkIndirectCommandsExecutionSetTokenEXT::pname:shaderStages used to
    create pname:indirectCommandsLayout
  * [[VUID-VkGeneratedCommandsInfoEXT-preprocessSize-11071]]
    pname:preprocessSize must: be greater than or equal to the memory
    requirement's size returned by
    flink:vkGetGeneratedCommandsMemoryRequirementsEXT using the matching
    inputs (pname:indirectCommandsLayout, ...) as within this structure
  * [[VUID-VkGeneratedCommandsInfoEXT-sequenceCountAddress-11072]]
    The underlying buffer for pname:sequenceCountAddress must: have the
    ename:VK_BUFFER_USAGE_2_INDIRECT_BUFFER_BIT_KHR bit set in its usage
    flag
  * [[VUID-VkGeneratedCommandsInfoEXT-sequenceCountAddress-11073]]
    If pname:sequenceCountAddress is not `NULL`, pname:sequenceCountAddress
    must: be aligned to `4`
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectAddress-11074]]
    pname:indirectAddress must: be aligned to `4`
  * [[VUID-VkGeneratedCommandsInfoEXT-sequenceCountAddress-11075]]
    If the underlying buffer for pname:sequenceCountAddress is non-sparse
    then it must: be bound completely and contiguously to a single
    sname:VkDeviceMemory object
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectAddress-11076]]
    pname:indirectAddress must: not be `NULL`
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectAddressSize-11077]]
    pname:indirectAddressSize must: be greater than zero
  * [[VUID-VkGeneratedCommandsInfoEXT-maxDrawCount-11078]]
    When not ignored, [eq]#pname:maxDrawCount {times}
    pname:maxSequenceCount# must: be less than [eq]#2^24#
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11079]]
    If pname:indirectCommandsLayout was created using a
    ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT token
ifdef::VK_EXT_shader_object[and shader objects are not bound]
    then the bound graphics pipeline must: have been created with
    ename:VK_DYNAMIC_STATE_VERTEX_INPUT_BINDING_STRIDE in
    pname:pDynamicStates
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-11083]]
    If the token sequence of the passed pname:indirectCommandsLayout
    contains a ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, the pname:indirectExecutionSet must: not be dlink:VK_NULL_HANDLE
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectCommandsLayout-10241]]
    If the token sequence of the passed pname:indirectCommandsLayout does
    not contains a ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT
    token, the pname:indirectExecutionSet must: be dlink:VK_NULL_HANDLE
  * [[VUID-VkGeneratedCommandsInfoEXT-indirectExecutionSet-11080]]
    If pname:indirectExecutionSet is dlink:VK_NULL_HANDLE, a
    slink:VkGeneratedCommandsPipelineInfoEXT
ifdef::VK_EXT_shader_object[or slink:VkGeneratedCommandsShaderInfoEXT]
    must: be included in the pname:pNext chain
****

include::{generated}/validity/structs/VkGeneratedCommandsInfoEXT.adoc[]
--

Referencing the functions defined in <<indirectmdslayout>>,
fname:vkCmdExecuteGeneratedCommandsEXT behaves as:

[source,c]
----
uint32_t sequencesCount = sequenceCountAddress ?
      min(maxSequenceCount, sequenceCountAddress.load_uint32()) :
      maxSequenceCount;


cmdProcessAllSequences(commandBuffer, indirectExecutionSet,
                       indirectCommandsLayout, indirectAddress,
                       sequencesCount);

// The stateful commands within indirectCommandsLayout will not
// affect the state of subsequent commands in the target
// command buffer (cmd)
----

[NOTE]
.Note
====
It is important to note that the affected values of all state related to the
pname:shaderStages used are undefined: after this command.
This means that e.g., if this command indirectly alters push constants, the
push constant state becomes undefined:.
====

[open,refpage='vkCmdPreprocessGeneratedCommandsEXT',desc='Performs preprocessing for generated commands',type='protos']
--
Commands can: be preprocessed prior execution using the following command:

include::{generated}/api/protos/vkCmdPreprocessGeneratedCommandsEXT.adoc[]

  * pname:commandBuffer is the command buffer which does the preprocessing.
  * pname:pGeneratedCommandsInfo is a pointer to a
    slink:VkGeneratedCommandsInfoEXT structure containing parameters
    affecting the preprocessing step.
  * pname:stateCommandBuffer is a command buffer from which to snapshot
    current states affecting the preprocessing step.
    When a graphics command action token is used, graphics state is
    snapshotted.
    When a compute action command token is used, compute state is
    snapshotted.
    When a ray tracing action command token is used, ray tracing state is
    snapshotted.
    It can be deleted at any time after this command has been recorded.

[NOTE]
.Note
====
pname:stateCommandBuffer access is not synchronized by the driver, meaning
that this command buffer must: not be modified between threads in an unsafe
manner.
====

.Valid Usage
****
ifdef::VK_VERSION_1_1[]
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-commandBuffer-11081]]
    pname:commandBuffer must: not be a protected command buffer
endif::VK_VERSION_1_1[]
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-pGeneratedCommandsInfo-11082]]
    pname:pGeneratedCommandsInfo's pname:indirectCommandsLayout must: have
    been created with the
    ename:VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EXPLICIT_PREPROCESS_BIT_EXT bit
    set
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-indirectCommandsLayout-11084]]
    If the token sequence of the passed
    slink:VkGeneratedCommandsInfoEXT::pname:indirectCommandsLayout contains
    a ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT token, the
    initial shader state of
    slink:VkGeneratedCommandsInfoEXT::pname:indirectExecutionSet must: be
    bound on pname:stateCommandBuffer
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-stateCommandBuffer-11138]]
    pname:stateCommandBuffer must: be in the recording state
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-deviceGeneratedCommands-11087]]
    The <<features-deviceGeneratedCommands,
    sname:VkPhysicalDeviceDeviceGeneratedCommandsFeaturesEXT::pname:deviceGeneratedCommands>>
    feature must: be enabled
  * [[VUID-vkCmdPreprocessGeneratedCommandsEXT-supportedIndirectCommandsShaderStages-11088]]
    Only stages specified in <<limits-supportedIndirectCommandsShaderStages,
    slink:VkPhysicalDeviceDeviceGeneratedCommandsPropertiesEXT::pname:supportedIndirectCommandsShaderStages>>
    can: be set in pname:pGeneratedCommandsInfo->shaderStages
****

include::{generated}/validity/protos/vkCmdPreprocessGeneratedCommandsEXT.adoc[]
--

The bound descriptor sets and push constants that will be used with indirect
command generation must: already be specified on pname:stateCommandBuffer at
the time of preprocessing commands with
flink:vkCmdPreprocessGeneratedCommandsEXT.
They must: match the bound descriptor sets and push constants used in the
execution of indirect commands with flink:vkCmdExecuteGeneratedCommandsEXT.

If push constants for shader stages are also specified in the
slink:VkGeneratedCommandsInfoEXT::pname:indirectCommandsLayout with a
ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT or
ename:VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT token, then those
values override the push constants that were previously pushed.

All state bound on pname:stateCommandBuffer will be used.
All state bound on pname:stateCommandBuffer must: be identical to the state
bound at the time flink:vkCmdExecuteGeneratedCommandsEXT is recorded.
The queue family index pname:stateCommandBuffer was allocated from must: be
the same as the queue family index of the command buffer used in
flink:vkCmdExecuteGeneratedCommandsEXT.

On some implementations, preprocessing may: have no effect on performance.

flink:vkCmdExecuteGeneratedCommandsEXT may: write to the preprocess buffer,
no matter the isPreprocess parameter.
In this case, the implementation must: insert appropriate synchronization
automatically, which corresponds to the following pseudocode:

* Barrier
** srcStageMask = DRAW_INDIRECT
** srcAccesMask = 0
** dstStageMask = COMMAND_PREPROCESS_BIT
** dstAccessMask = COMMAND_PREPROCESS_WRITE_BIT |
   COMMAND_PREPROCESS_READ_BIT
* Do internal writes
* Barrier
** srcStageMask = COMMAND_PREPROCESS_BIT
** srcAccesMask = COMMAND_PREPROCESS_WRITE_BIT
** dstStageMask = DRAW_INDIRECT
** dstAccessMask = INDIRECT_COMMAND_READ_BIT
* Execute

endif::VK_EXT_device_generated_commands[]
