// Copyright 2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

// This section is included inside the render pass chapter (renderpass.adoc)

[[renderpass-tile-shading]]
== Tile Shading Render Pass

[[renderpass-tile-shading-functionality]]
Tile shading can: be enabled within a render pass.

[open,refpage='VkRenderPassTileShadingCreateInfoQCOM',desc='Structure specifying, tile shading information for a render pass object.',type='structs']
--
To enable tile shading for a render pass object, add a
slink:VkRenderPassTileShadingCreateInfoQCOM to the pname:pNext chain of
slink:VkRenderPassCreateInfo
ifdef::VK_GRAPHICS_VERSION_1_2[or slink:VkRenderPassCreateInfo2]
.
ifdef::VK_GRAPHICS_VERSION_1_3,VK_KHR_dynamic_rendering[]
To enable tile shading for a dynamic render pass, add a
slink:VkRenderPassTileShadingCreateInfoQCOM to the pname:pNext chain of
slink:VkRenderingInfo.
endif::VK_GRAPHICS_VERSION_1_3,VK_KHR_dynamic_rendering[]
To execute a secondary command buffer within a render pass, add a
slink:VkRenderPassTileShadingCreateInfoQCOM to the pname:pNext chain of
slink:VkCommandBufferInheritanceInfo when the secondary command buffer is
recorded.

The sname:VkRenderPassTileShadingCreateInfoQCOM structure is defined as:

include::{generated}/api/structs/VkRenderPassTileShadingCreateInfoQCOM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:flags is a bitmask of elink:VkTileShadingRenderPassFlagBitsQCOM.
  * pname:tileApronSize is a slink:VkExtent2D describing the is size of the
    <<renderpass-tile-shading-aprons, tiling apron>> in each dimension.

If this structure is not present, the render pass will have pname:flags set
to `0` and pname:tileApronSize is set to `(0,0)`.

.Valid Usage
****
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-tileShading-10658]]
    If the <<features-tileShading, pname:tileShading>> feature is not
    enabled, ename:VK_TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM must: not be
    included in pname:flags
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-flags-10659]]
    If ename:VK_TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM is not included in
    pname:flags or the <<features-tileShadingApron,pname:tileShadingApron>>
    feature is not enabled, pname:tileApronSize must: be `(0,0)`
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-flags-10660]]
    If ename:VK_TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM is not included in
    pname:flags, or neither the
    <<features-tileShadingPerTileDispatch,tileShadingPerTileDispatch>> and
    <<features-tileShadingPerTileDraw,tileShadingPerTileDraw>> features are
    enabled, pname:flags must: not include
    ename:VK_TILE_SHADING_RENDER_PASS_PER_TILE_EXECUTION_BIT_QCOM
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-tileShadingAnisotropicApron-10661]]
    If the <<features-tileShadingAnisotropicApron,
    pname:tileShadingAnisotropicApron>> feature is not enabled,
    pname:tileApronSize.x and must: be equal to pname:tileApronSize.y
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-tileApronSize-10662]]
    pname:tileApronSize.x must: be less than or equal to
    <<limits-maxApronSize,pname:maxApronSize>>
  * [[VUID-VkRenderPassTileShadingCreateInfoQCOM-tileApronSize-10663]]
    pname:tileApronSize.y must: be less than or equal to
    <<limits-maxApronSize,pname:maxApronSize>>
****

include::{generated}/validity/structs/VkRenderPassTileShadingCreateInfoQCOM.adoc[]
--

[open,refpage='VkTileShadingRenderPassFlagBitsQCOM',desc='Bitmask specifying flags for tile shading',type='enums']
--
Bits which can: be set in
slink:VkRenderPassTileShadingCreateInfoQCOM::pname:flags describing
additional properties of the render pass are:

include::{generated}/api/enums/VkTileShadingRenderPassFlagBitsQCOM.adoc[]

  * ename:VK_TILE_SHADING_RENDER_PASS_ENABLE_BIT_QCOM specifies that the
    render pass has tile shading enabled.
  * ename:VK_TILE_SHADING_RENDER_PASS_PER_TILE_EXECUTION_BIT_QCOM specifies
    that the secondary command buffer will be executed within a
    <<renderpass-per-tile-execution-model,per-tile execution block>>.
--

[open,refpage='VkTileShadingRenderPassFlagsQCOM',desc='Bitmask of VkTileShadingRenderPassFlagBitsQCOM',type='flags']
--
include::{generated}/api/flags/VkTileShadingRenderPassFlagsQCOM.adoc[]

tname:VkTileShadingRenderPassFlagsQCOM is a bitmask type for setting a mask
of zero or more elink:VkTileShadingRenderPassFlagBitsQCOM.
--

[[renderpass-tile-shading-attachment-access]]
=== Tile Attachment Variables

Within a <<renderpass-tile-shading, tile shading render pass>>, fragment and
compute shader invocations can: use the <<interfaces-tile-attachment,Tile
Attachment Interface>> to perform load/store, operations on _storage tile
attachment_ variables, to perform load operations on _input tile attachment_
variables, and to perform sampling operations on _sampled tile attachment_
variables.
_Storage tile attachment_, _sampled tile attachment_, and _input tile
attachment_ variables must: be declared and used as described in the tile
attachment interface.

[[renderpass-tile-shading-aprons]]
=== Tiling Aprons

In a render pass that <<renderpass-tile-shading,enables>> tile shading, a
_tiling apron_ can: be enabled by setting
slink:VkRenderPassTileShadingCreateInfoQCOM::pname:tileApronSize to a value
other than [eq]#(0,0)#.
Additionally, subpass pname:flags must: include
ename:VK_SUBPASS_DESCRIPTION_TILE_SHADING_APRON_BIT_QCOM
ifdef::VK_GRAPHICS_VERSION_1_3,VK_KHR_dynamic_rendering[if the render pass is not a dynamic render pass]
or the apron size for that subpass will be [eq]#(0,0)#.
The tile apron enables shader invocations to load from tile attachment
variables at a location that is outside the current tile.
The pname:width and pname:height value of pname:tileApronSize specifies the
number of pixels in the horizontal and vertical directions that are included
in the apron region.
For example, (1,1) means that the apron region extends the top, bottom, left
and right margins of the tile by 1 pixel.
The pname:tileApronSize must: not exceed
slink:VkPhysicalDeviceTileShadingPropertiesQCOM::maxApronSize.

[NOTE]
====
A good mental model for the tiling apron is to think of it as enabling
"overlapping tiles".
The top/bottom and left/right margins of each tile are extended to include a
few pixels of the adjacent tiles.
Those pixels that are outside the original tile extents, but within the
apron extents are "`apron pixels`".
In a render pass that enables tile shading, apron pixels will be initialized
by the ename:VkAttachmentLoadOp, and may: be updated by any draw within the
render pass, but are always discarded and never written by
ename:VkAttachmentStoreOp.
Apron pixels can: be read as a result of using code:OpImageRead,
code:OpImageSparseRead, code:OpImageSample*, code:OpImageSparseSample*,
code:OpImage*Gather, code:OpImageSparse*Gather,
ifdef::VK_QCOM_image_processing[]
code:OpImageSampleWeightedQCOM, OpImageBoxFilterQCOM,
OpImageBlockMatch*QCOM,
endif::VK_QCOM_image_processing[]
code:OpImageFetch, or code:OpImageSparseFetch but cannot: be written using
code:OpImageWrite or with atomic operations using code:OpImageTexelPointer.

For image processing use cases, the tiling apron allows fragment and compute
shader invocations to read or sample color attachment pixels within the
neighborhood of a given fragment, even if the given fragment is close to a
tile edge.

Enabling the apron may: reduce the GPU efficiency, with larger apron sizes
having a greater potential impact.
Aprons should: be enabled only when needing to access pixels outside the
tile.
====

[[renderpass-tile-shading-offset-validation]]
=== Tile Attachment Coordinate Validation
Image operations that access a tile attachment can: use normalized,
unnormalized, or integer texel coordinates, but the final set of (i,j,[k])
integer texel coordinates accessed in <<textures-texel-filtering, texel
filtering>> must: be within the extents of the current tile and apron as
well as within the render pass pname:renderArea.
Any out of bounds access will result in undefined: values.

The <<features-robustImageAccess,robustImageAccess>> and
<<features-robustImageAccess2,robustImageAccess2>> features do not apply to
tile attachment accesses.

The built-in variables
<<interfaces-builtin-variables-tileoffset,code:TileOffsetQCOM>>,
<<interfaces-builtin-variables-tileapronsize, TileApronSizeQCOM>>, and
<<interfaces-builtin-variables-tilesize,code:TileDimensionQCOM>> define the
extent of the current tile and apron.

For _storage tile attachment_ stores using code:OpImageWrite and with an
code:Image operand from storage class code:TileAttachmentQCOM, the
code:Coordinate operand latexmath:[O_s] must: specify a framebuffer location
within the render pass pname:renderArea and within the extent of the tile.

[latexmath]
++++++++++++++++++++++++
\begin{aligned}
O_{min} &= max( O_{ra}, O_t) \\[1em]
O_{max} &= min( (O_{ra} + E_{ra}), (O_t + Size_t))  \\[1em]
O_{min} \leq &O_s < O_{max}  \\[1em]
\end{aligned}
++++++++++++++++++++++++

For _storage tile attachment_ using code:OpImageRead or
code:OpImageSparseRead, or _input tile attachment_ loads using
code:OpImageRead, and with an code:Image operand from storage class
code:TileAttachmentQCOM, the code:Coordinate operand latexmath:[O_l] must:
specify a framebuffer location within the render pass pname:renderArea and
within the combined extent of the tile and apron.

[latexmath]
++++++++++++++++++++++++
\begin{aligned}
O_{min} &= max( O_{ra}, O_t - Size_a)  \\[1em]
O_{max} &= min( (O_{ra} + E_{ra}), (O_t + Size_t + Size_a))  \\[1em]
O_{min} \leq &O_l < O_{max}
\end{aligned}
++++++++++++++++++++++++

where:

  {empty}:: latexmath:[O_s] represents code:offset operand to
            code:OpImageWrite
  {empty}:: latexmath:[O_l] represents code:offset operand to
            code:OpImageRead
  {empty}:: latexmath:[O_t] represents
            <<interfaces-builtin-variables-tileoffset,TileOffsetQCOM>>
  {empty}:: latexmath:[Size_t] represents
            <<interfaces-builtin-variables-tilesize,TileDimensionQCOM>>
  {empty}:: latexmath:[O_{ra}] represents the render pass
            pname:renderArea.offset
  {empty}:: latexmath:[E_{ra}] represents the render pass
            pname:renderArea.extent
  {empty}:: latexmath:[Size_a] represents
            <<interfaces-builtin-variables-tileapronsize,TileApronSizeQCOM>>

For _storage tile attachment_ atomic operations using
code:OpImageTexelPointer, the code:Coordinate operand must: specify a
framebuffer location within the render pass pname:RenderArea and within the
extent of the tile.
The code:Coordinate must: not point to the apron region.

When accessing a _sampled tile attachment_ using code:OpImageSample*,
code:OpImageSparseSample*, code:OpImageFetch, code:OpImageSparseFetch*,
ifdef::VK_QCOM_image_processing[]
code:OpImageSampleWeightedQCOM, OpImageBoxFilterQCOM,
OpImageBlockMatch*QCOM,
endif::VK_QCOM_image_processing[]
code:OpImage*Gather, or code:OpImageSparse*Gather, and with an code:Image
operand from storage class code:TileAttachmentQCOM, the code:Coordinate
operand must: not result in a any texels accessed that are outside the
pname:renderArea or outside the combined extent of the tile and apron.

[NOTE]
====
It is the application's responsibility to guarantee that the instruction and
texture coordinates do not cause any out of bounds texels to be accessed as
a result of loads, stores, atomics, or the sampling filter.
In practice, this may require that the coordinates are clamped in the shader
code.
====

[[renderpass-tile-shading-fragment-region]]
=== Tile Shading Fragment Regions

If _tile shading_ is <<renderpass-tile-shading, enabled>> for a render pass
instance, then <<synchronization-framebuffer-regions,framebuffer-local
dependencies>> defined using ename:VK_DEPENDENCY_BY_REGION_BIT specify a
<<synchronization-framebuffer-regions,framebuffer region>> equal to the
region covered by the _active tile_.

When <<renderpass-per-tile-execution-model,per-tile execution model>> is
enabled an _active tile_ is associated with each of the per-tile command
invocations with an extent described by shader built-in variables
<<interfaces-builtin-variables-tileoffset,code:TileOffsetQCOM>>,
<<interfaces-builtin-variables-tilesize, code:TileDimensionQCOM>>, and
<<interfaces-builtin-variables-tileapronsize, code:TileApronSizeQCOM>>.
Otherwise, the extent of the _active tile_ is defined by the tile exposed by
`apiext:VK_QCOM_tile_properties` that contains the framebuffer coordinate
latexmath:[(x,y,z)] of the fragment being processed.

[NOTE]
====
Without tile shading the <<synchronization-framebuffer-regions,_framebuffer
region_>> described by ename:VK_DEPENDENCY_BY_REGION_BIT must be assumed by
applications to be no larger than a single pixel or single sample.

The larger tile-sized _framebuffer region_ provided by tile shading allows
applications to achieve increased rendering efficiency on some tiling
architectures.
It enables synchronization commands with a framebuffer-local dependency to
be used for a dependency across fragments with different framebuffer
coordinates, as long as the fragments are located within the same tile.
In this situation, it avoids an otherwise required framebuffer-global
dependency and corresponding data flushing to memory as noted in the
<<synchronization-framebuffer-regions,synchronization chapter>>.
====

[[renderpass-per-tile-execution-model]]
=== Per-Tile Execution Model

Within a <<renderpass-tile-shading, tile shading render pass>> instance, the
per-tile execution model can be enabled.

[open,refpage='vkCmdBeginPerTileExecutionQCOM',desc='Begin per-tile execution mode',type='protos']
--
:refpage: vkCmdBeginPerTileExecutionQCOM

To enable the per-tile execution model, call:

include::{generated}/api/protos/vkCmdBeginPerTileExecutionQCOM.adoc[]

  * pname:commandBuffer is the command buffer in which to record the
    command.
  * pname:pPerTileBeginInfo is a pointer to a slink:VkPerTileBeginInfoQCOM
    structure containing information about how the _per-tile execution
    model_ is started.

When _per-tile execution model_ is enabled, recorded ftext:vkCmdDraw* or
ftext:vkCmdDispatch* commands are invoked per tile.
That is, the recorded draw or dispatch is invoked exactly once for each
_covered tile_.
The set of _covered tiles_ for a given render pass instance consists of the
set of render pass tiles, which can: be queried with
`apiext:VK_QCOM_tile_properties`, that are completely or partially covered
by the pname:renderArea for the render pass instance.
The draw or dispatch commands may: be invoked for uncovered tiles.

Each per-tile command invocation is associated with a single tile, the
_active tile_.
These per-tile invocations are not specified to execute in any particular
order, but the size and offset of the _active tile_ is available via shader
built-ins.

[[renderpass-tile-shading-command-restrictions]]
When _per-tile execution model_ is enabled, the following restrictions
apply:

ifdef::VK_EXT_transform_feedback[]
  * Transform feedback commands such as
    flink:vkCmdBeginTransformFeedbackEXT,
    flink:vkCmdEndTransformFeedbackEXT, flink:vkCmdBeginQueryIndexedEXT, and
    flink:vkCmdEndQueryIndexedEXT, must: not be recorded.
endif::VK_EXT_transform_feedback[]
  * Query commands such as flink:vkCmdWriteTimestamp,
ifdef::VK_EXT_debug_marker[]
    flink:vkCmdDebugMarkerBeginEXT, flink:vkCmdDebugMarkerEndEXT,
    flink:vkCmdDebugMarkerInsertEXT,
endif::VK_EXT_debug_marker[]
    flink:vkCmdBeginQuery, and flink:vkCmdEndQuery, must: not be recorded.
  * Event commands such as
ifdef::VK_KHR_synchronization2,VK_BASE_VERSION_1_3[flink:vkCmdWaitEvents2 and]
    flink:vkCmdWaitEvents must: not be recorded.
  * Render pass clears like flink:vkCmdClearAttachments must: not be
    recorded
ifdef::VK_EXT_attachment_feedback_loop_layout[]
  * Access of an attachment with layout
    ename:VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT as provided
    by `apiext:VK_EXT_attachment_feedback_loop_layout` is disallowed
endif::VK_EXT_attachment_feedback_loop_layout[]
  * Any commands that would cause a invocations of one of the following
    shader stages are not allowed
  ** tessellation
  ** geometry
ifdef::VK_KHR_ray_tracing_pipeline[  ** ray tracing]
ifdef::VK_NV_mesh_shader,VK_EXT_mesh_shader[  ** mesh shading]

.Valid Usage
****
  * [[VUID-vkCmdBeginPerTileExecutionQCOM-None-10664]]
    The current render pass must: be a <<renderpass-tile-shading,tile
    shading render pass>>
  * [[VUID-vkCmdBeginPerTileExecutionQCOM-None-10665]]
    The <<features-tileShadingPerTileDispatch,tileShadingPerTileDispatch>>
    or <<features-tileShadingPerTileDraw,tileShadingPerTileDraw>> feature
    must be enabled
****

include::{generated}/validity/protos/vkCmdBeginPerTileExecutionQCOM.adoc[]
--


[open,refpage='VkPerTileBeginInfoQCOM',desc='Structure specifying per-tile begin information',type='structs']
--
The sname:VkPerTileBeginInfoQCOM structure is defined as:

include::{generated}/api/structs/VkPerTileBeginInfoQCOM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.

include::{generated}/validity/structs/VkPerTileBeginInfoQCOM.adoc[]
--


[open,refpage='vkCmdEndPerTileExecutionQCOM',desc='End per-tile execution mode',type='protos']
--
:refpage: vkCmdEndPerTileExecutionQCOM

To disable per-tile execution model, call:

include::{generated}/api/protos/vkCmdEndPerTileExecutionQCOM.adoc[]

  * pname:commandBuffer is the command buffer in which to record the
    command.
  * pname:pPerTileEndInfo is a pointer to a slink:VkPerTileEndInfoQCOM
    structure containing information about how the _per-tile execution
    model_ is ended.

This command disables _per-tile execution model_.

.Valid Usage
****
  * [[VUID-vkCmdEndPerTileExecutionQCOM-None-10666]]
    The _per-tile execution model_ must: have been enabled in the current
    render pass
  * [[VUID-vkCmdEndPerTileExecutionQCOM-None-10667]]
    The current render pass must: be a <<renderpass-tile-shading,tile
    shading render pass>>
****

include::{generated}/validity/protos/vkCmdEndPerTileExecutionQCOM.adoc[]
--

[open,refpage='VkPerTileEndInfoQCOM',desc='Structure specifying per-tile end information',type='structs']
--
The sname:VkPerTileEndInfoQCOM structure is defined as:

include::{generated}/api/structs/VkPerTileEndInfoQCOM.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.

include::{generated}/validity/structs/VkPerTileEndInfoQCOM.adoc[]
--


[[area-based-dispatch]]
=== Area-Based Dispatch

When the <<renderpass-per-tile-execution-model, per-tile execution model>>
is enabled, the command flink:vkCmdDispatchTileQCOM can: be used to provide
an area-based dispatch, where the implementation determines the work group
count and size based on the tile size and a given shading rate.
