// Copyright 2022-2023 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

// This section is included inside the render pass chapter (renderpass.adoc)

[[renderpass-creation-feedback]]
== Render Pass Creation Feedback

[open,refpage='VkRenderPassCreationControlEXT',desc='Control about the creation of render pass or subpass',type='structs',xrefs='vkCreateRenderPass2 VkRenderPassCreateInfo2 VkSubpassDescription2']
--
A sname:VkRenderPassCreationControlEXT structure can: be included in the
pname:pNext chain of sname:VkRenderPassCreateInfo2 or pname:pNext chain of
slink:VkSubpassDescription2.
The sname:VkRenderPassCreationControlEXT structure is defined as:

include::{generated}/api/structs/VkRenderPassCreationControlEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:disallowMerging is a boolean value indicating whether subpass
    merging will be disabled.

If a sname:VkRenderPassCreationControlEXT structure is included in the
pname:pNext chain of slink:VkRenderPassCreateInfo2 and its value of
pname:disallowMerging is ename:VK_TRUE, the implementation will disable
subpass merging for the entire render pass.
If a sname:VkRenderPassCreationControlEXT structure is included in the
pname:pNext chain of slink:VkSubpassDescription2 and its value of
pname:disallowMerging is ename:VK_TRUE, the implementation will disable
merging the described subpass with previous subpasses in the render pass.

include::{generated}/validity/structs/VkRenderPassCreationControlEXT.adoc[]
--

[open,refpage='VkRenderPassCreationFeedbackCreateInfoEXT',desc='Request feedback about the creation of render pass',type='structs',xrefs='vkCreateRenderPass2 VkRenderPassCreateInfo2 VkRenderPassCreationControlEXT']
--
To obtain feedback about the creation of a render pass, include a
sname:VkRenderPassCreationFeedbackCreateInfoEXT structure in the pname:pNext
chain of slink:VkRenderPassCreateInfo2.
The sname:VkRenderPassCreationFeedbackCreateInfoEXT structure is defined as:

include::{generated}/api/structs/VkRenderPassCreationFeedbackCreateInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pRenderPassFeedback is a pointer to a
    slink:VkRenderPassCreationFeedbackInfoEXT structure in which feedback is
    returned.

include::{generated}/validity/structs/VkRenderPassCreationFeedbackCreateInfoEXT.adoc[]
--

[open,refpage='VkRenderPassCreationFeedbackInfoEXT',desc='Feedback about the creation of a render pass',type='structs',xrefs='VkRenderPassCreationFeedbackCreateInfoEXT']
--
The sname:VkRenderPassCreationFeedbackInfoEXT structure is defined as:

include::{generated}/api/structs/VkRenderPassCreationFeedbackInfoEXT.adoc[]

  * pname:postMergeSubpassCount is the subpass count after merge.

include::{generated}/validity/structs/VkRenderPassCreationFeedbackInfoEXT.adoc[]
--

[open,refpage='VkRenderPassSubpassFeedbackCreateInfoEXT',desc='Request for feedback about the creation of subpass',type='structs',xrefs='vkCreateRenderPass2 VkRenderPassCreateInfo2 VkSubpassDescription2 VkRenderPassCreationControlEXT']
--
Feedback about the creation of a subpass can: be obtained by including a
sname:VkRenderPassSubpassFeedbackCreateInfoEXT structure in the pname:pNext
chain of slink:VkSubpassDescription2.
sname:VkRenderPassSubpassFeedbackCreateInfoEXT structure is defined as:

include::{generated}/api/structs/VkRenderPassSubpassFeedbackCreateInfoEXT.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:pSubpassFeedback is a pointer to a
    slink:VkRenderPassSubpassFeedbackInfoEXT structure in which feedback is
    returned.

include::{generated}/validity/structs/VkRenderPassSubpassFeedbackCreateInfoEXT.adoc[]
--

[open,refpage='VkRenderPassSubpassFeedbackInfoEXT',desc='Feedback about the creation of subpass',type='structs',xrefs='VkRenderPassSubpassFeedbackCreateInfoEXT']
--
The sname:VkRenderPassSubpassFeedbackInfoEXT structure is defined as:

include::{generated}/api/structs/VkRenderPassSubpassFeedbackInfoEXT.adoc[]

  * pname:subpassMergeStatus is a ename:VkSubpassMergeStatusEXT value
    specifying information about whether the subpass is merged with previous
    subpass and the reason why it is not merged.
  * pname:description is an array of ename:VK_MAX_DESCRIPTION_SIZE code:char
    containing a null-terminated UTF-8 string which provides additional
    details.
  * pname:postMergeIndex is the subpass index after the subpass merging.

include::{generated}/validity/structs/VkRenderPassSubpassFeedbackInfoEXT.adoc[]
--

[open,refpage='VkSubpassMergeStatusEXT',desc='Specify a subpass merging status',type='enums']
--
Possible values of
sname:VkRenderPassSubpassFeedbackInfoEXT:subpassMergeStatus are:

include::{generated}/api/enums/VkSubpassMergeStatusEXT.adoc[]

  * ename:VK_SUBPASS_MERGE_STATUS_MERGED_EXT specifies the subpass is merged
    with a previous subpass.
  * ename:VK_SUBPASS_MERGE_STATUS_DISALLOWED_EXT specifies the subpass is
    disallowed to merge with previous subpass.
    If the render pass does not allow subpass merging, then all subpass
    statuses are set to this value.
    If a subpass description does not allow subpass merging, then only that
    subpass's status is set to this value.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SIDE_EFFECTS_EXT specifies the
    subpass is not merged because it contains side effects.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SAMPLES_MISMATCH_EXT specifies
    the subpass is not merged because sample count is not compatible with
    previous subpass.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_VIEWS_MISMATCH_EXT specifies
    the subpass is not merged because view masks do not match with previous
    subpass.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_ALIASING_EXT specifies the
    subpass is not merged because of attachments aliasing between them.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPENDENCIES_EXT specifies the
    subpass is not merged because subpass dependencies do not allow merging.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INCOMPATIBLE_INPUT_ATTACHMENT_EXT
    specifies the subpass is not merged because input attachment is not a
    color attachment from previous subpass or the formats are incompatible.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_TOO_MANY_ATTACHMENTS_EXT
    specifies the subpass is not merged because of too many attachments.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_INSUFFICIENT_STORAGE_EXT
    specifies the subpass is not merged because of insufficient memory.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_DEPTH_STENCIL_COUNT_EXT
    specifies the subpass is not merged because of too many depth/stencil
    attachments.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_RESOLVE_ATTACHMENT_REUSE_EXT
    specifies the subpass is not merged because a resolve attachment is
    reused as an input attachment in a subsequent subpass.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_SINGLE_SUBPASS_EXT specifies
    the subpass is not merged because the render pass has only one subpass.
  * ename:VK_SUBPASS_MERGE_STATUS_NOT_MERGED_UNSPECIFIED_EXT specifies other
    reasons why subpass is not merged.
    It is also the recommended default value that should be reported when a
    subpass is not merged and when no other value is appropriate.
--
