// Copyright 2024-2025 The Khronos Group Inc.
// SPDX-License-Identifier: CC-BY-4.0

[[lag-control]]
== Lag Control

Some implementations support extensions to reduce display latency and
control the swapchain present interval, as described in the remainder of
this section.

ifdef::VK_AMD_anti_lag[]
[[anti-lag]]
=== Anti-Lag

The apiext:VK_AMD_anti_lag extension lowers latency between receiving input
and displaying on the screen.
It adds a command to indicate when input is being processed for a frame, and
when that frame's images are presented.

[open,refpage='vkAntiLagUpdateAMD',desc='Provide information to reduce latency',type='protos']
--
To lower latency, call:

ifdef::VK_AMD_anti_lag[]
include::{generated}/api/protos/vkAntiLagUpdateAMD.adoc[]
endif::VK_AMD_anti_lag[]

  * pname:device is the logical device
  * pname:pData is a pointer to a slink:VkAntiLagDataAMD structure
    containing latency reduction parameters.

This command should be executed immediately before the application processes
user input.
If pname:pData is not `NULL` and
slink:VkAntiLagDataAMD::pname:pPresentationInfo is not `NULL`, this command
should: be executed again before flink:vkQueuePresentKHR, with
pname:pPresentationInfo set to matching values.

.Valid Usage
****
  * [[VUID-vkAntiLagUpdateAMD-antiLag-10061]]
    The <<features-antiLag, pname:antiLag>> feature must: be enabled
****

include::{generated}/validity/protos/vkAntiLagUpdateAMD.adoc[]
--

[open,refpage='VkAntiLagDataAMD',desc='Structure specifying the parameters for vkAntiLagUpdateAMD',type='structs']
--
The sname:VkAntiLagDataAMD structure is defined as:

include::{generated}/api/structs/VkAntiLagDataAMD.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:mode is a elink:VkAntiLagModeAMD value specifying the anti-lag
    status.
  * pname:maxFPS is the framerate limit, in frames per second, used by the
    application.
    This limit will be imposed if anti-lag is enabled.
    If the application tries to render faster, the framerate will be reduced
    to match this limit.
    A value of 0 will disable the limit.
  * pname:pPresentationInfo is a pointer to a
    slink:VkAntiLagPresentationInfoAMD structure containing information
    about the application stage.

This structure specifies anti-lag parameters.

include::{generated}/validity/structs/VkAntiLagDataAMD.adoc[]
--

[open,refpage='VkAntiLagModeAMD',desc='Set the status of the anti-lag feature',type='enums']
--
Possible values of slink:VkAntiLagDataAMD::pname:mode, specifying the
anti-lag status, are:

include::{generated}/api/enums/VkAntiLagModeAMD.adoc[]

  * ename:VK_ANTI_LAG_MODE_DRIVER_CONTROL_AMD specifies that anti-lag will
    be enabled or disabled depending on driver settings.
  * ename:VK_ANTI_LAG_MODE_ON_AMD specifies that anti-lag will be enabled.
  * ename:VK_ANTI_LAG_MODE_OFF_AMD specifies that anti-lag will be disabled.
--

[open,refpage='VkAntiLagPresentationInfoAMD',desc='Structure specifying information about stage',type='structs']
--
The sname:VkAntiLagPresentationInfoAMD structure is defined as:

include::{generated}/api/structs/VkAntiLagPresentationInfoAMD.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:stage is a elink:VkAntiLagStageAMD value specifying the current
    application stage.
  * pname:frameIndex is set just before the application processes input data
    (ename:VK_ANTI_LAG_STAGE_INPUT_AMD).
    The same pname:frameIndex value should: be set before the frame with
    current input data will be presented by flink:vkQueuePresentKHR
    (ename:VK_ANTI_LAG_STAGE_PRESENT_AMD).
    This should: be done for each frame.

This structure specifies information about the presentation stage for which
anti-lag parameters are being set.

include::{generated}/validity/structs/VkAntiLagPresentationInfoAMD.adoc[]
--

[open,refpage='VkAntiLagStageAMD',desc='Report the application stage',type='enums']
--
Possible values of slink:VkAntiLagPresentationInfoAMD::pname:stage,
specifying the current application stage, are:

include::{generated}/api/enums/VkAntiLagStageAMD.adoc[]

  * ename:VK_ANTI_LAG_STAGE_INPUT_AMD specifies the stage before processing
    input.
  * ename:VK_ANTI_LAG_STAGE_PRESENT_AMD specifies the stage before
    flink:vkQueuePresentKHR.
--
endif::VK_AMD_anti_lag[]


ifdef::VK_NV_low_latency2[]
[[low-latency2]]
=== Latency Reduction

[open,refpage='vkSetLatencySleepModeNV',desc='Enable or Disable low latency mode on a swapchain',type='protos']
--
To enable or disable low latency mode on a swapchain, call:

include::{generated}/api/protos/vkSetLatencySleepModeNV.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to enable or disable low latency mode
    on.
  * pname:pSleepModeInfo is `NULL` or a pointer to a
    slink:VkLatencySleepModeInfoNV structure specifying the parameters of
    the latency sleep mode.

If pname:pSleepModeInfo is `NULL`, fname:vkSetLatencySleepModeNV will
disable low latency mode, low latency boost, and set the minimum present
interval previously specified by slink:VkLatencySleepModeInfoNV to zero on
pname:swapchain.
As an exception to the normal rules for objects which are externally
synchronized, the swapchain passed to fname:vkSetLatencySleepModeNV may: be
simultaneously used by other threads in calls to functions other than
flink:vkDestroySwapchainKHR.
Access to the swapchain data associated with this extension must: be atomic
within the implementation.

include::{generated}/validity/protos/vkSetLatencySleepModeNV.adoc[]
--

[open,refpage='VkLatencySleepModeInfoNV',desc='Structure to set low latency mode',type='structs']
--
The sname:VkLatencySleepModeInfoNV structure is defined as:

include::{generated}/api/structs/VkLatencySleepModeInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:lowLatencyMode is the toggle to enable or disable low latency
    mode.
  * pname:lowLatencyBoost allows an application to hint to the GPU to
    increase performance to provide additional latency savings at a cost of
    increased power consumption.
  * pname:minimumIntervalUs is the microseconds between
    flink:vkQueuePresentKHR calls for a given swapchain that
    flink:vkLatencySleepNV will enforce.

If pname:lowLatencyMode is ename:VK_FALSE, pname:lowLatencyBoost will still
hint to the GPU to increase its power state and fname:vkLatencySleepNV will
still enforce pname:minimumIntervalUs between fname:vkQueuePresentKHR calls.

include::{generated}/validity/structs/VkLatencySleepModeInfoNV.adoc[]
--

[open,refpage='vkLatencySleepNV',desc='Trigger low latency mode Sleep',type='protos']
--
To provide the synchronization primitive used to delay host CPU work for
lower latency rendering, call:

include::{generated}/api/protos/vkLatencySleepNV.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to delay associated CPU work based on
    slink:VkLatencySubmissionPresentIdNV submissions.
  * pname:pSleepInfo is a pointer to a slink:VkLatencySleepInfoNV structure
    specifying the parameters of the latency sleep.

fname:vkLatencySleepNV returns immediately.
Applications should: use flink:vkWaitSemaphores with
pname:pSleepInfo->signalSemaphore to delay host CPU work.
CPU work refers to application work done before presenting which includes
but is not limited to: input sampling, simulation, command buffer recording,
command buffer submission, and present submission.
Applications should: call this function before input sampling, and exactly
once between presents.

include::{generated}/validity/protos/vkLatencySleepNV.adoc[]
--

[open,refpage='VkLatencySleepInfoNV',desc='Structure specifying the parameters of vkLatencySleepNV',type='structs']
--
The sname:VkLatencySleepInfoNV structure is defined as:

include::{generated}/api/structs/VkLatencySleepInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:signalSemaphore is a semaphore that is signaled to indicate that
    the application should: resume input sampling work.
  * pname:value is the value that pname:signalSemaphore is set to for
    resuming sampling work.

.Valid Usage
****
  * [[VUID-VkLatencySleepInfoNV-signalSemaphore-09361]]
    pname:signalSemaphore must: be a timeline semaphore
****

include::{generated}/validity/structs/VkLatencySleepInfoNV.adoc[]
--

[open,refpage='vkSetLatencyMarkerNV',desc='Pass in marker for timing info',type='protos']
--
An application can: provide timestamps at various stages of its frame
generation work by calling:

include::{generated}/api/protos/vkSetLatencyMarkerNV.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to capture timestamps on.
  * pname:pSetLatencyMarkerInfo is a pointer to a
    slink:VkSetLatencyMarkerInfoNV structure specifying the parameters of
    the marker to set.

At the beginning and end of simulation and render threads and beginning and
end of flink:vkQueuePresentKHR calls, fname:vkSetLatencyMarkerNV can: be
called to provide timestamps for the application's reference.
These timestamps are returned with a call to flink:vkGetLatencyTimingsNV
alongside driver provided timestamps at various points of interest with
regards to latency within the application.
As an exception to the normal rules for objects which are externally
synchronized, the swapchain passed to fname:vkSetLatencyMarkerNV may: be
simultaneously used by other threads in calls to functions other than
flink:vkDestroySwapchainKHR.
Access to the swapchain data associated with this extension must: be atomic
within the implementation.

include::{generated}/validity/protos/vkSetLatencyMarkerNV.adoc[]
--

[open,refpage='VkSetLatencyMarkerInfoNV',desc='Structure specifying the parameters of vkSetLatencyMarkerNV',type='structs']
--
The sname:VkSetLatencyMarkerInfoNV structure is defined as:

include::{generated}/api/structs/VkSetLatencyMarkerInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentID is an application provided value that is used to
    associate the timestamp with a fname:vkQueuePresentKHR command using
ifdef::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds or]
ifndef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds]
endif::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentId2KHR::pname:pPresentIds]
    for a given present.
  * pname:marker is the type of timestamp to be recorded.

include::{generated}/validity/structs/VkSetLatencyMarkerInfoNV.adoc[]
--

[open,refpage='VkLatencyMarkerNV',desc='Structure used to mark different points in latency',type='enums']
--
The elink:VkLatencyMarkerNV enum is defined as:

include::{generated}/api/enums/VkLatencyMarkerNV.adoc[]

The members of the elink:VkLatencyMarkerNV are used as arguments for
flink:vkSetLatencyMarkerNV in the use cases described below:

  * ename:VK_LATENCY_MARKER_SIMULATION_START_NV should: be called at the
    start of the simulation execution each frame, but after the call to
    fname:vkLatencySleepNV.
  * ename:VK_LATENCY_MARKER_SIMULATION_END_NV should: be called at the end
    of the simulation execution each frame.
  * ename:VK_LATENCY_MARKER_RENDERSUBMIT_START_NV should: be called at the
    beginning of the render submission execution each frame.
    This should: be wherever Vulkan API calls are made and must: not span
    into asynchronous rendering.
  * ename:VK_LATENCY_MARKER_RENDERSUBMIT_END_NV should: be called at the end
    of the render submission execution each frame.
  * ename:VK_LATENCY_MARKER_PRESENT_START_NV should: be called just before
    fname:vkQueuePresentKHR.
  * ename:VK_LATENCY_MARKER_PRESENT_END_NV should: be called when
    fname:vkQueuePresentKHR returns.
  * ename:VK_LATENCY_MARKER_INPUT_SAMPLE_NV should: be called just before
    the application gathers input data.
  * ename:VK_LATENCY_MARKER_TRIGGER_FLASH_NV should: be called anywhere
    between ename:VK_LATENCY_MARKER_SIMULATION_START_NV and
    ename:VK_LATENCY_MARKER_SIMULATION_END_NV whenever a left mouse click
    occurs.
--

[open,refpage='vkGetLatencyTimingsNV',desc='Get latency marker results',type='protos']
--
To get an array containing the newest collected latency data, call:

include::{generated}/api/protos/vkGetLatencyTimingsNV.adoc[]

  * pname:device is the device associated with pname:swapchain.
  * pname:swapchain is the swapchain to return data from.
  * pname:pLatencyMarkerInfo is a pointer to a
    slink:VkGetLatencyMarkerInfoNV structure specifying the parameters for
    returning latency information.

The timings returned by fname:vkGetLatencyTimingsNV contain the timestamps
requested from flink:vkSetLatencyMarkerNV and additional
implementation-specific markers defined in
slink:VkLatencyTimingsFrameReportNV.

include::{generated}/validity/protos/vkGetLatencyTimingsNV.adoc[]
--

[open,refpage='VkGetLatencyMarkerInfoNV',desc='Structure specifying the parameters of vkGetLatencyTimingsNV',type='structs']
--
The sname:VkGetLatencyMarkerInfoNV structure is defined as:

include::{generated}/api/structs/VkGetLatencyMarkerInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is either `NULL` or a pointer to a structure extending this
    structure.
  * pname:timingCount is an integer related to the number of previous frames
    of latency data available or queried, as described below.
  * pname:pTimings is either `NULL` or a pointer to an array of
    slink:VkLatencyTimingsFrameReportNV structures.

If pname:pTimings is `NULL` then the maximum number of queryable frame data
is returned in pname:timingCount.
Otherwise, pname:timingCount must: be set by the application to the number
of elements in the pname:pTimings array, and on return the variable is
overwritten with the number of values actually written to pname:pTimings.
The elements of pname:pTimings are arranged in the order they were requested
in, with the oldest data in the first entry.

include::{generated}/validity/structs/VkGetLatencyMarkerInfoNV.adoc[]
--

[open,refpage='VkLatencyTimingsFrameReportNV',desc='Structure containing latency data',type='structs']
--
The slink:VkLatencyTimingsFrameReportNV structure describes latency data
returned by flink:vkGetLatencyTimingsNV

include::{generated}/api/structs/VkLatencyTimingsFrameReportNV.adoc[]

The members of the slink:VkLatencyTimingsFrameReportNV structure describe
the following:

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentID is the application provided value that is used to
    associate the timestamp with a fname:vkQueuePresentKHR command using
ifdef::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds or]
ifndef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds]
endif::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentId2KHR::pname:pPresentIds]
    for a given present.
  * pname:simStartTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_SIMULATION_START_NV.
  * pname:simEndTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_SIMULATION_END_NV
  * pname:renderStartTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_RENDERSUBMIT_START_NV.
  * pname:renderEndTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_RENDERSUBMIT_END_NV.
  * pname:presentStartTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_PRESENT_START_NV.
  * pname:presentEndTimeUs is the timestamp written when
    fname:vkSetLatencyMarkerNV is called with the ename:VkLatencyMarkerNV
    enum ename:VK_LATENCY_MARKER_PRESENT_END_NV.
  * pname:driverStartTimeUs is the timestamp written when the first
    fname:vkQueueSubmit for the frame is called.
  * pname:driverEndTimeUs is the timestamp written when the final
    fname:vkQueueSubmit hands off from the Vulkan Driver.
  * pname:osRenderQueueStartTimeUs is the timestamp written when the final
    fname:vkQueueSubmit hands off from the Vulkan Driver.
  * pname:osRenderQueueEndTimeUs is the timestamp written when the first
    submission reaches the GPU.
  * pname:gpuRenderStartTimeUs is the timestamp written when the first
    submission reaches the GPU.
  * pname:gpuRenderEndTimeUs is the timestamp written when the final
    submission finishes on the GPU for the frame.

include::{generated}/validity/structs/VkLatencyTimingsFrameReportNV.adoc[]
--

[open,refpage='VkLatencySubmissionPresentIdNV',desc='Structure used to associate a queueSubmit with a presentId',type='structs']
--
The slink:VkLatencySubmissionPresentIdNV structure is defined as:

include::{generated}/api/structs/VkLatencySubmissionPresentIdNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentID is used to associate the fname:vkQueueSubmit with the
    presentId used for a given fname:vkQueuePresentKHR via
ifdef::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds or]
ifndef::VK_KHR_present_id2[slink:VkPresentIdKHR::pname:pPresentIds.]
endif::VK_KHR_present_id[]
ifdef::VK_KHR_present_id2[slink:VkPresentId2KHR::pname:pPresentIds.]

For any submission to be tracked with low latency mode pacing, it needs to
be associated with other submissions in a given present.
To associate a submission with pname:presentID for low latency mode, the
pname:pNext chain of flink:vkQueueSubmit must: include a
sname:VkLatencySubmissionPresentIdNV structure.

include::{generated}/validity/structs/VkLatencySubmissionPresentIdNV.adoc[]
--

[open,refpage='vkQueueNotifyOutOfBandNV',desc='Notify out of band queue',type='protos']
--
To mark a queue as _out of band_, so that all fname:vkQueueSubmit calls on
the queue are ignored for latency evaluation, call:

include::{generated}/api/protos/vkQueueNotifyOutOfBandNV.adoc[]

  * pname:queue is the VkQueue to be marked as out of band.
  * pname:pQueueTypeInfo is a pointer to a slink:VkOutOfBandQueueTypeInfoNV
    structure specifying the queue type.

include::{generated}/validity/protos/vkQueueNotifyOutOfBandNV.adoc[]
--

[open,refpage='VkOutOfBandQueueTypeInfoNV',desc='Structure used to describe the queue that is being marked as Out of Band',type='structs']
--
The slink:VkOutOfBandQueueTypeInfoNV structure is defined as:

include::{generated}/api/structs/VkOutOfBandQueueTypeInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:queueType describes the usage of the queue to be marked as out of
    band.

include::{generated}/validity/structs/VkOutOfBandQueueTypeInfoNV.adoc[]
--

[open,refpage='VkOutOfBandQueueTypeNV',desc='Type of out of band queue',type='enums']
--
The elink:VkOutOfBandQueueTypeNV enum is defined as:

include::{generated}/api/enums/VkOutOfBandQueueTypeNV.adoc[]

The members of the elink:VkOutOfBandQueueTypeNV are used to describe the
queue type in slink:VkOutOfBandQueueTypeInfoNV as described below:

  * ename:VK_OUT_OF_BAND_QUEUE_TYPE_RENDER_NV specifies that work will be
    submitted to this queue.
  * ename:VK_OUT_OF_BAND_QUEUE_TYPE_PRESENT_NV specifies that this queue
    will be presented from.
--

[open,refpage='VkSwapchainLatencyCreateInfoNV',desc='Specify that a swapchain will use low latency mode',type='structs']
--
To allow low latency mode to be used by a swapchain, add a
sname:VkSwapchainLatencyCreateInfoNV structure to the pname:pNext chain of
slink:VkSwapchainCreateInfoKHR.

The sname:VkSwapchainLatencyCreateInfoNV structure is defined as:

include::{generated}/api/structs/VkSwapchainLatencyCreateInfoNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:latencyModeEnable is ename:VK_TRUE if the created swapchain will
    utilize low latency mode, ename:VK_FALSE otherwise.

include::{generated}/validity/structs/VkSwapchainLatencyCreateInfoNV.adoc[]
--

[open,refpage='VkLatencySurfaceCapabilitiesNV',desc='Structure describing surface optimized presentation modes for use with low latency mode',type='structs']
--
The sname:VkLatencySurfaceCapabilitiesNV structure is defined as:

include::{generated}/api/structs/VkLatencySurfaceCapabilitiesNV.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:presentModeCount is the number of presentation modes provided.
  * pname:pPresentModes is list of presentation modes optimized for use with
    low latency mode with pname:presentModeCount entries.

If pname:pPresentModes is `NULL`, then the number of present modes that are
optimized for use with low latency mode returned in pname:presentModeCount.
Otherwise, pname:presentModeCount must: be set by the application to the
number of elements in the pname:pPresentModes array, and on return the
variable is overwritten with the number of values actually written to
pname:pPresentModes.
If the value of pname:presentModeCount is less than the number of optimized
present modes, at most pname:presentModeCount values will be written to
pname:pPresentModes.

include::{generated}/validity/structs/VkLatencySurfaceCapabilitiesNV.adoc[]
--
endif::VK_NV_low_latency2[]

