// Copyright 2019-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentId2KHR',desc='The list of presentation identifiers',type='structs']
--
The sname:VkPresentId2KHR structure is defined as:

include::{generated}/api/structs/VkPresentId2KHR.adoc[]

  * pname:sType is a elink:VkStructureType value identifying this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:swapchainCount is the number of swapchains being presented to the
    fname:vkQueuePresentKHR command.
  * pname:pPresentIds is `NULL` or a pointer to an array of uint64_t with
    pname:swapchainCount entries.
    If not `NULL`, each non-zero value in pname:pPresentIds specifies the
    present id to be associated with the presentation of the swapchain with
    the same index in the flink:vkQueuePresentKHR call.

For applications to be able to reference specific presentation events queued
by a call to fname:vkQueuePresentKHR, an identifier needs to be associated
with them.

When the slink:VkSurfaceCapabilitiesPresentId2KHR surface capability is
present for a surface, applications can: include the sname:VkPresentId2KHR
structure in the pname:pNext chain of the slink:VkPresentInfoKHR structure
to associate an identifier with each presentation request.
The pname:pPresentIds provides an identifier for the swapchain present at
the corresponding index in slink:VkPresentInfoKHR's pname:pSwapchains array.

If this presentId is non-zero, then the application can: later use this
value to refer to that image presentation.
A value of zero indicates that this presentation has no associated
presentId.
A non-zero presentId must: be greater than any non-zero presentId passed
previously by the application for the same swapchain.

ifdef::VK_KHR_present_wait2[]
If a non-zero presentId was provided, this may be used with
flink:vkWaitForPresent2KHR for the application to synchronize against the
presentation engine's processing of the presentation request.
endif::VK_KHR_present_wait2[]

[NOTE]
====
The ID namespace used by this extension must: be shared with other
extensions that allow the application to provide a 64-bit monotonically
increasing presentation ID, such as the original VK_KHR_present_id.

This is to allow existing extensions that depend on VK_KHR_present_id to use
VK_KHR_present_id2 provided IDs without change, as well as to simplify
writing future extensions that require application provided presentation
IDs.
====

.Valid Usage
****
  * [[VUID-VkPresentId2KHR-swapchainCount-10818]]
    pname:swapchainCount must: be the same value as
    sname:VkPresentInfoKHR::pname:swapchainCount, where this
    sname:VkPresentId2KHR is in the pname:pNext chain of the
    sname:VkPresentInfoKHR structure
  * [[VUID-VkPresentId2KHR-presentIds-10819]]
    Each pname:presentIds entry must: be greater than any previous
    pname:presentIds entry passed for the associated pname:pSwapchains entry
  * [[VUID-VkPresentId2KHR-None-10820]]
    The swapchain must have been created with
    ename:VK_SWAPCHAIN_CREATE_PRESENT_ID_2_BIT_KHR bit set in the
    ename:VkSwapchainCreateFlagBitsKHR field
****

include::{generated}/validity/structs/VkPresentId2KHR.adoc[]
--

ifdef::VK_KHR_present_wait2[]
include::{chapters}/VK_KHR_present_wait2/WaitForPresent2.adoc[]
endif::VK_KHR_present_wait2[]
